camunda/camunda-docs

docs/product-manuals/zeebe/deployment-guide/operations/resource-planning.md, docs/product-manuals/zeebe/deployment-guide/operations/upgrade-zeebe.md
Removes some leftovers where 15 minutes is mentioned as snapshot period default.
=> chore(docs): fix left overs

docs/product-manuals/clients/java-client/get-started.md, docs/product-manuals/clients/java-client/index.md, docs/product-manuals/clients/java-client/job-worker.md
Adds a description of the java client's job worker polling behaviour and how to configure its backoff strategy.
closes #183
=> clients/java: describe job worker polling and backoff

docs/product-manuals/zeebe/deployment-guide/operations/backpressure.md
Documents issues caused by problematic system clocks
=> Document system clock/backpressure issues

docs/reference/feel/builtin-functions/feel-built-in-functions-boolean.md, docs/reference/feel/builtin-functions/feel-built-in-functions-context.md, docs/reference/feel/builtin-functions/feel-built-in-functions-conversion.md, docs/reference/feel/builtin-functions/feel-built-in-functions-list.md, docs/reference/feel/builtin-functions/feel-built-in-functions-numeric.md, docs/reference/feel/builtin-functions/feel-built-in-functions-string.md, docs/reference/feel/builtin-functions/feel-built-in-functions-temporal.md, docs/reference/feel/language-guide/feel-data-types.md, docs/reference/feel/language-guide/feel-expression.md, docs/reference/feel/language-guide/feel-unary-tests.md, docs/reference/feel/what-is-feel.md
* Zeebe has updated the dependency `feel-engine` to `1.13.1` (camunda-cloud/zeebe#6586)
* **copy** the docs from the repository and replace the existing docs
* replace the local changes by the origin docs (e.g. code markers for function headlines, tailing semicolons in code snippets, etc.) to improve the maintainability (goal: just copy the docs without additional changes)
* no new content has been added compared to the origin docs
=> chore(feel): update the FEEL reference for version 1.13.1

docs/product-manuals/zeebe/technical-concepts/workflow-lifecycles.md
Fix error in workflow lifecycles page.
replaces #179 (the PR could not be merged properly, because of our tooling)
=> fix in workflow-lifecycles.md

docs/product-manuals/zeebe/technical-concepts/internal-processing.md
Zeebe no longer processes events, instead it processes commands exclusively.
Thus, the part about state changes triggering commands is no longer valid.
It makes sense to describe how the engine is driven by writing follow-up commands instead.
=> docs(zeebe): describe driving the engine

docs/reference/release-cycle.md
Considering Zeebe release `1.0.0` is nearing, I assume we should remove the note about breaking changes before Zeebe 1.0
=> Remove release-cycle pre-1.0 note

docs/product-manuals/zeebe/deployment-guide/kubernetes/helm/index.md, docs/product-manuals/zeebe/deployment-guide/kubernetes/helm/installing-helm.md, docs/product-manuals/zeebe/deployment-guide/kubernetes/operator/zeebe-operator.md, versioned_docs/version-0.25/product-manuals/zeebe/kubernetes/index.md, versioned_docs/version-0.25/product-manuals/zeebe/kubernetes/installing-helm.md, versioned_docs/version-0.25/product-manuals/zeebe/kubernetes/zeebe-operator.md
This PR updates all the URL making references to helm.zeebe.io to helm.camunda.io.
=> Updating Helm Repository URLs after renaming

docs/reference/overview.md, docs/reference/public-api.md, sidebars.js
Add a page to document the public API of Camunda Cloud. Public API is defined as an API which we guarantee backwards compatibility. At the moment we agreed that for 1.0 we only see the Java Client API as public API.
I choose to put it in the reference section as I didn't see fit in other sections, and wasn't sure how a new section could look like. Happy to take suggestions.
=> Add Public API page

docs/reference/bpmn-processes/call-activities/call-activities.md, docs/reference/bpmn-processes/embedded-subprocesses/embedded-subprocesses.md, docs/reference/bpmn-processes/error-events/error-events.md, docs/reference/bpmn-processes/event-based-gateways/event-based-gateways.md, docs/reference/bpmn-processes/event-subprocesses/event-subprocesses.md, docs/reference/bpmn-processes/exclusive-gateways/exclusive-gateways.md, docs/reference/bpmn-processes/message-events/message-events.md, docs/reference/bpmn-processes/multi-instance/multi-instance.md, docs/reference/bpmn-processes/none-events/none-events.md, docs/reference/bpmn-processes/parallel-gateways/parallel-gateways.md, docs/reference/bpmn-processes/receive-tasks/receive-tasks.md, docs/reference/bpmn-processes/service-tasks/service-tasks.md, docs/reference/bpmn-processes/timer-events/timer-events.md
- modeler gifs have to be updated and should maybe moved to the modeler docs
- workflow life cycle has to be updated
- promote xml representation and references to be subsections to be visible in table of content
closes #235
=> Remove modeler and workflow lifecycle from bpmn references

docs/product-manuals/clients/other-clients/rust.md
Updated verbiage surrounding this extension's [lifecycle status](https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md#abandoned-) and updated the link to direct to its new home in the community hub.
=> Add community hub repository link

docs/product-manuals/clients/other-clients/javascript.md
Updated links to the Node-RED and NestJS repos to indicate their migration to the Camunda Community Hub
=> Add new links to community hub repository location

docs/product-manuals/zeebe/technical-concepts/process-lifecycles.md
It seems that there aren't `EVENT_ACTIVATING` and `EVENT_ACTIVATED` in the Event-lifecycle diagram. So I guess it should be **ELEMENT_ACTIVATING** and **ELEMENT_ACTIVATED**. 
Please correct me if I understand it wrong. Thank you!
=> The figure and the table don’t seem to match

docs/guides/getting-started/deploy-your-process-and-start-process-instance.md
Adds the following to clarify what models/diagrams can be deployed to which platform.
```
:::note
BPMN diagrams must be created for the process engine they intend to be deployed on. You cannot run a BPMN diagram modeled for Camunda Platform in Camunda Cloud, or vice versa, at this time.
:::
```
=> Add note for diagram deploy

docusaurus.config.js
* contextual-search is useful for versioned docs to avoid multiple results from different versions
See here: https://docusaurus.io/docs/search#contextual-search
closes #280
=> Enable contextual-search for Algolia

docs/product-manuals/overview.md, docusaurus.config.js, versioned_docs/version-0.25/product-manuals/overview.md, versioned_docs/version-0.26/product-manuals/overview.md, versioned_docs/version-1.0/product-manuals/overview.md
This PR addresses trailing slash concerns in #304 and #269.
* Add `trailingSlash` config, set to false
* Remove `trailingSlash` from sitemap plugin (deprecation warning)
* Update previous version docs to add .md to fix broken links
=> Trailing slash config

docs/product-manuals/zeebe/deployment-guide/configuration/configuration.md
Adds a short paragraph explaining the pitfalls of the experimental configuration section, specifically those related to the backwards compatibility guarantees.
closes #38
=> Add experimental config note

docs/reference/bpmn-processes/bpmn-coverage.md, src/css/custom.css, versioned_docs/version-0.25/product-manuals/zeebe/bpmn-workflows/bpmn-coverage.md, versioned_docs/version-0.26/reference/bpmn-workflows/bpmn-coverage.md, versioned_docs/version-1.0/reference/bpmn-processes/bpmn-coverage.md
The orange highlighting currently used in the BPMN coverage map
feels like a warning color that one would expect to be used for the unsupported elements.
In addition the color is not a Camunda brand color.
The replacement color is from the official Icemunda color scale
and fits nicely to the hover color.
=> Switch orange to green on BPMN coverage

docs/product-manuals/cloud-console/manage-clusters/manage-alerts.md
The documentation for Webhook alerts currently only describes the JSON structure of a single alert.
However, the actual HTTP POST call made by Camunda Cloud wraps this in a bigger structure with a `alerts` array.
This PR updates the documentation to reflect this.
=> Fixed Webhook alerts JSON body

docs/components/iam/overview.md, docs/components/iam/what-is-iam.md, docs/components/overview.md, sidebars.js, static/.htaccess
I would like to rename the IAM landing page from something generic to something a little more inviting. Therefore I decided to go with `What is IAM?` which is a clear sign post to a user that within the page they will find out what IAM actually is and the role it plays.
=> fix: rename the IAM landing page

docs/self-managed/iam/deployment/making-iam-production-ready.md, sidebars.js
Solves https://github.com/camunda-cloud/camunda-cloud-documentation/issues/394
To make sure that users are aware that there are certain steps they should take to make the IAM component stable for production uses. At present the only variables that need to be considered are `DATABASE_ENCRYPTION_KEY` and `TOKEN_SIGNING_KEY`
=> feat: add page for making iam production ready

docs/self-managed/iam/deployment/configuration-variables.md
Solves https://github.com/camunda-cloud/camunda-cloud-documentation/issues/390
I noticed in the forums that there were a couple of configuration variables that aren't as clear as they should be, notably `ENFORCE_HTTPS` and `ENFORCE_ACCESS_CONTROL`
=> feat: add to list of environmental variables

docs/self-managed/zeebe-deployment/docker/install.md
Looking at the installation docs we are currently discussion, I recognized that the docs point to the community extension around docker-compose, which is quite outdated at the moment (old Zeebe versions, no tasklist, ...).
At the same time, the Zeebe team maintains one docker-compose file always using the latest version: https://github.com/camunda-cloud/camunda-cloud-get-started/blob/master/docker-compose.yaml - so we should simply point to this one instead.
=> Updated link to maintained/default docker-compose file

sidebars.js
make page ordering in sidebar of CCSM section consistent with bullet
point list in on overview page and aligned with the order in which we
believe users will typically install the components (e.g. Zeebe first)
closes #435
=> Align sidebar page ordering in CCSM section (#435)

docs/apis-clients/java-client/testing.md, docs/reference/announcements.md
We are deprecating `zeebe-test`: https://github.com/camunda-cloud/zeebe/issues/8143. We have already started to work on [a replacement](https://github.com/camunda-cloud/camunda-cloud-testing) but I've not mentioned that in the deprecation announcement because it's not finished yet.
@akeller This is my first documentation contribution so I'm happy to receive any suggestions. We can also discuss if you'd prefer we add more information to the announcement, for example a link to the new `camunda-cloud-testing` project.
=> Announce deprecation of `zeebe-test`

.github/workflows/linkcheck.yaml, static/.htaccess
This change set adds a new github workflow to check internal links in production and stage docs website, it is run every night at 22:00. Right now this doesn't fail anything and is more for us a way of understanding what the current state is. We can discuss how to move forward with this, but at least it allows us now to spot such issues easier.
Additionally this change contains a new rewrite rule to redirect any resource like bpmn, yaml, xml and images to remove the trailing slash.
closes #403
closes #419
=> Add link checker workflow and rewrite rule for trailing slash issue

versioned_docs/version-1.1/components/zeebe/deployment-guide/docker/install.md
Now the links are pointing to the maintained camunda-cloud-get-started repository instead of the deprecated from the community hub.
=> Fixed Links to docker-compose

docs/components/concepts/incidents.md
I got confused with the original wording. There is no option to complete tasks in Operate. In the GUI they a named operations.
=> change tasks to operations

static/.htaccess
This change is not necessary and there is no official mime type for yaml (see #478) but it would remove the warning from our link checker and it adds a content-type if anyone opens a yaml file in our docs.
closes #478
=> Add YAML mime type

.github/workflows/build-docs.yaml, docs/guides/getting-started-orchestrate-microservices.md, docs/reference/glossary.md, docs/self-managed/operate-deployment/authentication.md, docs/self-managed/operate-deployment/schema-and-migration.md, docs/self-managed/tasklist-deployment/authentication.md, static/.htaccess, versioned_docs/version-0.25/components/operate/deployment/configuration.md, versioned_docs/version-0.25/components/zeebe/clients/go-client/get-started.md, versioned_docs/version-0.25/components/zeebe/operations/upgrade-zeebe.md, versioned_docs/version-0.25/components/zeebe/yaml-workflows/data-flow.md, versioned_docs/version-0.26/components/cloud-console/manage-plan/professional-plan/billing-parameters.md, versioned_docs/version-0.26/components/zeebe/deployment-guide/operations/upgrade-zeebe.md, versioned_docs/version-0.26/reference/glossary.md, versioned_docs/version-1.0/components/operate/deployment/schema-and-migration.md, versioned_docs/version-1.0/reference/glossary.md, versioned_docs/version-1.1/components/operate/deployment/schema-and-migration.md, versioned_docs/version-1.1/reference/glossary.md
This PR does two things to fix our internal link issues.
1. Add link check to build docs workflow to discover broken internal links before merge
- adds steps to setup local apache webserver to test links
- remove https redirect from htaccess to test locally
- add mime type for bpmn, this is already configured in our prod apache  but is needed for the local test
2. Fix broken anchor links on master
- remove non-existing anchor links
- update anchors links to new locations
- update links in all versions of docs
After we merge this PR we should be able to detect internal link issues before merging PRs. There is still the risk that external links are broken. I would opt not to check internal links on every PR, as that might be temporary issues and should block a PR, but I'm happy to be …
=> Fix wrong anchor links and add link checker to docs build workflow

docusaurus.config.js
closes #495 
Enable Java syntax highlighting.
=> Enable Java syntax highlighting

docs/guides/update-guide/026-to-100.md, versioned_docs/version-1.0/guides/update-guide/026-to-100.md, versioned_docs/version-1.1/guides/update-guide/026-to-100.md
=> fix(update-guide): add link to composable index templates

src/theme/Footer/index.js
Problem: Mixpanel events are sent twice, I think it's somewhere part of the react/docusaurus lifecycpe api
Workaround: send max one event per second
=> Mixpanel Events: fix duplicate events

docs/apis-clients/tasklist-api/directives/include.mdx, docs/apis-clients/tasklist-api/directives/skip.mdx, docs/apis-clients/tasklist-api/directives/specified-by.mdx, docs/apis-clients/tasklist-api/generated.md, docs/apis-clients/tasklist-api/inputs/task-query.mdx, docs/apis-clients/tasklist-api/inputs/variable-input.mdx, docs/apis-clients/tasklist-api/mutations/claim-task.mdx, docs/apis-clients/tasklist-api/mutations/complete-task.mdx, docs/apis-clients/tasklist-api/mutations/delete-process-instance.mdx, docs/apis-clients/tasklist-api/mutations/unclaim-task.mdx, docs/apis-clients/tasklist-api/objects/form.mdx, docs/apis-clients/tasklist-api/objects/task.mdx, docs/apis-clients/tasklist-api/objects/user.mdx, docs/apis-clients/tasklist-api/objects/variable.mdx, docs/apis-clients/tasklist-api/queries/form.mdx, docs/apis-clients/tasklist-api/queries/task.mdx, docs/apis-clients/tasklist-api/queries/tasks.mdx, docs/apis-clients/tasklist-api/queries/variable.mdx, docs/apis-clients/tasklist-api/queries/variables.mdx, docusaurus.config.js
New docs for Graphql API are generated.
For some reason our doc generator decided to remove exclamation marks and square brackets from type defitnitions, but we still have them on place in upper part of the page:
closes #458
=> Update Tasklist Graphql API docs

docs/self-managed/zeebe-deployment/security/client-authorization.md, docs/self-managed/zeebe-deployment/security/secure-client-communication.md, docs/self-managed/zeebe-deployment/security/secure-cluster-communication.md, docs/self-managed/zeebe-deployment/security/security.md, sidebars.js
This PR adds secure cluster communication documentation. It additionally renames the other security pages to make it explicit these are for client/gateway communication, as opposed to inter-cluster communication.
=> Add Zeebe secure cluster communication docs

docs/apis-clients/go-client/get-started.md, docs/apis-clients/go-client/index.md, docs/self-managed/zeebe-deployment/security/client-authorization.md, docs/self-managed/zeebe-deployment/security/secure-client-communication.md
I saw that the Go versions are quite out of date and use the old import path for the dependencies. 
closes #528
=> chore(go): bump go version and zbc import

docs/components/modeler/bpmn/user-tasks/user-tasks.md
This adds a description of how assignments can be defined for user tasks.
This documentation is part of https://github.com/camunda-cloud/zeebe/issues/8020 (currently planned for release 1.3).
The full spec of assignment definitions can be found here: https://github.com/camunda-cloud/zeebe/issues/8053.
closes #463
relates to #454
=> Describe assignment definitions for user tasks

docs/apis-clients/tasklist-api/directives/include.mdx, docs/apis-clients/tasklist-api/directives/skip.mdx, docs/apis-clients/tasklist-api/directives/specified-by.mdx, docs/apis-clients/tasklist-api/generated.md, docs/apis-clients/tasklist-api/inputs/task-query.mdx, docs/apis-clients/tasklist-api/inputs/variable-input.mdx, docs/apis-clients/tasklist-api/mutations/claim-task.mdx, docs/apis-clients/tasklist-api/mutations/complete-task.mdx, docs/apis-clients/tasklist-api/mutations/delete-process-instance.mdx, docs/apis-clients/tasklist-api/mutations/unclaim-task.mdx, docs/apis-clients/tasklist-api/objects/form.mdx, docs/apis-clients/tasklist-api/objects/task.mdx, docs/apis-clients/tasklist-api/objects/user.mdx, docs/apis-clients/tasklist-api/objects/variable.mdx, docs/apis-clients/tasklist-api/queries/form.mdx, docs/apis-clients/tasklist-api/queries/task.mdx, docs/apis-clients/tasklist-api/queries/tasks.mdx, docs/apis-clients/tasklist-api/queries/variable.mdx, docs/apis-clients/tasklist-api/queries/variables.mdx, docusaurus.config.js
Apparently we must merge the changes for upcoming version strictly AFTER the version was released. That's why I'm reverting it now.
This reverts commit f91941eb
=> Revert "chore(tasklist): update Graphql API docs (#518)"

docs/self-managed/optimize-deployment/setup.md, sidebars.js
relates to OPT-5827
Configuration page for Optimize CCSM. Please do not merge, we still need to test this as part of a complete docker-compose file with all other components, and also confirm that no config is missing here.
It's also not clear where documentation should live for shared components such as IAM/Zeebe/Elasticsearch. Open to suggestions for how to make this clearer and/or more complete
=> feat(optimize): add ccsm configuration setup documentation

docs/components/concepts/expressions.md, versioned_docs/version-1.1/components/concepts/expressions.md, versioned_docs/version-1.2/components/concepts/expressions.md
This updates the available expressions overview in the expressions concept to align with what is available in each version.
Since 1.1, some new tasks are supports that sue the `job type` and `retries` like service task: business rule task, script task and send task. This documentation change has been made for both the current docs as well as the versioned docs from 1.1 onwards.
Since 1.3 (latest), user tasks now support assignments which can be specified using 2 attributes: `assignee` and `candidateGroups`. Both can be specified as static value and as expression. 
closes #566
=> Update available expressions overview in expressions concept

CONTRIBUTING.MD
Updated broken link in the Contributor Guide
=> fix(docs): correct link formatting

docs/guides/update-guide/120-to-130.md
This PR edits the update from 1.2.0 to 1.3.0 guide to add a warning to skip version 1.3.0 and 1.3.1 due to this [critical issue](https://github.com/camunda-cloud/zeebe/issues/8611).
Ideally, we should push and release this as soon as possible so users are aware of this notice as soon as possible.
=> Add update warning about faulty 1.3.0 and 1.3.1 versions

src/pages/contact.md
https://github.com/camunda-cloud/issues/issues is internal and no longer accessible for community members (customers and users) to use. We will now direct bugs and feature requests to Slack and the forums.
=> docs(contact): direct bugs and feature requests to community

docs/guides/message-correlation.md, docs/self-managed/zeebe-deployment/docker/install.md
Removing references to zeebe-docker-compose because it is depricated
=> Removing deprecated references

docs/guides/update-guide/introduction.md, docs/self-managed/zeebe-deployment/operations/backups.md, docs/self-managed/zeebe-deployment/operations/update-zeebe.md, sidebars.js
[Rendered](https://github.com/camunda-cloud/camunda-cloud-documentation/blob/zeebe-cold-backups/docs/self-managed/zeebe-deployment/operations/backups.md)
closes #581
=> Document Zeebe Cold Backups

docs/guides/update-guide/120-to-130.md
Update note on critical issue found on versions 1.3.0 to 1.3.3.
This can be merged as soon as reviewed
Related to https://github.com/camunda-cloud/operate/issues/2214
=> docs(operate): Update note for critical issue fixed on 1.3.4

docs/components/modeler/bpmn/business-rule-tasks/business-rule-tasks.md, docs/components/modeler/bpmn/message-events/message-events.md, docs/components/modeler/bpmn/receive-tasks/receive-tasks.md, docs/components/modeler/bpmn/script-tasks/script-tasks.md, docs/components/modeler/bpmn/send-tasks/send-tasks.md
Originates of: https://github.com/camunda-cloud/camunda-cloud-documentation/issues/610
I think it quite a good step to unify all the description for task-types which behave like service-tasks. 
Unified variable-mapping descriptions:
- business-rule-task
- script-tasks
- send-tasks
@korthout please let me know if I am missing a task type. 👍
=> Unified the variable-mapping description

static/.htaccess
* This will allow us to use the .../desktop-modeler/ URL as entry point
when linking to desktop modeler
* This allows us to dynamically adjust in the future which entry point
will be used, without changes in the linking docs
=> feat(.htaccess): provide static route for desktop-modeler

docs/components/modeler/desktop-modeler/connect-to-camunda-cloud.md, docs/components/modeler/desktop-modeler/model-your-first-diagram.md, docs/components/modeler/desktop-modeler/start-instance.md
* This brings the `release-1.4.0` and `master` branch back in sync for the DesktopModeler
* This updates and clarifies the basic tutorial texts
* No content changes, just polishing and corrections
=> chore(desktopModeler): polish basic tutorial texts (#685)

docs/components/operate/index.md
Renaming Camunda Cloud to Camunda Platform 8. Smaller PR than I was expecting!
=> docs(operate): renaming

docs/components/modeler/desktop-modeler/connect-to-camunda-cloud.md
* This makes the desktop modeler guide easier to read. 
* `Connect to Camunda Platform 8` is rather unspecific (what does connect mean?). Actually this page is about deploying after all and nothing else
=> chore(desktopModeler): change title of deploy diagram page

docs/apis-clients/cli-client/get-started.md, docs/apis-clients/cli-client/index.md, docs/apis-clients/cloud-console-api-reference.md, docs/apis-clients/go-client/get-started.md, docs/apis-clients/go-client/index.md, docs/apis-clients/java-client/index.md, docs/apis-clients/java-client/zeebe-process-test.md, docs/apis-clients/overview.md, docs/apis-clients/public-api.md
I did not include `docs/apis-clients/cli-client/assets/gettingstarted_quickstart_advanced.bpmn` in the renaming, although it looks like the name of the process model could be changed with no issues.
=> docs(apis-clients): renaming

docs/apis-clients/cloud-console-api-reference.md, docs/components/cloud-console/introduction.md, docs/components/cloud-console/manage-clusters/manage-alerts.md, docs/components/cloud-console/manage-organization/manage-users.md, docs/components/cloud-console/manage-organization/update-billing-reservations.md, docusaurus.config.js, sidebars.js
- Cloud Console in the sidebar is now just Console
- Cloud Console almost everywhere else is “Camunda Platform Console” (no 8, to match the UI)
- Cloud Console API clients is Console API clients
=> Renaming console c8

docs/components/concepts/incidents.md, docs/components/modeler/bpmn/business-rule-tasks/business-rule-tasks.md, docs/components/modeler/bpmn/manual-tasks/manual-tasks.md, docs/components/modeler/bpmn/user-tasks/user-tasks.md
Camunda Cloud 1.4 will add support for business rule tasks with a called decision extension element. This PR adds the related documentation on how to define such a business rule task and what its behavior is within the process execution, as well as how it links the business rule task to a DMN decision.
It also clearly separates the main implementation (calling a DMN decision) and the possibility to provide alternative implementations (using a job worker).
closes #421
=> Document business rule task with called decision

docs/self-managed/zeebe-deployment/security/secure-client-communication.md
@menski I only found one place where we didn't reference TLS by abbreviation, so I went ahead and updated it. Most of the current documentation (I assume since your original PR was opened) uses the abbreviation 😄
=> docs(zeebe-deployment): add TLS abbreviation

docs/apis-clients/cli-client/get-started.md, docs/apis-clients/cli-client/index.md, docs/apis-clients/go-client/get-started.md, docs/apis-clients/go-client/index.md, docs/apis-clients/grpc.md, docs/apis-clients/java-client-examples/process-deploy.md, docs/apis-clients/java-client/zeebe-process-test.md, docs/guides/utilizing-forms.md, docs/reference/announcements.md
This PR:
- documents the new DeployResource RPC
- deprecates the existing DeployProcess RPC
- updates all zbctl, Go-client and Java-client usage in the docs to their respective new uses of this RPC.
closes #707 
closes #708
=> Document new DeployResource RPC and its usage

docs/self-managed/tasklist-deployment/configuration.md
* Add description for configuration of TLS to Zeebe for Tasklist
Sorry for the late contribution, we had this for Operate but forgot for Tasklist.
Can you merge if everything is ok? Because I will be on vacation the next weeks.
Related with https://github.com/camunda-cloud/tasklist/issues/1632
=> Add TLS connection to Zeebe configuration

howtos/documentation-guidelines.md
Running the documentation does not allow testing redirects. The rules in .htaccess can be used with online tooling. To help people with this an example tool has been added to the guidelines.
=> Add hint for testing rewrite rules to the guidelines

docs/guides/assets/react-components/create-cluster.md, docs/guides/automating-a-process-using-bpmn.md, docs/guides/getting-started-orchestrate-human-tasks.md, docs/guides/getting-started-orchestrate-microservices.md, docs/guides/getting-started/connect-to-your-cluster.md, docs/guides/getting-started/create-camunda-cloud-account.md, docs/guides/getting-started/deploy-your-process-and-start-process-instance.md, docs/guides/getting-started/model-your-first-process.md, docs/guides/getting-started/monitor-your-process-in-operate.md, docs/guides/getting-started/setup-client-connection-credentials.md, docs/guides/improve-processes-with-optimize.md, docs/guides/introduction-to-camunda-cloud.md, docs/guides/message-correlation.md, docs/guides/operating-the-camunda-cloud-stack-on-kubernetes.md, docs/guides/setting-up-development-project.md, docs/guides/update-guide/introduction.md, docs/guides/utilizing-forms.md
In `/guides/update-guide/*` I did not do a rename because these versions are theoretically part of Camunda Cloud. If that's incorrect, let me know and we can adjust. It just felt odd to call something "Camunda Platform 8 1.2" 😆
=> docs(guides): renaming c8

docs/reference/notices.md
Adds a security notice for Zeebe regarding Spring4Shell. 
Some notes for the review
* Patched versions are not yet released, so I've left the "solution" part very generic.
* Older versions of Zeebe are also bundling unpatched versions of Spring but I've not mentioned them here since we don't support them anymore.
* We _could_ use more reassuring language when explaining that Zeebe is very likely not at all affected.
* We should probably extend this notice with information from other components like Operate and Tasklist
=> Add security notice for Zeebe & Spring4Shell

README.md
Addresses #813 
Replaces the previously broken brand logo with a new one:
=> docs(branding): replace broken logo in README

src/pages/styles.module.css
Addresses #817 
The source images for the feature icons are 150x150. They were previously displaying as 200x200, resulting in some low-res stretchiness. This PR scales them down, displaying them as slightly smaller than the sources (130x130) to better align with the proposed UI from marketing (which can be found in the slack conversation linked below). 
There is still a slight bit of blurriness to the icons, the edges don't seem totally sharp. My interpretation is that they were built that way intentionally, but if people still find it unsettling I can push for marketing to make new images with sharper edges. 
Before:
After: 
See [this thread](https://camunda.slack.com/archives/C01UMP0V17Z/p1649780222187189) for history. 
I've added reviewers based on the original slack conversation, with …
=> style(features): scale feature icons down a bit

.github/workflows/build-docs.yaml, src/css/custom.css
This PR scales down the size of navbar items at screen resolutions larger than mobile (996px) but smaller than most desktops (~1140px). "Scaling down" includes slightly reducing the font-size, horizontal padding, and size of the "self-managed" icon: 
https://user-images.githubusercontent.com/1627089/163476930-b5df483b-617f-459f-bdc0-a851eac5ce49.mov
At screen resolutions on the small side of desktop, but larger than the mobile breakpoint, the navbar items get a bit scrunchy and unpleasant: 
- The specific resolutions affected are 996px to ~1140px. At 996 and smaller, the "mobile" nav menu shows, which makes this problem go away. At 1140px and above, there's enough space available that items aren't forced to wrap. 
- The self-managed icon was reduced in size because at its original size, …
=> style(navbar): scale navbar items down in resolutions between mobile and desktop

package-lock.json, package.json
Pins the docusaurus dependencies to version 2.0.0-beta.15, until we can upgrade them properly. 
There are at least two breaking changes introduced in newer versions of the 2.0 beta that have been reported in the Camunda slack. They appear as these errors during `npm start`: 
```
[ERROR] ValidationError: "algolia.appId" is required. If you haven't migrated to the new DocSearch infra, please refer to the blog post for instructions: https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration
```
and
```
[ERROR] ValidationError: colorMode.switchConfig is deprecated. If you want to customize the icons for light and dark mode, swizzle IconLightMode, IconDarkMode, or ColorModeToggle instead.
```
Pinning the dependencies to version 2.0.0-beta.15 will force that version to be installed, …
=> chore(deps): pin docusaurus dependencies

docs/apis-clients/overview.md
Adding Micronaut to https://docs.camunda.io/docs/apis-clients/overview/
=> Add Micronaut to list of community clients

.github/workflows/publish-c8.yaml, .prettierignore
1. Adds two build artifact folders to the .prettierignore. They are generated by docusaurus, and excluded from git, and not worth us spending time formatting. 
2. Updates the formatting for a github action
This work is a follow-up to #815. @korthout noticed those folders being formatted in that PR, but we fixed it here in a follow-up for ease of PR review.
=> chore(format): exclude build artifacts from prettier

docs/apis-clients/grpc.md, docs/apis-clients/java-client/job-worker.md, docs/components/zeebe/technical-concepts/internal-processing.md, docs/self-managed/zeebe-deployment/operations/backpressure.md, docs/self-managed/zeebe-deployment/operations/backups.md, docs/self-managed/zeebe-deployment/operations/index.md, docs/self-managed/zeebe-deployment/operations/metrics.md, docs/self-managed/zeebe-deployment/operations/resource-planning.md, static/.htaccess
Thanks @falko for your feedback! I've added you as a reviewer for this PR. If you have a chance to review that would be great. 
@christinaausley in our docs we use both backpressure and back-pressure. I didn't correct this and instead added keywords to the frontmatter on both pages to handle this spelling. Can you check if this is something that is standardized in the software engineering space to use (or not use!) the hyphen? We should standardize on something, but whatever we decide we should keep the keywords as-is to assist with search.
=> Feedback on backpressure pages

.github/workflows/build-docs.yaml, CONTRIBUTING.MD, package.json
Adds a step to the build-docs workflow to check prettier formatting. This is a follow-up to #815.
- add a git pre-commit hook to auto-format changes (coming soon)
- format remaining folders in the docs (coming later, de-prioritized for now)
=> chore(ci): verify prettier formatting in build-docs workflow

docs/guides/update-guide/120-to-130.md
This PR documents how to upgrade the monitoring configuration from 1.2.x to 1.3.x. It doesn't go in depth into how to configure the Spring server, but instead mostly focuses on what was previously feasible and how to configure it similarly.
closes #861
=> Document how to upgrade the old monitoring config

docs/components/modeler/web-modeler/connectors/available-connectors/sendgrid.md
The example given only showed using static values for the dynamic template in sendgrid.  With this example users will see how to use process variables as well. Addresses issue #882
=> Add dynamic variable section to Sendgrid

product-links.txt
In order to make sure that we no longer break Zeebe readme, we need to check the links we use in the Readme.
See related issue https://github.com/camunda/zeebe/issues/9295#issuecomment-1118384455
=> Add zeebe readme links

package-lock.json, package.json
Removes the `color` dependency, which I don't think we are using. 
Causes no obvious regressions when I run the docs locally.
I'm tagging reviewers that might have more context about why it was pulled in, based on my spelunking described below.
I was going through dependabot PRs and saw #768, a major-version bump for the `color` package. I wanted to update it, but I like to know where things are used so I can smoke test them before I merge dependency updates. I didn't find anywhere that `color` was used.
I searched for `"color"`, `'color'`, `color(`, and `color.`, and saw no significant results. I attempted to search for the whole word `color` but there were too many results to meaningfully identify its usage.
These first two tell me that we never import or require this dependency (as in …
=> chore(deps): remove unused 'color' dependency

docs/components/modeler/bpmn/multi-instance/multi-instance.md
The BPMN 2.0 specification defines the following properties of a multi-instance body instance:
- `numberOfInstances`: The total number of instances created.
- `numberOfActiveInstances`: The number of instances currently active.
- `numberOfCompletedInstances`: The number of instances already completed.
These properties are available for use in the `completionCondition` expression. 
closes #884
=> Document new multi-instance properties for completion condition

.github/workflows/build-docs.yaml, .github/workflows/publish-stage.yaml, docusaurus.config.js
Partially addresses #634
The default branch in GitHub has changed from `master` to `main`. This PR updates the few places we have specified the `master` branch. 
(Bonus: the editUrl for docusaurus was incorrect since we moved the docs from the camunda-cloud to camunda org! So I fixed that here, too.)
=> chore: rename branch master to main

docs/guides/migrating-from-camunda-platform-7.md
Added content from https://camunda.com/blog/2022/05/what-to-do-when-you-cant-quickly-migrate-to-camunda-8/ to the migration guide.
Not sure if we need to copy over the images - at the moment I just referred to the one existing on the Camunda blog. Let me know what you think!.
=> Added content from blog post to migration guide

docs/guides/assets/react-components/create-cluster.md
According to consulting feedback and given selecting a region is not available in trial plans, removing from guides content.
=> removing regions detail from guides content

howtos/publish-documentation.md, howtos/setup.md
As discussed in person with @akeller, our setup docs for this project are a little vague. This PR expands them with more information about _why_ and _when_ you'll want to do certain things.
It also brings a couple details up to date -- (1) master is now main, and (2) we don't deploy to github pages anymore.
=> docs: improve setup and local development instructions

.github/workflows/build-docs.yaml
Addresses [this comment](https://github.com/camunda/camunda-platform-docs/pull/903#issuecomment-1145987703).
PRs from forks were not running our build-docs CI check, because it was triggered only by `push` events. 
This PR...
1. Triggers build-docs for `pull_request` events, too
2. But only if the pull request is coming from a fork, so that we don't run duplicate checks for internal PRs. 
Maybe not -- they'd run concurrently, so it wouldn't slow us down in that regard. But unnecessary compute cycles are unnecessary compute cycles, and it's nice when CI runs exactly when/how we want it to.
After this PR is merged, I'll reach out on #903 and ask Tobias to rebase that PR on main. We should then see the build-docs check run on that PR!
1. Check this PR itself. It's running a check for `push`, …
=> improvement(ci): run build-docs CI check for external pull requests

package-lock.json, package.json
While investigating the build failure in #919, I got curious about whether this dependency is even needed. 
I don't think it is, so this PR removes it. 
MDX support [is built into docusaurus](https://6220d0362c028b000827f851--docusaurus-2.netlify.app/docs/2.0.0-beta.15/markdown-features/react), even in the version we're using. I suspect that maybe it initially wasn't, and that's why the dependency [was added early on](https://github.com/camunda/camunda-platform-docs/blame/c13600365b206bf4d5de6e779e249f56063730dc/package.json).
I've tested the site locally, and found that docs that are using MDX render fine without this dependency. For example, the tabs we have throughout the site:
=> chore: remove unused mdx-js/react dependency

docs/apis-clients/grpc.md
As mentioned in https://forum.camunda.io/t/zeebe-git-examples-unaccessible/38459/5, users may be interested to use the api in other clients as well.
=> Add a link to the proto file

docs/apis-clients/grpc.md
The gRPC message `CreateProcessInstanceRequest` now supports start instructions which allow a user to switch from starting at the default none start event and instead, start 1 or multiple tokens at specific elements in the process. See https://github.com/camunda/zeebe/issues/9366 for more details on the feature.
This updates the Zeebe API (gRPC) documentation with the new start instructions definition. It also rectifies a previous change that wasn't pulled into the docs.
Note that no new errors are introduced for this feature. This may change in the future as command rejection reasons will be expanded.
This feature will be part of the upcoming 8.1 release, and so this PR targets the corresponding `release_8_1` branch.
closes #943
=> Document start instructions for CreateProcessInstanceRequest gRPC message

docs/apis-clients/go-client/get-started.md
We added a new getting started guide for the Go client, but forgot to update the link in the docs.
One thing to note: the code in the getting started guide on GitHub, and the one here in the docs, differs. I thought about aligning them, but decided against, primarily because the [code on GitHub](https://github.com/camunda/camunda-platform-get-started/tree/main/go) is more of a complete sample application, and the one here in the docs is just showing how to do specific things.
=> Link to new Go getting started guide

docusaurus.config.js, package-lock.json, package.json, sidebars.js, versioned_sidebars/version-0.25-sidebars.json, versioned_sidebars/version-0.26-sidebars.json, versioned_sidebars/version-1.0-sidebars.json, versioned_sidebars/version-1.1-sidebars.json, versioned_sidebars/version-1.2-sidebars.json, versioned_sidebars/version-1.3-sidebars.json
The main goal of this PR is to update from docusaurus beta-15 to beta-16, but it includes a couple side-quests required by this update: 
* Configures a standalone Algolia DocSearch instance
* Removes empty sidebar items
Note that there is no link in the sidebar titled "Create decision tables using DMN" under Next Steps. This doc was merged but not yet published:
Note that there are no search results for the new article, searched by exact title: 
Note that the DMN article now appears under Next Steps, so it's live:
Note that the search results locally, pointed at the new algolia instance, found the new doc by exact title:
=> chore(deps): Update docusaurus from beta-15 to beta-16, including configuring new Algolia instance

docs/components/best-practices/architecture/sizing-your-environment.md
A recent commit introduced a table format that prettier didn't like. This PR corrects it, to get builds back on track.
=> chore(format): correct prettier formatting of table

docs/guides/update-guide/800-to-810.md, docs/guides/update-guide/introduction.md, docs/self-managed/zeebe-deployment/operations/network-ports.md, docs/self-managed/zeebe-gateway-deployment/the-zeebe-gateway.md, sidebars.js
In this PR I made description about deprecating the `contactPoint` property and how to migrate to the new `initialContactPoints` property.
Closes #958.
=> Deprecate the contact point property

docusaurus.config.js, package-lock.json, package.json, src/theme/ColorModeToggle/index.js
Partially addresses #1024 
This PR updates docusaurus dependencies from beta-16 to beta-17. As a necessary side-quest due to feature deprecation, it rewrites our dark-mode suppression according to [docusaurus's recommendation](https://github.com/facebook/docusaurus/pull/6771). 
In other words, what it looks like if I delete the swizzled ColorModeToggle from this PR, to show that the file is actively doing something: 
https://user-images.githubusercontent.com/1627089/177629810-a64172f0-4911-43a0-9806-eb702ce332b2.mov
=> chore(deps): Update docusaurus from beta-16 to beta-17, including rewriting dark mode suppression

docs/components/best-practices/architecture/understanding-human-tasks-management.md
The numbers in the callouts were `1, 3, 3` instead of `1, 2, 3`.
=> Fix callout number related to tasklist-mockup.png

docs/components/best-practices/development/testing-process-definitions.md
As being recommended by the JUnit 5 User Guide. 
See: https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-classes-and-methods 
(This was brought up during a meetup talk I was giving about this topic. I thought it would be good to improve our documentation in that sense as well)
=> Omit public modifier for test classes

docs/components/modeler/bpmn/timer-events/timer-events.md
Adds documentation about the timer cycle with start time. E.g. `R/2022-01-01T10:00:00+02:00[Europe/Berlin]/P1D`
closes #986
=> Add timer cycle with start time

docs/components/modeler/bpmn/timer-events/timer-events.md
Reverts camunda/camunda-platform-docs#1084
That PR was not supposed to target `main`, but `release_8_1`.
=> Revert "Add timer cycle with start time"

CONTRIBUTING.MD
Updates the CONTRIBUTING.md guide to make it clear that, as discussed in #1089, asking for someone else to format changes is an option.
=> docs(contributing): Asking for us to format your changes is an option

.github/workflows/build-docs.yaml, .github/workflows/linkcheck.yaml
We've been noticing that link-checking is suddenly sporadically taking a very very long time ([example 1](https://github.com/camunda/camunda-platform-docs/actions/runs/2746917140), [example 2](https://github.com/camunda/camunda-platform-docs/actions/runs/2751525426), [example 3](https://github.com/camunda/camunda-platform-docs/actions/runs/2752589151)), but we don't really know why. 
This PR adds [the debug flag](https://github.com/filiph/linkcheck/blob/master/lib/linkcheck.dart#L204) to our link-checking steps, with the hopes of gaining insight into why the link-checking is taking so long. 
I anticipate this change to be temporary, and we'll revert after gaining (or not gaining) insight.
=> debug(ci): enable debug flag for link checking

static/.htaccess, versioned_docs/version-0.25/components/overview.md, versioned_docs/version-0.26/components/overview.md, versioned_docs/version-1.0/components/overview.md, versioned_docs/version-1.1/components/overview.md, versioned_docs/version-1.2/apis-clients/overview.md, versioned_docs/version-1.2/components/overview.md, versioned_docs/version-1.2/self-managed/overview.md, versioned_docs/version-1.3/apis-clients/overview.md, versioned_docs/version-1.3/components/overview.md, versioned_docs/version-1.3/self-managed/overview.md, versioned_sidebars/version-0.25-sidebars.json, versioned_sidebars/version-0.26-sidebars.json, versioned_sidebars/version-1.0-sidebars.json, versioned_sidebars/version-1.1-sidebars.json, versioned_sidebars/version-1.2-sidebars.json, versioned_sidebars/version-1.3-sidebars.json
Based on https://github.com/camunda/camunda-platform-docs/issues/1101, all main nav IDs changed in current version must be changed across all relevant versions. This PR should resolve this.
=> Docs versions fix

package-lock.json, package.json
This PR brings the docusaurus dependencies fully up to date, with version rc.1! 
**Update:** I'm not able to reproduce the whitespace regression anymore. I don't know what was going on before, or what's going on now that it's fixed. Once this is merged I'll peek at staging to see what it looks like, and decide what to do if it includes the regression.
<details>
<summary>
Out-of-date details about this whitespace regression
</summary>
One small visual regression is introduced in this PR -- there is now _always_ white space below the footer, on every page: 
I'd noticed this issue on _some_ pages prior to this update, especially ones with long content, but now it seems to be everywhere. 
I'm not sure which change in the changelogs (https://docusaurus.io/changelog/2.0.0-beta.21, …
=> chore(deps): update docusaurus to rc.1

docs/self-managed/zeebe-deployment/operations/metrics.md
Remove `zeebe_pending_jobs_total` and `zeebe_running_process_instances_total`.
Change `zeebe_stream_processor_events_total` to `zeebe_stream_processor_records_total`. 
See: https://forum.camunda.io/t/missing-metrics-related-to-process-processing/38852/2
=> Remove deprecated metrics. Update metric.

docs/self-managed/zeebe-deployment/configuration/configuration.md
This PR removes left over from the migration of the old Zeebe docs, which included some old unsupported include directive.
=> Remove old include directive

.github/workflows/build-docs.yaml, .github/workflows/linkcheck.yaml
Closes #1103.
This reverts commit 8a04615714e51c2d0085ce2927290fdaade9be97, which introduced verbose logging for link-checking. It seems that the slow link-checking was either (a) temporary, or (b) resolved by #1097.
=> chore: Revert "debug(ci): enable debug flag for link checking (#1098)"

docs/components/modeler/bpmn/user-tasks/user-tasks.md
Tasklist was `[Tasklist]` without a URL in a couple places on this page.
=> docs(chore): Add links to Tasklist

docs/self-managed/platform-deployment/kubernetes-helm.md, docs/self-managed/platform-deployment/kubernetes.md, docs/self-managed/platform-deployment/openshift-helm.md, docs/self-managed/platform-deployment/openshift.md, docs/self-managed/platform-deployment/platform-8-deployment.md, sidebars.js
**Description**
This PR adds documentation for self-managed platform deployments on OpenShift. I followed the existing pattern of having a general Kubernetes guide (without Helm) and a specific Helm chart deployment guide.
Both guides have some overlap, I guess, but I think generally the information is useful. I'm happy to also merge them and focus on a single Helm specific guide, ignoring non-Helm deployments on OpenShift :shrug: 
I also didn't want to link too much to the values and other files in the repository, as I wanted the documentation here to be as self-contained as possible. I still linked to the repository as a quick-start for impatient users, while taking more time to explain here in these docs. Let me know what you think.
=> Add OpenShift documentation

src/css/custom.css
This PR updates the styling of our Osano cookie-consent popup to match exactly the code given to us by marketing.
It changes the styling in a couple subtle ways, enumerated below this image (which shows the updated version on the left, and the original on the right): 
1. A different color for the Privacy Policy link
2. Rounded corners on the Accept/Deny buttons
=> style: update cookie consent styling

docs/components/modeler/bpmn/timer-events/timer-events.md
Adds documentation about the timer cycle with cron expressions.  E.g. `0 0 9-17 * * MON-FRI`
closes #1117
=> Add timer cycle with cron expressions

docs/self-managed/identity/deployment/configuration-variables.md
Resolves https://github.com/camunda-cloud/identity/issues/938
This PR adds the new configuration variable in Identity that allows a user to configure Identity to run using a subpath, for example: `http://adomain.com/identity`.
I've elected to use a `:::note` block to suggest to the user a caveat which is in place when using a subpath, this caveat is that there is a requirement to either be on localhost or to have a connection which is HTTPS.
I had initially anticipated a user guide addition but at this time I don't feel it would add any great value to the Identity docs so I have left out that change.
This change has been available since 8.1.0-alpha3 so it does not need to be backported to the 8.0 docs :)
=> docs(identity): reference new base path variable in configuration options

howtos/documentation-guidelines.md
Follow-up to #1118.
This PR updates our documentation guidelines to add clarity in regards to versioned documentation.
=> docs: update documentation guidelines based on new versioning strategy

docs/self-managed/platform-deployment/kubernetes.md, versioned_docs/version-1.3/self-managed/zeebe-deployment/kubernetes/index.md, versioned_docs/version-8.0/self-managed/platform-deployment/kubernetes.md
The wording of the official support platforms is not correct. There is no support for any other cloud platform, only stock K8s and OpenShift.
=> Fix: reword the official support of Helm charts

docs/components/modeler/about-modeler.md
In reference to https://github.com/camunda/camunda-platform-docs/issues/990, adding admonition to clarify usage of XML editing tab in Desktop Modeler rather than Web Modeler.
=> clarify xml editing in desktop modeler

docs/components/integration-framework/connectors/out-of-the-box-connectors/slack.md, versioned_docs/version-8.0/components/integration-framework/connectors/out-of-the-box-connectors/slack.md
I added a line right after the compose image directing users to Slack's documentation on how to format messages using markdown
=> Include link to Slack docs regarding message formatting

package-lock.json, package.json, src/mdx/expandVersionedUrl.js, src/mdx/expandVersionedUrl.spec.js, src/mdx/versionedLinks.js
Addresses #1167.
In #1166, we found that [markdown links across docs instances](https://github.com/camunda/camunda-platform-docs/pull/1166#discussion_r947018939) was going to introduce a ton of friction.
This PR introduces an MDX plugin that should remove this friction. Instead of needing to specify the version of the other docs instance to link to, we can now use a token like `$docs$` to have docusaurus interpret the version based on the source file. 
For example, if we have a link that goes to `$optimize$/what-is-optimize`, the target URL will be expanded to....
* `optimize/next/what-is-optimize` when the source file is in the `/docs/` folder
* `optimize/what-is-optimize` when the source file is in the `/versioned_docs/version-8.0` folder
* `optimize/3.7.0/what-is-optimize` when the …
=> feat: MDX plugin to interpret link target URLs based on source file directory

.github/workflows/sync-board.yaml
A collaboration with @akeller.
Addresses #1154 
This PR rewrites the `sync-board` workflow to:
1. Listen for reviewers to be assigned to a PR.
2. If the assigned reviewer isn't @akeller or @christinaausley, stop.
3. Otherwise, add the PR to the Documentation Board project, and set its status to In Review.
[Here is an example of a successful workflow run](https://github.com/camunda/camunda-platform-docs/actions/runs/2891812456).
1. We initially attempted to use existing actions to do this:
* [https://github.com/actions/add-to-project](actions/add-to-project) was able to add the PR to the project, but it does not support also setting the Status field to In Review.
* [https://github.com/alex-page/github-project-automation-plus](alex-page/github-project-automation-plus) is supposed to be …
=> feat: add PRs to Documentation board in In Review column when review requested from Amara or Christina

src/pages/index.js
There are two H1's on the home page and I'm embarrassed I did this, but more embarrassed that Bing Webmaster Tools caught it before any of us did... OOPS! The second one was changed to H2. This will need to be live for us to recheck in Bing Webmaster Tools, but you can also see it in the updated HTML.
No
Whenever, but this may be impacting SEO so sooner rather than later would be good.
=> Remove second H1 on the home page

versioned_docs/version-8.0/apis-clients/operate-api/index.md
Typo - @tobiasschaefer caught this in #1216, but we should also fix it in the 8.0 docs.
=> Typo in Operate API docs (8.0)

package.json
A Friday afternoon (my time) gift [for @tmetzke](https://github.com/camunda/camunda-platform-docs/issues/1104#issuecomment-1229865319): 
Updates the pre-commit hook to run prettier against _only_ files that have changed, for much faster commits.
I was using lint-staged incorrectly! In a case of over-pursuing the DRY principle, I configured lint-staged to run `npm run format`, to avoid defining what "format" meant in two places. 
But the `format` script passes `.` as the path to prettier, resulting in the entire codebase being formatted even for a one line change. 
lint-staged passes a glob for the committed files to the configured command...this change takes advantage of that, and now the hook will only format the files being committed.
=> fix: use lint-staged correctly (to decrease commit time)

docs/apis-clients/optimize-api/external-variable-ingestion.md
relates to OPT-5974
Feature is no longer in beta. Remove the flag
N/A
Next release
=> chore(docs): remove beta flag from external variable API docs

docs/components/modeler/bpmn/inclusive-gateways/inclusive-gateways.md
This PR makes some additional changes to the new inclusive gateway documentation, to:
- align the doc with the exclusive gateway docs
- improve the grammar
- highlight the intent of the images in the alt-text
- place concepts together for easier reading
- clarify behavior
🤷 
It's part of 8.1
=> Follow-up on inclusive gateway documentation

docusaurus.config.js
Child of #1234 
This will be merged into #1234 before #1234 is merged into `main`.
While building the `next` versions of the docs, we removed these folders from the sitemap to avoid a constantly changing (and usually incorrect) sitemap. 
This PR reverts that commit, adding the `docs/next` and `optimize/` folders back to the sitemap.
=> chore (optimize/3.8.0): revert "remove vNext and optimize docs from sitemap"

src/theme/NavbarItem/index.js
Child of #1234 
My intention is to merge this into #1234 before #1234 is merged into `main`. 
I expect link-checking to fail on this PR, because the redirect rules for moved docs are not defined yet.
Customizes the version selector in the top navigation so that it displays the correct versions based on which doc is being viewed. For Optimize docs, emits 3.8.0 and next....for all other docs, emits 8.0, next, and all the other c8 versions.
=> feat: show correct versions in navbar based on which docs you're viewing

src/theme/Footer/index.js
Mixpanel events haven't been sending since about the time that #1114 was published. This PR does two things: 
1. imports `mixpanel` because that line was removed in #1114 and shouldn't have been.
2. Adds some `console.log` statements for silently-caught errors, to help provide details when testing in production.
The big challenge with this is that the only way for us to test Mixpanel events is in production. (Maybe staging too? I'm not sure.) So in order to see if this fix works, we'll need to merge, and maybe also deploy to production. 
Immediately, so that I can test it in production.
=> fix?: attempt to fix mixpanel events

src/theme/Footer/index.js
In #1270, we introduced some logging for the Mixpanel code that uses exceptions for control flow. This PR reverts one log statement since it's purely for control flow, and reframes the other as something valuable for diagnosing legitimate problems.
=> chore: tune logging of errors for mixpanel logic

versioned_docs/version-1.1/components/clients/java-client/index.md, versioned_docs/version-1.2/apis-clients/java-client/index.md, versioned_docs/version-1.3/apis-clients/java-client/index.md
Based on https://github.com/camunda/camunda-platform-docs/issues/1009. Renaming `io.zeebe` to `io.camunda` we seemed to rename the text but not the actual link, causing the links to send users to old versions of the Javadocs.
=> change io.zeebe to io.camunda

versioned_docs/version-8.0/components/modeler/desktop-modeler/element-templates/using-templates.md
Add `using-templates.md` changes from #1252 & #1272 
Nope
This is a last-minute confirmation ahead of today's release.
=> docs(8.0): add using-templates changes

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
Related to https://github.com/bpmn-io/internal-docs/issues/636
Documenting the new `zeebe:Property` element template property supported as of Camunda Modeler 5.3.
Product Hub: https://github.com/camunda/product-hub/issues/335
No.
Will be supported across the entire stack once Camunda 8.1 is released.
=> Document `zeebe:Property` Element Template Property

docs/self-managed/identity/deployment/configuration-variables.md
With the merging of https://github.com/camunda-cloud/identity/pull/956 - the Identity component is now able to initialise with a preset for the Web Modeler component. 
This PR updates the values described to the user.
Not for this change specifically.
The preset support for Web Modeler is in the 8.1.0-alpha5 release so this change is fine to go into the `next` version of docs, and eventually in the 8.1 release.
=> docs(identity): add reference to the webmodeler preset placeholder

docs/apis-clients/grpc.md, docs/components/concepts/job-workers.md
Documents the Job retry backoff mechanism.
closes #964 
N/A
8.1.0 release.
=> Document job retry backoff

docs/reference/supported-environments.md, docs/self-managed/optimize-deployment/migration-update/3.9-preview-to-3.9.md
relates to OPT-6384
Optimize will no longer support ES 7.10-7.12 from our 3.9.0 release. This change amends the supported environments accordingly and adds a note to our migration notes for people updating from a previous version.
N/A
With the next release (Optimize 3.9.0 / Cloud 8.1.0)
=> chore(es): remove support for Elasticsearch 7.10-7.12

docs/components/integration-framework/connectors/custom-built-connectors/connector-sdk.md, docs/guides/update-guide/connectors/010-to-020.md, docs/guides/update-guide/connectors/introduction.md, docs/guides/update-guide/introduction.md, sidebars.js, versioned_docs/version-8.0/components/integration-framework/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.0/guides/update-guide/connectors/010-to-020.md, versioned_docs/version-8.0/guides/update-guide/connectors/introduction.md, versioned_docs/version-8.0/guides/update-guide/introduction.md, versioned_sidebars/version-8.0-sidebars.json
Moving to Connector SDK version 0.2. This moves from an imperative validation and secrets style to a declarative one.
Also, the SDK introduces a new validation module.
This can only be merged when all other tasks in https://github.com/camunda/team-connectors/issues/67 are done and the SDK version 0.2.0 is released.
When Connector SDK version 0.2.0 is released. We will ping here manually. Our aim is to release Sep 19 or Sep 20.
=> feat(connectors): move to Connector SDK 0.2

docusaurus.config.js
We have some protobuf codeblocks. Docusaurus does not enable syntax highlighting for these by default. This PR enables this.
Before:
After:
N/A
Whenever, it doesn't change any of the content, just makes it more readable.
=> Enable protobuf syntax highlighting

docs/self-managed/identity/deployment/configuration-variables.md, versioned_docs/version-8.0/self-managed/identity/deployment/configuration-variables.md
Resolves https://github.com/camunda/camunda-platform-docs/issues/1164 and https://github.com/camunda-cloud/identity/issues/988
The identity component offers different configuration options by way of environmental variables, there are values that Users may find helpful which are currently not listed. This PR adds these environmental variables to the existing list.
Nope :)
These configuration variable have existed for a while so they can go live whenever
=> docs(identity): add to identity config vars

docs/self-managed/backup-restore/backup-and-restore.md, sidebars.js
Add the upper-level section for Backup and Restore docs, that will be filled by several teams.
=> feat: add upper-level section for backup and restore feature

docs/components/integration-framework/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.0/components/integration-framework/connectors/custom-built-connectors/connector-sdk.md
Adjust SDK versions in the public SDK documentation (versions 8.0 and 8.1)
----
https://github.com/camunda/team-connectors/issues/153
https://github.com/camunda/camunda-platform-docs/issues/1360
=> feat(connector-sdk): release SDK version -> 0.2.0 to 0.2.2

docs/self-managed/platform-deployment/helm-kubernetes/deploy.md, docs/self-managed/platform-deployment/helm-kubernetes/guides/accessing-components-without-ingress.md, docs/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, docs/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md, docs/self-managed/platform-deployment/helm-kubernetes/overview.md, docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks.md, docs/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, docs/self-managed/platform-deployment/helm-kubernetes/upgrade.md, docs/self-managed/platform-deployment/overview.md, optimize_sidebars.js, sidebars.js, static/.htaccess
Added upgrade steps before Helm chart `v8.0.13`, which requires moving the upgrade to its own page. 
No.
Before the Camunda Platform `8.1.0` release.
=> docs(self-managed): add upgrade steps before helm chart v8.0.13

docs/self-managed/backup-restore/zeebe-backup-and-restore.md, docs/self-managed/zeebe-deployment/operations/backups.md, optimize_sidebars.js, sidebars.js
Related to #1297 https://github.com/camunda/product-hub/issues/104
This PR adds document for Zeebe backup and restore. To complete the documentation, we also have to add docs for Operate,Tasklist and Optimized. Once they are available, the main page `Backup & Restore` would describe how to take the backup of the C8 as a whole. Currently this page is empty. 
With 8.1.0 release
=> Docs on how to backup and restore Zeebe 

docs/self-managed/zeebe-deployment/operations/management-api.md, optimize_sidebars.js, sidebars.js
- Document pause/resume exporting api of Zeebe. This api is required for the C8 backup process.
=> feat: document zeebe pause and resume exporting management api

optimize_sidebars.js, sidebars.js
This PR regenerates the cross-instance sections in sidebars.js and optimize_sidebars.js, in preparation for cutting v8.1. 
#1116 introduced the need to keep these two files synchronized, but (a) we forgot to document that it was needed, and (b) it was easy to miss this synchronization in PRs. Especially with a flurry of new docs leading up to this release, the two files drifted. 
In the future I'd like to make it impossible to edit one without the other.
Note that I did not regenerate anything for v8.0 and previous versions -- those might also have drifted, but I think that most (if not all) of the new docs added recently were in vNext. 
no
Either before or at the same time as v8.1.
=> chore: re-synchronize sidebars & optimize_sidebars in prep for v8.1

docs/guides/update-guide/800-to-810.md, versioned_docs/version-8.1/guides/update-guide/800-to-810.md
Add a note to the update guides to inform users that we do not recommend from 8.0 to 8.1 at this point in time.
no
asap
=> Add note about critical issue in Operate 8.1 to update guide

optimize_sidebars.js, optimize_versioned_sidebars/version-3.8.0-sidebars.json, optimize_versioned_sidebars/version-3.9.0-sidebars.json, sidebars.js, versioned_sidebars/version-8.0-sidebars.json, versioned_sidebars/version-8.1-sidebars.json
Adds the 3.8-to-3.9-preview and 3.9-preview-to-3.9 update guides to the sidebar navigation.
cc @andromaqui 
We do have [docs on adding new pages](https://github.com/camunda/camunda-platform-docs/blob/f46fa75d646a380f67a3918a5ea6fae6d522a038/howtos/documentation-guidelines.md#adding-a-new-documentation-page), and it does mention adding to `sidebars` files, but (a) it's outdated and doesn't include info about `optimize_sidebars`, and (b) it's easy to overlook. I have it on my list to update this guide today to at least bring it up to date.
No
Soon!
=> chore: add newer optimize update guides to sidebars

docs/components/modeler/bpmn/none-events/none-events.md
Signed-off-by: Anurag Pathak <anuragpathak911@gmail.com>
fixes #1362 
The PR updates the documentation for the next release to reflect the changes of https://github.com/camunda/zeebe/pull/10618.
No.
Next minor release.
=> docs: mention all none-events support variable output mapping

docs/components/modeler/bpmn/user-tasks/user-tasks.md
As a user I would like to specify task candidate-users for user tasks.
closes #1370 
No.
No need to hurry. Maybe 8.2?
=> feat(modeler/bpmn): document candidate users for Assignments

docs/guides/update-guide/800-to-810.md, versioned_docs/version-8.1/guides/update-guide/800-to-810.md
Updated warning text in Update Guide to now point users to 8.1.1 version to use when updating from 8.0
=> Update Guide changes related to 8.1.1 import issue

versioned_docs/version-8.1/components/best-practices/best-practices-overview.md
I hope it is perfectly fine to ignore the template for these trivial typo fixes.
=> chore(typo): Fix grammar and missing Oxford Comma

versioned_docs/version-8.1/apis-clients/community-clients/micronaut.md
The feature was renamed from "zeebe" to "camunda-zeebe" in Micronaut. Therefore this link should be adapted.
This PR should also be backported to the documentation of 8.1
=> chore(broken link): Fix parameter "features"

docs/self-managed/backup-restore/backup-and-restore.md, docs/self-managed/backup-restore/operate-tasklist-backup.md, docs/self-managed/backup-restore/optimize-backup.md, docs/self-managed/backup-restore/zeebe-backup-and-restore.md, optimize_sidebars.js, sidebars.js, versioned_docs/version-8.1/self-managed/backup-restore/backup-and-restore.md, versioned_docs/version-8.1/self-managed/backup-restore/operate-tasklist-backup.md, versioned_docs/version-8.1/self-managed/backup-restore/optimize-backup.md, versioned_docs/version-8.1/self-managed/backup-restore/zeebe-backup-and-restore.md
related to OPT-6521
Align the backup docs for consistency across components
No
Not relevant
=> chore(backup): align backup docs

docs/apis-clients/grpc.md, docs/components/concepts/job-workers.md
Add variables argument for FailJob gRPC.
closes #1387 
No.
May be C8.2.
=> feat(api-clients/grpc): add variables argument for FailJob gRPC

docs/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md, sidebars.js
Also in an air-gapped environment, one would like to profit from the use of helm charts. By default the images are fetched via docker hub. 
Also with the dependencies to third-party images and helm charts, additional steps are required to have all charts available.
=> docs(self-managed): Add guide for air-gapped installation

versioned_docs/version-8.0/components/connectors/introduction.md, versioned_docs/version-8.1/components/connectors/introduction.md
Fix the backport of the Connector SDK top-level restructuring.
The introduction to Connectors was not properly adjusted in 8.0 and 8.1.
n/a
=> fix(components): adjust Connectors intro in 8.0 and 8.1

Dockerfile, docker-compose.yml, howtos/documentation-guidelines.md
Adds docker configuration & documentation for running a local Apache server so that .htaccess rules can be tested in an environment that simulates production.
In #1386, I wrote some rewrite rules that passed on https://htaccess.madewithlove.com/ but failed during CI checks. I spent a lot of time trying to figure out why they weren't passing CI, and if I'd been able to spin up a local server I'd have discovered the problem sooner. 
And in fact, the way I _did_ figure out what was wrong with those rules was to spin up a local Apache server with Docker. So this PR is really just capturing what I went through.
=> feat: add ability to run local Apache server to test htaccess redirects

docs/guides/update-guide/connectors/010-to-020.md, versioned_docs/version-8.0/guides/update-guide/connectors/010-to-020.md, versioned_docs/version-8.1/guides/update-guide/connectors/010-to-020.md
Fixes dead links pointing to [here](https://github.com/camunda/connector-sdk/tree/main/runtime#automatic-connector-discovery).
No.
I would be grateful if this PR would be accepted before 31.10.2022.
=> docs: fix dead links connector-sdk/runtime#automatic-connector-discovery

optimize/apis-clients/optimize-api/health-readiness.md, optimize/apis-clients/optimize-api/report/delete-report.md, optimize/apis-clients/optimize-api/report/get-data-export.md, optimize_versioned_docs/version-3.8.0/apis-clients/optimize-api/health-readiness.md, optimize_versioned_docs/version-3.8.0/apis-clients/optimize-api/report/delete-report.md, optimize_versioned_docs/version-3.8.0/apis-clients/optimize-api/report/get-data-export.md, optimize_versioned_docs/version-3.9.0/apis-clients/optimize-api/health-readiness.md, optimize_versioned_docs/version-3.9.0/apis-clients/optimize-api/report/delete-report.md, optimize_versioned_docs/version-3.9.0/apis-clients/optimize-api/report/get-data-export.md
This should never have been labelled as C7 only, so this PR removes the label from the next and previous docs
No
It's not urgent. But do we need to release the old docs at some point to see the changes reflected there? What is the process for this?
=> chore(docs): remove C7 only label from Optimize public API docs

optimize/self-managed/optimize-deployment/configuration/service-config.yaml, optimize/self-managed/optimize-deployment/configuration/system-configuration.md
relates to OPT-6410
Adds configuration information for a new feature to allow the disabling of ES hostname verification
N/A
In the next release, it is for a future Optimize version
=> improve(es): allow skipping of hostname verification

docs/components/best-practices/development/testing-process-definitions.md, versioned_docs/version-8.1/components/best-practices/development/testing-process-definitions.md
Currently, the Best Practices state to use Junit4. We introduced Junit5 support in 7.17 and use it since then.
no
asap
=> docs(best-practices): Updated the Camunda 7 part to use Junit 5

docs/self-managed/zeebe-deployment/security/secure-cluster-communication.md, docs/self-managed/zeebe-gateway-deployment/the-zeebe-gateway.md, versioned_docs/version-8.0/self-managed/zeebe-deployment/security/secure-cluster-communication.md, versioned_docs/version-8.0/self-managed/zeebe-gateway-deployment/the-zeebe-gateway.md, versioned_docs/version-8.1/self-managed/zeebe-deployment/security/secure-cluster-communication.md, versioned_docs/version-8.1/self-managed/zeebe-gateway-deployment/the-zeebe-gateway.md
Adds a note to specify that private keys for Zeebe (both broker and gateway) must be in the PKCS8 format, and explain how to convert existing private keys to this format.
For the record, this is a Netty limitation, and Netty is used both by the intra-cluster communication layer and grpc-java (for the clients). See https://netty.io/wiki/sslcontextbuilder-and-private-key.html
This came out of a question on Slack by @jonathanlukas, see https://camunda.slack.com/archives/CSQ2E3BT4/p1667382648872449, and a support ticket: https://jira.camunda.com/browse/SUPPORT-14626
Whenever, it's not particular urgent.
=> docs(zeebe): specify private key format

docs/guides/migrating-from-camunda-platform-7.md, versioned_docs/version-8.1/guides/migrating-from-camunda-platform-7.md
The migration guide is updated to reflect changes to the camunda-7-adapter library regarding handling of external task subscriptions.
The upgrade guide currently states that an external task worker needs to be transformed manually. This is now happening automatically as the camunda-7-adapter can now also wrap `@ExternalTaskHandler` beans.
no
=> docs(migrating-from-camunda-platform-7): Adjust to current state of development

docs/reference/notices.md, versioned_docs/version-8.0/reference/notices.md, versioned_docs/version-8.1/reference/notices.md
Add a security notice for Tasklist for the latest OpenSSL vulnerabilities
No
As soon as merged. The patched versions are released.
=> Add security notice for CVE-2022-3602 and CVE-2022-3786

docs/guides/update-guide/connectors/010-to-020.md, docs/guides/update-guide/connectors/020-to-030.md, docs/guides/update-guide/connectors/introduction.md, sidebars.js, versioned_docs/version-8.0/guides/update-guide/connectors/010-to-020.md, versioned_docs/version-8.0/guides/update-guide/connectors/020-to-030.md, versioned_docs/version-8.0/guides/update-guide/connectors/introduction.md, versioned_docs/version-8.1/guides/update-guide/connectors/010-to-020.md, versioned_docs/version-8.1/guides/update-guide/connectors/020-to-030.md, versioned_docs/version-8.1/guides/update-guide/connectors/introduction.md, versioned_sidebars/version-8.0-sidebars.json, versioned_sidebars/version-8.1-sidebars.json
Provide an update guide for Connectors from 0.2.x to 0.3
related to https://github.com/camunda/connector-sdk/issues/203
n/a
After Connector SDK `0.3.0` has been released, we'll ping manually here and remove the `hold` label.
=> feat(guides): add Connectors `0.3` update guide

docs/self-managed/backup-restore/zeebe-backup-and-restore.md, versioned_docs/version-8.1/self-managed/backup-restore/zeebe-backup-and-restore.md
----
I think this document is misleading, when I try to execute the command `./bin/restore 1` as shown in the documentation to restore a backup, I get the following error message, until I look at the source code and see the correct way to use it somewhere: `bin/resotre --backupId=1`
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-11-03 11:02:33.559 [] [main] ERROR
org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restoreApp': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'backupId' in value "${backupId}"
at …
```
=> fix(self-managed): fix misleading description for restore

docs/components/console/manage-organization/update-billing-reservations.md, versioned_docs/version-8.1/components/console/manage-organization/update-billing-reservations.md
* New Feature in SaaS: Development Clusters
* Add docs about how to change dev cluster reservations on billing page
I guess a blog post is in preparation for this feature.
After Prod Launch of dev clusters, relates https://github.com/camunda-cloud/console/issues/3520
=> feat(comp/console): add dev cluster reservations

docs/components/modeler/bpmn/event-subprocesses/event-subprocesses.md, versioned_docs/version-8.0/components/modeler/bpmn/event-subprocesses/event-subprocesses.md, versioned_docs/version-8.1/components/modeler/bpmn/event-subprocesses/event-subprocesses.md
When variables are coming with a start-event of an event-subprocess, the variable creation works in the default way. However, this might be confusing. So we should actually mention it.
Give a better insight on engine behaviour
no
asap
=> Explicitly mention variable creation behaviour

docs/self-managed/backup-restore/optimize-backup.md
related to OPT-6568
Update the response code for the take backup API as adjusted with OPT-6568 (https://github.com/camunda/camunda-optimize/pull/5466)
No
With the next release
=> chore(backup): update take backup response code

docs/self-managed/backup-restore/optimize-backup.md
related to OPT-6569
Document the additional error response when Optimize backup API encounters ES connection issues introduced with OPT PR: https://github.com/camunda/camunda-optimize/pull/5533
No.
With the next Optimize release.
=> chore(backup): document ES connection error response

docs/self-managed/platform-deployment/helm-kubernetes/guides/guides.md, sidebars.js, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/guides.md, versioned_sidebars/version-8.1-sidebars.json
The same as in #1502,  adding an index page for the `guides` category where it has its own link as well as embedded auto-generated items. 
This will also make it better for readability when referring to or sharing this specific category.
Here is the newly introduced link:
https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/guides/
No.
No specific time, as soon as possible.
=> chore(self-managed): set index page for platform guides

docs/apis-clients/go-client/go-get-started.md, versioned_docs/version-1.3/apis-clients/go-client/get-started.md, versioned_docs/version-8.0/apis-clients/go-client/go-get-started.md, versioned_docs/version-8.1/apis-clients/go-client/go-get-started.md
1. Went through the "Go client - Getting started guide" and in the end I noticed that my result looked slightly different as one  value was missing in my output. That value is there in the screenshots in the docs, however it is nowhere mentioned to (and how to) set it. Added that detail in all the relevant versions
2. As of now in the section https://docs.camunda.io/docs/next/apis-clients/go-client/go-get-started/#see-the-process-in-action it is mentioned to use Operate. Later in the text there still was a reference to "Zeebe Monitor" which was never mentioned before in the guide and should be replaced with Operate, especially as it already was introduced before in the guide.
No.
Not urgent. As soon as possible.
=> docs(go-client): add missing task header detail and refer to Operate instead of Zeebe Monitor

docs/components/connectors/use-connectors.md, docs/components/console/manage-clusters/manage-secrets.md, versioned_docs/version-8.0/components/connectors/use-connectors.md, versioned_docs/version-8.0/components/console/manage-clusters/manage-secrets.md, versioned_docs/version-8.1/components/connectors/use-connectors.md, versioned_docs/version-8.1/components/console/manage-clusters/manage-secrets.md
Move the secrets handling part from Console to the "Use Connectors" guide.
n/a
=> feat(connectors): move secrets handling to Connector guide

.gitignore, package-lock.json, package.json, playwright.config.ts, spec/regression/smoke.spec.ts
Part of #1171.
Installs & configures playwright, and introduces a single smoke test against the production site. 
For now the test would not be triggered by anything; but I'm PR'ing it in this state so that I can set this work aside for now. It's progress, and I don't want to throw it away.
* Schedule test(s) to run after a production deploy
* Write more tests to cover things described in #1171 
* Get the URL from an environment variable?
=> feat: initialize & configure playwright, and write a single regression/smoke test

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks.md
Our docs mentions - If you are already on 1.23 or later, the driver is already installed. But, as per the official EKS documentation, the add-on is not installed automatically. But , Refer EKS docs, "The Amazon EBS CSI driver isn't installed when you first create a cluster. To use the driver, you must add it as an Amazon EKS add-on or as a self-managed add-on." - https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html "If you plan to deploy workloads that use Amazon EBS volumes in a new 1.23 cluster, install the Amazon EBS CSI driver in your cluster before deploying the workloads your cluster. "- https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23 I have just installed C8 using helm profiles on a 1.23 Version EKS cluster and I had to add it …
=> Rectify information on EBS-CSI driver

docs/apis-clients/java-client/index.md, versioned_docs/version-8.0/apis-clients/java-client/index.md, versioned_docs/version-8.1/apis-clients/java-client/index.md
Related to https://github.com/camunda/developer-experience/issues/17. Eases finding the JavaDoc for the Zeebe Java client.
=> incorporate javadoc link

.github/workflows/sync-board.yaml
Resolves https://github.com/camunda/camunda-platform-docs/issues/1240. See also [this conversation](https://github.com/camunda/camunda-platform-docs/pull/1371#issuecomment-1277163771).
Updates the `sync_board` workflow so that it triggers on `pull_request_target` instead of `pull_request`. This grants the workflow the access it needs in order to assign items to the DX board on forked PRs.
Note that at one point I specified both `pull_request_target` and `pull_request` triggers, but as [pointed out in this thread](https://github.com/camunda/camunda-platform-docs/pull/1557#discussion_r1040793859) this was an unnecessary response to the workflow not running on this PR. 
By running on `pull_request_target`, I think we're giving this workflow access at whatever level [the personal access …
=> feat: run sync-board task for forked PRs

docs/reference/dependencies.md, versioned_docs/version-8.0/reference/dependencies.md, versioned_docs/version-8.1/reference/dependencies.md
Consolidate the third-party notice links for Connectors so they don't have to be adjusted in the future with every new Connector.
closes https://github.com/camunda/team-connectors/issues/256
n/a
ASAP
=> feat(connectors): consolidate third party notice links

docs/guides/update-guide/introduction.md, versioned_docs/version-8.1/guides/update-guide/introduction.md
I've just found out that the Introduction section misses links to Release Notes and the Blog Post.
No.
Better sonner, than later, I guess that this is some kind of minor bug.
=> fix: add release notes and link to the blog post in the introduction of update guide

docs/apis-clients/java-client/index.md, versioned_docs/version-8.1/apis-clients/java-client/index.md
The documentation usally uses `address` for this URL. Also, generated credential files use `ZEEBE_ADDRESS` as a name. Using `API` here can be confusing.
No
No
=> Unify naming

docs/self-managed/platform-deployment/helm-kubernetes/guides/using-existing-keycloak.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/using-existing-keycloak.md
Include the Identity guide to configuring existing Keycloak, which needed to be done before deploying the Camunda Platform 8 Self-Managed with disabled embedded Keycloak.
Thanks to @dlavrenuek for the suggestion :rocket: 
No.
No specific time, as soon as possible.
=> chore(self-managed): update using existing keycloak guide

howtos/documentation-guidelines.md
Corrects a couple links in the documentation-guidelines. Both were leading to 404 pages.
Whenever!
=> docs: fix sidebar links

.github/workflows/enforce-labels.yaml
Run the `enforce-labels` check more frequently! 
When @christinaausley and I introduced that workflow, I specifically remember removing several events from the list of triggers because I didn't know why they were there.
The new list of events comes directly from [the workflow's example](https://github.com/yogevbd/enforce-label-action).
Now I know why they are there! It's to avoid situations like [this PR](https://github.com/camunda/camunda-platform-docs/pull/1582), where a force-push reset all of the checks, and it wasn't mergeable until a label was removed/added again.
Doesn't matter!
=> fix: run the enforce-labels action more frequently to avoid unmergeable PRs

sidebars.js, versioned_docs/version-8.1/reference/regions.md, versioned_sidebars/version-8.1-sidebars.json
A few missing from adding the Regions page. Adds Regions to 8.1 and sidebars for both `Next` and `8.1`.
No
I promised @felix-mueller a special release 🙂
=> docs(regions): add to 8.1 & sidebars

docs/components/best-practices/architecture/sizing-your-environment.md, versioned_docs/version-8.1/components/best-practices/architecture/sizing-your-environment.md
self-managed and SaaS figures differed because of various updates. As more updates are expected to occur over time, I relaxed the binding and no longer say the self-manged example is exactly "S". Also I removed the sum, as it makes adjusting the table much easier - waiting for push back on this.
no
whenever / asap
=> Updated sizing recommendation and relaxed binding to SaaS

.github/workflows/add-to-project.yaml
A follow-up to #1605.
Renames the `sync-board` workflow to `add-to-project`. The name `sync-board` was intentionally vague, because we thought we could use it to do more things....but #1605 proved that it wasn't really usable for even closely related workflows. 
This new name is more precise and descriptive about what the workflow is doing.
=> improvement: rename sync-board workflow to add-to-project for precision

docs/components/connectors/custom-built-connectors/connector-sdk.md, docs/self-managed/platform-deployment/manual.md, versioned_docs/version-8.0/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.0/self-managed/platform-deployment/local.md, versioned_docs/version-8.1/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.1/self-managed/platform-deployment/manual.md
The previous link caused ambiguity because artifact `-with-dependencies` (which is mentioned a few lines below on the page) was not discoverable via Sonatype.
We should use a direct link to Maven repo instead, since all artifacts are visible there right away.
=> fix(connectors): edit Connector Runtime link

docs/self-managed/backup-restore/operate-tasklist-backup.md
* Main URL entry is renamed to `backups`
* Make endpoints description up-to-date
* Document that the endpoint is exposed on management port
* Document the ENV var to configure the snapshot repository
closes #1609
-
They can go live at any moment, the changes are already released in 8.2.0-alpha3
=> docs(operate): adjust Hot backup API docs

docusaurus.config.js, src/css/custom.css
Adds the ability to dismiss the announcement bar. 
Note that the dismissal state [is persisted in browser Local Storage](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-common/src/contexts/announcementBar.tsx#L63).
=> feat: make announcement bar dismissable

docs/guides/update-guide/810-to-820.md, sidebars.js
Document changes in backpressure algorithm between 8.1 and 8.2
closes #1428 
No
With 8.2.0 release
=> Document changes in Zeebe 8.2 in update guide

.github/workflows/build-docs.yaml
Pins the bitnami/apache image to a known working version ([2.4.54](https://hub.docker.com/layers/bitnami/apache/2.4.54/images/sha256-f04551fd50664c04d363694516b4f52743fb57b91c516ed7282d582c11da1489?context=explore)).
The `build-docs` action started failing when one of the `2.4.55.*` tags was released as `latest`. I'm not exactly sure which one, and I can't see any documentation on [the docker image page](https://hub.docker.com/r/bitnami/apache) that suggests breaking changes with those versions.
[`build-docs` got to the step where it waits for a local server to be reachable (so that it can do link checking), and the wait would time out and fail the build](https://github.com/camunda/camunda-platform-docs/actions/runs/4045969704/jobs/6958155381). 
Running locally, I was able to get to …
=> fix(ci): resolve build-docs failures by pinning the bitnami/apache image to a known working version

docs/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.0/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.1/components/modeler/desktop-modeler/flags/flags.md
Better describe the intended purpose of `--zeebe-ssl-certificate`.
Handle some pain points documented in https://github.com/camunda/camunda-modeler/issues/3326#issuecomment-1405764329 and following.
None.
Once engineering approved.
=> docs(desktop-modeler/flags): clarify `--zeebe-ssl-certificate`

docs/components/modeler/bpmn/business-rule-tasks/business-rule-tasks.md, docs/components/modeler/bpmn/service-tasks/service-tasks.md, versioned_docs/version-8.0/components/modeler/bpmn/business-rule-tasks/business-rule-tasks.md, versioned_docs/version-8.0/components/modeler/bpmn/service-tasks/service-tasks.md, versioned_docs/version-8.1/components/modeler/bpmn/business-rule-tasks/business-rule-tasks.md, versioned_docs/version-8.1/components/modeler/bpmn/service-tasks/service-tasks.md
Closes https://github.com/camunda/developer-experience/issues/36. In reference to [this Slack thread](https://camunda.slack.com/archives/C026U8GBNSW/p1674768047324169), docs required some clarification surrounding `type` and the worker.
Thank you @MaxTru for the assistance on this one!
=> clarify type and taskdefinition

docusaurus.config.js
Enables "Edit this page" links for Optimize documentation. I just noticed now, but these had been missing since we extracted those docs to support their own versions. 
When I configured the Optimize docs instance, I overlooked this `editUrl` setting 😅
=> chore: enable Edit This Page links for optimize docs

docs/apis-clients/operate-api/index.md, versioned_docs/version-8.1/apis-clients/operate-api/index.md
Part of https://github.com/camunda/developer-experience/issues/28
Adds context to the arguments passed to the token server when authenticating for Operate API calls.
Inspired by the similar [Optimize docs](https://docs.camunda.io/optimize/apis-clients/optimize-api/optimize-api-authorization/#how-to-obtain-the-access-token-for-c8-saas-cloud-usage), which are more clear about what those values should be. 
During https://github.com/camunda/developer-experience/issues/28, I had a hard time trying to figure out what the `audience` param should be. I tried a value from my secrets download before I found the value in the example curl request.
=> feat: explain in detail the arguments sent to token server

.github/workflows/build-docs.yaml, .github/workflows/linkcheck.yaml
1. Swaps a tarball download of https://github.com/filiph/linkcheck for its github action
I noticed some comments in the actions that indicate we were waiting for a specific release to switch back to the github action. That release has been shipped, so we should switch back to the github action to simplify the workflow definitions.
2. On the cron-based `link-check` workflow, reports connection failures as warnings instead of errors
Our cron-based link-check workflow fails more often than it succeeds, and it appears to be mostly a result of "connection failures" for certain pages. Since we just ignore those failing workflows anyway, we can tell the linkcheck tool not to bother reporting them as errors, and hopefully get to more successful runs than failed ones.
=> ci(linkcheck): use github action instead of downloading tar, and ignore connection failures for cron-based workflow

docs/apis-clients/tasklist-api/assets/tasklist.graphqls, docs/apis-clients/tasklist-api/inputs/task-query.mdx, versioned_docs/version-8.1/apis-clients/tasklist-api/assets/tasklist.graphqls, versioned_docs/version-8.1/apis-clients/tasklist-api/inputs/task-query.mdx
Adding two new fields for tasks query on TaskList API. Those new fields are part of [this feature](https://github.com/camunda/product-hub/issues/356).
This change should go live on 8.2.0 release (this change will also be available in 8.1.0 in the same date)
=> adding new fields for TaskQuery on tasklist

docs/self-managed/backup-restore/optimize-backup.md
related to OPT-6764
For consistency with Zeebe, Optimize's hot backup API now requires the backupID to be integer, not string.
No.
With the next release.
=> chore(backups): optimize takes integer backupID

docs/self-managed/backup-restore/zeebe-backup-and-restore.md, versioned_docs/version-8.1/self-managed/backup-restore/zeebe-backup-and-restore.md
* Documents a new feature available in Zeebe's S3 Backup Store.
* Fixes wrongly indented configuration example
I tried to find a good balance between keeping the docs brief and on point while also mentioning reasons to enable backup compression and trade offs to consider.
closes #1522 
The feature becomes available with 8.2.
=> Document Zeebe S3 backup store compression config

docs/guides/update-guide/connectors/040-to-050.md, docs/guides/update-guide/connectors/050-to-060.md, docs/guides/update-guide/connectors/introduction.md, sidebars.js, versioned_docs/version-8.0/guides/update-guide/connectors/040-to-050.md, versioned_docs/version-8.0/guides/update-guide/connectors/050-to-060.md, versioned_docs/version-8.0/guides/update-guide/connectors/introduction.md, versioned_docs/version-8.1/guides/update-guide/connectors/040-to-050.md, versioned_docs/version-8.1/guides/update-guide/connectors/050-to-060.md, versioned_docs/version-8.1/guides/update-guide/connectors/introduction.md, versioned_sidebars/version-8.0-sidebars.json, versioned_sidebars/version-8.1-sidebars.json
SDK migration guides were missing. Although these does not require any manual change from the user, we should include these for uniformity.
Any time. Preferably asap.
https://github.com/camunda/team-connectors/issues/339
=> chore(connectors): add missing sdk migration guides

src/css/custom.css
The red color of the fonts, links, navigation, search, etc. used in the Docs is not the color I would expect to be used at Camunda. I would expect that we use Orangemunda `#FC5D0D` as our primary color.
It is unclear to me why `#ff1f00` was used as the primary color before. It might be related to contrast to improve accessibility. However, it may also simply be a leftover from the start of the camunda-platform-docs. I propose we switch, so the Docs fit our branding, unless we confirm we need increased contrast. In that case I wonder if there are other colors that might fit better. 
This pull request switches Infima's (the design system used by Docusaurus) primary colors to shades of `Orangemunda`. The shades are produced using Docusaurus' own tool for producing different shades.
Left: How …
=> style: use orangemunda as primary color

versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
Updates a link in v8.1, [which should have also been updated in #1699](https://github.com/camunda/camunda-platform-docs/pull/1699#issuecomment-1431786715)
=> oops: update broken link in v8.1 also

docs/components/zeebe/open-source/get-help-get-involved.md, docs/self-managed/platform-deployment/overview.md, docs/self-managed/zeebe-deployment/zeebe-installation.md, docusaurus.config.js, src/pages/contact.md, versioned_docs/version-8.0/components/zeebe/open-source/get-help-get-involved.md, versioned_docs/version-8.0/self-managed/platform-deployment/platform-8-deployment.md, versioned_docs/version-8.0/self-managed/zeebe-deployment/zeebe-installation.md, versioned_docs/version-8.1/components/zeebe/open-source/get-help-get-involved.md, versioned_docs/version-8.1/self-managed/platform-deployment/overview.md, versioned_docs/version-8.1/self-managed/zeebe-deployment/zeebe-installation.md
Update all references to camunda-slack-invite.herokuapp.com/ to the new link, http://camunda.com/slack
Fixes #1708 
No
You decide
=> chore:replace slack link

src/css/custom.css
A follow-up to #1698 
Shifts the primary brand color to a slightly darker shade of orange, to meet WCAG minimum contrast guidelines. 
See [this comment](https://github.com/camunda/camunda-platform-docs/pull/1698#issuecomment-1433808640) for more details on how I arrived at this specific shade.
What it looks like:
=> feat: darker shade of orange to meet WCAG minimum contrast requirements

docs/self-managed/zeebe-deployment/operations/backpressure.md, versioned_docs/version-8.1/self-managed/zeebe-deployment/operations/backpressure.md
I'm trying to understand how back pressure can be configured. First hurdle are the unknown acronyms RTT and AIMD.
Clarify the backpressure calculation
no
As soon as possible.
=> Clarify acronyms and defaults on backpressure

docs/components/modeler/bpmn/receive-tasks/receive-tasks.md, versioned_docs/version-1.3/components/modeler/bpmn/receive-tasks/receive-tasks.md, versioned_docs/version-8.0/components/modeler/bpmn/receive-tasks/receive-tasks.md, versioned_docs/version-8.1/components/modeler/bpmn/receive-tasks/receive-tasks.md
This fixes a typo I noticed in the Receive Task docs:
No.
-
=> fix: correctly tag note in receive task docs

docs/apis-clients/operate-api/index.md, versioned_docs/version-8.1/apis-clients/operate-api/index.md
Collab with @christinaausley 
in #1671, I introduced some strange indentation issues, by writing a very long ordered list. 
This PR removes the indentation issues, by rewriting the content without an ordered list.
=> eliminate ordered-list indentation issues by rewriting operate API auth section

docs/self-managed/backup-restore/zeebe-backup-and-restore.md, versioned_docs/version-8.1/self-managed/backup-restore/zeebe-backup-and-restore.md
- Backup is not an experimental feature anymore. So the configuration to enable/disable it is removed. (https://github.com/camunda/zeebe/pull/11780)
- Some smaller improvements to the documentation based on the feedback.
No.
With 8.2.0 release
=> Update zeebe backup docs

docs/components/connectors/use-connectors.md, versioned_docs/version-8.0/components/connectors/use-connectors.md, versioned_docs/version-8.1/components/connectors/use-connectors.md
Clarified connector exec retries
No
Any time.
=> docs(connctors): clarified connector exec retries

optimize/apis-clients/optimize-api/health-readiness.md, optimize_versioned_docs/version-3.8.0/apis-clients/optimize-api/health-readiness.md, optimize_versioned_docs/version-3.9.0/apis-clients/optimize-api/health-readiness.md
Adds an admonition to vNext and v3.9.0 Optimize API docs readiness endpoint, calling out that this endpoint does not work with an `Authorization` header.
This is in response to [my API exploration findings](https://github.com/camunda/developer-experience/issues/31#issuecomment-1438778116), where I got stuck for a bit because I was trying to send the header in a `/readyz` request, and getting a confusing error.
=> docs(optimize): call out that the readiness endpoint does not want an Authorization header

docs/self-managed/platform-deployment/overview.md, versioned_docs/version-8.1/self-managed/platform-deployment/overview.md
Docker (and Docker Compose) was inadvertently dropped from the list of development options. This PR adds it back.
No
There is no associated release, but this could be considered a bug fix.
=> docs(platform-deployment): add docker back to development list

.github/workflows/move-to-done.yaml
Updates the `move-to-done` workflow to run on `pull_request_target`, instead of `pull_request`, so that external/forked PRs can use the github token.
(Because when running on `pull_request`, [they fail](https://github.com/camunda/camunda-platform-docs/actions/runs/4319043727/jobs/7538049888).)
=> chore: fix move-to-done for external PRs

optimize/self-managed/optimize-deployment/configuration/service-config.yaml, optimize/self-managed/optimize-deployment/configuration/system-configuration.md
relates to OPT-6790
Certificates can now be self-signed and this config flag is used to determine it, so should be added to config
N/A
It will be part of 8.2 release and not backported, so nothing needed before
=> feat(security): allow self-signed certificates for ES connection

docs/reference/glossary.md, versioned_docs/version-8.0/reference/glossary.md, versioned_docs/version-8.1/reference/glossary.md
Based on [Slack discussion](https://camunda.slack.com/archives/C026U8GBNSW/p1677835374614279), the [Deployment](https://docs.camunda.io/docs/reference/glossary/#deployment) link in the glossary routes to https://docs.camunda.io/docs/self-managed/about-self-managed/. This has been adjusted to https://docs.camunda.io/docs/apis-clients/grpc/#deployresource-rpc .
=> adjust deployment glossary link

docs/components/modeler/desktop-modeler/element-templates/about-templates.md, docs/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.0/components/modeler/desktop-modeler/element-templates/about-templates.md, versioned_docs/version-8.0/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.1/components/modeler/desktop-modeler/element-templates/about-templates.md, versioned_docs/version-8.1/components/modeler/desktop-modeler/element-templates/defining-templates.md
As @p-e-e-t-e-r raised in https://github.com/camunda/camunda-platform-docs/pull/1760 the documentation for element templates currently does a bad job to tell apart which element template features are available in with context (C7 vs. C8). While we plan to completely separate both (https://github.com/bpmn-io/internal-docs/issues/663) this is the first step to introduce clear markings for individual features. 
Marks are introduced via notes: 
```
:::note
{SOME NAME} is only supported in {TARGET PLATFORM}
:::
```
In addition this PR fixes a number of smaller issues with the documentation, including miss-leading and/or broken content.
None.
As soon as merged.
----
Closes https://github.com/camunda/camunda-modeler/issues/3482
=> docs(element-templates): clearly mark support for different features per platform

docs/components/modeler/bpmn/assets/react-components/iso-8601-date-time.md, docs/components/modeler/bpmn/timer-events/timer-events.md, docs/components/modeler/bpmn/user-tasks/user-tasks.md
With https://github.com/camunda/product-hub/issues/215, Camunda Platform 8 supports user task scheduling with the `dueDate` and `followUpDate` attributes.
/
With version `8.2.0`.
closes #1733
=> Add user task scheduling docs section

docs/self-managed/zeebe-deployment/operations/rebalancing.md, versioned_docs/version-1.3/self-managed/zeebe-deployment/operations/rebalancing.md, versioned_docs/version-8.0/self-managed/zeebe-deployment/operations/rebalancing.md, versioned_docs/version-8.1/self-managed/zeebe-deployment/operations/rebalancing.md
Removes the trailing slash from Zeebe's rebalance URL. By upgrading Spring Boot to version 3.x in Zeebe, any request with a trailing will fail with 404.
related to https://github.com/camunda/zeebe/pull/11103
=> fix(zeebe): remove trailing slash from rebalance url

docs/reference/supported-environments.md
Reverts the changes added in https://github.com/camunda/camunda-platform-docs/pull/1819 due to a [bug that was found](https://github.com/camunda-cloud/identity/issues/1515).
no
no
=> docs(identity): revert Keycloak 20 support

docs/self-managed/platform-deployment/helm-kubernetes/deploy.md, docs/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md, docs/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md
The structure of the Camunda 8 Helm chart has recently been refactored (the Web Modeler subchart has been merged to the parent chart; see https://github.com/camunda/camunda-platform-helm/pull/584). This change requires a few updates to the documentation.
Closes https://github.com/camunda/web-modeler/issues/4170.
no
It can go live any time.
=> docs(self-managed): update Helm chart docs after Web Modeler subchart was merged to parent

docs/self-managed/modeler/web-modeler/configuration.md, versioned_docs/version-8.1/self-managed/web-modeler/configuration.md
Update the configuration page since Web Modeler now has support for running it on a context path of a domain.
Closes https://github.com/camunda/web-modeler/issues/4136
no
It can go live any time.
=> docs(web-modeler): update configuration page for context path support

docs/components/modeler/desktop-modeler/telemetry/telemetry.md
Update telemetry docs according to https://github.com/camunda/camunda-modeler/issues/3486. TLDR: remove data we don't send anymore
n/a
Officially release date is April 13th but can go live before
=> docs(desktop-modeler): update telemtry docs

optimize/self-managed/optimize-deployment/configuration/system-configuration-platform-8.md
The default value we use for the import batch size will be changed in the next release
N/A
With the upcoming 8.2 release
=> chore(config): reduce default zeebe import batch size to 200

optimize/self-managed/optimize-deployment/migration-update/3.9-to-3.10.md
relates to OPT-6826
Optimize now requires minimum 7.16.2, we should have this reflected in the docs
N/A
With the 8.2 release
=> chore(docs): drop support for ES <7.16.2

docusaurus.config.js, howtos/release-procedure.md
OOTB Docusaurus puts up a banner stating older docs versions are "unmaintained," which is not entirely true. 
This PR removes the banner from 8.0 since OOTB, we only have 3 options - no banner, "unmaintained," or "unreleased" (as in `next`).  
Shoutout to @remcowesterhoud for starting this discussion 😄! 
No.
This should not be merged until feedback is collected internally.
=> remove version banner from 8.0

docs/self-managed/identity/user-guide/groups/assigning-roles-to-a-group.md, docs/self-managed/identity/user-guide/groups/assigning-users-to-a-group.md, docs/self-managed/identity/user-guide/groups/creating-a-group.md, docs/self-managed/identity/user-guide/groups/creating-authorizations-for-a-group.md
I spotted that as part of a recent change I made, the sidebar labels for several pages were altered, this is because they were `sidebar_labels` and not `description`. This PR updates the fields to now be `description`
Nope :)
Before the next docs release
=> docs(identity): fix sidebar labels for group related pages

docs/guides/update-guide/810-to-820.md, docs/reference/announcements.md, docs/reference/supported-environments.md
With Operate 8.2, it comes with Spring Boot 3.0 the following needs to documented/updated:
Operate now requires Java 17+
URLs with a trailing slash will fail with a HTTP status 404: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-mvc-and-webflux-url-matching-changes
Unrelated: While updating version requirements, also added the elastic search supported versions since I will be making those doc changes as well in any case.
No
As part of 8.2 minor release
=> docs(operate): Announce changes from Spring Boot 3 update, plus elasticsearch versions

docs/components/modeler/bpmn/script-tasks/script-tasks.md
* Add a new documentation section for script tasks covering the usage of FEEL expressions.
* Point out that there are two different implementations for script tasks in Camunda Platform 8 (FEEL expressions and job workers).
* Add an example for script tasks using inline FEEL expressions.
/
Before the Camunda Platform 8.2 release.
- Only added for version `8.2`, it shouldn't be ported to older versions.
closes #1548
=> Inline FEEL expressions in script tasks

docs/self-managed/operate-deployment/data-retention.md, docs/self-managed/operate-deployment/operate-configuration.md
With the update to Elasticsearch 8, the Elasticsearch Curator will no longer function. It is replaced with Index Lifecycle Management. This change documents the configuration needed to enable ILM.
No
As part of the 8.2 minor release
=> docs(operate): Elasticsearch 8 ILM support

docs/apis-clients/web-modeler-api/index.md, docs/reference/licenses.md, docs/reference/supported-environments.md, docs/self-managed/about-self-managed.md, docs/self-managed/modeler/web-modeler/api.md, docs/self-managed/modeler/web-modeler/configuration.md, docs/self-managed/modeler/web-modeler/installation.md, docs/self-managed/platform-deployment/docker.md, docs/self-managed/platform-deployment/helm-kubernetes/deploy.md, docs/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md, docs/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, docs/self-managed/platform-deployment/helm-kubernetes/platforms/platforms.md, docs/self-managed/platform-deployment/overview.md, optimize_sidebars.js, sidebars.js, src/css/custom.css
Update the docs for the General Availability (GA) release of Web Modeler Self-Manged (= remove beta status).
Closes https://github.com/camunda/web-modeler/issues/3764.
There will probably be a blog post on the Camunda Platform 8.2 release that mentions Web Modeler GA.
With the 8.2 release next week (April 11).
=> docs(web-modeler): remove beta status

optimize_versioned_sidebars/version-3.9.0-sidebars.json
Synchronizes the sidebars for the APIs & Tools documentation, versions 8.1/3.9.0. 
Yet to come, in a different PR: APIs & Tools sidebars for versions `next`.
Merged today, hopefully!
=> chore(sidebars): synchronize sidebars for 8.1/3.9.0 apis-tools 

docs/apis-tools/working-with-apis-tools.md, versioned_docs/version-8.2/apis-tools/working-with-apis-tools.md
Fixes `main`!!!
Corrects the apis-tools cards URLs. I'd created the release PR prior to @christinaausley's fixes in #1938, and for some reason I was able to merge without conflicts? 
Immediately! `main` is broken.
=> chore: correct apis-tools cards URLs

docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, docs/components/connectors/out-of-the-box-connectors/gitlab.md, optimize_sidebars.js, sidebars.js, versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/gitlab.md, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/gitlab.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/gitlab.md, versioned_sidebars/version-8.0-sidebars.json, versioned_sidebars/version-8.1-sidebars.json, versioned_sidebars/version-8.2-sidebars.json
Introduce a new OOTB connector doc: GitLab.
No
Any time
=> docs(connectors): added docs for GitLab connector

docs/apis-tools/working-with-apis-tools.md
Add Postman Link to next. This makes it available for early engagers, but gives us time to build out and update APIs & collections available there.
No
Not urgent
=> docs(apis-tools): add postman link

docs/reference/regions.md, versioned_docs/version-8.2/reference/regions.md
Updating the naming of the GCP available regions of Camunda Platform 
=> docs(regions): update available GCP regions

docs/apis-tools/operate-api/overview.md, versioned_docs/version-8.2/apis-tools/operate-api/overview.md
During document update for new fields, some were accidently added the incorrect api endpoints. This update fixes that, as well as also adding the new fields to the relevant object schema definitions.
Closes #1980.
N/A
Should go live for 8.e versions as soon as possible please.
=> docs(api): Fix incorrect fields for api endpoints

docs/components/connectors/out-of-the-box-connectors/http-webhook.md, docs/self-managed/connectors-deployment/connectors-configuration.md, docs/self-managed/connectors-deployment/install-and-start.md, docs/self-managed/platform-deployment/docker.md, docs/self-managed/platform-deployment/helm-kubernetes/deploy.md, docs/self-managed/platform-deployment/helm-kubernetes/guides/accessing-components-without-ingress.md, docs/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md, docs/self-managed/platform-deployment/helm-kubernetes/upgrade.md, docs/self-managed/platform-deployment/overview.md, versioned_docs/version-8.0/self-managed/connectors-deployment/connectors-configuration.md, versioned_docs/version-8.0/self-managed/connectors-deployment/install-and-start.md, versioned_docs/version-8.0/self-managed/platform-deployment/docker.md, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/http-webhook.md, versioned_docs/version-8.1/self-managed/connectors-deployment/connectors-configuration.md, versioned_docs/version-8.1/self-managed/connectors-deployment/install-and-start.md, versioned_docs/version-8.1/self-managed/platform-deployment/docker.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/deploy.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/accessing-components-without-ingress.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.1/self-managed/platform-deployment/overview.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/http-webhook.md, versioned_docs/version-8.2/self-managed/connectors-deployment/connectors-configuration.md, versioned_docs/version-8.2/self-managed/connectors-deployment/install-and-start.md, versioned_docs/version-8.2/self-managed/platform-deployment/docker.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/deploy.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/accessing-components-without-ingress.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.2/self-managed/platform-deployment/overview.md
With `8.2.0` Camunda and `0.18.0` Connectors releases, there's numerous changes, that have to be reflected in the doc. Those changes are reflected here.
None
Anytime
=> docs(connectors): update changes to reflect 8.2 release

sidebars.js, versioned_sidebars/version-8.0-sidebars.json, versioned_sidebars/version-8.1-sidebars.json, versioned_sidebars/version-8.2-sidebars.json
Caught the missing status page that wasn't in the sidebar.
No
Technically its a bug, but it's gone unnoticed for a while and the link is on the Reference overview.
=> docs(status): add status page to sidebars 8.0+

.github/workflows/publish-stage.yaml
Partially addresses https://github.com/camunda/developer-experience/issues/61 (for the staging environment)
Updates the publish-stage workflow to publish to our new AWS hosting environment. 
Note that #1994 was opened as an experiment/playground. This PR is making that experiment a reality, by updating the `publish-stage` workflow instead of a temporary `publish-stage-temp` workflow.
Yes! I confirmed with a recently merged PR that after I published to the new staging, I could see the changes.
In the next day or so, so that we can confirm its validity before I leave for vacation on Thursday!
=> chore: update publish-stage for move to AWS hosting

docs/apis-tools/operate-api/overview.md, versioned_docs/version-8.2/apis-tools/operate-api/overview.md
PR1996 accidently overwrote changes on the api page for operate docs which was made in pr 1981. This change just adds the overwritten changes back.
no
with the next 8.2 patch update.
=> Fix accidental overwrite of previous api update pr

docs/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.0/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.1/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/flags/flags.md
This gives us a place to link to for disabling plug-ins.
Ensure we have something to link to when hinting our users at the `--disable-plugins` flag.
No.
Immediately.
=> docs(modeler/flags): document `disable-plugins` flag

docs/components/modeler/desktop-modeler/element-templates/configuring-templates.md, docs/components/modeler/desktop-modeler/search-paths/search-paths.md, versioned_docs/version-8.0/components/modeler/desktop-modeler/search-paths/search-paths.md, versioned_docs/version-8.1/components/modeler/desktop-modeler/search-paths/search-paths.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/element-templates/configuring-templates.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/search-paths/search-paths.md
Rephrased documentation of configuring element templates to distinct between element templates available for all diagrams (`resouces/element-templates`) and element templates available for specific diagrams only (`.camunda/element-templates)`. This is based on feedback from our QA engineers and a follow-up to https://github.com/camunda/camunda-modeler/pull/3561.
No.
Immediately.
=> chore: rephrase element templates configuration

.github/workflows/publish-prod.yaml
Partially addresses https://github.com/camunda/developer-experience/issues/61 (for the production environment)
No longer blocked by:
Updates the publish-stage workflow to publish to our new AWS hosting environment. 
Note that #2018 was opened as an experiment/playground. This PR is making that experiment a reality, by updating the `publish-prod` workflow instead of a temporary `publish-prod-temp` workflow.
~Not yet!~
Yes!!!!!
Hopefully by early Wednesday! If we don't make it by then, we're going to wait until after I return from vacation.
=> chore: update publish-prod for move to AWS hosting

docs/components/connectors/out-of-the-box-connectors/aws-lambda.md, versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/aws-lambda.md, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/aws-lambda.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/aws-lambda.md
Link to manage-secrets.md is incorrect in all versions of aws-lambda docs. 
No
This is a bug, we should merge and trigger a release to get this updated.
=> docs(aws-lambda): fix link to manage-secrets

docs/apis-tools/community-clients/micronaut.md
Adding link change in #2042 to `/next/`.
No.
This link is broken. Could be considered a bug.
=> docs(micronaut): change link in next

docs/components/connectors/out-of-the-box-connectors/automation-anywhere.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/automation-anywhere.md
A note block was declared with an indented end, leading to the whole document below was shown as note.
no
asap
=> Fix note block

versioned_docs/version-8.2/apis-tools/java-client/index.md
* build: two methods in client instantiation now call "zeebeAdress" instead of "zeebeAPI"
_The code change is to replace the use of the "zeebeAPI" variable with "zeebeAddress" in two client instantiation methods. The configurations are needed for the code to work correctly after the upgrade._
_No._
_As soon as possible. This can help other developers who may be working on the same code avoid errors and issues._
=> fix the call of adress variable

docs/components/connectors/out-of-the-box-connectors/aws-dynamodb.md, versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/aws-dynamodb.md, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/aws-dynamodb.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/aws-dynamodb.md
Added internal link to Item operations : `[Item](#item-operations)` in aws dynamoDB connector docs
https://github.com/camunda/camunda-platform-docs/issues/2066
TBD
=> docs(ootbc): dynamoDb add internal link to item operations

docs/reference/supported-environments.md, versioned_docs/version-8.2/reference/supported-environments.md
The decision was made to update the wording to make it more explicit that we support the AWS OpenSearch 1.3 version in 8.2.
no
as soon as possible
=> Make wording on supported OpenSearch version more specific

docs/self-managed/modeler/web-modeler/configuration.md, versioned_docs/version-8.2/self-managed/modeler/web-modeler/configuration.md
Link the new configuration page on the _Play_ mode in Web Modeler from the `PLAY_ENABLED` environment variable.
no
It can go live any time.
=> docs(web-modeler): link Play mode docs from configuration page

docs/components/connectors/out-of-the-box-connectors/google-maps-platform.md, versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/automation-anywhere.md, versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/google-maps-platform.md, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/automation-anywhere.md, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/google-maps-platform.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/google-maps-platform.md
Inspired by #2053, cleans up the remaining "dangling" `:::note` terminators.
Prettier gets confused when a `:::note` block is terminated with a `:::` on the line _immediately_ following a list. If we put a blank line after the last list item, it understands properly. 
In other words, prettier gets confused by this:
```
:::note
1. thing
2. thing
:::
```
And it indents the final `:::`. 
But if we do this, it leaves the closing tag out-dented: 
```
:::note
1. thing
2. thing
:::
```
There might be a way to lint for this, but I think that's a pretty low-priority improvement, and these prettier mistakes are easy to find & fix manually.
=> chore: clean up remaining dangling :::note terminators

docs/self-managed/identity/getting-started/install-identity.md, docs/self-managed/identity/troubleshooting/common-problems.md, docs/self-managed/identity/user-guide/configuration/configure-external-identity-provider.md, docs/self-managed/identity/user-guide/configuration/connect-to-an-existing-keycloak.md, docs/self-managed/platform-deployment/troubleshooting.md, versioned_docs/version-8.0/self-managed/identity/getting-started/install-identity.md, versioned_docs/version-8.0/self-managed/identity/troubleshooting/common-problems.md, versioned_docs/version-8.0/self-managed/platform-deployment/known-limitations.md, versioned_docs/version-8.1/self-managed/identity/getting-started/install-identity.md, versioned_docs/version-8.1/self-managed/identity/troubleshooting/common-problems.md, versioned_docs/version-8.1/self-managed/identity/user-guide/configure-external-identity-provider.md, versioned_docs/version-8.1/self-managed/identity/user-guide/connect-to-an-existing-keycloak.md, versioned_docs/version-8.1/self-managed/platform-deployment/troubleshooting.md, versioned_docs/version-8.2/self-managed/identity/getting-started/install-identity.md, versioned_docs/version-8.2/self-managed/identity/troubleshooting/common-problems.md, versioned_docs/version-8.2/self-managed/identity/user-guide/configuration/configure-external-identity-provider.md, versioned_docs/version-8.2/self-managed/identity/user-guide/configuration/connect-to-an-existing-keycloak.md, versioned_docs/version-8.2/self-managed/platform-deployment/troubleshooting.md
Fixes https://camunda.slack.com/archives/C026U8GBNSW/p1683562739617529. The external links to Keycloak docs now contain the latest supported version (19.0.3) instead of referencing `latest`
no
any time
=> chore: use links to 19.0.3 keycloak docs

CONTRIBUTING.MD
As I began to write up a document describing [redirect rule best practices](https://github.com/camunda/camunda-platform-docs/pull/2058#discussion_r1187957017), I noticed a lot of things in the contributing.md that were out of date. This PR cleans that guide up, as pre-work for the guide I'm going to write on redirect rules.
I did a bad dirty, and made all my changes without committing. It was a challenge to separate into multiple commits, so I just crammed everything into one commit. I'm sorry!
=> chore: bring contributing.md up to date

docs/self-managed/zeebe-deployment/configuration/gateway.md, versioned_docs/version-8.2/self-managed/zeebe-deployment/configuration/gateway.md
env vars for the authentication config contained the `BROKER_` suffix that only applies to the embedded gateway but not the standalone gatway.
no
asap
=> fix(zeebe): Remove `BROKER_` suffix from env vars in gateway config

docs/reference/supported-environments.md, versioned_docs/version-8.1/reference/supported-environments.md, versioned_docs/version-8.2/reference/supported-environments.md
Align the Keycloak versions supported by Web Modeler with the ones for Identity.
no
It can go live any time.
=> chore(web-modeler): align supported Keycloak versions with Identity

docs/self-managed/identity/user-guide/configuration/configure-logging.md, versioned_docs/version-8.1/self-managed/identity/user-guide/configure-logging.md, versioned_docs/version-8.2/self-managed/identity/user-guide/configuration/configure-logging.md
It was picked up by QA that the docs around the logging configuration for Identity. We do not have a `Log` appender, this should be `File`.
Nope
This change can be included in an upcoming release but is not urgent to trigger a release of its own.
=> docs(identity): fix the log appender options to match reality

src/pages/contact.md, src/pages/index.js, src/theme/NavbarItem/index.js
Adjusts a few things in preparation for #1173:
1. Corrects a link on the Contact page, which was incorrectly traveling one ancestor too far. This has no effect on the current docs, but will have an effect on the archived versions.
2. Updates the "feature" links on the home page to do two things: 
1. Use the `<Link>` element instead of `<a>`, which enables docusaurus to navigate with the client-side router. To the user, this looks like more seamless transitions when they click on the feature.
2. Wrap the `url` of each link in a `useBaseUrl()` call. This tells docusaurus to use the `baseUrl` property of its configuration when generating the link. This has no effect on the current docs, but will have an effect on the archived versions. 
3. Broadens the scope of the `docsPluginId`-sniffing …
=> assorted: Archive pre-work

docs/reference/supported-environments.md
As per the decisions in https://github.com/camunda/product-hub/issues/981 from 8.3 we will support Keycloak v21+, this PR updates the `Supported Environments` for the `next` version. 
Currently there are no dependency updates to document for the Identity component.
As mentioned above, this change will be official for the 8.3 release, but the functionality will arrive in 8.3.0-alpha2.
=> docs(identity): update the keycloak supported version for next (8.3) version

howtos/versioning.md
Adds a rough initial description of the process for archiving an unsupported version of the docs.
I'll be updating this new content as I learn things during the archival process.
=> feat(docs): describe the process for archiving an unsupported version of the docs

.github/workflows/publish-prod.yaml
Part of #1173. 
This PR is BLOCKING the deployment of 0.25 to unsupported.docs.camunda.io/0.25.
Excludes any 0.25.x tags from the publish-prod workflow, so that a 0.25 isolated website isn't accidentally deployed to the main/supported/active docs site (docs.camunda.io).
[The GitHub docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-branches-and-tags) describe this approach of combining include & exclude tags, as well as the importance of the order.
Context for this PR is discussed [here](https://github.com/camunda/camunda-platform-docs/pull/2167#discussion_r1214887291).
After this is merged, I'll tag a 0.25.x release, and make sure (1) the 0.25 site gets deployed to unsupported.docs.camunda.io, and (2) no deployment …
=> chore(ci): prevent 0.25.x tags from accidentally being deployed to docs.camunda.io

docs/components/modeler/data-handling.md, versioned_docs/version-8.2/components/modeler/data-handling.md
This fixes the documentation about scoped example variables to reflect the latest changes from https://github.com/camunda/example-data-properties-provider/pull/8 .
related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/934
=> fix(data-handling): correct variable scope documentation

sidebars.js, versioned_sidebars/version-8.1-sidebars.json, versioned_sidebars/version-8.2-sidebars.json
This PR adds a common sidebar entry for RabbitMQ Connectors:
```
| RabbitMQ
| - RabbitMQ Producer Connector
| - RabbitMQ Consumer Connector
```
We have previously done the same for Kafka and GitHub
Any time.
=> Common sidebar entry for RabbitMQ connectors

optimize/components/userguide/process-analysis/report-analysis/define-reports.md, optimize_versioned_docs/version-3.10.0/components/userguide/process-analysis/report-analysis/define-reports.md, optimize_versioned_docs/version-3.7.0/components/userguide/process-analysis/report-analysis/edit-mode.md, optimize_versioned_docs/version-3.8.0/components/userguide/process-analysis/report-analysis/define-reports.md, optimize_versioned_docs/version-3.9.0/components/userguide/process-analysis/report-analysis/define-reports.md
relates to OPT-7028
Some report types aren't available in C8, but this is not necessarily clear to users. We should make this clearer in our docs.
I know we typically use the label for our docs but that doesn't neatly fit this page, as only a small part is C7-specific. Open to alternatives here @christinaausley :)
=> chore(docs): mark assignee/candidate group data reports as C7 only

optimize/self-managed/optimize-deployment/configuration/system-configuration-platform-7.md, optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/configuration/system-configuration-platform-7.md, optimize_versioned_docs/version-3.7.0/self-managed/optimize-deployment/setup/configuration.md, optimize_versioned_docs/version-3.8.0/self-managed/optimize-deployment/configuration/system-configuration-platform-7.md, optimize_versioned_docs/version-3.9.0/self-managed/optimize-deployment/configuration/system-configuration-platform-7.md
relates to OPT-6890
From a support ticket, we should clarify that engine data needs to remain for enough time for Optimize to import it, or it will be lost
=> chore(docs): warn about engine historic data clean up time

docs/reference/dependencies.md, versioned_docs/version-8.0/reference/dependencies.md, versioned_docs/version-8.1/reference/dependencies.md, versioned_docs/version-8.2/reference/dependencies.md
We need to update our docs and the camunda docs to reflect the new reality that connectors are now all managed in the same project. In scope of https://github.com/camunda/team-connectors/issues/422
=> docs: update dependencies.md

docs/components/modeler/desktop-modeler/troubleshooting.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/troubleshooting.md
This enables further debug logging that was previously hidden:
This supports nicely further improvements in `zeebe-node` logging: https://github.com/camunda-community-hub/zeebe-client-node-js/pull/321.
=> docs(desktop-modeler): enable further debug logging

docs/components/connectors/out-of-the-box-connectors/kafka-inbound.md, optimize_sidebars.js, optimize_versioned_sidebars/version-3.10.0-sidebars.json, optimize_versioned_sidebars/version-3.9.0-sidebars.json, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/kafka-inbound.md, versioned_docs/version-8.1/self-managed/connectors-deployment/install-and-start.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/kafka-inbound.md, versioned_docs/version-8.2/self-managed/connectors-deployment/install-and-start.md
Fix Kafka Consumer Connector response description. Removed `topic` from response description in relevant docs.
https://github.com/camunda/camunda-platform-docs/issues/2215
=> chore(connectors): remove topic from Kafka consumer response in the docs

docs/self-managed/modeler/web-modeler/configuration/configuration.md, versioned_docs/version-8.1/self-managed/web-modeler/configuration.md, versioned_docs/version-8.2/self-managed/modeler/web-modeler/configuration/configuration.md
Updates the version to the Laravel documentation to version 10 used by the latest websockets image.
No.
With the next Web Modeler SM patch/alpha release.
=> docs(web-modeler): upgrade Laravel to v10

docs/self-managed/tasklist-deployment/tasklist-authentication.md, versioned_docs/version-8.0/self-managed/tasklist-deployment/tasklist-authentication.md, versioned_docs/version-8.1/self-managed/tasklist-deployment/tasklist-authentication.md, versioned_docs/version-8.2/self-managed/tasklist-deployment/tasklist-authentication.md
Closes https://github.com/camunda/tasklist/issues/3051
The yaml configuration for custom user and password is wrong so I'm fixing it. The only change is that the username config doesn't exist, the correct is userId.
=> docs(tasklist): Fix custom user and password configuration

docs/components/concepts/backups.md, versioned_docs/version-8.2/components/concepts/backups.md
The `alpha1` suffix on the generation is a bit confusing (also technically true). It might make customers think that its not supported on stable versions.
=> feat(backups): clearer generation

hacks/isolateVersion/5-updateThemeComponents.sh, hacks/isolateVersion/allSteps.sh, hacks/isolateVersion/assets/README.md, hacks/isolateVersion/assets/theme/DocVersionBanner/index.js
Part of #1173.
Adds an archival script, and associated assets, for making the theme changes that an isolated site needs. 
The end result of running this step is [this commit](https://github.com/camunda/camunda-platform-docs/pull/2167/commits/bfb4071aa7c492f5db947cb3a3593005ac5c1747), from [this 0.25 isolation PR](https://github.com/camunda/camunda-platform-docs/pull/2167).
=> feat: add an archival script for updating theme components

docs/reference/announcements.md, versioned_docs/version-8.2/reference/announcements.md
Added text to the announcements section to warn users to not directly udpate from 8.1.x to 8.2.6.
asap
=> operate_8_2_6_support_notice

static/.htaccess
Note that this is targeting the `unsupported/0.26` branch, not `main`.
The rules in the htaccess file for the 0.26 site were incorrect. This fixes them!
I don't consider this blocking the release of `main`, as it's a very minor edge-case that we probably don't care much about anyway. But I'll get this out today, if it receives approval.
=> chore: isolation of version 0.26, followup: fix htaccess rules

optimize/self-managed/optimize-deployment/install-and-start.md, optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/install-and-start.md, optimize_versioned_docs/version-3.7.0/self-managed/optimize-deployment/setup/installation.md, optimize_versioned_docs/version-3.8.0/self-managed/optimize-deployment/install-and-start.md, optimize_versioned_docs/version-3.9.0/self-managed/optimize-deployment/install-and-start.md
Currently, the description can be misleading as the snake case is interpreted as env variable.
This PR changes the variable name to be not recognized as env variable by mistake.
Ref: https://camunda.slack.com/archives/C55U06YRG/p1686731615564369?thread_ts=1686728398.497259&cid=C55U06YRG
This fix improves readability and reduces misunderstanding.
=> Update code snippet to replace misleading reference

docs/components/modeler/bpmn/timer-events/timer-events.md
As of 8.3 Zeebe officially supports Timers defined with a time date in intermediate and boundary events.
For non-interrupting boundary events there is a slight caveat. Usually these are repeatable and can be triggered multiple times. For a time date the event will only be triggered once, as this is not repeatable.
closes #2012
[This](https://camunda.slack.com/archives/C02UMKN3DTL/p1683214870123299?thread_ts=1682677528.275489&cid=C02UMKN3DTL) (internal) slack link provides a nice overview of the supported timer events. This might help out with the technical review.
=> Document support for time date events

docs/reference/supported-environments.md, optimize/self-managed/optimize-deployment/migration-update/3.10-to-3.11.md
=> chor(es8): Update docs to reflect the current ES supported versions

docs/self-managed/zeebe-deployment/zeebe-installation.md, versioned_docs/version-8.2/self-managed/zeebe-deployment/zeebe-installation.md
It is irritating to have Overview as menu point while the title is Installation.
Just a small adjustment
=> Self-Managed Zeebe Overview: Update page Title

docs/apis-tools/console-api-reference.md, versioned_docs/version-8.2/apis-tools/console-api-reference.md
Retroactive technical review of https://github.com/camunda/camunda-platform-docs/pull/2232.
=> technical review backups

howtos/documentation-guidelines.md
Adds Distribution team to review process list for tagging instead of individuals.
=> Add Distribution team

hacks/isolateVersion/1-deleteOtherVersions.sh, hacks/isolateVersion/allSteps.sh
This PR adds logic to the `1-deleteOtherVersions` isolation step to delete optimize documentation. I did this manually when isolating versions 0.25 and 0.26 because I kept forgetting to automate it. 
It also corrects some information messages output by the script.
=> archive(1.0) preparation: add optimize docs removal to isolation script

docs/reference/supported-environments.md, versioned_docs/version-8.2/reference/supported-environments.md
Documents Web Modeler support for Amazon Aurora PostgreSQL 13.x and 15.x
Relates to https://github.com/camunda/web-modeler/pull/5322 and https://github.com/camunda/web-modeler/issues/4458
=> docs(web-modeler): support for Amazon Aurora PostgreSQL 13.x & 15.x

optimize/components/userguide/process-analysis/report-analysis/define-reports.md, optimize_versioned_docs/version-3.10.0/components/userguide/process-analysis/report-analysis/define-reports.md, optimize_versioned_docs/version-3.7.0/components/userguide/process-analysis/report-analysis/edit-mode.md, optimize_versioned_docs/version-3.8.0/components/userguide/process-analysis/report-analysis/define-reports.md, optimize_versioned_docs/version-3.9.0/components/userguide/process-analysis/report-analysis/define-reports.md
Retro review of https://github.com/camunda/camunda-platform-docs/pull/2179. Adds period to complete sentence.
=> retro review OPT-7028

versioned_docs/version-8.2/components/connectors/custom-built-connectors/connector-templates.md, versioned_docs/version-8.2/components/modeler/about-modeler.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/index.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/install-the-modeler.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/model-your-first-diagram.md, versioned_docs/version-8.2/guides/create-decision-tables-using-dmn.md, versioned_docs/version-8.2/guides/introduction-to-camunda-platform-8.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/overview.md, versioned_sidebars/version-8.2-sidebars.json
This backports https://github.com/camunda/camunda-platform-docs/pull/2029 to stable (8.2).
Any time.
=> chore(desktop-modeler): backport about page to stable (8.2)

docs/apis-tools/tasklist-api/inputs/task-query.mdx, versioned_docs/version-8.2/apis-tools/tasklist-api/inputs/task-query.mdx
This presented itself in the Bing Webmaster tools console -
> There are multiple `<h1>` tags on the page.
Looks like there was a merge conflict and this PR cleans that up. I did not see any issues in 8.1 or 8.0.
=> Correct merge conflict in Tasklist API

docs/components/modeler/web-modeler/advanced-modeling/publish-public-processes.md, docs/components/modeler/web-modeler/run-or-publish-your-process.md, docs/components/tasklist/userguide/starting-processes.md
Retroactive review of https://github.com/camunda/camunda-platform-docs/pull/2194.
=> retro review public process

docs/components/modeler/desktop-modeler/flags/flags.md
Documents flags introduced via https://github.com/camunda/camunda-modeler/pull/3720.
The flags will be available with Desktop Modeler release on 8th August, and in tomorrow's nightly build.
=> docs(modeler/flags): document engine version flags

docs/self-managed/tasklist-deployment/tasklist-authentication.md, versioned_docs/version-8.2/self-managed/tasklist-deployment/tasklist-authentication.md
On TaskList we are adding extra configurations for users that are created automatically when starting ("act" and "view") to make possible to change the userIds, display names or passwords.
This change is part of the next patch release (8.2.8).
=> docs: adding configuration for users act and view

docs/components/modeler/desktop-modeler/troubleshooting.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/troubleshooting.md
The documented path for Windows logs does not exist. It used `camunda-modeler` instead of `Camunda Modeler` in the path
=> fix(modeler): correct windows app path

docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, docs/components/connectors/out-of-the-box-connectors/aws-eventbridge.md, optimize_sidebars.js, sidebars.js, versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/aws-eventbridge.md, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/aws-eventbridge.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/aws-eventbridge.md, versioned_sidebars/version-8.0-sidebars.json, versioned_sidebars/version-8.1-sidebars.json, versioned_sidebars/version-8.2-sidebars.json
Added AWS EventBridge docs, 
Related : 
https://github.com/camunda/product-hub/issues/467
=> docs(ootbc): add eventBridge documentation

docs/apis-tools/tasklist-api-rest/tasklist-api-rest-overview.md, versioned_docs/version-8.2/apis-tools/tasklist-api-rest/tasklist-api-rest-overview.md
This PR addresses the issues raised in [ticket #2310](https://github.com/camunda/camunda-platform-docs/issues/2310). 
The changes made include the correction of incorrect HTTP methods, with GET replacing POST where necessary. 
The [Save draft task variables](https://github.com/camunda/product-hub/issues/1154) endpoint has been added for the endpoints overview for the `next` version. 
In addition, for both `8.2` and `next` versions, a link has been added to each endpoint, redirecting users to a more detailed description of the endpoint. This should assist with providing more comprehensive information about each endpoint.
=> docs: (tasklist) update tasklist-rest-api overview

hacks/isolateVersion/6-updateCIWorkflows.sh, hacks/isolateVersion/allSteps.sh
Part of #1173.
This PR automates the CI workflow updates involved in archiving an unsupported version. 
See the changes in https://github.com/camunda/camunda-platform-docs/pull/2235/files, specifically within the `.github/workflows` folder, for a snapshot of all the changes included in this automated step.
=> feat(archiving): Automate workflow updates

docs/reference/supported-environments.md
Zeebe supports OpenSearch 2.5.x as of release 8.3. We can already mention this in this section of the docs so users know this is coming.
=> Add OpenSearch 2.5.x support to Zeebe

sidebars.js, versioned_sidebars/version-8.0-sidebars.json, versioned_sidebars/version-8.1-sidebars.json, versioned_sidebars/version-8.2-sidebars.json
Connectors and Elasticsearch appear above the Camunda Platform 8 guides in the sidebar and I'm concerned that could create confusion. This moves those directories below the individual guide pages.
=> Move update guides up sidebar

src/css/custom.css
Fixes the ick I get looking at the Guides badging. 😆 
Also, closes #848 because that seems like more work than it's worth.
=> Add css tweak for Guide badging

docs/components/connectors/custom-built-connectors/connector-sdk.md, docs/guides/update-guide/connectors/0100-to-0110.md, docs/guides/update-guide/connectors/introduction.md, sidebars.js, versioned_docs/version-8.0/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.0/guides/update-guide/connectors/0100-to-0110.md, versioned_docs/version-8.0/guides/update-guide/connectors/introduction.md, versioned_docs/version-8.1/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.1/guides/update-guide/connectors/0100-to-0110.md, versioned_docs/version-8.1/guides/update-guide/connectors/introduction.md, versioned_docs/version-8.2/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.2/guides/update-guide/connectors/0100-to-0110.md, versioned_docs/version-8.2/guides/update-guide/connectors/introduction.md, versioned_sidebars/version-8.0-sidebars.json, versioned_sidebars/version-8.1-sidebars.json, versioned_sidebars/version-8.2-sidebars.json
This PR updates the Connectors docs to reflect some major changes in the Connector SDK 0.11 release.
What's inside
- Update guide for migrating to SDK 0.11
- Adjustments for code examples of custom connectors
=> Update Connectors docs to reflect the latest SDK changes

docusaurus.config.js
Closes #2320 and #2288. 
Unfortunately, the sitemap does not generate on an `npm run start`. So you need to do a `build` and `serve`.
Screenshot shows no returns for "assets".
I marked this as a bug but with no urgency because I don't think it's hurting anyone but looks unpolished.
=> add assets to ignorePatterns

docs/guides/update-guide/820-to-830.md, docs/guides/update-guide/introduction.md, sidebars.js
Closes #2339 
Related [issue](https://github.com/camunda/zeebe/issues/13233)
Removed resource from `Deployment:CREATED` event. Resource is still available in `Process:CREATED` or `DecisionRequirements:CREATED`
=> [Zeebe] Removed resource from Deployment:CREATED event

docs/guides/update-guide/820-to-830.md, docs/self-managed/zeebe-deployment/configuration/gateway-health-probes.md, docs/self-managed/zeebe-deployment/operations/health.md
This PR documents the upcoming health probe endpoint changes in Zeebe, starting with 8.3.0. The changes are mostly dropping old routes which were redirects, and using the proper endpoints directly.
At least 8.3, but can be earlier since it's good to have for the next alpha next week.
=> docs(zeebe): document health probe changes

docs/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
Update OpenShift-supported versions (mark v4.11, v4.12, and v4.13 as supported).
Any time.
=> docs(self-managed): update openshift supported versions

hacks/isolateVersion/7-updateDocusaurusConfig.sh, hacks/isolateVersion/allSteps.sh
Part of #1173.
This PR automates the updates of docusaurus.config.js during a version archival. 
See the changes in #2421, specifically within the `docusaurus.config.js` file, for an example of the changes this step generates.
The file that's being edited is a javascript file, though the large majority of the contents are a single JSON object. I considered two approaches other than the `sed` commands in this PR: 
1. Use [jq](https://jqlang.github.io/jq/) to edit the JSON directly, since it's a tool designed for parsing/editing JSON. The issue here was that the file is _JavaScript_, not JSON, so jq can't parse it. I also couldn't _convert it_ from JavaScript to JSON, because (a) I think docusaurus only supports JavaScript for the config, probably because (b) there are run-time `require` …
=> feat(archive): automate update of docusaurus.config.js

docusaurus.config.js
Note that this targets the `unsupported/1.1` branch, and will not make it into `main`.
Part of #2186.
Fixes the footer social icons in the unsupported/1.1 site. 
The path to them is incorrect in these isolated sites, because they sit in a "virtual directory" named according to their version. So this one, for example, lives at `unsupported.docs.camunda.io/1.1/`. The footer icons are in the _root_ in the main site, but here the path needs to be adjusted based on the `/1.1/`. 
I'll update my automation changes from #2422 in a separate PR, so that I don't miss this on the next version archival.
=> archive(1.1) fix: update icon URLs based on virtual directory

docs/guides/improve-processes-with-optimize.md, versioned_docs/version-1.3/guides/improve-processes-with-optimize.md, versioned_docs/version-8.0/guides/improve-processes-with-optimize.md, versioned_docs/version-8.1/guides/improve-processes-with-optimize.md, versioned_docs/version-8.2/guides/improve-processes-with-optimize.md
=> docs(alerts): alerts are part of collection not report

howtos/configuration.md
Addresses feedback from #2438.
Updates our documentation on Algolia DocSearch integration.
=> feat(docs): update Algolia configuration information

docs/components/modeler/reference/modeling-guidance/index.md
Allows us to add new pages without the need to update the parent.
Uses DocCardList to link all modeling guidance sub-pages as suggested by @pepopowitz in https://github.com/camunda/camunda-platform-docs/pull/2454#issuecomment-1682670842.
=> chore: list child pages as carts

hacks/isolateVersion/1-deleteOtherVersions.sh, hacks/isolateVersion/allSteps.sh
Modifies the 1-deleteOtherVersions.sh script to take into account Optimize docs when deleting other versions for archival.
(And also updates the versions in allSteps.sh because it's useful to call out that both should be set from now on.)
=> feat(archival): take into account Optimize when deleting other versions

docs/components/connectors/use-connectors/inbound.md, versioned_docs/version-8.1/components/connectors/use-connectors/inbound.md, versioned_docs/version-8.2/components/connectors/use-connectors/inbound.md
chore(ootbc): removed incorrect note
Anytime
=> chore(ootbc): removed incorrect note

versioned_docs/version-8.2/reference/supported-environments.md
This PR updates the supported environments section for the 8.2 docs to include the Keycloak 21 support.
=> docs(identity): update the keycloak supported version for the 8.2 version

hacks/isolateVersion/2-reduceVersionManifest.sh, hacks/isolateVersion/3-preventCrawling.sh, hacks/isolateVersion/4-fixDockerfile.sh, hacks/isolateVersion/5-updateThemeComponents.sh, hacks/isolateVersion/6-updateCIWorkflows.sh, hacks/isolateVersion/7-updateDocusaurusConfig.sh, hacks/isolateVersion/8-configureOptimizeDocs.sh, hacks/isolateVersion/allSteps.sh
This PR makes adjustments to the automated steps for version archival, including: 
* Specifying the archived version in all commit messages (because I like it that way).
* Removing the deletion of link-check.yaml, because that file no longer exists in `main`.
* _Updating_ the announcement bar configuration, instead of _adding_ it, because the announcement bar was added back to `main` recently.
* Accounting for the Optimize docs instance.
I _think_ this is the last set of changes I am making to the automation process for now.
=> feat: update automated archival steps (for Optimize & changes to main)

docs/components/best-practices/modeling/building-flexibility-into-bpmn-models.md, docs/components/best-practices/modeling/creating-readable-process-models.md, versioned_docs/version-8.2/components/best-practices/modeling/building-flexibility-into-bpmn-models.md, versioned_docs/version-8.2/components/best-practices/modeling/creating-readable-process-models.md
This PR removes caution hints on Camunda 8 not supporting Escalation Events, Link Events, OR Gateways, and Conditional Events. This is no longer the case as of version 8.2. The changes were done for doc version 8.2 and /docs.
=> Stadtler best practices 82 hints

docusaurus.config.js
Note: targets the unsupported/0.26 branch.
Part of #2475.
Removes the Search experience from the unsupported/0.26 docs, because none of the results lead to an active page.
=> [unsupported/0.26] cleanup: remove Search from 0.26 docs

docusaurus.config.js
Note: targets the unsupported/0.25 branch.
Part of #2475.
Removes the Search experience from the unsupported/0.25 docs, because none of the results lead to an active page.
=> [unsupported/0.25] chore: remove Search from 0.25 docs

docusaurus.config.js
Note: targets the unsupported/1.0 branch.
Part of #2475.
Removes the Search experience from the unsupported/1.0 docs, because none of the results lead to an active page.
=> [unsupported/1.0] cleanup: remove Search from 1.0 docs

docusaurus.config.js
Note: targets the unsupported/1.1 branch.
Part of #2475.
Removes the Search experience from the unsupported/1.1 docs, because none of the results lead to an active page.
=> [unsupported/1.1] cleanup: remove Search from 1.1 docs

docusaurus.config.js
Note: targets the unsupported/1.2 branch.
Part of #2475.
Removes the Search experience from the unsupported/1.2 docs, because none of the results lead to an active page.
=> [unsupported/1.2] cleanup: remove Search from 1.2 docs

docusaurus.config.js
Note: targets the unsupported/1.3 branch.
Part of #2475.
Removes the Search experience from the unsupported/1.3 docs, because none of the results lead to an active page.
=> [unsupported/1.3] cleanup: remove Search from 1.3 docs

docs/self-managed/operational-guides/update-guide/810-to-820.md, versioned_docs/version-8.2/guides/update-guide/810-to-820.md
This configuration flag was added to help users that rely on path-style access. We've had users who were confused about this so hopefully a mention in our update guide will be helpful.
Closes #1431
=> docs(zeebe): refer to `forcePathStyleAccess` in upgrade guide

docs/components/concepts/resource-authorizations.md, docs/self-managed/operate-deployment/operate-authentication.md
Closes https://github.com/camunda-cloud/identity/issues/2118
Quick fix! Adds an admonition for changes to RBA w/ Operate taking 30 seconds.
=> RBA - Add one-liner for Operate changes

docs/components/modeler/bpmn/service-tasks/service-tasks.md, versioned_docs/version-8.0/components/modeler/bpmn/service-tasks/service-tasks.md, versioned_docs/version-8.1/components/modeler/bpmn/service-tasks/service-tasks.md, versioned_docs/version-8.2/components/modeler/bpmn/service-tasks/service-tasks.md
taskDefiniton -> taskDefinition
This should be backported to all supported versions.
- [] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
=> Typo in Service Task

howtos/moving-content.md
Immediately after merging #2577, I re-read the docs that I was about to publicize in Slack, and realized they were out of date. This PR corrects them, based on the last feedback I addressed in #2577.
=> docs: Update canonical guidance

howtos/documentation-workflows.MD
=> Update image in docs-on-docs

howtos/documentation-workflows.MD
Update links found here - https://github.com/camunda/camunda-platform-docs/pull/2636#pullrequestreview-1640093105
=> Add links to documentation-workflows.md

docs/components/connectors/use-connectors/outbound.md
Added an example of configuring the custom retry backoff. The feature is already available in the latest 8.3 alpha.
=> feat(connectors): outbound connector retry backoff

docs/components/modeler/bpmn/message-events/message-events.md, versioned_docs/version-1.3/components/modeler/bpmn/message-events/message-events.md, versioned_docs/version-8.0/components/modeler/bpmn/message-events/message-events.md, versioned_docs/version-8.1/components/modeler/bpmn/message-events/message-events.md
feat(zeebe): message start events clarification
=> feat(zeebe): message start events clarification

src/theme/DocItem/Metadata/determineCanonical.js
Fixes the docs for Safari versions <= 16.3, which [do not yet support lookbehind in regular expressions](https://caniuse.com/js-regexp-lookbehind).
The regular expression used here was overly complex anyway. We were previously doing something with the resulting `matches`. Now, the expression is only used for a test, and we don't use the match. 
Initially raised in [Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1695712165348429) by @remcowesterhoud (cc @christinaausley).
=> fix: remove unnecessary complexity from canonical regular expression

.github/pull_request_template.md, CONTRIBUTING.MD, docs/reference/licenses.md, docusaurus.config.js, howtos/documentation-guidelines.md, howtos/markdown-and-mdx-features.md, howtos/release-procedure.md, howtos/versioning.md, src/mdx/expandVersionedUrl.spec.js, versioned_docs/version-8.0/reference/licenses.md, versioned_docs/version-8.1/reference/licenses.md, versioned_docs/version-8.2/reference/licenses.md
=> update camunda platform docs references

.github/workflows/check-format.yaml, .vale.ini, styles/camunda/all/hrefProduction.yml, styles/camunda/docsInstance/hrefDocsToDocs.yml, styles/camunda/docsInstance/hrefDocsToOptimize.yml, styles/camunda/optimizeInstance/hrefOptimizeToDocs.yml, styles/camunda/optimizeInstance/hrefOptimizeToOptimize.yml
Addresses #1876.
See #2664 for more details and context about how this PR came about. 
This PR introduces [vale](https://vale.sh/) as a markdown linter. It introduces 4 linting rules that detect links that cross over instances or versions of the docs, and runs them as a pull request check.
- The 4 rules are run against only the changes included in the PR.
- If a rule is violated in a PR, a comment is added at the point of violation, as an FYI.
- If a rule is violated in a PR, the check **does not** fail.
An example of a violation can be found [in this prototype PR](https://github.com/camunda/camunda-docs/pull/2664#discussion_r1340415150). It looks like this: 
The rules in this PR are inspired by [our guidance on preferred link format](https://github.com/camunda/camunda-platform-docs/blob/m …
=> feat: detect crossover links as a PR check

hacks/generateOptimizeSidebars.md, optimize_sidebars.js, sidebars.js
This PR synchronizes sidebars for the "next" version of the docs. The sidebars tend to drift significantly during new doc development, as it is non-intuitive to update two different sidebars files. This explains the rather large size of this PR.
- Synchronization for other versions. That will come in a separate PR.
=> chore: synchronize sidebars for vNext

optimize_versioned_sidebars/version-3.9.0-sidebars.json, versioned_sidebars/version-8.1-sidebars.json
This PR synchronizes sidebars for the 8.1 version of the docs. 
- Synchronization for <= 8.1. If that needs to happen, it will come in a separate PR.
=> chore: synchronize sidebars for v8.1/3.9.0

optimize_versioned_sidebars/version-3.8.0-sidebars.json, versioned_sidebars/version-8.0-sidebars.json
This PR synchronizes sidebars for the 8.0/3.8.0 versions of the docs. 
- Synchronization for <= 8.1. If that needs to happen, it will come in a separate PR.
=> chore: synchronize sidebars for v8.0/3.8.0

optimize_versioned_sidebars/version-3.7.0-sidebars.json
This PR synchronizes sidebars for the 1.3/3.7.0 version of the docs. 
- Synchronization for <= 8.1. If that needs to happen, it will come in a separate PR.
=> chore: synchronize sidebars for v1.3/3.7.0

docs/self-managed/operational-guides/update-guide/introduction.md, versioned_docs/version-8.3/self-managed/operational-guides/update-guide/introduction.md
Add release note and blog links to update guidelines
closes #2377
=> docs(8.3-release): add release notes and blog link

docs/apis-tools/java-client/job-worker.md, versioned_docs/version-8.3/apis-tools/java-client/job-worker.md
This commit adds a section about Multi tenancy in Job workers and how to configure them. It also includes some small code examples to guide users during implementation.
Part of the 8.3 release
closes #2697
=> Add multi tenancy section to Job Worker

docs/reference/announcements.md, docs/self-managed/operational-guides/update-guide/820-to-830.md, versioned_docs/version-8.3/reference/announcements.md, versioned_docs/version-8.3/self-managed/operational-guides/update-guide/820-to-830.md
Updating the migration warning we added based on suggestions from support to make less confusing for customers.
The /versioned file contains the text as we would like it to show prior to the upcoming 8.3.1 patch.
Once the patch it released, we will update the /versioned file to have the same text as the updated /next file
asap please
=> make migration warning clearer

docs/apis-tools/working-with-apis-tools.md, versioned_docs/version-8.2/apis-tools/working-with-apis-tools.md, versioned_docs/version-8.3/apis-tools/working-with-apis-tools.md
Removing the beta border from Web Modeler, but retaining the CSS in the case we need to use it again. Closes https://github.com/camunda/developer-experience/issues/145.
=> remove beta border for web modeler

versioned_sidebars/version-8.2-sidebars.json
The message-correlation page was accidentally removed from the 8.2 sidebars, in https://github.com/camunda/camunda-docs/pull/2510/files#diff-9bea8823b9627af89bbc878e80abdc54f3126d99b77da400b7623a50b688d121. The page couldn't be found in the 8.2 sidebar navigation, but it could still be found through search -- and when it was displayed, it didn't include any sidebar navigation.
This PR puts it back in the sidebars.
First reported in [Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1697222038025109).
=> Put message-correlation back into 8.2 sidebars

docs/self-managed/concepts/multi-tenancy.md, docs/self-managed/zeebe-deployment/configuration/gateway.md, versioned_docs/version-8.2/self-managed/zeebe-deployment/configuration/gateway.md, versioned_docs/version-8.3/self-managed/concepts/multi-tenancy.md, versioned_docs/version-8.3/self-managed/zeebe-deployment/configuration/gateway.md
This resolves multiple small problems with the documentation on configuring the Zeebe Gateway for multi-tenancy.
1. While the gateway configuration page discusses how to configure the gateway, it can be used to configure both a standalone gateway (`zeebe.gateway.*`) and an embedded gateway (`zeebe.broker.gateway.*`). However, the page focuses on documenting the standalone gateway. I've corrected all references to configuring an embedded gateway to a standalone gateway. I've also added an admonition to clarify how users can use the information on the page to configure an embedded gateway.
2. I also discovered that the caution admonition for the multi-tenancy concept was formatted wrongly, and fixed it.
3. Lastly, it wasn't documented that users must use Identity when they want to use …
=> Small improvements to configuring multi-tenancy in zeebe gateway

docs/components/connectors/out-of-the-box-connectors/salesforce.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/salesforce.md, versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/salesforce.md
This PR will add a hint that each operation description contains a link to the Salesforce docs which contains useful examples.
Also, this PR adds examples to each parameter.
closes https://github.com/camunda/team-connectors/issues/495
=> Connectors/OOTB/Salesforce: Added reference to examples

docs/self-managed/connectors-deployment/connectors-configuration.md, docs/self-managed/platform-deployment/manual.md, versioned_docs/version-8.0/self-managed/platform-deployment/local.md, versioned_docs/version-8.1/self-managed/connectors-deployment/connectors-configuration.md, versioned_docs/version-8.1/self-managed/platform-deployment/manual.md, versioned_docs/version-8.2/self-managed/connectors-deployment/connectors-configuration.md, versioned_docs/version-8.2/self-managed/platform-deployment/manual.md, versioned_docs/version-8.3/self-managed/connectors-deployment/connectors-configuration.md, versioned_docs/version-8.3/self-managed/platform-deployment/manual.md
chore(connectors): updated runtime execution information
Anytime
=> chore(connectors): updated runtime execution information

docs/apis-tools/build-your-own-client.md, versioned_docs/version-8.3/apis-tools/build-your-own-client.md
Make audience in the example taken from env variable ${ZEEBE_TOKEN_AUDIENCE}
=> doc: Update build-your-own-client.md

docs/reference/supported-environments.md, versioned_docs/version-8.3/reference/supported-environments.md
This change will let customers know which component versions are officially supported on version 8.3.
Soon, but there's no urgency. I think this PR should have been created before 8.3 but our team got busy with other things, so we forgot to add it.
=> fix(reference): added 8.3 version matrix for dependency components

versioned_docs/version-8.0/components/best-practices/development/service-integration-patterns.md, versioned_docs/version-8.0/components/console/console-troubleshooting/feedback-and-support.md, versioned_docs/version-8.0/components/modeler/bpmn/exclusive-gateways/exclusive-gateways.md, versioned_docs/version-8.0/components/zeebe/open-source/get-help-get-involved.md, versioned_docs/version-8.0/reference/status.md, versioned_docs/version-8.0/self-managed/platform-deployment/platform-8-deployment.md, versioned_docs/version-8.0/self-managed/zeebe-deployment/zeebe-installation.md
Note: this targets the `unsupported/8.0` branch and will never make it to main.
Incorporates two recent PRs that merged into main after I branched `unsupported/8.0`:
- #2835
- #2834
=> archive(8.0) isolation: port recent changes in main

docs/components/modeler/web-modeler/play-your-process.md, versioned_docs/version-8.2/components/modeler/web-modeler/play-your-process.md, versioned_docs/version-8.3/components/modeler/web-modeler/play-your-process.md
Zeebe Play has not updated its version to support 8.3. Therefore, Signal events are not supported. However, our docs suggest that they are supported. This is inaccurate.
With the next release
=> clarify-zeebe-version

docs/self-managed/zeebe-deployment/operations/cluster-scaling.md, sidebars.js
related to #2855 
This PR adds a minimal documentation for Cluster scaling api of Zeebe. 
Release with `8.4.0-alpha1`
=> docs(zeebe): add docs for dynamic scaling api

docs/self-managed/identity/deployment/configuration-variables.md, docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/irsa.md
Fixes https://github.com/camunda-cloud/identity/issues/2267
Adds documentation on how to configure Identity to use a AWS Aurora database.
The functionality will be released with Identity `8.4.0-alpha1` on 07. Nov 2023. The release announcement is normally made a week later, so these changes can be released from 2023-11-07 to 2023-11-14
=> feat: add AWS Aurora documentation for Identity

docs/components/console/manage-clusters/create-cluster-include.md, versioned_docs/version-8.3/components/console/manage-clusters/create-cluster-include.md
Closes #2860.
I only added this to the create cluster reusable component since it looks like a tag is automatically assigned (at least on a trial cluster). @felix-mueller can you confirm tags are automatically assigned for any cluster type?
I don't think this is big enough to warrant a separate page.
=> Add cluster tag to docs

docs/components/modeler/feel/what-is-feel.md, versioned_docs/version-8.3/components/modeler/feel/what-is-feel.md
I find the existing mention of `Camunda Extension` on the what is FEEL page confusing, and this is a proposal to improve it:
=> Clarify extensions

docs/reference/release-policy.md, versioned_docs/version-8.1/reference/release-policy.md, versioned_docs/version-8.2/reference/release-policy.md, versioned_docs/version-8.3/reference/release-policy.md
We have alpha features and alpha releases? How does the user know the difference?
=> chore(reference): clarify alpha features vs alpha releases

docs/reference/supported-environments.md
Zeebe recently upgraded to Java 21: https://github.com/camunda/zeebe/issues/13716
=> fix: new Zeebe versions require Java 21

versioned_docs/version-8.3/reference/supported-environments.md
Since [this thread](https://camunda.slack.com/archives/C03UR0V2R2M/p1698328767448689), we now use the Optimize C8 versioning in our Helm charts. This should be reflected in our docs
=> chore(docs): use Optimize C8 versioning for helm chart matrix

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
=> feat: document `zeebe:taskDefinition` binding

docs/components/modeler/desktop-modeler/telemetry/telemetry.md
This adds the new `formFieldTypes` data we track with closed forms.
Related to https://github.com/camunda/camunda-modeler/pull/3954
=> docs(desktop-modeler): add `formFieldTypes` to closed forms

optimize/self-managed/optimize-deployment/migration-update/3.10-to-3.11_8.3.md
related to OPT-7421
We encountered a potential migration issue for 3.11 and recommend C7 customers to skip straight to 3.11.3 for a safer migration path.
These docs refer to the upcoming 3.11.3 patch which we are releasing asap, imo we can merge the docs even beforehand.
=> chore(migration): add upgrade notice for issue OPT-7419

docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md, docs/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
Both the Elasticsearch and OpenSearch exporters support a new configuration option with the upcoming 8.4 release:
- `index.userTask`
This boolean flag (default `true`) allows to filter records related to the upcoming Zeebe user tasks feature.
=> Add `userTask` flag to ES and OS exporters

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.3/components/modeler/desktop-modeler/element-templates/defining-templates.md
This pull request documents the message templates and generated values which were added in 8.3 as part of https://github.com/camunda/product-hub/issues/817
Closes https://github.com/bpmn-io/internal-docs/issues/797
=> Document message templates and generated value

docs/apis-tools/tasklist-api-rest/schemas/models/include-variable.mdx, docs/apis-tools/tasklist-api-rest/schemas/requests/task-search-request.mdx, docs/apis-tools/tasklist-api-rest/schemas/responses/task-search-response.mdx, docs/apis-tools/tasklist-api-rest/schemas/responses/variable-search-response.mdx
closes https://github.com/camunda/tasklist/issues/3774
=> docs(tasklist): document Fetch variables in Task Search REST api

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
This PR:
- documents changes in the display of templated correlationKey. It will be automatically hidden in Start Events on a Process, but will still be visible for start events in event based subprocesses (and boundary/intermediate events)
- adds a new condition
=> feat(templates): document correlationKey changes

docs/self-managed/platform-deployment/helm-kubernetes/guides/install-zeebe-exporters.md, sidebars.js, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/install-zeebe-exporters.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/install-zeebe-exporters.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/install-zeebe-exporters.md, versioned_sidebars/version-8.1-sidebars.json, versioned_sidebars/version-8.2-sidebars.json, versioned_sidebars/version-8.3-sidebars.json
This guide was in [camunda/camunda-platform-helm](https://github.com/camunda/camunda-platform-helm), and as we keep the repo for development, all guides should be in the official docs.
=> docs(self-managed): add install zeebe exporters guide

docs/components/modeler/forms/configuration/forms-config-data-binding.md, versioned_docs/version-8.3/components/modeler/forms/configuration/forms-config-data-binding.md
The examples seem to mix up the paths `user.data` and `user.info`. I unified this to `user.info`. Please check if this was the intention.
Up to you to decide. It fixes an issue in the current docs of the latest release 8.3.
=> fix: unify paths

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
Retro review of https://github.com/camunda/camunda-docs/pull/2949.
=> retro review of 2949

docs/reference/announcements.md
Add 8.4 to Announcements page, including the release date and 18-month maintenance window.
This can be merged at any time since it's a placeholder for the `next` version of docs.
=> Add 8.4 to Announcements

optimize/components/userguide/collections-dashboards-reports.md, optimize_versioned_docs/version-3.10.0/components/userguide/collections-dashboards-reports.md, optimize_versioned_docs/version-3.11.0/components/userguide/collections-dashboards-reports.md, optimize_versioned_docs/version-3.7.0/components/userguide/collections-dashboards-reports.md
related to OPT-7413
User groups are currently not available to assign in Optimize collections for SaaS and CCSM: https://jira.camunda.com/browse/OPT-7413
=> chore(opt): add notice about user groups in C8

docs/components/modeler/web-modeler/collaborate-with-modes.md, versioned_docs/version-8.2/components/modeler/web-modeler/collaborate-with-modes.md, versioned_docs/version-8.3/components/modeler/web-modeler/collaborate-with-modes.md
Generalizing Play's availability so the documentation is robust as we roll out Play to more organizations.
Sometime this week (by 8 Dec) is ideal
=> fix(docs): clarify availability for enterprise customers

docs/self-managed/operational-guides/backup-restore/operate-tasklist-backup.md, versioned_docs/version-8.3/self-managed/operational-guides/backup-restore/operate-tasklist-backup.md
Currently, the docs state that a "repository" has to be present on ES side.
I was confused by this term (as it can have some meanings) and found out it means snapshot repository and that Elastic has a guide about it.
Also, the yaml has been fixed.
Minor improvement
=> Clarify Operate and Tasklist Backup prerequisity

docs/components/modeler/desktop-modeler/connect-to-camunda-8.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/connect-to-camunda-8.md, versioned_docs/version-8.3/components/modeler/desktop-modeler/connect-to-camunda-8.md
Desktop Modeler deploy diagram guide had two "1.'s" in some versions.
=> Fix typo in Modeler guide

docs/components/concepts/variables.md, versioned_docs/version-8.3/components/concepts/variables.md
This PR document the new corrected behavior changes in FEEL [bug](https://github.com/camunda/feel-scala/issues/701) fix
=> docs(variables): document escaped characters handling

docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, docs/components/connectors/out-of-the-box-connectors/microsoft-o365-mail.md, docs/components/connectors/protocol/http-webhook.md, optimize_sidebars.js, sidebars.js, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/microsoft-o365-mail.md, versioned_docs/version-8.1/components/connectors/protocol/http-webhook.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/microsoft-o365-mail.md, versioned_docs/version-8.2/components/connectors/protocol/http-webhook.md, versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/available-connectors-overview.md, versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/microsoft-o365-mail.md, versioned_docs/version-8.3/components/connectors/protocol/http-webhook.md, versioned_sidebars/version-8.1-sidebars.json, versioned_sidebars/version-8.2-sidebars.json, versioned_sidebars/version-8.3-sidebars.json
Adds doc related to Microsoft Office 365 Mail Connector.
With release 2023-12-12.
=> feat(connectors): add MSFT O365 Connector

docs/apis-tools/java-client/job-worker.md, docs/components/concepts/job-workers.md
This PR adds streaming job worker back pressure documentation. This describes the specific Java worker implementation, and also adds technical details about explaining how other clients should implement it in the reference section.
It also promotes the feature from experimental to stable by removing any notes referring to it as experimental :tada:
=> docs(zeebe): add job worker back pressure docs

docs/components/connectors/protocol/rest.md, versioned_docs/version-8.1/components/connectors/protocol/rest.md, versioned_docs/version-8.2/components/connectors/protocol/rest.md, versioned_docs/version-8.3/components/connectors/protocol/rest.md
feat(connectors): added note on OData support
Anytime
=> feat(connectors): added note on OData support

docs/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.1/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.2/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.3/components/connectors/custom-built-connectors/connector-sdk.md
Copy-paste error fix in the inbound connector project outline.
This is just a typo fix, so nothing urgent, but the sooner the better
=> fix(connectors): typo in the inbound project outline

versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md
=> Backport #3050 to 8.1-8.3

.github/workflows/publish-prod.yaml, .github/workflows/publish-stage.yaml, docusaurus.config.js
In #2944, I mistakenly left a configuration change that set `noIndex: true`. I did this so that when I deployed that PR as a preview site, it didn't get picked up by crawlers. Unfortunately, I overlooked it before merging, and now the production site is _also_ not indexed. 😱 
This PR: 
1. Resolves the fact that production is currently not indexed.
2. Swaps our default `noIndex` strategy, so that _everything_ is not indexed by default, and only the production build toggles `noIndex` to false.
=> fix: enable indexing in production (by swapping our default indexing strategy)

docs/components/modeler/bpmn/user-tasks/user-tasks.md, docs/components/modeler/web-modeler/advanced-modeling/form-linking.md, docs/components/modeler/web-modeler/advanced-modeling/publish-public-processes.md, docs/components/modeler/web-modeler/run-or-publish-your-process.md, docs/components/tasklist/userguide/starting-processes.md, docs/guides/utilizing-forms.md, sidebars.js, static/.htaccess
Closes https://github.com/camunda/web-modeler/issues/7121
The feature itself was already available for SaaS users. However, it was wrapped with the "Publication" feature, which does not exist yet on Self-Managed.
In this PR, I have:
- Removed duplication around how to link a form with a none start event.
- Extracted the section above in a separate independent one (that is not targeted anymore to SaaS only).
Please let me know if we can improve anything.
=> docs(web-modeler): start forms in self-managed

docs/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md
Previously, there were environment variables recommended to users who wish to authenticate with an OIDC provider (or Azure).  Existing helm chart users would read this documentation and expect to add env vars rather than configuring the helm chart options designed for this purpose.
This change includes 2 possible views of code snippets on this guide, 
1. One to view the environment variables necessary to configure
2. One to view the equivalent values.yaml variables necessary to edit.
Hopefully prior to 8.4 release.
Also, should be merged after this PR gets merged:
https://github.com/camunda/camunda-platform-helm/pull/1155
=> fix: added helm equivalent values for env vars for generic oidc provider

docs/components/connectors/protocol/http-webhook.md, docs/components/connectors/use-connectors/inbound.md, versioned_docs/version-8.1/components/connectors/use-connectors/inbound.md, versioned_docs/version-8.2/components/connectors/use-connectors/inbound.md, versioned_docs/version-8.3/components/connectors/protocol/http-webhook.md, versioned_docs/version-8.3/components/connectors/use-connectors/inbound.md
The webhook response expression now supports access to the correlation result via the `correlation` object.
=> docs(webhook): Document webhook correlation result

docs/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md
Mention the current limitation of Connectors not working OIDC.
=> docs(oidc): Connectors warning regarding OIDC

docs/apis-tools/grpc.md, versioned_docs/version-8.2/apis-tools/grpc.md, versioned_docs/version-8.3/apis-tools/grpc.md
Add SM auth instruction link in Zeebe API (gRPC) docs.
=> add zeebe auth intructions

docs/apis-tools/grpc.md, docs/components/concepts/job-workers.md
Adding the documentation for Update Job Timeout epic (please see the details [here](https://github.com/camunda/zeebe/issues/15020))
The following files were updated and the changes were verified locally:
- `grpc.md` new `UpdateJobTimeout` section added
- `job-workers.md` new `Timeout update` section added.
@abbasadel could you please verify the wording and let me know who else should be added to this PR?
closes #2862
=> Add update job timeout docs

docs/apis-tools/grpc.md, docs/components/concepts/process-instance-migration.md
List PR document the limitation that resulted by [Revert Migrate task instances with recreated event subscriptions](https://github.com/camunda/zeebe/issues/15659)
Closes #3089
=> docs: document boundary events migration limitation

static/.htaccess
Follow-up for #3066 
Fixes the rewrite rule which currently doesn't work: https://docs.camunda.io/docs/next/components/modeler/web-modeler/advanced-modeling/user-task-linking/
=> fix(web-modeler): fix rewrite rule for user task linking

docs/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.3/components/modeler/desktop-modeler/flags/flags.md
This adds an in-page link to make contents easier accessible.
=> docs(modeler): link default execution platform version flag

docs/components/console/manage-clusters/manage-alerts.md, versioned_docs/version-8.3/components/console/manage-clusters/manage-alerts.md
make sure the requirement for `HEAD` requests when configuring alert-webhooks is reflected in the docs
documenting the status quo, can be pushed to prod anytime
=> console: HEAD requests need to be accepted for alert-webhooks

docs/self-managed/platform-deployment/helm-kubernetes/guides/multi-namespace-deployment.md, sidebars.js
Highlight the changes needed for multi-namespace deployment which will be part of 8.4 release.
ASAP
=> docs(self-managed): add multi-namespace deployment guide

docs/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, docs/self-managed/platform-deployment/helm-kubernetes/platforms/google-gke.md, docs/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks.md, docs/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, docs/self-managed/platform-deployment/troubleshooting.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/platforms/google-gke.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, versioned_docs/version-8.1/self-managed/platform-deployment/troubleshooting.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/platforms/google-gke.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, versioned_docs/version-8.2/self-managed/platform-deployment/troubleshooting.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/google-gke.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, versioned_docs/version-8.3/self-managed/platform-deployment/troubleshooting.md
related to https://github.com/camunda/team-infrastructure-experience/issues/24.
[ingress-nginx Controller](https://github.com/kubernetes/ingress-nginx) and [NGINX Ingress Controller](https://docs.nginx.com/nginx-ingress-controller/) are often homogeneously used and abstracted by just `nginx`, `ingress controller`, `nginx ingress controller`. All of which results in confusion of which one to use as both have different target groups and histories.
The Camunda 8 Helm chart heavily focuses on `ingress-nginx`, which results in e.g. `NGINX Ingress Controller` not working out of the box since first it doesn't have `http2` enabled out of the box = no grpc and second annotations are missing to make it work. It can be done but we have nothing documented about it.
This PR aims to fix the confusion …
=> docs(ingress-nginx): correct nginx mentionings and replace NGINX Ingress usage

docs/apis-tools/console-api-reference.md, docs/apis-tools/grpc.md, docs/apis-tools/operate-api/overview.md, docs/apis-tools/tasklist-api-rest/tasklist-api-rest-overview.md, docs/apis-tools/tasklist-api/tasklist-api-overview.md, docs/apis-tools/web-modeler-api/index.md, optimize/apis-tools/optimize-api/optimize-api-authentication.md
Closes https://github.com/camunda/camunda-docs/issues/1438.
=> add gh and postman links to docs

docs/self-managed/zeebe-deployment/security/secure-cluster-communication.md, versioned_docs/version-8.1/self-managed/zeebe-deployment/security/secure-cluster-communication.md, versioned_docs/version-8.2/self-managed/zeebe-deployment/security/secure-cluster-communication.md, versioned_docs/version-8.3/self-managed/zeebe-deployment/security/secure-cluster-communication.md
Update Zeebe security docs to highlight PKCS1 support.
Closes https://github.com/camunda/camunda-docs/issues/3086
=> Update Zeebe security docs to highlight PKCS1 support

src/css/custom.css
Adds a `height:auto` property to images in the docs, so that large ones don't stretch vertically when running locally. 
This style _will_ apply in staging/production, also....but those already have the same style applied, so it should cause no noticeable difference.
cc @philippfromme @nikku who reported this in slack during the fallout of #3069.
In production, a CSS module is adding a `height:auto` property to images. 
For some reason that style is not applied locally. I don't see anything in our source that mentions this style (except in the changes introduced in this PR). 🤷
=> fix: prevent large images from stretching locally

optimize_versioned_sidebars/version-3.10.0-sidebars.json
Pre-work for #3151.
Synchronizes sidebars for the 8.2/3.10.0 versions of the docs.
Synchronization for versions 1.3, 8.1, 8.3, or next.
=> chore: synchronize sidebars for v8.2/3.10.0

docs/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md, versioned_docs/version-8.3/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
Part of https://github.com/camunda/web-modeler/issues/7279
After release of the new self managed versions https://github.com/camunda/web-modeler/issues/7354 (8.3.3) and https://github.com/camunda/web-modeler/issues/7355 (8.4.0).
=> docs(web-modeler): update ci-cd polling approach

docs/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.3/self-managed/operate-deployment/operate-configuration.md
This adds the available `CAMUNDA_OPERATE_MULTITENANCY_ENABLED` env flag to the documentation.
Related to [this discussion](https://camunda.slack.com/archives/C9B5270DA/p1702288473663209).
Changes mirror naming in [other product components](https://docs.camunda.io/optimize/self-managed/optimize-deployment/configuration/multi-tenancy/#configuration). 
> :information_source: Note that you seem to swap `default value` and description (compared to other components). I did not clean that up.
=> feat(self-managed): document multi-tenancy enabled flag

versioned_docs/version-8.3/reference/supported-environments.md
Removes a rogue comma from Identity + Optimize.
=> Typo in Supported Environments

docs/apis-tools/cli-client/cli-get-started.md, docs/apis-tools/go-client/go-get-started.md, docs/self-managed/concepts/multi-tenancy.md, versioned_docs/version-8.3/apis-tools/go-client/go-get-started.md
Document that the Go and CLI clients don't support multi-tenancy in Camunda 8.4 as well.
closes #2893
closes #2894
=> doc(self-managed): expand docs on unsupported multi-tenancy components

docs/apis-tools/tasklist-api-rest/schemas/models/task-variables.mdx, docs/apis-tools/tasklist-api-rest/schemas/requests/variable-input.mdx, versioned_docs/version-8.3/apis-tools/tasklist-api-rest/schemas/models/task-variables.mdx
Add a textual description related to variable values over the models and schema.
=> chore: Improve description for variables values

docs/apis-tools/cli-client/cli-get-started.md, docs/apis-tools/go-client/go-get-started.md, docs/apis-tools/java-client/job-worker.md, docs/apis-tools/tasklist-api/tasklist-api-graphql-to-rest-migration.md, docs/apis-tools/tasklist-api/tasklist-api-tutorial.md, docs/components/best-practices/architecture/understanding-human-tasks-management.md, docs/components/best-practices/development/connecting-the-workflow-engine-with-your-world.md, docs/components/concepts/process-instance-modification.md, docs/components/connectors/custom-built-connectors/update-guide/030-to-040.md, docs/components/connectors/out-of-the-box-connectors/amazon-dynamodb.md, docs/components/connectors/out-of-the-box-connectors/automation-anywhere.md, docs/components/connectors/out-of-the-box-connectors/googledrive.md, docs/components/connectors/out-of-the-box-connectors/power-automate.md, docs/components/connectors/out-of-the-box-connectors/twilio.md, docs/components/connectors/out-of-the-box-connectors/uipath.md, docs/self-managed/concepts/access-control/resource-authorizations.md, docs/self-managed/tasklist-deployment/tasklist-authentication.md, versioned_docs/version-8.2/self-managed/concepts/access-control/resource-authorizations.md, versioned_docs/version-8.2/self-managed/tasklist-deployment/tasklist-authentication.md, versioned_docs/version-8.3/self-managed/concepts/access-control/resource-authorizations.md, versioned_docs/version-8.3/self-managed/tasklist-deployment/tasklist-authentication.md
Closes https://github.com/camunda/developer-experience/issues/209.
The terminology in multi-tenancy was already cleaned up in a previous PR, so figured I would still get a little bang for my buck with this issue in other docs.
Added a note to add this to the WCoE. Most of these terms can be cleaned up on an as-found basis.
=> clean up vague termminology

optimize_versioned_sidebars/version-3.11.0-sidebars.json
Pre-work for #3151.
Synchronizes sidebars for the 8.3/3.11.0 versions of the docs.
Synchronization for versions 1.3, 8.1, 8.2, or next.
=> chore: synchronize sidebars for v8.3/3.11.0

sidebars.js
This PR adds the missing link to the Go job worker documentation to the sidebar.
=> fix: fix missing go job worker sidebar link

docs/components/concepts/process-instance-migration.md
This limitation was added in order to fix a bug with process instance migration.
closes #3178
=> Only migrate waiting process instances

docs/components/concepts/process-instance-migration.md
Applies a review hint of:
- #3179
The term 'wait state' was not fully described.
=> Clarify wait state term

docs/reference/announcements.md, versioned_docs/version-8.4/reference/announcements.md
* This PR adds a section about known limiations to annoucements
* The idea is to ensure that customer can discover centrally, what we know about limitations of certain releases
* The idea would be to use this as a standard section within announcements going forward
=> feat(announcements): add known limitations section

docs/components/modeler/bpmn/call-activities/call-activities.md, versioned_docs/version-8.2/components/modeler/bpmn/call-activities/call-activities.md, versioned_docs/version-8.3/components/modeler/bpmn/call-activities/call-activities.md, versioned_docs/version-8.4/components/modeler/bpmn/call-activities/call-activities.md
=> docs(call activity): add `propagateAllParentVariables`

src/theme/DocItem/Metadata/determineCanonical.js
The `determineCanonicalFromDoc` function, which is run on pretty much every page in the docs to identify a canonical source for it, is spamming the build output. It also pollutes the dev tools with an inaccurate warning message on each page.
It turns out...I used an incorrect regular expression to identify pages who pointed canonically at something other than the current version 😅 😬 
This PR corrects that regular expression. The result should be a cleaner build output, and more accuracy on the warnings that remain.
=> fix: quiet down noisy console logs from determineCanonical

docs/components/console/manage-clusters/manage-alerts.md, versioned_docs/version-8.4/components/console/manage-clusters/manage-alerts.md
related to https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/1946 - https://github.com/camunda/product-hub/issues/2007
change is already on production
=> console-webhook-alerts: HEAD is now optional again

docs/reference/announcements.md, versioned_docs/version-8.4/reference/announcements.md
* We had to relaese 8.4.1 due to a high criticality bug. Hence the 8.4.1 mention is not correct anymore. This commit fixes that.
=> fix(announcements): correct connector version reference

docs/components/connectors/protocol/http-webhook.md, versioned_docs/version-8.3/components/connectors/protocol/http-webhook.md, versioned_docs/version-8.4/components/connectors/protocol/http-webhook.md
Remove admonition as http webhook connector supports GET, not just POST.
This may need further backporting, but I cannot find exactly when this was introduced.
Internal Slack thread - https://camunda.slack.com/archives/C0637A56SVD/p1704917832213219?thread_ts=1702497257.276749&cid=C0637A56SVD
=> Remove POST only admonition for http webhook connector

docs/self-managed/platform-deployment/helm-kubernetes/deploy.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/deploy.md
Removes the rogue or extra ::: that looks like it was left after https://github.com/camunda/camunda-docs/commit/0ebba5ff4bcf902cf842faab33aa48fbc0c4e069#diff-f44dcc10786fc4c947fdcd613e96d4f7fd6e4f4fe460d972242d8043d215c796L64. 
If it makes sense to add this back, please do.
=> Remove rogue ::: in SM deploy

docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
Describe the new suffix pattern configuration, which allows to change the index suffixes
=> Add indexSuffixDatePattern to ES exporter config

docs/components/concepts/data-retention.md, versioned_docs/version-8.4/components/concepts/data-retention.md
Partially addresses feedback in https://github.com/camunda/product-gaps/issues/140. Possible it can be backported further, but the data retention page for Tasklist doesn't currently exist before 8.4.
=> Add Tasklist to SaaS concepts page on data retention

optimize/components/userguide/additional-features/alerts.md, optimize/self-managed/optimize-deployment/configuration/system-configuration.md, optimize/self-managed/optimize-deployment/configuration/webhooks.md, optimize_versioned_docs/version-3.10.0/components/userguide/additional-features/alerts.md, optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/configuration/system-configuration.md, optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/configuration/webhooks.md, optimize_versioned_docs/version-3.11.0/components/userguide/additional-features/alerts.md, optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/configuration/system-configuration.md, optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/configuration/webhooks.md, optimize_versioned_docs/version-3.12.0/components/userguide/additional-features/alerts.md, optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/configuration/system-configuration.md, optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/configuration/webhooks.md, optimize_versioned_docs/version-3.9.0/components/userguide/additional-features/alerts.md, optimize_versioned_docs/version-3.9.0/self-managed/optimize-deployment/configuration/system-configuration.md, optimize_versioned_docs/version-3.9.0/self-managed/optimize-deployment/configuration/webhooks.md
Reported via #3205 by @nareshgoswami1508. I chose to over-document with both labels and admonitions for the most transparency possible. This does mean some pages have two admonitions at the top of the page.
Reviewers - please double check that the edits per version are correct.
=> Clarify Optimize alerting (webhooks and email)

howtos/configuration.md
#2732 included a temporary adjustment where @akeller hosted the gist for the CLA. This has been fixed via https://github.com/camunda/developer-experience/issues/118#issuecomment-1768758672, but the documentation was not updated.
=> Update CLA config to camundait user

docs/self-managed/identity/what-is-identity.md, versioned_docs/version-8.4/self-managed/identity/what-is-identity.md
Cross link deployment guides on What is Identity page. ~Will backport after initial review~
Related to https://camunda.slack.com/archives/C06112NS4GJ/p1705065758885659.
=> Add guides link to what-is-identity

versioned_docs/version-8.2/self-managed/tasklist-deployment/data-retention.md, versioned_docs/version-8.2/self-managed/tasklist-deployment/importer-and-archiver.md, versioned_docs/version-8.3/self-managed/tasklist-deployment/data-retention.md, versioned_docs/version-8.3/self-managed/tasklist-deployment/importer-and-archiver.md, versioned_sidebars/version-8.2-sidebars.json, versioned_sidebars/version-8.3-sidebars.json
Partially addresses feedback from https://github.com/camunda/product-gaps/issues/140.
~TODO: Should this page also be included in the backport? Or did the importer and archiver not exist? https://docs.camunda.io/docs/self-managed/tasklist-deployment/importer-and-archiver/#archive-period~
=> Backport tasklist data retention page

docs/apis-tools/zeebe-api/gateway-service.md, versioned_docs/version-8.4/apis-tools/zeebe-api/gateway-service.md
This PR documents the new `StreamActivatedJobs` RPC that was added in 8.4.
> [!Note]
> While it was present in 8.3, it was experimental, I think it's OK to omit it.
closes #3195
=> docs: document StreamActivatedJobs RPC

docs/self-managed/operational-guides/update-guide/830-to-840.md, docs/self-managed/zeebe-deployment/configuration/configuration.md, versioned_docs/version-8.4/self-managed/operational-guides/update-guide/830-to-840.md, versioned_docs/version-8.4/self-managed/zeebe-deployment/configuration/configuration.md
With https://github.com/camunda/zeebe/issues/14398 we stopped logging the configuration at startup and instead make it available via the monitoring API. This change documents that in both the configuration page (i.e. https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/#verifying-configuration) and in the update announcement.
=> Document how to verify Zeebe configuration starting with 8.4

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.4/components/modeler/desktop-modeler/element-templates/defining-templates.md
Related to https://github.com/camunda/product-hub/issues/1807
=> feat: document `zeebe:calledElement` bindings

docs/self-managed/concepts/exporters.md, versioned_docs/version-8.4/self-managed/concepts/exporters.md
This Pr documents changes that had to be made in order to expose partitionId on Exporter Context in the exporter API. Namely During the loading phase, the configuration when each exporter is validated, on instantiating the Exporter Context, we pass a null partition id, which gets replaced by the correct one at runtime.
See https://github.com/camunda/zeebe/pull/16070 and https://github.com/camunda/zeebe/issues/15418#issuecomment-1900442019
=> Document configuration changes to the Exporter Context

docs/components/modeler/forms/form-element-library/forms-element-library-iframe.md
We are adding a new feature to iframes which lets users relax the iframe's securities to access some more features. This can be risky when used in an uneducated manner, so we're both providing details on what the various settings do, but also what risks they can potentially incur. 
I've decided to make the security docs quite "scary" to avoid users compromising their own security. The risks are very low to start with, as modern browsers (and tasklist) enforce certain security policies that make it all quite safe. However, a browser vulnerability combined with the right set of deactivated securities could, under hypothetical circumstances, be exploited. This is important context when reviewing if we are communicating the right things to the user.
=> feat: document iframe security parameters and add advisory

howtos/documentation-guidelines.md
The reviewer for tasklist is out-of-date
=> fix(guidelines): Update reviewers for Tasklist

docs/components/console/manage-clusters/create-cluster-include.md, docs/components/modeler/web-modeler/run-or-publish-your-process.md, docs/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
Closes https://github.com/camunda/web-modeler/issues/7660
We are adding a few information about the roles necessary to deploy a diagram to `prod` clusters, and other tags. See Product Hub epic: https://github.com/camunda/product-hub/issues/1240
=> docs: add information about prod clusters deployment and roles

docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
I copy & pasted an `date and time` example from the docs and I didn't have a clue why it didn't work. Turned out the date time syntax was invalid, i.e. one `0` to many.
Preferably ASAP - I don't want others to stumble across the wrong example. The change is trivial.
Note: I don't have permission to set @christinaausley  as assignee.
=> docs( feel-built-in-functions-conversion): Fix invalid date time syntax

versioned_docs/version-1.3/reference/feel/builtin-functions/feel-built-in-functions-conversion.md, versioned_docs/version-8.1/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md, versioned_docs/version-8.2/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md, versioned_docs/version-8.3/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md, versioned_docs/version-8.4/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
Backport follow up on #3273, as reported by @tobiasschaefer - thank you!
=> Backport follow up on #3273

docs/self-managed/operational-guides/update-guide/840-to-850.md, docs/self-managed/zeebe-deployment/operations/health.md, sidebars.js
Documents the changes to the Zeebe broker health checks done in https://github.com/camunda/zeebe/pull/15913, namely:
- Routes are migrated to the health actuator
- The old routes will now return a 301
closes #3221
=> Document new Zeebe broker health checks

docs/components/tasklist/userguide/using-tasklist.md
Documentation update for https://github.com/camunda/tasklist/pull/4325
Describe the Auto-select feature being added into the next release.
=> docs(tasklist): describe the auto-select option

docs/components/modeler/forms/sidebar-schema.js
This fix adds a missing reference to the newly added documentation page of the html component.
=> fix: add html form component to sidebar schema

docs/apis-tools/zeebe-api/gateway-service.md, docs/components/concepts/process-instance-migration.md
Zeebe and Operate `8.5.0-alpha1` support the migration of process instances with active user tasks.
Both task implementations are supported:
- `Job worker`
- `Zeebe user task`
Mapping instructions cannot change the task implementation.
All values of a job or a 'zeebe user task' are left unchanged after migration.
closes https://github.com/camunda/zeebe/issues/15964
=> Support process instance migration with active user tasks

docs/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, docs/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, docs/self-managed/platform-deployment/troubleshooting.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, versioned_docs/version-8.2/self-managed/platform-deployment/troubleshooting.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, versioned_docs/version-8.3/self-managed/platform-deployment/troubleshooting.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md, versioned_docs/version-8.4/self-managed/platform-deployment/troubleshooting.md
Closes https://github.com/camunda/camunda-docs/issues/3159. To add casing guidelines to WCoE at next release.
The casing here really aligned by chance with what Red (Rad) Hat does by its product naming to help distinguish the terminology references from one another.
"NGINX Ingress Controller" and "ingress-nginx controller" really helps distinguish between the two, but let me know if you have additional thoughts or questions.
=> style(formatting): retro review 3147

docs/components/concepts/backups.md
We released a feature in Alpha 2 - Dual region backups. One clarification is needed as we are getting customer question for support and CSM.
- [ x] This functionality is already available but undocumented.
=> Adding cost statement to Dual region Backups

docs/apis-tools/zeebe-api/gateway-service.md, versioned_docs/version-8.1/apis-tools/grpc.md, versioned_docs/version-8.2/apis-tools/grpc.md, versioned_docs/version-8.3/apis-tools/grpc.md, versioned_docs/version-8.4/apis-tools/zeebe-api/gateway-service.md
The gRPCs `CreateProcessInstance` and `CreateProcessInstanceWithResult` support start instructions, but these instructions have limitations that are undocumented, i.e., models may contain elements that cannot be used in start instructions. Since the start instructions use the same command as the `ModifyProcessInstance` call, a respective reference has been added as note.
=> Document limitations of startinstructions

docs/reference/announcements.md, versioned_docs/version-8.4/reference/announcements.md
The term wrong was missing in the announcement, making it harder to understand.
=> Revised Camunda 8.4 Announcement For Form Linking Bug

versioned_docs/version-8.3/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
Closes #3348
Partially reverts https://github.com/camunda/camunda-docs/pull/3054, see also https://camunda.slack.com/archives/C026U8GBNSW/p1708120962924399
=> fix(web-modeler): remove mention of 8.4 features

versioned_docs/version-8.4/apis-tools/frontend-development/introduction-to-task-applications.md
Remove "\" in text. I don't know how it got there but it looks strange.
=> docs(task application): Remove strange backslash

docs/components/operate/userguide/operate-feedback-and-questions.md, sidebars.js, static/.htaccess, versioned_docs/version-8.1/components/operate/userguide/operate-feedback-and-questions.md, versioned_docs/version-8.2/components/operate/userguide/operate-feedback-and-questions.md, versioned_docs/version-8.3/components/operate/userguide/operate-feedback-and-questions.md, versioned_docs/version-8.4/components/operate/userguide/operate-feedback-and-questions.md, versioned_sidebars/version-8.1-sidebars.json, versioned_sidebars/version-8.2-sidebars.json, versioned_sidebars/version-8.3-sidebars.json, versioned_sidebars/version-8.4-sidebars.json
We don't need an individual page for feedback and support for Operate. I've removed this and redirect to the Contact page.
=> Remove operate feedback page and redirect

docs/reference/dependencies.md, versioned_docs/version-8.1/reference/dependencies.md, versioned_docs/version-8.2/reference/dependencies.md, versioned_docs/version-8.3/reference/dependencies.md, versioned_docs/version-8.4/reference/dependencies.md
Adds a link to the Connectors release that includes the SBOMs. These links currently go to an archived repo or 404.
=> Quick win - link to Connectors dependencies in release assets

.github/workflows/announce-release.yaml
A GitHub Action to post a simple message on #ask-c8-documentation with the tag name and release URL. This uses the Slack Workflow builder - Docs Release Bot
Closes https://github.com/camunda/developer-experience/issues/21.
=> Add simple release announcement to Slack

docusaurus.config.js, src/theme/Footer/index.js, static/plugins/osano/index.js
Requested by @antantunes (I think, assuming I guessed correctly from the username), [in Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1708440411893479).
Adds a script that does some Google Tag Manager things prior to loading the Osano.js script. 
TBH I don't really know what it is doing and how that's fixing the problem (or even what the problem is to require this change), but I hope that doesn't matter. I recognize it as referencing Google Tag Manager, so it doesn't seem unsafe to me, but 🤷 
[Below is updated:]
Below is a screenshot of the source for a page when running locally, to prove that scripts run in the following sequence in the `head` element: 
1. Google Consent Mode Default Script
2. Osano dependency
3. Google Tag Manager initialization
To control the order of scripts, …
=> feat: execute tag manager script right before loading osano.js

docs/components/modeler/desktop-modeler/flags/flags.md
Documents the newly added `disable-httl-hint`.
Related to https://github.com/camunda/camunda-modeler/issues/4062
Depends on https://github.com/camunda/camunda-docs/pull/3324
=> feat(components/modeler): document `disable-httl-hint` flag

docs/components/modeler/desktop-modeler/flags/flags.md
Documents the newly added `default-httl` flag, contributed via https://github.com/camunda/camunda-modeler/pull/4147 and https://github.com/camunda/camunda-modeler/pull/4162.
Depends on https://github.com/camunda/camunda-docs/pull/3387
=> feat(components/modeler): document `default-httl` flag

.github/workflows/check-versions.yaml
Addresses #3358. 
Updates the check-versions workflow to _check out_ the PR branch, and _fetch_ the target branch, and use those for a comparison to determine which files have changed in this PR. This should function equally on local and forked PRs, which the current approach does not do. 
See #3396, #3397, and #3398 for an experiment that proves this new approach.
=> fix: make check-versions workflow function on forked PRs

docs/components/console/manage-clusters/manage-api-clients.md, docs/guides/getting-started-orchestrate-human-tasks.md, docs/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md, optimize/self-managed/optimize-deployment/migration-update/2.5-to-2.6.md, optimize/self-managed/optimize-deployment/migration-update/instructions.md, optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/migration-update/2.5-to-2.6.md, optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/migration-update/instructions.md, optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/migration-update/2.5-to-2.6.md, optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/migration-update/instructions.md, optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/migration-update/2.5-to-2.6.md, optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/migration-update/instructions.md, optimize_versioned_docs/version-3.7.0/self-managed/optimize-deployment/migration-update/2.5-to-2.6.md, optimize_versioned_docs/version-3.7.0/self-managed/optimize-deployment/migration-update/instructions.md, optimize_versioned_docs/version-3.9.0/self-managed/optimize-deployment/migration-update/2.5-to-2.6.md, optimize_versioned_docs/version-3.9.0/self-managed/optimize-deployment/migration-update/instructions.md, versioned_docs/version-8.1/components/console/manage-clusters/manage-api-clients.md, versioned_docs/version-8.2/components/console/manage-clusters/manage-api-clients.md, versioned_docs/version-8.2/guides/getting-started-orchestrate-human-tasks.md, versioned_docs/version-8.3/components/console/manage-clusters/manage-api-clients.md, versioned_docs/version-8.3/guides/getting-started-orchestrate-human-tasks.md, versioned_docs/version-8.4/components/console/manage-clusters/manage-api-clients.md, versioned_docs/version-8.4/guides/getting-started-orchestrate-human-tasks.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md
Closes https://github.com/camunda/developer-experience/issues/255. To be added to this week's WCoE release.
=> adjust step x references

package.json
`npm run format` was only formatting the Tasklist API Explorer...because I told it to. I accidentally committed a change from while I was doing that work, which limited the scope of input files for `npm run format`. 
This PR reverts that and gets `npm run format` back to working properly.
=> oops: fix formatter by reverting accidental commit

docs/components/modeler/bpmn/user-tasks/user-tasks.md, docs/guides/getting-started-orchestrate-human-tasks.md
* Adjust the user task BPMN modeling reference to reflect Zeebe user tasks as the default. Job worker-based user tasks are still featured but only as an alternative option. Differences and limitations for those job worker-based tasks are outlined. Form handling is also adjusted to reflect the differences and to hint at what's different for job worker-based user tasks.
closes #3297 
depends on https://github.com/camunda/camunda-docs/issues/3277
=> Adjust user tasks to Zeebe user tasks

docs/components/modeler/reference/modeling-guidance/rules/history-time-to-live.md
Retro review of https://github.com/camunda/camunda-docs/pull/3324.
=> 3324 retro review

docs/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md
One of customers face problems setup camunda to work with their own oidc, because of missing information about what are the supported (required) grant_types and which type of token they are required.
- [x ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.
=> docs(identity): add required grant types with oidc

versioned_docs/version-8.4/self-managed/concepts/exporters.md
Fix github urls for exporter example and api
I got a 404 when trying to follow the exporter links.
=> Update exporters.md - Fix links

hacks/generateOptimizeSidebars.md, howtos/versioning.md, optimize_sidebars.js, optimize_versioned_sidebars/version-3.12.0-sidebars.json
collaboration with @christinaausley 
Synchronizes the sidebars for the Optimize instance, versions Next and Current, based on the release of our new API Explorers. I missed this when I published the explorers.
Note that we will need to do synchronization again for the upcoming release, and this PR only covers the API Explorer changes, intentionally.
=> chore: sync sidebars based on new API Explorers

.github/workflows/check-versions.yaml
Reverts commit #3402. 
Those changes were resulting in inaccurate, noisy comments from the check-versions workflow. Rather than listing the differences between the PR and its target branch _at the time the PR was opened_, it was listing the differences between the PR and its target branch _right now_. When the `main` branch had evolved since opening the PR, that meant the check-versions comment listed basically everything that had been merged since the PR was opened. Reverting this PR will put us back in a place where the check-versions workflow doesn't work for forked PRs, but it is giving accurate messages for 99% of our PRs (which are local instead of forked).
I thought I'd tested this case in https://github.com/camunda/camunda-docs/pull/3396, but the workflow seems to be functioning …
=> Revert #3402 (check-versions running on forks)

docs/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.2/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.3/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.4/self-managed/operate-deployment/operate-configuration.md
Add a small note to provide a bit more guidance for customers on how to turn configuration properties into environment variables.
- We opted to not do this on 8.1 docs since that version is almost out of support.
=> chore: add note to turn properties to ENV_VARS

docs/components/modeler/bpmn/user-tasks/user-tasks.md
Add an info board on User Task for modeler on assignment section
It can be merged after the approval, once the component is live already.
=> chore: add on assignments a link to user task restrictions

docs/self-managed/operational-guides/update-guide/830-to-840.md, docs/self-managed/operational-guides/update-guide/840-to-850.md, versioned_docs/version-8.4/self-managed/operational-guides/update-guide/830-to-840.md
* Details what changes for user task records from 8.4 to 8.5, including the breaking changes for candidate attributes.
* Fixes headings for the 8.3 to 8.4 update guide
=> docs: add user task changes to the update guide

docs/self-managed/platform-deployment/overview.md, versioned_docs/version-8.2/self-managed/platform-deployment/overview.md, versioned_docs/version-8.3/self-managed/platform-deployment/overview.md, versioned_docs/version-8.4/self-managed/platform-deployment/overview.md
Closes #3492 - removes redundant information found on Supported Environments page
=> Remove technology from components list

howtos/documentation-guidelines.md
Adding @dlavrenuek for Identity docs reviews (replacing @ultraschuppi).
=> Add Identity EM

docs/self-managed/operational-guides/update-guide/840-to-850.md, docs/self-managed/platform-deployment/helm-kubernetes/upgrade.md
Due to the limitations of the Helm sub-chart structure where the sub-charts cannot access the parent or other sub-charts, we moved away from that structure. Also, renamed a couple of keys to make that possible and followed a unified naming.
This is a breaking change since the user needs to restructure the values file according to the new names.
=> docs(self-managed): upgrade instractions fo components moved to top-level in v8.5

docs/self-managed/operational-guides/backup-restore/optimize-backup.md, versioned_docs/version-8.3/self-managed/operational-guides/backup-restore/optimize-backup.md, versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/optimize-backup.md
Hi Optimize-Team!
Very small changes, but maybe it will help so the backup procedure is better understood by users.
As normally you backup the entire stack, one could easily assume that it works the same way as for Operate / Tasklist. However, it's slightly different as it's the only tool that has a dedicated management port and will NOT use the contextpath then.
=> docs(self-managed): backup procedure slightly different for optimize

optimize/self-managed/optimize-deployment/migration-update/3.12_8.4-to-3.13_8.5.md, optimize/self-managed/optimize-deployment/migration-update/instructions.md, optimize/self-managed/optimize-deployment/migration-update/translation-diffs/differences_localization_312_313.diff
related to 3.13 release
This adds the migration guide for the 3.13 Optimzie release.
=> chore(optimize): add 3.13 Optimize migration notes

docs/apis-tools/administration-api/authentication.md, docs/components/console/manage-clusters/manage-api-clients.md, versioned_docs/version-8.4/apis-tools/administration-api/authentication.md, versioned_docs/version-8.4/components/console/manage-clusters/manage-api-clients.md
Closes https://github.com/camunda/developer-experience/issues/274.
=> draft out rate limit details

versioned_docs/version-8.4/self-managed/zeebe-deployment/zeebe-gateway/interceptors.md
=> docs(interceptors): improve custom interceptor doc.

docs/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md
Closes https://github.com/camunda-cloud/identity/issues/2701
Through the investigation and implementation of an upcoming piece of work we discovered that there are known limitations in the OpenID spec for front channel logout due to third party cookie settings.
This is something that we should make the customers aware of. The OpenID spec lists the limitation [here](https://openid.net/specs/openid-connect-frontchannel-1_0.html#ThirdPartyContent) and an example of this in the Microsoft docs is [here](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-spa-sign-in?tabs=javascript2#sign-out-behavior-on-browsers)
=> docs(identity): Add note regarding single sign out limitation

docs/components/best-practices/development/routing-events-to-processes.md, versioned_docs/version-8.1/components/best-practices/development/routing-events-to-processes.md, versioned_docs/version-8.2/components/best-practices/development/routing-events-to-processes.md, versioned_docs/version-8.3/components/best-practices/development/routing-events-to-processes.md
Backporting https://github.com/camunda/camunda-docs/pull/3546.
=> backport 3546

docs/self-managed/zeebe-deployment/security/client-authorization.md
This PR updates the authorization documentation for Zeebe clients, specifically for the new `CredentialsProvider` API. The Go client portion is left mostly untouched since we will not support REST with the Go client.
=> docs: update credentials provider docs with new API

docs/self-managed/operational-guides/update-guide/840-to-850.md, docs/self-managed/zeebe-deployment/configuration/broker.md, docs/self-managed/zeebe-deployment/configuration/gateway.md, docs/self-managed/zeebe-deployment/operations/health.md, docs/self-managed/zeebe-deployment/operations/management-api.md, docs/self-managed/zeebe-deployment/operations/network-ports.md, docs/self-managed/zeebe-deployment/zeebe-gateway/zeebe-gateway-overview.md
This PR documents the new server side configuration options for the REST API. Since many of these properties were previously used to configure the management server, I've also added how to configure it explicitly as part of our configuration page, and added an update guide note about the possibly breaking change.
closes #3278
With the release of 8.5.0.
=> docs: document REST & management configuration

docs/apis-tools/java-client/zeebe-process-test.md, versioned_docs/version-8.1/apis-tools/java-client/zeebe-process-test.md, versioned_docs/version-8.2/apis-tools/java-client/zeebe-process-test.md, versioned_docs/version-8.3/apis-tools/java-client/zeebe-process-test.md, versioned_docs/version-8.4/apis-tools/java-client/zeebe-process-test.md
The term "Zeebe test engine" confuses users because they are unsure if the test engine is the same as the production engine.
Replace the term "test engine" by just "Zeebe engine" and describe it as a lightweight in-memory Zeebe engine.
=> feat: Clarify terms in Zeebe-Process-Test

docs/apis-tools/zeebe-api/gateway-service.md, docs/apis-tools/zeebe-api/grpc.md, versioned_docs/version-8.1/apis-tools/grpc.md, versioned_docs/version-8.2/apis-tools/grpc.md, versioned_docs/version-8.3/apis-tools/grpc.md, versioned_docs/version-8.4/apis-tools/zeebe-api/gateway-service.md, versioned_docs/version-8.4/apis-tools/zeebe-api/grpc.md
The "Gateway service" page contains Zeebe's available RPCs. Technically, the name "Gateway service" is correct because the service is called "Gateway" in the protobuf file. However, users (like me) might not expect Zeebe's gRPC API under this name. Rename the page to "Zeebe API RPCs" and link it from the overview page.
The module of the protobuf file was moved. Change the link for the current version to the new directory. Change the link of previous versions to the correct branch.
=> feat: Rename Zeebe gPRC page title (Gateway service)

docs/components/connectors/custom-built-connectors/connector-sdk.md
Related issue: https://github.com/camunda/team-connectors/issues/630
Related PR: https://github.com/camunda/connectors/pull/2146
=> docs(connectors): Add documentation and exemple for ConnectorRetryException

docs/components/connectors/protocol/graphql.md, docs/components/connectors/protocol/rest.md, versioned_docs/version-8.1/components/connectors/protocol/graphql.md, versioned_docs/version-8.1/components/connectors/protocol/rest.md, versioned_docs/version-8.2/components/connectors/protocol/graphql.md, versioned_docs/version-8.2/components/connectors/protocol/rest.md, versioned_docs/version-8.3/components/connectors/protocol/graphql.md, versioned_docs/version-8.3/components/connectors/protocol/rest.md, versioned_docs/version-8.4/components/connectors/protocol/graphql.md, versioned_docs/version-8.4/components/connectors/protocol/rest.md
Update timeout settings in network communication docs
related : 
https://github.com/camunda/web-modeler/pull/8689
April release
=> docs(ootbc): Update timeout settings in network communication docs

docs/self-managed/zeebe-deployment/operations/update-zeebe.md
Documents that Zeebe 8.5.0 now supports rolling updates and how to execute them using our helm charts.
I've also added a troubleshooting section to catch common problems.
Part of https://github.com/camunda/zeebe/issues/15879
This documents a new ability of Zeebe 8.5.0, ideally it should be released as part of 8.5.
=> docs(zeebe): document rolling updates

sidebars.js
#3507 [accidentally removed the Zeebe REST API Explorer from the sidebar nav](https://github.com/camunda/camunda-docs/pull/3507/files#diff-9a6a0fdafefb0eecffb77784bc94f5ad984062167b8bcb7c4a899c90f6f567e8L720). This was resulting in no sidebar appearing on the Zeebe REST API Explorer pages ([as described](https://github.com/camunda/camunda-docs/pull/3597#issuecomment-2037428039) in #3597). 
This PR reverts that removal, so that the Zeebe REST API docs appear in the sidebar again. 
(Note that there were no issues with the optimize_sidebars.js, because I was lazy and was waiting to add the Zeebe REST API docs to that sidebar during my bulk sidebar synchronization tomorrow 😅 )
=> fix: revert zeebe-api-rest sidebar removal

docs/reference/announcements.md, versioned_docs/version-8.2/reference/announcements.md, versioned_docs/version-8.3/reference/announcements.md, versioned_docs/version-8.4/reference/announcements.md
Adds a note on how to update from Web Modeler 8.2 to a newer minor version (an update to the latest 8.2.x patch version is required first in some cases).
Closes https://github.com/camunda/web-modeler/issues/8535.
- Docs update should be published with the Web Modeler 8.2.13 patch release (due date April 9)
=> docs(announcements): add note on updating Web Modeler 8.2 to a newer version

docs/components/concepts/backups.md, versioned_docs/version-8.2/components/concepts/backups.md, versioned_docs/version-8.3/components/concepts/backups.md, versioned_docs/version-8.4/components/concepts/backups.md
This back ports the new backup documentation to all versions above 8.2. The new feature of backup schedule is supported in all these versions. I tried to improve the wording and removed some redundancies. 
Relates to:
https://github.com/camunda-cloud/camunda-operator/issues/2543
PDP: https://github.com/camunda/product-hub/issues/1355
Note for the checklist: I was a bit unsure whether I should check the last two. The `or` sentence is accurate in both cases. 😅 .
=> feat(concepts): update backup docs

docs/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md
My goal is to improve the local deployment guide to help users do E2E
=> Update Local deployment guide with connectivity topics

docs/apis-tools/frontend-development/01-task-applications/02-user-task-lifecycle.md
Follow up to https://github.com/camunda/camunda-docs/pull/3549.
=> typo for update endpoint

optimize_versioned_sidebars/version-3.12.0-sidebars.json, versioned_sidebars/version-8.4-sidebars.json
Synchronizes sidebars for **v8.4**.
* There are many whitespace changes in this PR. In the past I've not included whitespace changes for sidebar synchronization, but since they are generated by the script consistently every time, we realized it makes more sense to commit them....so that in the future, all we see during synchronization are meaningful changes.
* There are no significant changes in the main instance's sidebars.json file! That means we did a great job of updating the main instance sidebars when we made structural changes to the Optimize documentation in v8.4. Yay, us!
* There are many significant changes in the Optimize instance's optimize_sidebars.json file. We introduced multiple API Explorers, and we also made a big folder for all the Components in the …
=> chore(sidebars): sync sidebars in v8.4

docs/self-managed/setup/deploy/amazon/aws-marketplace.md, docs/self-managed/setup/deploy/openshift/redhat-openshift.md, docs/self-managed/setup/deploy/other/docker.md, docs/self-managed/setup/guides/ingress-setup.md, docs/self-managed/setup/guides/multi-namespace-deployment.md, docs/self-managed/setup/upgrade.md
This PR updates the Helm documentation to include the new Zeebe REST API, specifically references to the old Zeebe Gateway ingress and various use cases around that.
> [!Note]
> I did not update any images, as I don't know where the source images live.
I tried to update as much as it made sense to me, but some things (like the OpenShift route set up, and the managed console stuff) I know little about, so there may be some errors. Please review these more carefully.
With the 8.5.0 release.
=> docs: update Helm chart docs for REST API

sidebars.js
The self-managed installation restructuring https://github.com/camunda/camunda-docs/pull/3476 has accidentally lost a link in the sidebar.
This PR aims to fix that. The remaining dual-region topics are still present, only the AWS one is lost in the sidebar.
Doesn't require port back since 8.5 isn't cut yet.
=> docs(sidebar): resurrect aws dual-region setup

static/.htaccess
For some reason, the old Operate & Tasklist API explorer URLs are not redirecting to their new homes. I'm not sure why this is. And it's actually even weirder, because you can _see_ the explorer on the screen for a second before it changes to a "Not found" screen. [Example](https://docs.camunda.io/api/operate/docs/operate-public-api/).
When investigating, I noticed the redirect rules for these explorers were missing the `[R=301,L]` options. I don't _think_ this would cause the URL to not redirect, because it still matches, and nothing matches after it....but it's the only thing I can see that looks funny about these two rules, so maybe?????
=> fix?: maybe fix these two api explorer redirects?

docs/self-managed/setup/guides/air-gapped-installation.md, docs/self-managed/setup/guides/multi-namespace-deployment.md, docs/self-managed/setup/install.md, docs/self-managed/setup/upgrade.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.5/self-managed/setup/guides/air-gapped-installation.md, versioned_docs/version-8.5/self-managed/setup/guides/multi-namespace-deployment.md, versioned_docs/version-8.5/self-managed/setup/install.md, versioned_docs/version-8.5/self-managed/setup/upgrade.md
Using Web Modeler PostgreSQL helm key `webModelerPostgresql` is not possible until the 8.6 release.
ASAP.
=> docs(self-managed): set web-modeler postgresql helm key back

docs/apis-tools/web-modeler-api/index.md
Removes the migration guide for the public-api for all versions > 8.5 and finally closes https://github.com/camunda/web-modeler/issues/8250.
=> docs(web-modeler): remove migration guide from next

howtos/interactive-api-explorers.md
Now that all API Explorers have been migrated to the main docs, we can remove documentation describing the old approach.
=> docs: simplify API Explorer docs

docs/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md, versioned_docs/version-8.2/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md, versioned_docs/version-8.3/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md, versioned_docs/version-8.4/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md, versioned_docs/version-8.5/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md
Closes https://github.com/camunda/web-modeler/issues/8999
=> chore(web-modeler): clarify target container for timeout increases

versioned_docs/version-8.5/self-managed/setup/deploy/local/local-kubernetes-cluster.md
=> Backport to 8.5

docs/self-managed/operational-guides/update-guide/introduction.md, versioned_docs/version-8.5/self-managed/operational-guides/update-guide/introduction.md
8.5 update guide link was missing from intro page.
I also added a | between the release notes and release blog, as that spacing has bothered me for years.
=> Add 8.5 update guide to intro page

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.5/components/modeler/desktop-modeler/element-templates/defining-templates.md
This PR adds documentation for new element template features: number and boolean types as well as the `feel: static` option.
This was released with 8.5 but not documented.
related to https://github.com/bpmn-io/internal-docs/issues/919
=> feat(modeler): document boolean and number template types

optimize_sidebars.js, optimize_versioned_sidebars/version-3.13.0-sidebars.json, sidebars.js, versioned_sidebars/version-8.5-sidebars.json
The optimize usertask link seems to have slipped into the filters section erroneously.
=> chore(optimize): move usertask sidebars to correct location

static/.htaccess
Closes https://github.com/camunda/doc-hospital/issues/14.
=> adjust redirect for grpc link

versioned_docs/version-8.5/components/connectors/out-of-the-box-connectors/slack.md
This error has already been fixed in #3573, but apparently I forgot to rebase onto main and it slipped away from me that we've already had the 8.5 version directory by then 🤦
=> fix(connectors): slack inbound data mapping

docs/reference/release-notes/850.md, versioned_docs/version-8.5/reference/release-notes/850.md
Emphasize on Optimize, Identity and Connectors not supported yet.
The former wording in the release notes was not aligned with the [documentation](https://docs.camunda.io/docs/self-managed/concepts/multi-region/dual-region/#limitations), where we clearly state these 3 components are not supported in the dual-region setups.
Context: https://camunda.slack.com/archives/C0486FPV076/p1713534628804619?thread_ts=1713370090.038159&cid=C0486FPV076 (conversation with @ManuelDittmar)
=> fix(dual-region): Rephrase the release notes on supported components for clarity

sidebars.js, versioned_sidebars/version-8.5-sidebars.json
Noticed that the 3.13. migration notes for Optimize were not added to the sidebars
=> chore(optimize): add 3.13 migration notes to sidebars

optimize_sidebars.js, sidebars.js
=> sync sidebars for next

docs/apis-tools/operate-api/overview.md, docs/apis-tools/tasklist-api-rest/tasklist-api-rest-overview.md, docs/apis-tools/zeebe-api-rest/zeebe-api-rest-overview.md, versioned_docs/version-8.2/apis-tools/operate-api/overview.md, versioned_docs/version-8.2/apis-tools/tasklist-api-rest/tasklist-api-rest-overview.md, versioned_docs/version-8.3/apis-tools/operate-api/overview.md, versioned_docs/version-8.3/apis-tools/tasklist-api-rest/tasklist-api-rest-overview.md, versioned_docs/version-8.4/apis-tools/operate-api/overview.md, versioned_docs/version-8.4/apis-tools/tasklist-api-rest/tasklist-api-rest-overview.md, versioned_docs/version-8.5/apis-tools/operate-api/overview.md, versioned_docs/version-8.5/apis-tools/tasklist-api-rest/tasklist-api-rest-overview.md, versioned_docs/version-8.5/apis-tools/zeebe-api-rest/zeebe-api-rest-overview.md
Adds details on where to find the Zeebe, Tasklist, and Operate REST API endpoints.
Backported until version 8.2 where applicable.
closes #3698
=> Add context path info to component REST APIs

docs/self-managed/setup/upgrade.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.5/self-managed/setup/upgrade.md
For smooth operations and upgrades, we need to ensure that the Helm CLI version we used in the tests and release is visible to the end user.
=> docs(self-managed): add section about helm cli in the upgrade page

docs/self-managed/zeebe-deployment/operations/management-api.md, versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/management-api.md, versioned_docs/version-8.3/self-managed/zeebe-deployment/operations/management-api.md, versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/management-api.md, versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/management-api.md
This PR adds documentation for the soft pause exporter: https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/operations/management-api/#exporting-api
This also affects versions 8.3, 8.4, and 8.5.
closes https://github.com/camunda/zeebe/issues/17424
=> Document soft pause exporter.

hacks/isolateVersion/6-updateCIWorkflows.sh, hacks/isolateVersion/8-configureOptimizeDocs.sh, hacks/isolateVersion/allSteps.sh
Updates the scripts for archiving versions, to fix a couple things that were being dropped during the archival.
Also updates the versions in the archival script, which is unnecessary, but is also a good hint for the next time we archive.
=> fix: update archival scripts

docs/self-managed/setup/install.md
This is a change to help our customers avoid confusion with CI/CD configuration.
=> Adding section to avoid issue with Ci/CD

src/theme/DocItem/Metadata/determineCanonical.js, src/theme/DocItem/Metadata/determineCanonical.spec.js, src/theme/DocItem/Metadata/index.js
Part of #3731.
Ports https://github.com/camunda/camunda-docs/pull/3760/commits/d00a54d1bb2fbdc42bcbd743232129faeee7ec7f, which was required during the 8.1 archival, to the main docs. This allows us to specify canonical URLs which include `https://docs.camunda.io`, which is necessary when archiving a version to `https://unsupported.docs.camunda.io`.
=> feat: support fully-qualified absolute canonical URLs

docs/apis-tools/tasklist-api/tasklist-api-authentication.md, docs/self-managed/tasklist-deployment/tasklist-configuration.md, versioned_docs/version-8.5/apis-tools/tasklist-api/tasklist-api-authentication.md, versioned_docs/version-8.5/self-managed/tasklist-deployment/tasklist-configuration.md
We add the CSRF Token protections for the version: 8.5.1 and 8.6.0-alpha1. On the docs I am bringing a short explanation how to enabled/disabled this for self-managed. Also considering the cookies authentication on API, API developers should disable CSRF Protection in order to use the operations on API without blockers on POST operations.
=> feature: add csrf token to the tasklist docs

docs/components/connectors/out-of-the-box-connectors/kafka.md, versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/kafka.md, versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/kafka.md, versioned_docs/version-8.4/components/connectors/out-of-the-box-connectors/kafka.md, versioned_docs/version-8.5/components/connectors/out-of-the-box-connectors/kafka.md
-Added kafka avro documentation to kafka consumer connector
May release
=> docs(ootbc): add avro to kafka consumer docs

docs/self-managed/setup/deploy/openshift/redhat-openshift.md, optimize_sidebars.js, optimize_versioned_sidebars/version-3.13.0-sidebars.json, sidebars.js, versioned_docs/version-8.5/self-managed/setup/deploy/openshift/redhat-openshift.md, versioned_sidebars/version-8.5-sidebars.json
Keep the names in the sidebar consistent and add the OpenShift version (already supported for 8.5).
ASAP.
=> docs(self-managed): tidy up sidebar names and add openshift version

docs/self-managed/tasklist-deployment/data-retention.md, versioned_docs/version-8.4/self-managed/tasklist-deployment/data-retention.md, versioned_docs/version-8.5/self-managed/tasklist-deployment/data-retention.md
With the same setup for ILM, we are now supporting ISM for Open Search
=> feat: activate support for ISM

docs/self-managed/zeebe-deployment/configuration/gateway.md
Added documentation for using new long polling config options implemented here
https://github.com/camunda/zeebe/pull/18432
=> docs: added long polling config info

.github/pull_request_template.md, howtos/documentation-guidelines.md
We have more than one tech writer now! Yay! We should reflect this in the PR template so our writers can distribute work.
=> Add tech-writers team to PR template

docs/components/modeler/desktop-modeler/element-templates/c7-defining-templates.md, docs/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.4/components/modeler/desktop-modeler/element-templates/c7-defining-templates.md, versioned_docs/version-8.4/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.5/components/modeler/desktop-modeler/element-templates/c7-defining-templates.md, versioned_docs/version-8.5/components/modeler/desktop-modeler/element-templates/defining-templates.md
This PR documents the `placeholder` attribute added to the element templates via https://github.com/bpmn-io/bpmn-js-element-templates/issues/92
The changes will be available in the upcoming Desktop Modeler 5.24 release, and also in Web Modeler SaaS as soon as released.
Closes https://github.com/camunda/camunda-modeler/issues/4331
=> feat: document `placeholder` attribute on templates properties

docs/components/modeler/web-modeler/process-applications.md
Process applications will also be available in Web Modeler Self-Managed with the 8.6.0-alpha2 release.
=> docs(web-modeler): remove "saas only" limitation for process applications

docs/components/connectors/out-of-the-box-connectors/amazon-eventbridge.md, docs/components/connectors/out-of-the-box-connectors/amazon-sns.md, docs/components/connectors/out-of-the-box-connectors/amazon-sqs.md, docs/components/connectors/out-of-the-box-connectors/github.md, docs/components/connectors/out-of-the-box-connectors/kafka.md, docs/components/connectors/out-of-the-box-connectors/rabbitmq-outbound.md, docs/components/connectors/out-of-the-box-connectors/slack.md, docs/components/connectors/out-of-the-box-connectors/twilio.md, docs/components/connectors/protocol/http-webhook.md
This PR will update the docs for many inbound connectors by adding:
- New correlation features (message ID expression, message TTL)
- New activation condition features for selected connectors (SQS, Kafka, RabbitMQ)
I also updated a couple of lines where I noticed outdated references to element template sections that were renamed.
=> feat(connectors): new inbound correlation and activation features

docs/components/console/manage-organization/external-sso.md, versioned_docs/version-8.5/components/console/manage-organization/external-sso.md
https://camunda.slack.com/archives/C076Z98GED8/p1717743102904059?thread_ts=1717737012.745669&cid=C076Z98GED8
this adds a poorly written note about social login no longer working when externalSSO is configured in C8-SaaS.
we have had a couple of occurances of people failing on that, and since we cannot really add a note about that in the login-screen itself the support folks have been asking for a public doc coverage about that so they can add that to the onboarding procedure
=> externalSSO: new section about social login no longer working

docs/reference/supported-environments.md, docs/self-managed/setup/deploy/openshift/redhat-openshift.md, versioned_docs/version-8.5/reference/supported-environments.md, versioned_docs/version-8.5/self-managed/setup/deploy/openshift/redhat-openshift.md
This PR adds documentation for configuring Ingress for Camunda 8 deployment on OpenShift. It provides instructions for both using Kubernetes Ingress and OpenShift Routes, along with prerequisites and considerations for each method. This documentation aims to guide users in exposing Camunda 8 services externally and ensuring proper setup for ingress components.
This work is related to https://github.com/camunda/team-infrastructure-experience/issues/239
=> doc(openshift): rework structure

static/.htaccess
The [Desktop Modeler landing page](https://docs.camunda.io/docs/components/modeler/desktop-modeler) works well on `next` but is redirected to the now nearly obsolete ("just for SEO purposes") [install page](https://docs.camunda.io/docs/components/modeler/desktop-modeler/install-the-modeler/) on `latest`. This hopefully fixes the issue.
=> fix: allow accessing Desktop Modeler landing page

docs/components/modeler/web-modeler/play-your-process.md, versioned_docs/version-8.2/components/modeler/web-modeler/play-your-process.md, versioned_docs/version-8.3/components/modeler/web-modeler/play-your-process.md, versioned_docs/version-8.4/components/modeler/web-modeler/play-your-process.md, versioned_docs/version-8.5/components/modeler/web-modeler/play-your-process.md
Closes https://github.com/camunda/developer-experience/issues/315.
=> Adjust Play page for keywords

docs/reference/release-notes/860.md
Related to https://github.com/camunda/product-hub/issues/2348.
=> Add API Orch guide on Help Center Announcement to Release notes

docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eks-helm.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
The change adds a warning about DNS ownership and external-dns to make people aware of adjusting things if running external-dns multiple times in different clusters. Otherwise will result in negative side effects of two external-dns with same ownership fighting over DNS records and deleting those.
=> docs(aws): add disclaimer about ownership for external-dns

docs/self-managed/modeler/web-modeler/configuration/ssl.md, versioned_docs/version-8.5/self-managed/modeler/web-modeler/configuration/ssl.md
Corrects the environment variables for configuring a SSL certificate for Web Modeler's `webapp` component, see [Slack discussion](https://camunda.slack.com/archives/C0693F1NFK5/p1718870324947619?thread_ts=1717514003.442609&cid=C0693F1NFK5).
=> fix(web-modeler): correct environment variables for webapp certificate

.github/workflows/preview-env-deploy.yml, .github/workflows/preview-env-teardown.yml, docusaurus.config.js
This pr adds two workflows which aim to assist in deploying the `camunda-docs` preview environments as well as tearing the environments down:
[preview-env-deploy.yml](https://github.com/camunda/camunda-docs/pull/3960/files#diff-3ba2b32605d5a9a991f461a7ac4e2f013808e2caddea0b241022c98702e4a526):
- `Deployment Trigger:` Activates on labeled pull requests.
- `Build:` Installs dependencies, builds the project
- `Deployment`: Syncs the content of the path in the bucket to the local folder `build`. I did a test and using the gsutil command with the  `rsync -d -r` option does the following:
a. Files which don’t exist in the bucket but exist locally in the build folder will get uploaded
b. Files which exist in the bucket but not in the local folder will get deleted from the bucket
c. File which …
=> chore(preview-envs): Add preview env workflows to camunda docs repo

versioned_docs/version-8.2/self-managed/backup-restore/backup-and-restore.md, versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/management-api.md, versioned_docs/version-8.3/self-managed/operational-guides/backup-restore/backup-and-restore.md, versioned_docs/version-8.3/self-managed/zeebe-deployment/operations/management-api.md, versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/backup-and-restore.md, versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/management-api.md, versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/backup-and-restore.md, versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/management-api.md
This PR makes changes in the pages `backup-and-restore.md` and `management-api.md` in the versions 8.5, 8.4, 8.3, and 8.2 to specify in which patch versions the soft pause feature is available.
The respective patch versions that this feature is available are: 8.2.27, 8.3.11, 8.4.7 and 8.5.1.
closes: https://github.com/camunda/camunda/issues/19410
=> Doc: Specify the patch version for soft pause feature.

docs/components/best-practices/operations/versioning-process-definitions.md, versioned_docs/version-8.4/components/best-practices/operations/versioning-process-definitions.md, versioned_docs/version-8.5/components/best-practices/operations/versioning-process-definitions.md
=> Remove statements that C8 does not support instance migration

docs/self-managed/setup/upgrade.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.5/self-managed/setup/upgrade.md
Task: https://github.com/camunda/camunda-platform-helm/issues/2067
=> docs(self-managed): mention the change of using image.tag

docs/self-managed/console-deployment/configuration.md, docs/self-managed/identity/deployment/configuration-variables.md, docs/self-managed/operate-deployment/operate-configuration.md, docs/self-managed/tasklist-deployment/tasklist-configuration.md, docs/self-managed/zeebe-deployment/configuration/configuration.md, docs/self-managed/zeebe-deployment/configuration/environment-variables.md, versioned_docs/version-1.3/self-managed/zeebe-deployment/configuration/configuration.md, versioned_docs/version-1.3/self-managed/zeebe-deployment/configuration/environment-variables.md, versioned_docs/version-8.2/self-managed/identity/deployment/configuration-variables.md, versioned_docs/version-8.2/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.2/self-managed/tasklist-deployment/tasklist-configuration.md, versioned_docs/version-8.2/self-managed/zeebe-deployment/configuration/configuration.md, versioned_docs/version-8.2/self-managed/zeebe-deployment/configuration/environment-variables.md, versioned_docs/version-8.3/self-managed/identity/deployment/configuration-variables.md, versioned_docs/version-8.3/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.3/self-managed/tasklist-deployment/tasklist-configuration.md, versioned_docs/version-8.3/self-managed/zeebe-deployment/configuration/configuration.md, versioned_docs/version-8.3/self-managed/zeebe-deployment/configuration/environment-variables.md, versioned_docs/version-8.4/self-managed/console-deployment/configuration.md, versioned_docs/version-8.4/self-managed/identity/deployment/configuration-variables.md, versioned_docs/version-8.4/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.4/self-managed/tasklist-deployment/tasklist-configuration.md, versioned_docs/version-8.4/self-managed/zeebe-deployment/configuration/configuration.md, versioned_docs/version-8.4/self-managed/zeebe-deployment/configuration/environment-variables.md, versioned_docs/version-8.5/self-managed/console-deployment/configuration.md, versioned_docs/version-8.5/self-managed/identity/deployment/configuration-variables.md, versioned_docs/version-8.5/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.5/self-managed/tasklist-deployment/tasklist-configuration.md, versioned_docs/version-8.5/self-managed/zeebe-deployment/configuration/configuration.md, versioned_docs/version-8.5/self-managed/zeebe-deployment/configuration/environment-variables.md
Resolves #3501 
- Added an explicit callout and links to the Spring docs on external configs to spring components
- Updated existing spring doc links
- Where we specifically call out using a config file, added examples of converting the property name to an env variable (did not add this to pages where we only discuss env variables to begin with)
=> clarify spring boot conventions for config, update spring links

docs/components/connectors/out-of-the-box-connectors/slack.md
This is an update for the documentation, as we have added a new feature to the `post_message` function.
We can now add a specific thread, which correspond to the id of the message one wants to start a thread from
=> add documentation for new post message in slack feature (thread id)

docs/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.2/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.3/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.4/components/connectors/custom-built-connectors/connector-sdk.md, versioned_docs/version-8.5/components/connectors/custom-built-connectors/connector-sdk.md
Adds a missing space between the link and the following word "or", see defect docs:
=> docs: add missing space between the link and the following word "or"

docs/self-managed/connectors-deployment/connectors-configuration.md
=> docs(connectors): add docs for secure TLS connexion

docs/guides/getting-started-java-spring.md, docs/guides/react-components/install-plain-java.md, versioned_docs/version-8.5/guides/getting-started-java-spring.md
I recently recorded a walkthrough of the Spring Zeebe guide, and while doing so, noticed a few things that could be specified more precisely.
=> docs: update spring Zeebe guide 

docs/self-managed/zeebe-deployment/operations/update-zeebe.md, versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/update-zeebe.md
Closes https://github.com/camunda/developer-experience/issues/345.
Clarifying unique instances of rollback.
=> clarify possible instances of zeebe rollback

docs/guides/getting-started-orchestrate-human-tasks.md, versioned_docs/version-8.2/guides/getting-started-orchestrate-human-tasks.md, versioned_docs/version-8.3/guides/getting-started-orchestrate-human-tasks.md, versioned_docs/version-8.4/guides/getting-started-orchestrate-human-tasks.md, versioned_docs/version-8.5/guides/getting-started-orchestrate-human-tasks.md
Arcade experiences are becoming stale, the quick win is to remove them.
=> Remove Arcade from HTO guide

docs/self-managed/concepts/exporters.md
Tells the user how to aadd metrics to their exporter and notes a potential pitfall about interacting with a to be discarded registry.
=> Exporter metrics with Micrometer

docs/reference/announcements.md
docs: added ES,OS versions to announcement
Hi team, sorry for urgency, we missed this announcement and would like to release it rather earlier. If possible, this week or early next week would do the trick. Thank you!
=> docs: added ES,OS versions to announcement

docs/components/best-practices/development/testing-process-definitions-c7.md, docs/components/connectors/out-of-the-box-connectors/sql.md, docs/reference/help-center.md, docs/self-managed/console-deployment/overview.md, docs/self-managed/setup/deploy/other/docker.md
Cleaning up a few tiny descriptions with the August Bing review.
=> august bing tweaks

src/css/custom.css
When the Self-Managed icon was removed from the top nav (I couldn't find the PR for it 😞), the CSS remained, creating a visually odd experience. An area of the Self-Managed docs also randomly picked up the styles. 
Thanks for the nudge @Sijoma! 
Changes to **docs infra**, including updates to workflows and adding new npm packages, must be first discussed via issue or #ask-c8-documentation and linked for context.
=> Remove SM top-nav CSS

docs/self-managed/setup/guides/ingress-setup.md, versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md, versioned_docs/version-8.5/self-managed/setup/guides/ingress-setup.md
Relates to https://github.com/camunda/developer-experience/issues/199
A quick win for cleaning up some of this content is to add tabs to the combined/separated Ingress instructions. Holding off on any additional content rework and the potential for creating new pages (instead of tabs) is separated out into https://github.com/camunda/developer-experience/issues/367.
=> Reorganize Ingress content

docs/guides/getting-started-java-spring.md, versioned_docs/version-8.5/guides/getting-started-java-spring.md
Related to https://camunda.slack.com/archives/C07CQC289JP/p1722509762138649 -- adding note of intention behind Java/Spring to guide content.
=> add note of intention to spring java guide

docs/reference/announcements.md
* Change for consistency and readability
=> chore(announcements): simplify changes in supported envs

optimize/self-managed/optimize-deployment/plugins/plugin-system.md, optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/plugins/plugin-system.md, optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/plugins/plugin-system.md, optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/plugins/plugin-system.md, optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/plugins/plugin-system.md
Plugins never worked or were supported in Optimize 8. We are now [removing the code from the mono repo](https://github.com/camunda/camunda/pull/21159), and realised that this should probably have already been labelled on the overview page
=> refactor: remove optimize 7 plugins from mono repo

docs/reference/glossary.md
Closes https://github.com/camunda/developer-experience/issues/323 -- adds hybrid mode to glossary.
=> add hybrid mode to glossary

docs/components/connectors/use-connectors/index.md, versioned_docs/version-8.2/components/connectors/use-connectors/index.md, versioned_docs/version-8.3/components/connectors/use-connectors/index.md, versioned_docs/version-8.4/components/connectors/use-connectors/index.md, versioned_docs/version-8.5/components/connectors/use-connectors/index.md
Making this more function more clear for users who are familiar with BPMN concepts, but who are now learning Connectors.
=> docs(connectors): clarify jobError's relationship to incidents

.github/workflows/sync-rest-api-docs.yaml
Looking at the generated [PR](https://github.com/camunda/camunda-docs/pull/4217) there is a problem with adding @camunda/tech-writers as reviewers, this PR fix this.
=> fix: use proper properties for assign team reviews

versioned_docs/version-8.4/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md
Corrects links going to current version, not staying within 8.4
This is a bug, but it's not something that's urgent enough for a review, merge, and release on a Friday afternoon.
=> remove link to current version

docs/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/terraform-setup.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
fix(self-managed): Fix AWS provider constraint
Update to current version, relax constraint to work with any 5.x versions in the future
Context: https://camunda.slack.com/archives/C05S0M7KG6A/p1725028961672329
How to check:
- Create `config.tf` from https://docs.camunda.io/docs/self-managed/setup/deploy/amazon/amazon-eks/eks-terraform/#terraform-prerequsites (of this PR)
- Create `main.tf` from https://docs.camunda.io/docs/self-managed/setup/deploy/amazon/amazon-eks/eks-terraform/#cluster-module
- Run `terraform init`
=> fix(self-managed): Fix AWS provider constraint

src/pages/index.js, src/pages/styles.module.css
CSS fix to remove hyperlink padding on docs landing page card components.
Previously, there was padding around card hyperlinks when hovering:
- This is now fixed so the entire card area is hyperlinked.
- Tested in Google Chrome and Firefox
=> Docs landing page card hyperlinks

docs/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.5/self-managed/operate-deployment/operate-configuration.md
Added `awsEnabled` to the Operate OpenSearch configuration description and fixed "Elasticsearch" being written in some places in the OpenSearch documentation.
Related PRs:
https://github.com/camunda/camunda/pull/21481
https://github.com/camunda/camunda/pull/21488
=> Update Operate OpenSearch configuration to include awsEnabled

docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md, docs/components/modeler/feel/builtin-functions/feel-built-in-functions-string.md, docs/components/modeler/feel/language-guide/feel-temporal-expressions.md, docs/components/modeler/feel/language-guide/feel-unary-tests.md, versioned_docs/version-8.2/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md, versioned_docs/version-8.2/components/modeler/feel/builtin-functions/feel-built-in-functions-string.md, versioned_docs/version-8.2/components/modeler/feel/language-guide/feel-temporal-expressions.md, versioned_docs/version-8.2/components/modeler/feel/language-guide/feel-unary-tests.md, versioned_docs/version-8.3/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md, versioned_docs/version-8.3/components/modeler/feel/builtin-functions/feel-built-in-functions-string.md, versioned_docs/version-8.3/components/modeler/feel/language-guide/feel-temporal-expressions.md, versioned_docs/version-8.3/components/modeler/feel/language-guide/feel-unary-tests.md, versioned_docs/version-8.4/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md, versioned_docs/version-8.4/components/modeler/feel/builtin-functions/feel-built-in-functions-string.md, versioned_docs/version-8.4/components/modeler/feel/language-guide/feel-temporal-expressions.md, versioned_docs/version-8.4/components/modeler/feel/language-guide/feel-unary-tests.md, versioned_docs/version-8.5/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md, versioned_docs/version-8.5/components/modeler/feel/builtin-functions/feel-built-in-functions-string.md, versioned_docs/version-8.5/components/modeler/feel/language-guide/feel-temporal-expressions.md, versioned_docs/version-8.5/components/modeler/feel/language-guide/feel-unary-tests.md
Extend the FEEL documentation to clarify edge cases, related to the following issues:
- https://github.com/camunda/feel-scala/pull/887
- https://github.com/camunda/feel-scala/issues/801
- https://github.com/camunda/feel-scala/issues/731
- https://github.com/camunda/feel-scala/issues/867  
The changes are relevant for all versions 8.2+.
=> feat(feel): Clarify edge cases in FEEL expressions

docs/components/modeler/bpmn/message-events/message-events.md
Here is a suggested edit for the note on start messages and correlationKey values.
=> TW edits: Note and formatting

docs/reference/announcements.md, docs/self-managed/operational-guides/update-guide/850-to-860.md
The ideal setup for Elasticseaech is 3 nodes, so we set it to 3 by default in the Helm chart for Camunda Self-Managed 8.6.
=> docs(self-managed): Helm chart Elasticsearch nodes number changed

docs/self-managed/zeebe-deployment/operations/cluster-scaling.md, docs/self-managed/zeebe-deployment/operations/management-api.md
Related to https://github.com/camunda/camunda/issues/16126 
This PR documents 
1. The new features added to cluster scaling API for supporting the dual-region deployment
2. The new API for enabling and disabling the exporter
How to use these APIs are already documented in https://github.com/camunda/camunda-docs/pull/4205 
With the next 8.6 alpha or 8.6 minor which ever is the earliest.
=> Document Zeebe APIs for dual-region operations

docs/apis-tools/go-client/go-get-started.md, docs/apis-tools/go-client/index.md, docs/apis-tools/go-client/job-worker.md, docs/reference/announcements.md, sidebars.js
This is the announcement of the go client deprecation with 8.6.
See https://github.com/camunda/camunda/issues/21817.
PDP epic https://github.com/camunda/product-hub/issues/2438
Also relates to https://github.com/camunda/camunda-docs/pull/4228 (announces it)
=> Announce Go client & zbctl deprecation

docs/components/modeler/web-modeler/play-your-process.md
With this recent change in the[ camunda-platform](https://github.com/camunda/camunda-platform) repository, the keycloak port in docker-compose files were updated: https://github.com/camunda/camunda-platform/pull/806 
This affected Play Self Managed example values. Which is what this PR aims to fix.
⚠️  I can see that keycloak:8080 is mentioned in a couple more places in our docs, which might also need to be updated, but I don't have enough time to check all of these, nor the confidence to confirm they need to be updated. It might worth to double-check with the respective teams.
=> fix: fix keycloak url in play docs

docs/self-managed/zeebe-deployment/operations/metrics.md
Resolves [#179](https://github.com/camunda/developer-experience/issues/179)
The "Configure the HTTP server" line is unhelpful/not descriptive. Update this to include mention of the actual env var required to configure metrics.
=> add metrics env var requirement

docs/reference/announcements.md
As part of https://github.com/camunda/camunda-platform-helm/issues/2286, we want to announce the deprecation of the failover / failback options in the helm chart for multi-region enabled deployments. These helm variables were difficult to work around and instead, there are application-specific changes to zeebe to make this process easier. That process involves using API endpoints on the actuator to trigger certain events in zeebe, and is already documented here:
https://docs.camunda.io/docs/next/self-managed/operational-guides/multi-region/dual-region-operational-procedure/?lost-region=region-0-lost&failback=step1&failover=step1#introduction
This PR is a notice that for 8.6,  the options will remain in the helm chart, but for 8.7, they will be dropped. Users must migrate to using the new …
=> fix(self-managed): deprecation notice for helm multiregion options

docs/apis-tools/camunda-api-rest/camunda-api-rest-overview.md
Documents experimental C8 REST Query API as alpha feature, not experimental. Alpha features are clearly defined in the reference documentation and contracts in contrast to experimental features.
related to https://github.com/camunda/camunda/issues/22224
=> docs: move from experimental Query API to alpha

docs/components/modeler/desktop-modeler/flags/flags.md, docs/components/modeler/desktop-modeler/troubleshooting.md, versioned_docs/version-1.3/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.2/components/modeler/desktop-modeler/troubleshooting.md, versioned_docs/version-8.3/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.3/components/modeler/desktop-modeler/troubleshooting.md, versioned_docs/version-8.4/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.4/components/modeler/desktop-modeler/troubleshooting.md, versioned_docs/version-8.5/components/modeler/desktop-modeler/flags/flags.md, versioned_docs/version-8.5/components/modeler/desktop-modeler/troubleshooting.md
Adds Windows-specific commands based on Feedack received via Slack: https://camunda.slack.com/archives/C0693F1NFK5/p1726472771042949
=> Add Windows-specific commands to Flags & Troubleshooting pages

docs/apis-tools/testing/assertions.md, docs/apis-tools/testing/connectors.md, docs/apis-tools/testing/getting-started.md, docs/apis-tools/testing/utilities.md, sidebars.js
Adds a new reference documentation for the new Camunda Process Test Java library. It describes how to install and use the library to write process tests. Take inspiration from the [Zeebe Process Test](https://docs.camunda.io/docs/apis-tools/java-client/zeebe-process-test/) documentation.
The new documentation is added to the sidebar under: `API & Tools > Testing > Camunda Process Test`.
closes #3921
=> feat: [CPT] I can read how to write process tests

docs/self-managed/zeebe-deployment/operations/metrics.md, versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/metrics.md, versioned_docs/version-8.3/self-managed/zeebe-deployment/operations/metrics.md, versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/metrics.md, versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/metrics.md
Backport the changes from #4262.
=> backport metrics updates

docs/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md, docs/self-managed/setup/deploy/amazon/amazon-eks/irsa.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/irsa.md
Retro review of https://github.com/camunda/camunda-docs/pull/4302.
=> retro review of 4302

optimize/apis-tools/optimize-api/optimize-api-authentication.md, optimize_versioned_docs/version-3.13.0/apis-tools/optimize-api/optimize-api-authentication.md
Part of #4117.
Rewrites the Optimize API authentication guide according to specs defined in #4117.
=> feat: rewrite Optimize API auth guide

docs/apis-tools/zeebe-api-rest/zeebe-api-rest-authentication.md, versioned_docs/version-8.5/apis-tools/zeebe-api-rest/zeebe-api-rest-authentication.md
Part of #4117, and resolves #4092.
Rewrites the (deprecated) Zeebe REST API authentication guide according to specs defined in #4117.
=> feat: rewrite Zeebe API auth guide

docs/apis-tools/working-with-apis-tools.md, docs/apis-tools/zeebe-api/gateway-service.md, docs/components/best-practices/development/dealing-with-problems-and-exceptions.md, docs/components/best-practices/development/understanding-transaction-handling-c7.md, docs/components/concepts/job-workers.md, docs/components/concepts/process-instance-migration.md, docs/components/concepts/resource-deletion.md, docs/components/modeler/bpmn/error-events/error-events.md, docs/components/modeler/bpmn/exclusive-gateways/exclusive-gateways.md, docs/components/modeler/bpmn/inclusive-gateways/inclusive-gateways.md, optimize/components/userguide/additional-features/ml-dataset.md, versioned_docs/version-8.5/apis-tools/working-with-apis-tools.md, versioned_docs/version-8.5/apis-tools/zeebe-api/gateway-service.md, versioned_docs/version-8.5/components/best-practices/development/dealing-with-problems-and-exceptions.md, versioned_docs/version-8.5/components/concepts/job-workers.md, versioned_docs/version-8.5/components/concepts/process-instance-migration.md, versioned_docs/version-8.5/components/concepts/resource-deletion.md, versioned_docs/version-8.5/components/modeler/bpmn/error-events/error-events.md, versioned_docs/version-8.5/components/modeler/bpmn/exclusive-gateways/exclusive-gateways.md, versioned_docs/version-8.5/components/modeler/bpmn/inclusive-gateways/inclusive-gateways.md
Closes https://github.com/camunda/developer-experience/issues/385 -- links to incidents on first reference.
🥳 I think(?) this is our first resolved PushFeedback-related issue??
=> link to incidents on first reference

docs/reference/announcements.md
closes https://github.com/camunda/camunda/issues/20747
=> docs: update Announcement doc with new Operate and Tasklist webapp urls

docs/apis-tools/administration-api/authentication.md, docs/apis-tools/administration-sm-api/administration-sm-api-authentication.md, docs/apis-tools/camunda-api-rest/camunda-api-rest-authentication.md, docs/apis-tools/operate-api/authentication.md, docs/apis-tools/tasklist-api-rest/tasklist-api-rest-authentication.md, docs/apis-tools/web-modeler-api/authentication.md, docs/apis-tools/zeebe-api-rest/zeebe-api-rest-authentication.md, optimize/apis-tools/optimize-api/optimize-api-authentication.md, optimize_versioned_docs/version-3.13.0/apis-tools/optimize-api/optimize-api-authentication.md, versioned_docs/version-8.5/apis-tools/administration-api/authentication.md, versioned_docs/version-8.5/apis-tools/operate-api/authentication.md, versioned_docs/version-8.5/apis-tools/tasklist-api-rest/tasklist-api-rest-authentication.md, versioned_docs/version-8.5/apis-tools/web-modeler-api/authentication.md, versioned_docs/version-8.5/apis-tools/zeebe-api-rest/zeebe-api-rest-authentication.md
Part of #4117.
Implements feedback provided in https://github.com/camunda/camunda-docs/pull/4315.
=> docs: address auth rewrite feedback

optimize_versioned_sidebars/version-3.13.0-sidebars.json, versioned_sidebars/version-8.5-sidebars.json
Synchronizes sidebars for v8.5/3.13.0.
* There is only one meaningful change in the main instance's version-8.5-sidebars.json file, and a bunch of whitespace changes.
* There are a handful of meaningful changes in the Optimize instance's version-3.13.0-sidebars.json file.
=> chore(sidebars): sync sidebars in v8.5/3.13.0

docs/reference/dependencies.md
* Legal change
* Related to camunda/engineering-leadership-team#68
* Planning this change for the October release
=> feat(dependencies): link to written offer

optimize/self-managed/optimize-deployment/migration-update/camunda-7/3.13-to-3.14.md, optimize/self-managed/optimize-deployment/migration-update/camunda-8/3.13_8.5-to-8.6.md, optimize/self-managed/optimize-deployment/migration-update/translation-diffs/differences_localization_313_314.diff
=> chore: add optimize translation diff

docs/self-managed/setup/deploy/amazon/amazon-eks/dual-region.md, docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md, docs/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md, docs/self-managed/setup/deploy/amazon/amazon-eks/irsa.md, docs/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eks-helm.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eksctl.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/irsa.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/terraform-setup.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/dual-region.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/irsa.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
related to https://github.com/camunda/team-infrastructure-experience/issues/343
The PR bumps versions referenced in InfraEx related docs for 8.4/8.5/next.
The helm charts are already referencing the latest releases, which should be available in the next day.
=> docs(infraex): bump versions and fix links

docs/apis-tools/java-client/job-worker.md, versioned_docs/version-8.6/apis-tools/java-client/job-worker.md
Backporting https://github.com/camunda/camunda-docs/pull/4376. Note that this is sufficient to merge for the `8.6` release, but there are lingering comments in the original PR to refine this content.
CC @koevskinikola
=> document rest api long polling limitation

docs/guides/getting-started-java-spring.md, docs/guides/react-components/install-c8run.md, docs/self-managed/setup/deploy/local/c8run.md, docs/self-managed/setup/deploy/local/local-kubernetes-cluster.md, versioned_docs/version-8.5/self-managed/setup/deploy/local/local-kubernetes-cluster.md, versioned_docs/version-8.6/guides/getting-started-java-spring.md, versioned_docs/version-8.6/guides/react-components/install-c8run.md, versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md
[#c8run-sdk-auth-issue](https://camunda.slack.com/archives/C07RB6W8URX)
=> Auth issue c8run

docs/guides/getting-started-java-spring.md, docs/guides/react-components/install-c8run.md, docs/self-managed/setup/deploy/local/c8run.md, docs/self-managed/setup/deploy/local/local-kubernetes-cluster.md, versioned_docs/version-8.5/self-managed/setup/deploy/local/local-kubernetes-cluster.md, versioned_docs/version-8.6/guides/getting-started-java-spring.md, versioned_docs/version-8.6/guides/react-components/install-c8run.md, versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md
This PR provides further temporary fixes to help resolve the Camunda 8 Run/REST API authentication issue.
- Changed the warning to a caution, and reworded to remove limitation language and other components.
- Additionally, fixed link format and typo
This does not address further changes required for this authentication issue, as detailed in the relevant Slack channel, namely:
> To access the REST API (v1 or v2) you need to make use of the Cookie auth setup by the webapps and we need to document that too.
Once that documentation is complete, we should revisit these pages and change the caution link to point to the new auth documentation.
=> Camunda 8 Run authentication warning

docs/guides/getting-started-java-spring.md, versioned_docs/version-8.5/guides/getting-started-java-spring.md, versioned_docs/version-8.6/guides/getting-started-java-spring.md
Adding xml and yaml to codeblocks for better styling
=> Add language to codeblock in Java Spring GSG

docs/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md, docs/guides/getting-started-java-spring.md, docs/guides/getting-started-orchestrate-apis.md, docs/guides/getting-started-orchestrate-human-tasks.md, docs/guides/getting-started-orchestrate-microservices.md, docs/guides/model-your-first-process.md, src/css/custom.css, versioned_docs/version-8.6/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md, versioned_docs/version-8.6/guides/getting-started-java-spring.md, versioned_docs/version-8.6/guides/getting-started-orchestrate-apis.md, versioned_docs/version-8.6/guides/getting-started-orchestrate-human-tasks.md, versioned_docs/version-8.6/guides/getting-started-orchestrate-microservices.md, versioned_docs/version-8.6/guides/model-your-first-process.md
This PR fixes the outstanding CSS issues from https://github.com/camunda/camunda-docs/pull/4324
- Border on API schema tabs.
- Extraneous break tags added into Getting Started guides.
(And also any other enhancements/fixes that may arise following feedback on the recent CSS changes).
=> CSS styling enhancements

versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md
Adding missing env variables for Spring SDK documentation
- for REST configuration
- for gRPC configuration
Closes: #4297
=> Adding missing env variables for Spring SDK documentation

docs/self-managed/setup/guides/connect-to-an-oidc-provider.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md, versioned_docs/version-8.5/self-managed/setup/guides/connect-to-an-oidc-provider.md, versioned_docs/version-8.6/self-managed/setup/guides/connect-to-an-oidc-provider.md
=> consistent usage of tenant id placeholder

docs/apis-tools/java-client/job-worker.md, versioned_docs/version-8.6/apis-tools/java-client/job-worker.md
Add examples under what use-cases job long-polling isn't possible with the Java client via the Zeebe
REST API.
closes #4375
=> refactor: expand java client limitation documentation

docs/reference/release-notes/860.md, versioned_docs/version-8.6/reference/release-notes/860.md
Update release note to make it accurate and clear. New correlation endpoint is on the REST API, and does not accept a `ttl` property.
=> Add message correlation API ref link to release notes

docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md, docs/self-managed/operational-guides/update-guide/860-to-870.md, sidebars.js
=> feat(broker): update docs in backups/GCS regarding initialization and added update guide from 8.6 to 8.7

docs/apis-tools/spring-zeebe-sdk/getting-started.md, docs/guides/getting-started-java-spring.md, versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md, versioned_docs/version-8.5/guides/getting-started-java-spring.md, versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/getting-started.md, versioned_docs/version-8.6/guides/getting-started-java-spring.md
This closes https://github.com/camunda/camunda-docs/issues/4495 with the following changes:
* removal of the identity repo setup for 8.5+ docs, it's not needed as the Spring Zeebe SDK has no dependency on identity artifacts
* inline of the maven setup for the sdk in the [Getting started with Spring](https://docs.camunda.io/docs/next/guides/getting-started-java-spring/#configure-spring-boot-starter) guide - alternative is to just link to the separate page but I figured this would just interrupt the user reading the guide and I went for inlining the dependency to add
=> Spring Zeebe SDK - Getting Started - Removal of unnecessary identity repo setup

docs/self-managed/identity/deployment/configuration-variables.md, docs/self-managed/setup/guides/connect-to-an-oidc-provider.md, versioned_docs/version-8.6/self-managed/identity/deployment/configuration-variables.md, versioned_docs/version-8.6/self-managed/setup/guides/connect-to-an-oidc-provider.md
Closes #4357 
The `INITIAL_CLAIMS` identity variables were not fully described, leading to user confusion when setting up OIDC providers.
=> Clarify and describe how to use initial claims

docs/components/best-practices/architecture/sizing-your-environment.md, versioned_docs/version-8.6/components/best-practices/architecture/sizing-your-environment.md
This PR updates the performance numbers based on the new results of the benchmarks (see [slack message](https://camunda.slack.com/archives/C07J9URA0B1/p1729846009457529) from @rodrigo-lourenco-lopes ). 
These values are just valid for 8.6+.
* Assigning @rodrigo-lourenco-lopes to double check the numbers.
* Assigning @mesellings as you had been responsible for the docs in the first place as a FYI and to make sure I dont change anything unexpected :D
=> adjust performance numbers based on new benchmark results

docs/components/modeler/web-modeler/play-your-process.md, docs/self-managed/modeler/web-modeler/configuration/configuration.md
Relates to https://github.com/camunda/web-modeler/issues/10571 - no changes needed; the documents on deployment pipelines/stages look compatible with the expected self managed behavior, and may only need screenshot updates when the SaaS and SM visuals are aligned
Implements to https://github.com/camunda/web-modeler/issues/10570 - added the ID field to the SM web modeler config table, and updated references to the Docker distro to include the option in Helm as well.
=> add new web modeler deploy config

docs/self-managed/concepts/multi-region/dual-region.md, versioned_docs/version-8.6/self-managed/concepts/multi-region/dual-region.md
=> Fix admonition syntax

optimize/apis-tools/optimize-api/event-ingestion.md, optimize/apis-tools/optimize-api/external-variable-ingestion.md, optimize/apis-tools/optimize-api/report/get-data-export.md, optimize_versioned_docs/version-3.10.0/apis-tools/optimize-api/event-ingestion.md, optimize_versioned_docs/version-3.10.0/apis-tools/optimize-api/report/get-data-export.md, optimize_versioned_docs/version-3.11.0/apis-tools/optimize-api/event-ingestion.md, optimize_versioned_docs/version-3.11.0/apis-tools/optimize-api/report/get-data-export.md, optimize_versioned_docs/version-3.12.0/apis-tools/optimize-api/event-ingestion.md, optimize_versioned_docs/version-3.12.0/apis-tools/optimize-api/external-variable-ingestion.md, optimize_versioned_docs/version-3.12.0/apis-tools/optimize-api/report/get-data-export.md, optimize_versioned_docs/version-3.13.0/apis-tools/optimize-api/event-ingestion.md, optimize_versioned_docs/version-3.13.0/apis-tools/optimize-api/external-variable-ingestion.md, optimize_versioned_docs/version-3.13.0/apis-tools/optimize-api/report/get-data-export.md, optimize_versioned_docs/version-3.14.0/apis-tools/optimize-api/event-ingestion.md, optimize_versioned_docs/version-3.14.0/apis-tools/optimize-api/external-variable-ingestion.md, optimize_versioned_docs/version-3.14.0/apis-tools/optimize-api/report/get-data-export.md
I did a little PoC this afternoon and found ~300 issues that will prevent us from smoothly updating/upgrading to Docusaurus 3. I learned about acorns and how it almost always applied to having unwrapped code just hanging out on docs pages.
=> Add codewrap to request bodies

optimize/self-managed/optimize-deployment/migration-update/camunda-7/2.1-to-2.2.md, optimize/self-managed/optimize-deployment/migration-update/camunda-7/3.3-to-3.4.md, optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/migration-update/2.1-to-2.2.md, optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/migration-update/3.3-to-3.4.md, optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/migration-update/2.1-to-2.2.md, optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/migration-update/3.3-to-3.4.md, optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/migration-update/2.1-to-2.2.md, optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/migration-update/3.3-to-3.4.md, optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/migration-update/2.1-to-2.2.md, optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/migration-update/3.3-to-3.4.md, optimize_versioned_docs/version-3.14.0/self-managed/optimize-deployment/migration-update/camunda-7/2.1-to-2.2.md, optimize_versioned_docs/version-3.14.0/self-managed/optimize-deployment/migration-update/camunda-7/3.3-to-3.4.md
Related to #2719, fixes build issues by getting docs.camunda.org syntax out.
=> Remove {{}} in Optimize update guide links

docs/components/connectors/protocol/http-webhook.md, versioned_docs/version-8.2/components/connectors/protocol/http-webhook.md, versioned_docs/version-8.3/components/connectors/protocol/http-webhook.md, versioned_docs/version-8.4/components/connectors/protocol/http-webhook.md, versioned_docs/version-8.5/components/connectors/protocol/http-webhook.md, versioned_docs/version-8.6/components/connectors/protocol/http-webhook.md
=> Add backticks for JWT-Token in Connectors HTTP Webhook docs

api/camunda/generation-strategy.js
In https://github.com/camunda/camunda/pull/24340, we removed all docs-specific formatting from the upstream spec. We'd already accounted for adding links in #4541, but we also need to add admonitions for alpha warnings.
This PR turns a text-only alpha warning into a `:::note` admonition.
This injection has no effect on the _current_ docs spec, because the admonitions are already there -- this is why there are no files changed other than the generation strategy. However, when https://github.com/camunda/camunda/pull/24340 makes it to this project via the weekly spec sync, our spec will be missing admonitions, and we'll want to regenerate with this new step.
=> feat: replace raw alpha warnings with admonitions when generating C8 REST API docs

docs/components/modeler/dmn/dmn.md, docs/reference/release-notes/860.md, versioned_docs/version-8.5/components/modeler/dmn/dmn.md, versioned_docs/version-8.6/components/modeler/dmn/dmn.md, versioned_docs/version-8.6/reference/release-notes/860.md
Related to https://jira.camunda.com/browse/SUPPORT-24243
This documents the missing support for BKMs in Operate. As there's no documentation on decisions in Operate, I've added it to the Modeler docs on BKM.
=> chore: document missing support for BKM viewing in Operate

docs/guides/configuring-out-of-the-box-connector.md, docs/guides/create-cluster.md, docs/guides/getting-started-orchestrate-apis.md, docs/guides/getting-started-orchestrate-human-tasks.md, docs/guides/getting-started-orchestrate-microservices.md, docs/guides/improve-processes-with-optimize.md, docs/guides/setting-up-development-project.md, sidebars.js, versioned_docs/version-8.6/guides/configuring-out-of-the-box-connector.md, versioned_docs/version-8.6/guides/create-cluster.md, versioned_docs/version-8.6/guides/getting-started-orchestrate-apis.md, versioned_docs/version-8.6/guides/getting-started-orchestrate-human-tasks.md, versioned_docs/version-8.6/guides/getting-started-orchestrate-microservices.md, versioned_docs/version-8.6/guides/improve-processes-with-optimize.md, versioned_docs/version-8.6/guides/setting-up-development-project.md, versioned_sidebars/version-8.6-sidebars.json
Closes https://github.com/camunda/developer-experience/issues/253.
**Will backport upon approval.**
=> adjust guides naming

docs/guides/react-components/_install-c8run.md, versioned_docs/version-8.6/guides/react-components/_install-c8run.md
Fixes the issue we only seem to see in #4598 and #4594 🥲 ?
=> Remove slash link to heading

docs/components/modeler/desktop-modeler/troubleshooting.md, versioned_docs/version-8.5/components/modeler/desktop-modeler/troubleshooting.md, versioned_docs/version-8.6/components/modeler/desktop-modeler/troubleshooting.md
This adds a knowledge base / troubleshooting entry for https://github.com/camunda/camunda-modeler/issues/4695.
Related to https://github.com/camunda/camunda-modeler/issues/4695
=> docs(modeler): add troubleshooting entry for sandboxing issue

docs/components/concepts/clusters.md, versioned_docs/version-8.2/components/concepts/clusters.md, versioned_docs/version-8.3/components/concepts/clusters.md, versioned_docs/version-8.4/components/concepts/clusters.md, versioned_docs/version-8.5/components/concepts/clusters.md, versioned_docs/version-8.6/components/concepts/clusters.md
The first statement says "No data is lost", the second then "disk space is cleared". 
I think we can keep it simple and just keep the latter.
Still needs to be back ported to all versions.
=> Update trial pause docs

docs/apis-tools/zeebe-api/gateway-service.md, versioned_docs/version-8.6/apis-tools/zeebe-api/gateway-service.md
Closes https://github.com/camunda/camunda-docs/issues/3367.
Updates protobuf references based on https://github.com/camunda/camunda/blob/86828ff3fd3caef48b3229c1f717466b35c955eb/gateway-protocol/src/main/proto/gateway.proto
**To backport upon approval**
=> update gateway service protobuf references

docs/components/best-practices/architecture/extending-human-task-management-c7.md, docs/components/best-practices/modeling/naming-technically-relevant-ids.md, docs/components/concepts/messages.md, docs/components/console/manage-organization/external-sso.md, docs/components/modeler/bpmn/call-activities/call-activities.md, docs/components/modeler/bpmn/message-events/message-events.md, docs/components/modeler/bpmn/signal-events/signal-events.md, docs/components/modeler/bpmn/timer-events/timer-events.md, docs/components/modeler/desktop-modeler/telemetry/telemetry.md, docs/components/modeler/dmn/decision-literal-expression.md, docs/components/modeler/dmn/decision-requirements-graph.md, docs/components/modeler/dmn/decision-table-input.md, docs/components/modeler/dmn/decision-table-output.md, docs/components/modeler/dmn/decision-table.md, docs/components/modeler/dmn/dmn.md, docs/components/modeler/feel/language-guide/feel-data-types.md, docs/components/operate/userguide/monitor-operation-status.md, docs/components/zeebe/technical-concepts/process-lifecycles.md, docs/guides/configuring-out-of-the-box-connector.md, docs/guides/getting-started-orchestrate-apis.md, docs/guides/getting-started-orchestrate-microservices.md, docs/guides/model-your-first-process.md
Part of https://github.com/camunda/developer-experience/issues/197.
Update all cases of "id" and "Id" to "ID" where relevant across the following areas:
* Concepts
* Console
* Best Practices
* Early access
* Modeler
* Operate
* Tasklist
* Zeebe
* Guides
=> Update ID references

docs/components/best-practices/modeling/creating-readable-process-models.md, src/css/custom.css
Closes https://github.com/camunda/camunda-docs/issues/4629.
This is a quick fix that applies an inline style to these BPMN icon images to at least make them smaller and remove borders, padding, and so on.
However, some of these icons already have vertical spacing within the SVG, and we shouldn't changes these icons without understanding the impact on wherever else these are used in the docs. As a result, the gateway icon does not 'sit' on the baseline.
=> Add inline-image style for BPMN icon images

docs/self-managed/setup/deploy/local/local-kubernetes-cluster.md, versioned_docs/version-8.6/self-managed/setup/deploy/local/local-kubernetes-cluster.md
Instructions in steps 3 and 4 should be merged since they are both about installing with helm. If separate, a beginner might wonder what is to be done in step 3, whilst the command to run is in step 4.
=> docs: clarify installation steps for local kubernetes cluster

docs/components/modeler/bpmn/call-activities/call-activities.md, versioned_docs/version-8.3/components/modeler/bpmn/call-activities/call-activities.md, versioned_docs/version-8.4/components/modeler/bpmn/call-activities/call-activities.md, versioned_docs/version-8.5/components/modeler/bpmn/call-activities/call-activities.md, versioned_docs/version-8.6/components/modeler/bpmn/call-activities/call-activities.md
Backporting https://github.com/camunda/camunda-docs/pull/4677 by removing duplicate content. The removed content is referenced a few paragraphs below.
=> remove duplicate call activity content

docs/components/modeler/bpmn/embedded-subprocesses/embedded-subprocesses.md, versioned_docs/version-8.4/components/modeler/bpmn/embedded-subprocesses/embedded-subprocesses.md, versioned_docs/version-8.5/components/modeler/bpmn/embedded-subprocesses/embedded-subprocesses.md, versioned_docs/version-8.6/components/modeler/bpmn/embedded-subprocesses/embedded-subprocesses.md
There has been some confusion about the ability to collapse expanded subprocesses, which is not currently possible. This PR attempts to clarify the language around collapsed subprocesses.
=> update language around collapsed subprocesses

docs/components/modeler/web-modeler/deploy-process-application.md, docs/components/modeler/web-modeler/play-your-process.md, docs/components/modeler/web-modeler/run-or-publish-your-process.md, docs/self-managed/modeler/web-modeler/configuration/configuration.md
Related to https://github.com/camunda/web-modeler/issues/10572
=> docs(web-modeler): adapt documentation to accomodate change in authorization for deploy/run/play

docs/self-managed/zeebe-deployment/configuration/priority-election.md, versioned_docs/version-8.3/self-managed/zeebe-deployment/configuration/priority-election.md, versioned_docs/version-8.4/self-managed/zeebe-deployment/configuration/priority-election.md, versioned_docs/version-8.5/self-managed/zeebe-deployment/configuration/priority-election.md, versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/priority-election.md
Fixed property key in the Priority Election section of Zeebe self-hosted docs, along with some minor grammar mistakes.
=> docs(priority-election): fix the property key

docs/components/modeler/feel/builtin-functions/feel-built-in-functions-list.md
Extend the FEEL documentation with the following new built-in function:
* https://github.com/camunda/feel-scala/issues/881
=> feat(feel): Add new built-in function

docs/components/modeler/web-modeler/git-sync.md, versioned_docs/version-8.6/components/modeler/web-modeler/git-sync.md
Introduces the GitLab sync functionality, which was added to the existing Git Sync feature.
Epic: https://github.com/camunda/product-hub/issues/2469
Part of https://github.com/camunda/web-modeler/issues/10911
=> docs(web-modeler): introduce gitlab sync

package-lock.json, package.json
#4673 bumped replace-in-file to a version that is incompatible with our API generators! This PR reverts to a version that works. 
Honestly, I have no idea why #4673 didn't fail when I tested it locally. It obviously won't work -- the release notes make it clear that it has been rewritten as an ES module, which our code can not run. I didn't read those notes when I tested locally, which I should have....but I definitely tested locally, and I guess I must not have run `npm install` when I did. I tried, I really did! 😭
=> fix: repair API doc generation by reverting replace-in-file dependency

docs/reference/announcements/870.md
Minor edits to the 8.7 Announcements page.
See Slack thread: https://camunda.slack.com/archives/C06GF0JPY68/p1734007941840379
=> Update 8.7 Announcements

versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md
Adds `ZEEBE_TOKEN_SCOPE` env var to sdk config, to make transparent how the client scope can be set with 8.5
=> feat(8.5): spring sdk oauth scope config

docs/components/modeler/web-modeler/git-sync.md
Another follow-up for https://github.com/camunda/camunda-docs/pull/4583
The statement for Gitlab `This path is not automatically created if it does not exist.` is not true anymore. A path will be created like it is done for GitHub.
=> docs(web-modeler): correct gitlab path path-creation statement

docs/components/best-practices/development/testing-process-definitions.md, versioned_docs/version-8.6/components/best-practices/development/testing-process-definitions.md
Spring support with Zeebe Process Test is not available from 8.6+ and comes from a community-supported SDK. This is not clear and causing support tickets, so we add a note that this is unavailable.
In addition, I removed the step linking to the fully supported Spring Zeebe SDK. It's not applicable and redundant (you get this info on the ZPT repo README, including the annotation `spring-zeebe-test`.). 
More internal context can be found [here](https://camunda.slack.com/archives/C06VC96GMNE/p1734021018422249?thread_ts=1729598950.187899&cid=C06VC96GMNE).
Related to https://github.com/camunda/zeebe-process-test/pull/1282.
=> Add note that Spring support is unavailable in 8.6+

docs/self-managed/modeler/web-modeler/configuration/configuration.md
Follow up to comments on [4769](https://github.com/camunda/camunda-docs/pull/4769/files#r1883885653)
The deploy diagram modal will no longer prompt the user to enter their cluster information if one is not configured in advance. This change makes the configuration clearer as a requirement to perform cluster-related actions.
=> Clarify SM Web Modeler cluster config requirement

api/generate-api-docs.js
While investigating #3736, I discovered that the error handling in the API generator code doesn't actually run 😰.
This is not really a significant issue because the only way to find it is to improperly call the API generators, but it's probably better to actually tell people how they're misusing them.
For what it's worth, I'm pretty sure GitHub Copilot wrote these blocks for me, demonstrating again that computers should never be trusted.
=> fix: use real, actual javascript in api generators

docs/self-managed/operational-guides/update-guide/860-to-870.md
For https://github.com/camunda/camunda/issues/25502, we had to document some incompatibilities introduced in 8.7:
closes https://github.com/camunda/camunda/issues/26338
closes https://github.com/camunda/camunda/issues/26339
These changes were made together by @ana-vinogradova-camunda @ce-dmelnych and @korthout so they don't require additional Engineering review. A Technical writer review is appreciated.
=> User Task Listeners update guide changes

docs/apis-tools/spring-zeebe-sdk/configuration.md, versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/configuration.md
@npepinpe once told me to use `zeebe.client.message.max-message-size=4194304`, which sounds like the default value and seems to be in bytes. If we use a too small example value, users may think the value is in megabytes. Obviously, we could also just document the unit but even then 3 bytes is likely not a workable value.
=> Fix example value for max-message-size

docs/components/modeler/bpmn/user-tasks/user-tasks.md, versioned_docs/version-8.4/components/modeler/bpmn/user-tasks/user-tasks.md, versioned_docs/version-8.5/components/modeler/bpmn/user-tasks/user-tasks.md, versioned_docs/version-8.6/components/modeler/bpmn/user-tasks/user-tasks.md
Add info related to the `assignee` attribute on modeler for User Task
Once on SaaS is case insensitive (once it uses e-mail, and consoler transforms all e-mails to lower case) and on Self-Managed is case sensitive (we are dealing with userIds)
Relates to: https://github.com/camunda/tasklist/issues/5035
=> fix: set info user task assignee for saas and sm

docs/apis-tools/zeebe-api/gateway-service.md
Updating `gateway-service.md` file `CompleteJobRequest`:
- added `JobResult` to `CompleteJobRequest`
- added `JobResultCorrections` to `JobResult`
closes https://github.com/camunda/camunda/issues/26345
=> Adding `JobResult` to `CompleteJobRequest` for gRPC

docs/components/connectors/out-of-the-box-connectors/amazon-bedrock.md
Updated documentation [issue](https://github.com/camunda/team-connectors/issues/978)
=> update bedrock documentation to include support for doc handling

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.5/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.6/components/modeler/desktop-modeler/element-templates/defining-templates.md
Related to https://github.com/camunda/product-hub/issues/2368
With [Element Templates Runtime Versions](https://github.com/camunda/product-hub/issues/2368) feature integrated in both Desktop and Web Modelers, we should add it to the documentation.
Element template JSON schema has a new `engines` property which can be used to specify template's compatibility with different execution platforms.
=> Add execution platform compatibility section for element templates

docs/apis-tools/zeebe-api/gateway-service.md
As there might be multiple task listeners that are triggered in sequence, the word `reset` might be misleading as it may imply that a previously made correction can be "reset" (i.e. undone).
Solution: using `clear` instead of `reset`
=> docs: changing the `reset` to `clear`

docs/components/concepts/job-workers.md, docs/components/concepts/user-task-listeners.md
Scope:
- Added a short section on job results in `completing or failing jobs`.
- Linked to the `User task listeners` concept page
- Added note that job result is used for the user task listeners only right now.
These changes were made together by @ana-vinogradova-camunda and @ce-dmelnych so they don't require additional Engineering review. A Technical writer review is appreciated.
closes https://github.com/camunda/camunda/issues/26344
=> Document job result in Job Workers concept page

docs/components/modeler/bpmn/user-tasks/user-tasks.md
Scope:
- added subsection on how to define user task listeners.
- linked with the `User task listeners` concept page.
- provided an XML example for the user task with the defined user task listeners.
These changes were made together by @ana-vinogradova-camunda and @ce-dmelnych so they don't require additional Engineering review. A Technical writer review is appreciated.
closes https://github.com/camunda/camunda/issues/26343
=> Document user task listeners for user task modeling

docs/self-managed/setup/deploy/local/local-kubernetes-cluster.md, versioned_docs/version-8.5/self-managed/setup/deploy/local/local-kubernetes-cluster.md
Back- and forward-porting a contributor change for 8.6 here: https://github.com/camunda/camunda-docs/pull/4686
The files and instructions for 8.5 through /next are the same, and the portforwarding command should be updated to match.
=> fix portforwarding command example for local k8s

docs/components/concepts/signals.md, versioned_docs/version-8.6/components/concepts/signals.md
Looking for something else in the docs and I noticed the C8 REST API endpoint should be on the signal page. I added it and reordered the list, with gRPC at the bottom.
=> Add REST endpoint to Concepts > Signal

docs/guides/getting-started-java-spring.md, versioned_docs/version-8.6/guides/getting-started-java-spring.md
- update the current Spring framework version
- add a link to prefill the Spring starter page with the Camunda information leaving out the moving parts
=> feat: links to fill spring started page

docs/guides/migrating-from-camunda-7/adjusting-source-code.md, docs/guides/migrating-from-camunda-7/conceptual-differences.md, docs/guides/migrating-from-camunda-7/index.md, docs/guides/migrating-from-camunda-7/migration-readiness.md, versioned_docs/version-8.3/guides/migrating-from-camunda-7/adjusting-source-code.md, versioned_docs/version-8.3/guides/migrating-from-camunda-7/conceptual-differences.md, versioned_docs/version-8.3/guides/migrating-from-camunda-7/index.md, versioned_docs/version-8.3/guides/migrating-from-camunda-7/migration-readiness.md, versioned_docs/version-8.4/guides/migrating-from-camunda-7/adjusting-source-code.md, versioned_docs/version-8.4/guides/migrating-from-camunda-7/conceptual-differences.md, versioned_docs/version-8.4/guides/migrating-from-camunda-7/index.md, versioned_docs/version-8.4/guides/migrating-from-camunda-7/migration-readiness.md, versioned_docs/version-8.5/guides/migrating-from-camunda-7/adjusting-source-code.md, versioned_docs/version-8.5/guides/migrating-from-camunda-7/conceptual-differences.md, versioned_docs/version-8.5/guides/migrating-from-camunda-7/index.md, versioned_docs/version-8.5/guides/migrating-from-camunda-7/migration-readiness.md, versioned_docs/version-8.6/guides/migrating-from-camunda-7/adjusting-source-code.md, versioned_docs/version-8.6/guides/migrating-from-camunda-7/conceptual-differences.md, versioned_docs/version-8.6/guides/migrating-from-camunda-7/index.md, versioned_docs/version-8.6/guides/migrating-from-camunda-7/migration-readiness.md
Quick updates of updated information about migration and timelines.
Quick fix for now - planing a proper overhaul of the migration guide later this year when we release more tooling support
=> Quick overhaul of outdated information in the migration guide

docusaurus.config.js, src/css/custom.css
Closes #4701.
Removes the Osano styles, so that they can be customized on a third party platform.
=> chore: remove osano styles

versioned_docs/version-8.6/self-managed/setup/guides/ingress-setup.md
The current example states that:
`zeebeGateway.ingress.rest` needs to be enabled.
This is only the case if the rest api should be served from a different host than the global ingress.
=> Update example values as the rest ingress is not required as stated

docs/components/concepts/execution-listeners.md, versioned_docs/version-8.6/components/concepts/execution-listeners.md
Previously, the documentation did not clearly state that execution listeners can be defined and executed at the process levels. This ambiguity led to user concerns about the scope of execution listener functionality, as highlighted in a recent [Slack conversation](https://camunda.slack.com/archives/C06CNGWTBAS/p1736938266363259). 
This update enhances the **Define an execution listener** section to explicitly specify that execution listeners can be configured for tasks, events, gateways, as well as for processes and subprocesses.
These updates are applicable to Camunda versions starting from 8.6 and were backported accordingly within the current PR.
closes https://github.com/camunda/camunda/issues/26937
=> Clarify scope of `Execution listeners` in concept page

docs/self-managed/operational-guides/multi-region/dual-region-ops.md, versioned_docs/version-8.6/self-managed/operational-guides/multi-region/dual-region-ops.md
Discovered in my docusaurus 3 branch, [during a failed build](https://github.com/camunda/camunda-docs/actions/runs/12837674495/job/35801829157?pr=4872).
In two docs we are referencing the `TabsItem` component despite importing the `TabItem` component. I have no idea why this works fine in the main branch, let alone doesn't cause an error. 
I'm making these corrections in main, which I will then propagate to my docusaurus 3 branch after merge.
=> fix: correct component name for TabItem

docs/components/connectors/protocol/rest.md, versioned_docs/version-8.6/components/connectors/protocol/rest.md
Added hint about new feature of grouping headers
=> connectors: Add hint about merging set cookie headers

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.5/components/modeler/desktop-modeler/element-templates/defining-templates.md, versioned_docs/version-8.6/components/modeler/desktop-modeler/element-templates/defining-templates.md
Adjusts the element template documentation. Bindings of type `zeebe:input` and `zeebe:output` are allowed to be `Boolean` or `Number` [if they are optional or static FEEL expressions](https://github.com/camunda/element-templates-json-schema/pull/156). 
Related to https://github.com/camunda/camunda-modeler/issues/4593#issuecomment-2434684367
=> fix(element-templates): add allowed types

docs/components/modeler/web-modeler/process-application-versioning.md, docs/components/modeler/web-modeler/versions.md, docs/reference/announcements/870.md
Part of https://github.com/camunda/web-modeler/issues/12551 and follow-up for https://github.com/camunda/camunda-docs/pull/4868
=> docs(web-modeler): announce milestone to version renaming

docs/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md, docs/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md, docs/self-managed/setup/deploy/openshift/redhat-openshift.md, versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md, versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md, versioned_docs/version-8.6/self-managed/setup/deploy/amazon/openshift/terraform-setup.md
This PR improves the **Requirements** section by advising the user to check the minimum quota for resources. 
This is related to a future improvement tracked by https://github.com/camunda/team-infrastructure-experience/issues/539 and a question raised by @ingorichtsmeier and @daniel-ewing https://camunda.slack.com/archives/C03UR0V2R2M/p1735927166282649.
=> doc(self-managed): clarify quotas needed for AWS usage

docs/components/early-access/alpha/sap/rfc-connector.md, versioned_docs/version-8.7/components/early-access/alpha/sap/rfc-connector.md
accidentally mentioned `OData` in the RFC doc, which (obviously) throws people off 😬 
Once final location of the "SAP Integration" docs are determined, this will need backporting to 8.5 and 8.6 as well.
But for now, `alpha` in `next` docs (both 8.7 and 8.8) is fine.
=> fix: spelling

docs/self-managed/connectors-deployment/connectors-configuration.md, versioned_docs/version-8.6/self-managed/connectors-deployment/connectors-configuration.md, versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md
hybrid connector configurations breaks when env vars have hyphens in the name, fex `CAMUNDA_CLIENT_CLUSTER-ID` needs to be `CAMUNDA_CLIENT_CLUSTERID` to work reliably for autobinding at runtime.
Source: https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.relaxed-binding
proof:
- working https://github.com/camunda/sap-rfc-connector/actions/runs/13308725894/job/37165648937#step:6:25
- breaking: https://github.com/camunda/sap-rfc-connector/actions/runs/13308063013/job/37163546517#step:6:25
Tagging @sbuettner and @jonathanlukas for additional validation.
=> fix: no hypen in env var

docs/guides/react-components/_install-c8run.md, docs/guides/react-components/_install-plain-java.md, versioned_docs/version-8.7/guides/react-components/_install-c8run.md, versioned_docs/version-8.7/guides/react-components/_install-plain-java.md
Reverts camunda/camunda-docs#4990 as 8.7.0-alpha4 was not released yet and alpha3 has issues.
=> Revert "bump to alpha3"

docs/apis-tools/spring-zeebe-sdk/configuration.md, versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/configuration.md, versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/configuration.md
- Job streaming should be is disabled by default for job workers.
Job streaming should be disabled by default for job workers.
Currently, job streaming is enabled by default for job workers and this can lead to 504 issues logged in the application if it's not configured correctly. Since it's not expected to be enabled by default, users are not aware that they need to configure it accordingly.
Related issue: https://github.com/camunda/camunda/issues/27502
Fix and backports: https://github.com/camunda/camunda/pull/28239
closes #5021
=> Job streaming should be disabled by default

styles/camunda/all/americanBritish.yml, styles/camunda/all/codeBlocksAreOurs.yml, styles/camunda/all/glossary.yml, styles/camunda/all/inclusiveLanguage.yml
Related to the [slack thread](https://camunda.slack.com/archives/C026U8GBNSW/p1739976167023769)
Adds vale outputs for:
- technical glossary
- inclusive language
- American English
Adds confluence related pages for:
- technical glossary
- inclusive language
TBH with vale now printing error and solution, might even be able to drop the URL reference or just keep it as reference so people can get there quickly. I opted for just the URL as if you run vale cli locally it won't transform markdown but feel free to adjust.
Fixed the code block references.
The regex was too lash allowing something like `camundaluckyluke`, anything as long as it contains camunda.
Example outputs of vale:
```
34:1  error  Improper codeblock                   all.codeBlocksAreOurs
source: '```bash reference …
=> fix: let vale print the problem and solution

docs/components/connectors/out-of-the-box-connectors/amazon-textract.md, versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/amazon-textract.md
update textract documentation with doc handing feature
[`issue`](https://github.com/camunda/team-connectors/issues/985)
=> update textract documentation with doc handing feature

docs/apis-tools/java-client/index.md, docs/apis-tools/java-client/job-worker.md, docs/apis-tools/spring-zeebe-sdk/configuration.md, docs/apis-tools/spring-zeebe-sdk/getting-started.md, docs/guides/getting-started-java-spring.md, versioned_docs/version-8.3/apis-tools/java-client/job-worker.md, versioned_docs/version-8.4/apis-tools/java-client/job-worker.md, versioned_docs/version-8.5/apis-tools/java-client/job-worker.md, versioned_docs/version-8.6/apis-tools/java-client/job-worker.md, versioned_docs/version-8.7/apis-tools/java-client/job-worker.md, versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/getting-started.md, versioned_docs/version-8.7/guides/getting-started-java-spring.md
=> docs(sdk): Update Java Client and spring SDK docs

docs/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eksctl.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md, versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md, versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
Resolves https://github.com/camunda/camunda-docs/issues/4259 - the EKS page has a code block which references `# Multi-region zones` which is misleading, as it is just referring to multiple zones for the region (not multiple regions). This PR removes "region" from the comment.
=> Update eks cluster config to not imply multi-region

howtos/interactive-api-explorers.md
Related to https://github.com/camunda/camunda/pull/28943.
Updates the API Explorer guidance to recommend using the synchronization workflow to update docs when possible. 
Inspired by [conversation in this PR](https://github.com/camunda/camunda-docs/pull/5095).
=> docs: recommend the sync workflow for changes to C8 REST API vNext

docs/apis-tools/java-client/authentication.md, docs/apis-tools/java-client/index.md, docs/apis-tools/spring-zeebe-sdk/configuration.md, docusaurus.config.js, sidebars.js
This PR adds basic auth configuration to the documentation. For the Spring SDK this was quite small. For the Java Client It's not as small as adding it to a page. Instead I:
1. Created a new `Authentication` page
2. Added basic auth to this page
3. Added (existing) oidc auth to this page
4. Added (existing) x.509 auth to this page
5. Removed existing oidc and x.509 auth from the `Quick Reference` page.
In addition to this I noticed we use a bunch of `bash` code blocks throughout our docs. The sytnax highlighting for this was never added. I've added this to make those code blocks a lot easier to read.
=> Add basic auth to Java client / Spring SDK

docs/reference/announcements.md, docs/reference/announcements/870.md, docs/reference/announcements/880.md, versioned_docs/version-8.7/reference/announcements.md, versioned_docs/version-8.7/reference/announcements/870.md
Fixes and aligns the mini-toc links on the 8.7 and 8.8 announcements pages, as per https://github.com/camunda/camunda-docs/issues/5067.
=> Fix 8.8 and 8.7 announcements links

docs/self-managed/operate-deployment/importer-and-archiver.md, docs/self-managed/tasklist-deployment/importer-and-archiver.md, versioned_docs/version-8.3/self-managed/operate-deployment/importer-and-archiver.md, versioned_docs/version-8.3/self-managed/tasklist-deployment/importer-and-archiver.md, versioned_docs/version-8.4/self-managed/operate-deployment/importer-and-archiver.md, versioned_docs/version-8.4/self-managed/tasklist-deployment/importer-and-archiver.md, versioned_docs/version-8.5/self-managed/operate-deployment/importer-and-archiver.md, versioned_docs/version-8.5/self-managed/tasklist-deployment/importer-and-archiver.md, versioned_docs/version-8.6/self-managed/operate-deployment/importer-and-archiver.md, versioned_docs/version-8.6/self-managed/tasklist-deployment/importer-and-archiver.md, versioned_docs/version-8.7/self-managed/operate-deployment/importer-and-archiver.md, versioned_docs/version-8.7/self-managed/tasklist-deployment/importer-and-archiver.md
Quick win to update the informal use of "guess" to a more appropriate/professional "determine". :) 
Requested/context on slack: https://camunda.slack.com/archives/C026U8GBNSW/p1741188378847419
=> Update usage of "guess" to "determine"

docs/reference/supported-environments.md, versioned_docs/version-8.6/reference/supported-environments.md, versioned_docs/version-8.7/reference/supported-environments.md
Part of https://github.com/camunda/product-hub/issues/1247, but this time we remove the link to the C7 Optimize matrix because Optimize is included in the above matrix alongside the other components.
=> Remove link to C7 Optimize matrix in supported environments

docs/self-managed/setup/deploy/local/c8run.md
Removes the now unnecessary cookie auth for the C8Run API, which is unprotected by default starting with 8.8.0-alpha2.
Also added a section to instruct the user on how to enable authentication and authorization, should they want to make use of it.
closes https://github.com/camunda/documentation-team/issues/463
=> feat: unprotected API for C8Run

docs/self-managed/zeebe-deployment/configuration/broker.md, docs/self-managed/zeebe-deployment/configuration/gateway.md, docs/self-managed/zeebe-deployment/security/secure-cluster-communication.md, versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/broker.md, versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/gateway.md, versioned_docs/version-8.6/self-managed/zeebe-deployment/security/secure-cluster-communication.md, versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/broker.md, versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/gateway.md, versioned_docs/version-8.7/self-managed/zeebe-deployment/security/secure-cluster-communication.md
This PR fixes the documentation around broker/gateway configuration support for PKCS12 keystores. Parts were missing in the general configuration overview, while in others we referenced the wrong environment variables.
=> Update configuration to match PKCS12 support

docs/components/concepts/access-control/user-groups.md, docs/components/console/manage-organization/manage-users.md, versioned_docs/version-8.5/components/concepts/access-control/user-groups.md, versioned_docs/version-8.5/components/console/manage-organization/manage-users.md, versioned_docs/version-8.6/components/concepts/access-control/user-groups.md, versioned_docs/version-8.6/components/console/manage-organization/manage-users.md, versioned_docs/version-8.7/components/concepts/access-control/user-groups.md, versioned_docs/version-8.7/components/console/manage-organization/manage-users.md
Closes https://github.com/camunda/camunda-docs/issues/3665.
Users reported they missed out on the docs for the config options for task access restrictions for user groups.
As a result, we should update "Manage users" and "user groups" pages to reference the "user task access restrictions" settings for user groups.
https://docs.camunda.io/docs/components/console/manage-organization/manage-users/
https://docs.camunda.io/docs/components/concepts/access-control/user-groups/
=> provide details on user task restrictions

versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/configuration.md
This PR removes a configuration option that will not be present in Camunda 8.7.
=> remove non-existent config options

docs/components/modeler/bpmn/error-events/error-events.md, versioned_docs/version-8.6/components/modeler/bpmn/error-events/error-events.md, versioned_docs/version-8.7/components/modeler/bpmn/error-events/error-events.md
This PR addresses [Error Variables need clarification](https://github.com/camunda/camunda-docs/issues/5078) task.
In this PR:
- `Throwing the error` section is updated: the link to REST request `Report error for job` is added (it has only a link to gRPC command prior to that).
- `Variable mappings` section updated with more detailed information.
=> Error variables clarification

docs/self-managed/zeebe-deployment/exporters/camunda-exporter.md
- The archiver properties will be renamed to history.
- Remove the disabling of the archiver e.g. remove `archiver.enable`
=> docs: renamed archiver to history and removed enable setting

docs/reference/notices.md, versioned_docs/version-8.3/reference/notices.md, versioned_docs/version-8.4/reference/notices.md, versioned_docs/version-8.5/reference/notices.md, versioned_docs/version-8.6/reference/notices.md, versioned_docs/version-8.7/reference/notices.md
We had a critical vulnerability in Web Modeler. Jira ticket: https://jira.camunda.com/browse/SEC-1285
=> chore: add security notice 14

docs/reference/release-notes/880.md
Includes notes or placeholders for alpha2 [labeled epics](https://github.com/orgs/camunda/projects/9/views/31).
=> 8.8-alpha2 release notes

docs/components/connectors/protocol/rest.md, docs/reference/announcements/860.md, docs/self-managed/operational-guides/update-guide/850-to-860.md, versioned_docs/version-8.6/components/connectors/protocol/rest.md, versioned_docs/version-8.6/reference/announcements.md, versioned_docs/version-8.6/self-managed/operational-guides/update-guide/850-to-860.md, versioned_docs/version-8.7/components/connectors/protocol/rest.md, versioned_docs/version-8.7/reference/announcements/860.md, versioned_docs/version-8.7/self-managed/operational-guides/update-guide/850-to-860.md
The behavior for grouping headers had a breaking change from 8.5 to 8.6. This is now documented.
=> fix(rest-connector): add hint about breaking change in 8.6

docs/self-managed/operational-guides/data-purge.md, sidebars.js
This PR describes the new cluster data purge functionality described here: [#25861](https://github.com/camunda/camunda/issues/25861)
=> docs(data-purge): adds operational guide for data purge

docs/components/concepts/document-handling.md, versioned_docs/version-8.7/components/concepts/document-handling.md
This PR adds documentation around the permissions required by the API clients used by our application to manage documents when using GCP or AWS as storage.
Relates to https://github.com/camunda/camunda-docs/issues/5273
=> feat: Include cloud permissions in doc handling docs

howtos/release-procedure.md
This is the docs-on-docs update to state the Algolia crawler now runs daily. The change to the Algolia config has already happened.
Does not apply. These are unversioned docs-on-docs.
=> Algolia crawler now runs daily

versioned_docs/version-8.5/apis-tools/tasklist-api/tasklist-api-authentication.md, versioned_docs/version-8.6/apis-tools/tasklist-api/tasklist-api-authentication.md, versioned_docs/version-8.7/apis-tools/tasklist-api/tasklist-api-authentication.md
Closes https://github.com/camunda/documentation-team/issues/260.
Cookie authentication works only for SM, and in case the customer is not using Identity (in case Identity is up, is not possible to use it).
We can copy this from Operate docs: https://docs.camunda.io/docs/apis-tools/operate-api/operate-api-authentication/#authentication-via-cookie-self-managed-only and just highlight that this works for scenarios where authentication is not managed by Identity.
=> clarify sm cookie auth for tasklist api

howtos/release-procedure.md
As discussed in the backlog review.
I've also verified that all Docs Team members have the right access and should be able to trigger crawls manually. 
These changes are for the docs-on-docs.
=> Update Algolia crawler instructions for manual triggers

howtos/interactive-api-explorers.md
Describes a very annoying manual step in generating back-versions of API docs.
=> docs on docs: tip for generating numbered versions of API docs

docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md, docs/self-managed/zeebe-deployment/exporters/opensearch-exporter.md, versioned_docs/version-8.3/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md, versioned_docs/version-8.3/self-managed/zeebe-deployment/exporters/opensearch-exporter.md, versioned_docs/version-8.4/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md, versioned_docs/version-8.4/self-managed/zeebe-deployment/exporters/opensearch-exporter.md, versioned_docs/version-8.5/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md, versioned_docs/version-8.5/self-managed/zeebe-deployment/exporters/opensearch-exporter.md, versioned_docs/version-8.6/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md, versioned_docs/version-8.6/self-managed/zeebe-deployment/exporters/opensearch-exporter.md, versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md, versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
Document how to configure the ES/OS exporters with self signed certificates.
=> docs: document how to use ES/OS exporter with self signed certificates

docs/reference/supported-environments.md, versioned_docs/version-8.3/reference/supported-environments.md, versioned_docs/version-8.4/reference/supported-environments.md, versioned_docs/version-8.5/reference/supported-environments.md, versioned_docs/version-8.6/reference/supported-environments.md, versioned_docs/version-8.7/reference/supported-environments.md
As we release the alpha Helm charts publically, I've added the version matrix links for those charts.
Also, I added it to previous Camunda docs from 8.3-8.5
=> docs(self-managed): update helm version matrix

static/.htaccess
Some already published content had linked to the ad-hoc sub-process page when it existed under Markers. It was moved in PR #5335 and now the old link is giving a 404 error. Example:
https://camunda.com/blog/2025/02/building-ai-agent-camunda/ links to https://docs.camunda.io/docs/8.7/components/modeler/bpmn/ad-hoc/ in the second paragraph.
The .htaccess rules include a redirect for that path _without_ the version, but was missing a versioned path.
=> fix(ad-hoc): fix 8.7 redirect after page move

docs/components/rpa/getting-started.md, docs/components/rpa/overview.md, docs/components/rpa/production.md, docs/reference/supported-environments.md, versioned_docs/version-8.7/components/rpa/getting-started.md, versioned_docs/version-8.7/components/rpa/overview.md, versioned_docs/version-8.7/components/rpa/production.md, versioned_docs/version-8.7/reference/supported-environments.md
Closes https://github.com/camunda/camunda-docs/issues/5256 -- adding feedback from @bastiankoerber courtesy of notes from @marstamm.
Perhaps we can create a separate issue for an architecture diagram?
=> rework RPA docs

docs/self-managed/operate-deployment/operate-configuration.md, docs/self-managed/tasklist-deployment/tasklist-configuration.md, versioned_docs/version-8.7/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md
Added workaround for the logs of Operate and Tasklist being flooded with deprecation warnings from Elasticsearch when newer Elasticsearch versions (>=8.16.0) are used as recommendation to the documentation.
I added this to current and 8.7. because the default Elasticsearch version from 8.7 onwards will be 8.17.3.
Please let me know if you think it makes more sense to put this elsewhere.
I'm also unsure if this should be added to the update guidelines for 8.7 (this workaround will also be put as [default to the Helm charts for 8.7 and 8.8](https://github.com/camunda/camunda-platform-helm/issues/3243))
relates to: https://github.com/camunda/camunda/issues/26285
=> docs: added recommendation for suppressing ES deprecation logs

docs/self-managed/zeebe-deployment/configuration/logging.md, versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/logging.md, versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/logging.md
This PR documents the logging configuration used by the C8 orchestration cluster.
I've opted to link to the configuration instead of pasting its contents, since this is more likely to get out of sync. I then focused mostly on the ways the user can re-configure it without providing their own `log4j2.xml` file.
Note that since 8.6, this applies not just to Zeebe, but to C8 as a whole. However, we have no "general" or "streamlined" configuration section, everything is by components =/
I think it would be good to have this, but it may be a bit out of scope here, and a bigger refactoring/rewrite.
=> docs: document default log configuration

docs/self-managed/setup/deploy/local/c8run.md, src/components/CamundaDistributions/C8Run.jsx, src/components/CamundaDistributions/index.jsx, versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md, versioned_docs/version-8.7/self-managed/setup/deploy/local/c8run.md
Long gone are the cave-person days of updating manual links for c8run on every release. This PR introduces a jsx file which will  construct a URL pointing to the latest patch release of that minor version. We have a change like this for the DockerCompose link. I used the same code and adapted it to work for C8Run.
No rush on this change.
=> fix: make link to c8run release dynamic

docs/apis-tools/spring-zeebe-sdk/configuration.md, versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md, versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/configuration.md, versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/configuration.md
Changed and backported the default settings for maxInboundMessageSize. The server does just an approximation and thus sometimes even though rarely it might send a payload that is slightly larger than 4MB (old default) and the client would have denied this before. Thus we are increasing the size on the client side to not be overly rigorous.
(for more details check out the SDK PR https://github.com/camunda/camunda/pull/29608)
=> feat: change sdk default for maxMessageSize

.github/workflows/add-to-project.yaml
Updates the list of reviewers for whom a PR will automatically be added to the docs team board, including: 
1. Removing @conceptualshark 🪦 😭 
2. Adding @mesellings only 8 months late 😰 
I had thought that Tech Writers team assignments weren't being added to the board, but in my debugging it seems like they are, so no changes there.
=> chore: update add-to-project user IDs

static/.htaccess
Follow up to https://camunda.slack.com/archives/C026U8GBNSW/p1744138526427809.
These were removed in the 8.7 release process, but it looks like Google crawled the 8.7 docs and got this old URL. I added them all back just in case, but we can remove them if needed.
Adding or removing pages requires extra steps.
=> Add (back) 8.7 release announcements redirects

static/.htaccess
I realized too late that the URLs I added were all `/next/` instead of versionless in https://github.com/camunda/camunda-docs/pull/5503. This PR corrects them.
=> add redirects

docs/self-managed/concepts/access-control/user-task-access-restrictions.md, docs/self-managed/identity/deployment/configuration-variables.md, docs/self-managed/tasklist-deployment/tasklist-authentication.md, versioned_docs/version-8.4/self-managed/concepts/access-control/user-task-access-restrictions.md, versioned_docs/version-8.4/self-managed/identity/deployment/configuration-variables.md, versioned_docs/version-8.4/self-managed/tasklist-deployment/tasklist-authentication.md, versioned_docs/version-8.5/self-managed/concepts/access-control/user-task-access-restrictions.md, versioned_docs/version-8.5/self-managed/identity/deployment/configuration-variables.md, versioned_docs/version-8.5/self-managed/tasklist-deployment/tasklist-authentication.md, versioned_docs/version-8.6/self-managed/concepts/access-control/user-task-access-restrictions.md, versioned_docs/version-8.6/self-managed/identity/deployment/configuration-variables.md, versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-authentication.md, versioned_docs/version-8.7/self-managed/concepts/access-control/user-task-access-restrictions.md, versioned_docs/version-8.7/self-managed/identity/deployment/configuration-variables.md, versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-authentication.md
Context of this PR: 
@romansmirnov  and myself went through docs, and Roman verified code. 
Basic rationale of this change:
* The status-quo of the docs refer to a `USER_RESTRICTIONS_ENABLED` flag in the Identity application that controls whether tasks in Tasklists are shown or not based on set properties (assignee, candidate, ...).
* Checking code, Roman found that this flag in Identity is not used. Instead, another flag in tasklist seems to be used.
* This PR adjusts the documentation accordingly. 
My ask for the reviewers:
* @marcosgvieira  - can you please verify that our findings and corrections are correct - in particular for how Tasklist handles the check for user task access restrictions?
* @ThorbenLindhauer - can you please verify that our findings and corrections are correct - …
=> Correct user task restirciton

docs/self-managed/concepts/exporters.md
=> docs(data-purge): fix note formatting

docs/components/camunda-integrations/sap/csap-cli.md, versioned_docs/version-8.7/components/camunda-integrations/sap/csap-cli.md
so no warning message will be displayed any more when the cli is used ootb
`csap` is now signed and notarized during the release process, so Mac users can use the cli w/o any security message popus.
=> feat: csap is now notarized by Apple

docs/components/modeler/web-modeler/play-your-process.md, docs/reference/announcements-release-notes/870/870-release-notes.md, versioned_docs/version-8.7/components/modeler/web-modeler/play-your-process.md, versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md
This PR adjust the release notes and docs to specify that Scenarios are for SaaS only.
Relates to https://camunda.slack.com/archives/C026U8GBNSW/p1744890221807049 and the support ticket https://jira.camunda.com/browse/SUPPORT-26885.
=> Replay scenarios saas only

.github/workflows/preview-env-deploy.yml
Updates the preview-env-deploy.yaml workflow to correct a couple small issues:
1. The build doesn't take nearly as long as it used to.
2. The preview link was taking you to a URL that contains two home pages stacked on top of each other 😱. I have no idea why this was happening. But everything is fine if we remove the `index.html` from the URL, which is how the real docs site would be navigated anyway. (We were originally including the index.html due to the preview environment infrastructure requiring it, but it doesn't seem to be required anymore.)
=> docs: fix a couple preview deploy incorrections

docs/apis-tools/testing/assertions.md
Adds documentation for 
```
assertThat(processInstance).hasActiveIncidents();
assertThat(processInstance).hasNoActiveIncidents();
assertThat(processInstance).hasActiveElementsExactly("task_A", "task_B");
assertThat(processInstance).hasNoActiveElements("task_A", "task_B");
assertThat(processInstance).hasNotActivatedElements("task_A", "task_B");
assertThat(processInstance).hasCompletedElementsInOrder("task_A", "task_B");
```
Closes #5320, #5374, #5375, #5472, #5223, #5299
=> docs(assert): add docs for newly implemented asserts

docs/self-managed/tasklist-deployment/tasklist-configuration.md, versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-configuration.md, versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md
=> feat: allow for non-self assignment

package-lock.json, package.json, src/css/custom.css
Bumps prettier, and reformats with new version.
=> chore: bump prettier to 3.5.3

static/.htaccess
=> chore: clean up 8.7 redirect rules

howtos/documentation-guidelines.md
The internal links section already document what we should do. However, there is also a linter that checks against this. Contributors are likely to encounter this, and may be looking for advice on what to do.
This adds a note to the internal links section of the documentation guidelines to help users that encounter this linting error.
I've re-ordered the guidelines to highlight what we should always do first.
This came up in Slack [here](https://camunda.slack.com/archives/C01H4NG9XDY/p1745945897036719?thread_ts=1745876798.510449&cid=C01H4NG9XDY).
=> Document internal linking lint error workaround

sidebars.js, versioned_sidebars/version-8.7-sidebars.json
This PR adds a new link to the sidebar that takes the user to the [API spec for the OOTB RPA libraries](https://camunda.github.io/rpa-python-libraries/).
related to https://camunda.slack.com/archives/C07DA2WBMAL/p1745570511438299 and https://camunda.slack.com/archives/C026U8GBNSW/p1745572225448259
=> feat(rpa): prominently link to RPA library docs

docs/self-managed/setup/guides/connect-to-an-oidc-provider.md, versioned_docs/version-8.7/self-managed/setup/guides/connect-to-an-oidc-provider.md
First I suspected a documentation bug because of the format differences between different doc pages on `existingSecret`. But then I saw the documentation of the Helm Chart saying both string or object are possible:
```
[string,object] A string literal secret can be provided. [...] Recommended: reference an existing Kubernetes Secret using global.identity.auth.identity.existingSecret.name. 
```
This should probably be the default recommendation in the docs aw well so that users follow K8s security best practices.
=> Add link from OIDC guide to Identity secrets

docs/apis-tools/camunda-api-rest/intermediate-tutorial.md, docs/apis-tools/camunda-api-rest/sidebar-schema.js, docs/apis-tools/camunda-api-rest/tutorial.md
Docs aligned with tutorial https://github.com/camunda/camunda-api-tutorials/pull/13. This PR should _not_ be merged until the actual tutorial is merged.
=> C8 api intermediate tutorial

docs/self-managed/operational-guides/troubleshooting/diagnostics.md, sidebars.js, versioned_docs/version-8.4/self-managed/platform-deployment/diagnostics.md, versioned_docs/version-8.5/self-managed/operational-guides/troubleshooting/diagnostics.md, versioned_docs/version-8.6/self-managed/operational-guides/troubleshooting/diagnostics.md, versioned_docs/version-8.7/self-managed/operational-guides/troubleshooting/diagnostics.md
closes https://github.com/camunda/team-distribution/issues/495
This script automates the collection of logs and diagnostics from a Camunda Helm Chart deployment in a Kubernetes cluster. It gathers relevant information from the specified namespace and outputs it in a .zip file for easy sharing with the Camunda Support team.
Once this change is approved, I will backport it to the other versions.
Example output file: [camunda-diagnostics-logs-20250501-082547.zip](https://github.com/user-attachments/files/19999492/camunda-diagnostics-logs-20250501-082547.zip)
Terminal output: 
```
========================================
Camunda Diagnostics Collection Script
========================================
Namespace: immi-test
Output Directory: camunda-diagnostics-logs-20250501-082547
Current kubectl …
```
=> add diagnosis script

docs/self-managed/operate-deployment/operate-configuration.md, docs/self-managed/tasklist-deployment/tasklist-configuration.md, docs/self-managed/zeebe-deployment/security/secure-cluster-communication.md, versioned_docs/version-8.6/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.6/self-managed/operational-guides/update-guide/850-to-860.md, versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-configuration.md, versioned_docs/version-8.6/self-managed/zeebe-deployment/security/secure-cluster-communication.md, versioned_docs/version-8.7/self-managed/operate-deployment/operate-configuration.md, versioned_docs/version-8.7/self-managed/operational-guides/update-guide/850-to-860.md, versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md, versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md, versioned_docs/version-8.7/self-managed/zeebe-deployment/security/secure-cluster-communication.md
Document Intra cluster TLS configuration for Tasklist & Operate for versions 8.6, 8.7 and 8.8.
To be released alongside May's scheduled patch releases.
Version _note_ for 8.7.2 and 8.6.14
- docs/8.6/self-managed/tasklist-deployment/tasklist-configuration/#intra-cluster-secure-connection
- docs/8.7/self-managed/tasklist-deployment/tasklist-configuration/#intra-cluster-secure-connection
- docs/next/self-managed/tasklist-deployment/tasklist-configuration/#intra-cluster-secure-connection
Version _note_ for 8.7.2 and 8.6.14
- docs/8.6/self-managed/operate-deployment/operate-configuration/#intra-cluster-secure-connection
- docs/8.7/self-managed/operate-deployment/operate-configuration/#intra-cluster-secure-connection
- docs/next/self-managed/operate-deployment/operate-configuration/#intra-cluste …
=> docs: document intra cluster tls config

.github/workflows/auto-assign-pr.yml
Example of failure in the past:
- https://github.com/camunda/camunda-docs/pull/5783
- https://github.com/camunda/camunda-docs/actions/runs/15048544007/job/42297253158?pr=5783
```
Run actions-ecosystem/action-add-assignees@v1
Error: HttpError: Not Found
Error: Not Found
```
=> ci: exclude docs automation from assign to itself

docs/guides/migrating-from-camunda-7/migration-tooling.md, versioned_docs/version-8.6/guides/migrating-from-camunda-7/migration-tooling.md, versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-tooling.md
To help customers better understand the tool, I've renamed it to represent its true functionality. It not just analyzes your diagrams, but converts them.
The rename will happen in the tool as well:
https://github.com/camunda-community-hub/camunda-7-to-8-migration-analyzer/pull/112
=> Rename tool to migration analyzer and diagram converter

docs/self-managed/operational-guides/update-guide/860-to-870.md, docs/self-managed/operational-guides/update-guide/870-to-880.md, versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md
* Streamlines how V2 API changes are headlined.
* Hints at removed OpenAPI DTOs relevant for custom REST API client.
closes https://github.com/camunda/camunda-docs/issues/5623
=> docs: extend update guide with OpenAPI changes

docs/apis-tools/testing/getting-started.md
As part of the changes in renaming the property `camunda.version` in favor of `camunda.dockerImageVersion` (see here: https://github.com/camunda/camunda/pull/33515), the documentation also needed to be updated.
=> fix: rename `camunda.version` to `camunda.dockerImageVersion`

docs/components/best-practices/development/writing-good-workers.md, docs/components/concepts/job-workers.md
Adds a performance best practices section for job workers, with two notes: one about fetch variables, and one about job streaming.
=> refactor: add performance best practices section

docs/self-managed/setup/deploy/gcp/google-gke.md
A tiny fix for 8.8 docs, as in https://github.com/camunda/camunda-docs/pull/5971, I've made the changes for other versions, but not for the 8.8 version.
=> docs(self-managed): typo in gke ingress for camunda 8.8

docs/self-managed/operational-guides/monitoring/metrics.md, versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/metrics.md, versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/metrics.md, versioned_docs/version-8.6/self-managed/operational-guides/monitoring/metrics.md, versioned_docs/version-8.7/self-managed/operational-guides/monitoring/metrics.md
This came up in a support case [#inc-support-27804-questions-about-process-processing-metrics](https://camunda.slack.com/archives/C092SJEQ6M9), where it was not clear to the customer that in order to see the
zeebe_process_instance_creations_total or the
zeebe_incident_events_total, there needs to be some activity on the cluster that causes the recording of these metric events.
To avoid this in the future, I've added a note to the page in the Available metrics section.
Please note that the example `zeebe_incident_events_total`, currently has a known bug where it is called `zeebe_incidents_events_total` instead (https://github.com/camunda/camunda/issues/34342). But, I still think it's a good example so I prefer to use it even though that bug is not yet resolved.
=> Document processing metrics availability

.github/renovate.json5
This PR is to configure Renovate's automerge for most dependencies, based on the conversation on this [#ask-infra question on slack](https://camunda.slack.com/archives/C5AHF1D8T/p1752568821040499)
In particular, here the suggested automerge policies:
* devDependencies (like jest, playwright, prettier etc.) -> we can automerge any version (major-minor-patch)
consider also grouping all devDeps into a single upgrade PR to simplify the flow
* docusaurus dependencies
* patch versions are fine to auto-merge
* minor versions should go through a review via the Docs team first -> we've had examples in the past when the minor versions of the plugins were misbehaving and needed adjustment. Docs team will be able to verify with the preview environments that all works well and approve the rollout
* …
=> Update renovate automerge config

docs/self-managed/connectors-deployment/connectors-configuration.md, versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md
This PR introduces tenant-aware secret handling in Connectors.
This feature is introduced with https://github.com/camunda/connectors/pull/5069
=> feat: introduce tenant-aware connector secrets

docs/apis-tools/zeebe-api/gateway-service.md, docs/components/concepts/job-workers.md, docs/components/concepts/user-task-listeners.md
This PR updates documentation to align with the API changes introduced in:
- Issue: camunda/camunda#34493
- PR camunda/camunda#35466
Includes the following updates:
1. Updated code examples in `user-task-listeners.md` and `job-worker.md` to use the new lambda-based `.withResult(r -> r.forUserTask()...)` style instead of `new CompleteJobResult()`.
This reflects the new structure for completing user task listener jobs with corrections or denial flags.
3. Extended the `JobResult` gRPC message in `gateway-service.md` with new fields:
- `type`: to distinguish between `userTask` and `adHocSubprocess`
- `activateElements`: a list of elements that should be activated after the job is completed.
- `JobResultActivateElement`: defines element ID and scoped variables
- `deniedReason`: optional …
=> docs: update `CamundaClient` examples and JobResult gRPC docs

docs/components/concepts/user-task-listeners.md, docs/components/modeler/bpmn/user-tasks/user-tasks.md
This changes the documentation about user task listeners across a few pages applying previously received feedback:
- the [User tasks](https://docs.camunda.io/docs/next/components/modeler/bpmn/user-tasks/#user-task-listeners) page
- the [User task listeners](https://docs.camunda.io/docs/next/components/concepts/user-task-listeners/) page
<details><summary>Changes to the User tasks page</summary>
<p>
- Removed the section on supported events, as these are much nicer documented in the concept page (which is referenced at the end of this section)
- Added more detail to the definitions of a listener like the `type`, including examples. Aligning it to the task definition section of the service tasks page.
| Before | After |
|--------|--------|
| <img width="1264" height="1191" alt="Screenshot …
=> Improvements to the user task listener documentation

docs/reference/announcements-release-notes/880/880-announcements.md
Add a deprecation notice for the Web Modeler API endpoints under `/api/v1/milestones`.
**Note**: The endpoints were already marked as deprecated in the [Swagger API docs](https://modeler.camunda.io/swagger-ui/index.html#/Milestones) with the 8.7 release, but we haven't mentioned the deprecation in the release announcements yet.
Closes https://github.com/camunda/web-modeler/issues/16241
=> docs: announce deprecation of Web Modeler API milestone endpoints

docs/self-managed/components/modeler/web-modeler/troubleshooting/troubleshoot-proxy-configuration.md, versioned_docs/version-8.5/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-proxy-configuration.md, versioned_docs/version-8.6/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-proxy-configuration.md, versioned_docs/version-8.7/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-proxy-configuration.md
Fixes the name of the environment variable that can be used to configure a proxy for Web Modeler's `restapi` component (it's [`JAVA_OPTIONS`](https://github.com/camunda/web-modeler/blob/26b3454520b122f5b5921da1293bdd9d0150a639/restapi/docker-entrypoint.sh#L12) instead of `JAVA_OPTS`).
Related to https://github.com/camunda/web-modeler/issues/16044
=> fix: use correct environment variable for proxy configuration in Web Modeler

docs/self-managed/components/components-upgrade/870-to-880.md, docs/self-managed/components/orchestration-cluster/operate/importer-and-archiver.md, docs/self-managed/components/orchestration-cluster/tasklist/importer-and-archiver.md, docs/self-managed/installation-methods/helm/upgrade/helm-870-880.md
By default in 8.8 the Operate/Tasklist importers will be disabled, however they are still required for the update from 8.7 -> 8.8. 
relates to https://github.com/camunda/camunda/issues/37080
=> Disabled Operate/Tasklist importers in 8.8

.github/workflows/build-docs.yaml, docs/reference/announcements-release-notes/850/850-announcements.md, docs/reference/announcements-release-notes/860/860-announcements.md, docs/reference/announcements-release-notes/870/870-announcements.md, docs/reference/announcements-release-notes/880/880-announcements.md, docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/eks-helm.md, docs/self-managed/installation-methods/helm/configure/air-gapped-installation.md, docs/self-managed/installation-methods/helm/upgrade/helm-820-830.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/irsa.md, versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/upgrade.md, versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/irsa.md, versioned_docs/version-8.5/self-managed/setup/guides/air-gapped-installation.md, versioned_docs/version-8.5/self-managed/setup/upgrade.md, versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md, versioned_docs/version-8.6/self-managed/setup/guides/air-gapped-installation.md, versioned_docs/version-8.6/self-managed/setup/upgrade.md, versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md, versioned_docs/version-8.7/self-managed/setup/guides/air-gapped-installation.md, versioned_docs/version-8.7/self-managed/setup/upgrade.md
Task: https://github.com/camunda/camunda-platform-helm/issues/3999
Add Bitname Docker repo change to the announcements.
Note: I'm not sure if I should make the changes the older versions dir (I've added to other versions announcements in latest).
=> docs: add bitname repo change to the announcements

.github/workflows/check-format.yaml
Makeshift solution to fix prettier check.
We forked the action repo as it got abandoned and went back to an older reviewdog version to reinstate known behavior.
We will also create a follow-up issue. 
See details in this [ask-infra question](https://camunda.slack.com/archives/C5AHF1D8T/p1756973496578219).
=> fix: prettier check

docs/components/modeler/using-web-and-desktop-modeler-together.md
During my previous review I missed this phrase which is not accurate. What I originally tried to communicate is that desktop modeler can load multiple templates defined in a single file, while web modeler cannot. 
From what I learnt, in desktop modeler multiple templates in a single file is a recommended approach to defining multiple versions of the same template. Web Modeler keeps track of all versions, so there is no need to store all of them in a list, or in multiple files.
=> chore(element-templates): fix warning around multiple templates in a single file

static/js/render-diagrams.js
When running the docs in dev mode with `npm start` I noticed that for some sections with a name starting with a number it would throw a runtime error. 
I checked in the released version of the docs and I noticed that the error is thrown, but it's not visible to the user, just in the console.
Screenshot of the errors thrown in the console from the `main`:
The function renderDiagrams would call scrollToHash on every render even if no bpmn diagrams are present in the page.
The function scrollToHash would throw an error if the location.hash starts with a number like '#1-example'.
If no diagrams are present in the page, renderDiagrams now just return immediately instead.
@mesellings please assign to whoever is best fit for this review, I was not sure who to assign it to
=> fix: do not invoke scrollToHash if no diagrams are present in the page

docs/apis-tools/testing/getting-started.md
This pull request updates the `getting-started.md` documentation for process testing tools. The main changes clarify dependency configuration for Maven (to align with Java Client docs) and change the example test assertions to check if the process instance is active.
**Dependency configuration improvements:**
* Added explicit `<version>${camunda.version}</version>` tags to both the `camunda-process-test-spring` and `camunda-process-test-java` Maven dependency examples to ensure users specify the correct version. [[1]](diffhunk://#diff-74867037373dcaa0bcd94147e2fc1bc2657f8a17c4df7599f8d2673ed896c8e1R61) [[2]](diffhunk://#diff-74867037373dcaa0bcd94147e2fc1bc2657f8a17c4df7599f8d2673ed896c8e1R76)
**Test example corrections:**
* Updated the example test assertions from `isCompleted()` to …
=> fix: Camunda process test

docs/reference/announcements-release-notes/880/880-announcements.md, docs/reference/announcements-release-notes/880/whats-new-in-88.md, docs/self-managed/update/administrators/prepare-for-update.md
Closes https://github.com/camunda/camunda-docs/issues/6404
This PR introduces the notes relating to the removal of support for tenant providing interceptors to both the "Whats new in 8.8" and the "Prepare for an update" pages. I have included, where relevant, links to relevant supporting materials.
=> docs: update whats new/upgrade guide to note tenant interceptor changes

versioned_docs/version-8.6/self-managed/operate-deployment/importer-and-archiver.md, versioned_docs/version-8.6/self-managed/tasklist-deployment/importer-and-archiver.md, versioned_docs/version-8.7/self-managed/operate-deployment/importer-and-archiver.md, versioned_docs/version-8.7/self-managed/tasklist-deployment/importer-and-archiver.md
Adds a min officially supported version for rollover interval
addition to https://github.com/camunda/camunda-docs/pull/6850 as it was merged
=> docs: add minimum supported version for rollover interval
