docs/product-manuals/clients/go-client/get-started.md

Adjust go get started guide

---

docs/product-manuals/concepts/job-workers.md

Clarify job delivery guarantees/idempotency requirements

---

docs/product-manuals/zeebe/open-source/get-help-get-involved.md

Aligning to the rebranding with a generic reference to the Slack and forum.

Community updates

---

docs/reference/bpmn-workflows/multi-instance/multi-instance.md

* correct the XML representation for sequential subprocesses

Correct the XML representation of sequential subprocesses

---

docs/product-manuals/cloud-console/manage-organization/manage-users.md
docs/product-manuals/cloud-console/manage-plan/available-plans.md
versioned_docs/version-0.25/product-manuals/cloud-console/overview.md

I had some long-standing changes to the original camunda-cloud-docs repository (waited too long with the PR), most of which have already been refreshed in this consolidated repository. These are the remaining changes.

Fix typos and wordings.

---

docs/product-manuals/operate/deployment/authentication.md
docs/product-manuals/operate/deployment/configuration.md
docs/product-manuals/operate/deployment/install-and-start.md
docs/product-manuals/operate/deployment/schema-and-migration.md
docs/product-manuals/tasklist/deployment/authentication.md
docs/product-manuals/tasklist/deployment/configuration.md
docs/product-manuals/tasklist/deployment/install-and-start.md
docs/reference/tasklist-api/generated.md
docs/reference/tasklist-api/inputs/task-query.mdx
docs/reference/tasklist-api/inputs/variable-input.mdx
docs/reference/tasklist-api/mutations/claim-task.mdx
docs/reference/tasklist-api/mutations/complete-task.mdx
docs/reference/tasklist-api/mutations/unclaim-task.mdx
docs/reference/tasklist-api/objects/form.mdx
docs/reference/tasklist-api/objects/task.mdx
docs/reference/tasklist-api/objects/user.mdx
docs/reference/tasklist-api/objects/variable.mdx
docs/reference/tasklist-api/queries/current-user.mdx
docs/reference/tasklist-api/queries/form.mdx
docs/reference/tasklist-api/queries/task.mdx
docs/reference/tasklist-api/queries/tasks.mdx
docs/reference/tasklist-api/scalars/int.mdx
docs/reference/tasklist-api/sidebar-schema.js
docusaurus.config.js

* Update GraphQL API
* Update migration docs
* Update SSO docs
* Add TLS note
Sidenote: Add documentation to create the documentation: https://github.com/camunda-cloud/tasklist/wiki/Generate-GraphQL-API-docs because it is a bit tricky currently

Operate Tasklist update documentation (#180)

---

docs/product-manuals/zeebe/deployment-guide/operations/health.md

Add documentation for the new endpoint for startup probe added by PR https://github.com/camunda-cloud/zeebe/pull/6852

Add startup probe

---

docusaurus.config.js
src/css/custom.css
src/theme/Footer/gtag.js
src/theme/Footer/index.js
src/theme/Footer/styles.module.css

replaces https://github.com/camunda-cloud/camunda-cloud-documentation/pull/229

feat(core): add osano and google analytics

---

docs/guides/setting-up-development-project.md

Updates **Setting up your first development** project page

Fix Kotling typo in documentation

---

docs/product-manuals/operate/deployment/configuration.md
docs/product-manuals/operate/deployment/install-and-start.md
docs/product-manuals/operate/index.md
docs/product-manuals/operate/userguide/operate-feedback-and-questions.md
docs/product-manuals/tasklist/deployment/api-client.md
docs/product-manuals/tasklist/deployment/authentication.md
docs/product-manuals/tasklist/deployment/configuration.md
docs/product-manuals/tasklist/deployment/install-and-start.md
docs/product-manuals/tasklist/introduction.md
docs/reference/tasklist-api/generated.md
docs/reference/tasklist-api/queries/variables.mdx
docs/reference/tasklist-api/sidebar-schema.js
yarn.lock

- Update configuration docs
- Update GraphQL API docs
- Change contact point
Closes #225 and in projects: https://jira.camunda.com/browse/OPE-1278 , https://github.com/camunda-cloud/tasklist/issues/856

Update Operate and Tasklist config documentation

---

docs/product-manuals/zeebe/open-source/community-contributions.md

Added links and references to the Camunda Community Hub where applicable

Update links + add references to Community Hub

---

docs/product-manuals/clients/other-clients/c-sharp.md

Added link to this repository in the Camunda Community Hub

Added new link to community hub

---

docs/product-manuals/clients/build-your-own-client.md
docs/product-manuals/clients/cli-client/get-started.md
docs/product-manuals/clients/cli-client/index.md
docs/product-manuals/clients/java-client-examples/cluster-topology-request.md
docs/product-manuals/clients/java-client-examples/data-pojo.md
docs/product-manuals/clients/java-client-examples/index.md
docs/product-manuals/clients/java-client-examples/job-worker-open.md
docs/product-manuals/clients/java-client-examples/process-deploy.md
docs/product-manuals/clients/java-client-examples/process-instance-create-nonblocking.md
docs/product-manuals/clients/java-client-examples/process-instance-create-with-result.md
docs/product-manuals/clients/java-client-examples/process-instance-create.md
docs/product-manuals/clients/java-client/job-worker.md
docs/product-manuals/zeebe/deployment-guide/configuration/configuration.md
docs/product-manuals/zeebe/deployment-guide/getting-started/next-steps-resources.md
docs/product-manuals/zeebe/deployment-guide/getting-started/tutorial-setup.md
docs/product-manuals/zeebe/deployment-guide/kubernetes/helm/prerequisites.md
docs/product-manuals/zeebe/deployment-guide/local/install.md
docs/product-manuals/zeebe/deployment-guide/local/quickstart.md
docs/product-manuals/zeebe/deployment-guide/operations/metrics.md
docs/product-manuals/zeebe/deployment-guide/security/authorization.md
docs/product-manuals/zeebe/open-source/community-contributions.md
docs/product-manuals/zeebe/open-source/exporters.md
docs/product-manuals/zeebe/open-source/get-help-get-involved.md
docs/product-manuals/zeebe/technical-concepts/architecture.md
docs/product-manuals/zeebe/technical-concepts/exporters.md
docs/product-manuals/zeebe/technical-concepts/protocols.md
docs/product-manuals/zeebe/zeebe-overview.md
sidebars.js

docs(clients/java): Dead links in docs (#258)

---

docs/product-manuals/best-practices.md
docs/product-manuals/zeebe/technical-concepts/index.md
sidebars.js

Closes 257 for 2/3 blogs (last blog has not been written).

docs(product-manuals): Include Best Practices Blog Posts links (#257)

---

docusaurus.config.js

change Slack URL

---

docs/reference/bpmn-processes/error-events/error-events.md
docs/reference/grpc.md

Describes the changes introduced in https://github.com/camunda-cloud/zeebe/pull/7292, targeted for `Zeebe 1.1`. 
This pull request should **NOT** be merged into master, but into a special branch for Camunda Cloud version 1.1 documentation. However, this branch does not yet exist.
closes #281 
closes https://github.com/camunda-cloud/zeebe/issues/7307

Describe uncaught error incident handling

---

docs/reference/bpmn-processes/bpmn-coverage.md

Based on #300
* mark send tasks, business rule tasks, and script tasks as implemented

Update BPMN coverage page

---

docs/product-manuals/zeebe/zeebe-overview.md

Comment from Kanish today that there were a number of questions around enterprise support for Zeebe, hopefully this will clear some of that up!

Clarify Zeebe enterprise support

---

docusaurus.config.js

Update blog link to Camunda cloud tag

---

docs/product-manuals/zeebe/technical-concepts/exporters.md

Add note for exporters in SaaS

---

docs/guides/update-guide/introduction.md

Closes #313 
FYI @menski I changed the order so the latest update guide is at the top. Does that work for you?

Add release notes and release blog, order latest first

---

docs/guides/introduction-to-camunda-cloud.md
docs/product-manuals/concepts/what-is-camunda-cloud.md
docusaurus.config.js
src/css/custom.css
src/pages/index.js

* add links to console
* make main page logos clickable (testing functionality for @falko)
* cleanup footer, bring console link to top, create Legal section

Activation rate link adds

---

docs/product-manuals/best-practices.md

updated branch name and launched new PR

Bestpractices-addlinks-editorialreview

---

docs/product-manuals/zeebe/technical-concepts/partitions.md

**Description**
Adds a short explanation on how to configure the new experimental fixed partitioning scheme.

Explain fixed partitioning

---

docs/guides/getting-started/bpmn/gettingstarted_quickstart.bpmn
docs/guides/getting-started/bpmn/gettingstarted_quickstart_advanced.bpmn
versioned_docs/version-1.0/guides/getting-started/bpmn/gettingstarted_quickstart.bpmn

add executionPlatform to quickstart.bpmn

---

docs/guides/message-correlation.md

Update: Fix Link

---

docs/self-managed/operate-deployment/configuration.md

chore(doc): update the default Operate configuration

---

docs/self-managed/tasklist-deployment/authentication.md
docs/self-managed/tasklist-deployment/configuration.md

fix(doc): update the default Tasklist configuration

---

docs/guides/getting-started-orchestrate-microservices.md

I find it more convenient to repeat the download at the moment when I really need it. But I could also understand if we don't want to repeat that information all over the place. Take it as a suggestion and feel free to close.

Added hint where to download things

---

docs/self-managed/zeebe-deployment/kubernetes/helm/accessing-operate.md
docs/self-managed/zeebe-deployment/kubernetes/helm/installing-helm.md

Updated the files: 
* installing-helm.md 
* accessing-operate.md 
Fixed some commands which were wrong or outdated. 
Additionally I linked the newer "kind-values.yaml"/ zeebe-dev-profile from the actual zeebe-helm-profiles repository.

Fixed docu for deploying Zeebe on Kubernetes

---

docs/self-managed/zeebe-deployment/kubernetes/index.md

helm.camunda.io  repplaced  zeebe-io /zeebe-kubernetes

Update readme to point to helm.camunda.io

---

docs/components/tasklist/faq.md
sidebars.js

Closes camunda-cloud/tasklist#1410

Add FAQ section for Tasklist

---

docs/reference/bpmn-processes/timer-events/timer-events.md

Minor improvements to the explanation of Time Duration, and the correction of a small typo at the Timers section, which could mislead users (which actually happened to me hehehe)

Update Time Duration section of timer-events.md

---

docs/components/concepts/expressions.md

Minor typo at the Temporal expressions section.

Update Temporal expressions at expressions.md

---

docs/apis-clients/grpc.md

I found a command name that is not part of the command list. @Zelldon told me the right name.

update name of renamed command

---

docs/self-managed/troubleshooting/log-levels.md
sidebars.js

Closes #465.
Any further thoughts here?

Create troubleshooting section CCSM with log levels

---

docs/guides/message-correlation.md
versioned_docs/version-1.1/guides/message-correlation.md

chore(guides): add note that npm version 6 is needed

---

docs/guides/update-guide/120-to-130.md
sidebars.js

chore(update-guide): describe Tasklist and Operate update limitations

---

docs/self-managed/zeebe-deployment/operations/index.md
docs/self-managed/zeebe-deployment/operations/rebalancing.md
sidebars.js

closes https://github.com/camunda-cloud/zeebe/issues/8340

Document Zeebe's Rebalancing API

---

docs/self-managed/optimize-deployment/migration-update/3.6-to-3.7.md
docs/self-managed/optimize-deployment/migration-update/instructions.md
docs/self-managed/optimize-deployment/rest-api/dashboard/dashboard-api.md
docs/self-managed/optimize-deployment/rest-api/dashboard/delete-dashboard.md
docs/self-managed/optimize-deployment/rest-api/report/delete-report.md
docs/self-managed/optimize-deployment/rest-api/report/get-data-export.md
docs/self-managed/optimize-deployment/rest-api/report/report-api.md
docs/self-managed/optimize-deployment/setup/configuration.md
sidebars.js

PRs from Optimize on docs.camunda.org & Dashboard API docs

299, 300, 301 and dashboard API docs

---

docs/guides/update-guide/120-to-130.md
sidebars.js

… (#523)
closes #522
(cherry picked from commit e65593935d312c72f2ced0590b4b7720f0767dee)

#522 Operate tasklist update 1.3.0

---

docs/self-managed/operate-deployment/usage-metrics.md
docs/self-managed/tasklist-deployment/usage-metrics.md
sidebars.js

Document usage metrics for Tasklist and Operate

#540 Tasklist and Operate usage metrics

---

docs/guides/update-guide/120-to-130.md

Warn users about a known issue in the Zeebe 1.3.0 docker image

Add warning for known issue in Zeebe 1.3.0

---

docs/components/optimize/userguide/decision-analysis/decision-report.md

docs(optimize): link typo

---

docs/components/optimize/what-is-optimize.md
docs/guides/improve-processes-with-optimize.md
sidebars.js
static/.htaccess
versioned_docs/version-1.2/guides/integrating-optimize.md

Integrating Optimize implies a heavy development/IT task
In reality, Camunda Cloud offers turnkey Optimize usage
We should emphasize what Optimize does, rather than have setup a goal into itself

Rename Optimize section

---

docs/components/modeler/cloud-modeler/save-and-deploy.md

Closes #577.
Somewhat hacky workaround 🤷‍♀️

docs(cloud-modeler): shorten sidebar title

---

docs/components/modeler/bpmn/multi-instance/multi-instance.md

This adds a description of how completionCondition can be defined for multi-instance.
closes  #508

Describe multi-instance completion condition

---

docs/components/concepts/expressions.md
docs/components/concepts/incidents.md
docs/components/concepts/job-workers.md
docs/components/concepts/process-instance-creation.md
docs/components/concepts/processes.md
docs/components/concepts/variables.md

As part of [Trello card/OKR](https://trello.com/c/oA6Leofc/1328-prepare-migrated-documentation-for-camunda-8) for this quarter, I've reviewed all Concepts documentation to ensure uniform styling across all pre-existing AND migrated Camunda Cloud documentation. Particular adjustments include incorporating admonitions on note references, general stylistic updates, next steps, descriptions, and potential document restructures (though this was not applicable within current Concepts documentation.)

style(formatting): technical review of existing Concepts documentation

---

docs/components/modeler/bpmn/call-activities/call-activities.md

Originates from PR #485 (Fixes modeler properties panel)

Added variable propagation in xml

---

docs/components/modeler/bpmn/script-tasks/script-tasks.md

Fixed variable mapping link & added zeebe script worker community extension.

Modified script-task Docu

---

docs/components/modeler/bpmn/business-rule-tasks/business-rule-tasks.md
docs/components/modeler/bpmn/service-tasks/service-tasks.md

Linked variable mappings

---

.github/workflows/build-docs.yaml
.github/workflows/linkcheck.yaml
product-links.txt
static/.htaccess

Check product links on build and link check

---

docs/components/cloud-console/introduction.md
docs/components/cloud-console/manage-clusters/create-cluster-include.md
docs/components/cloud-console/manage-clusters/create-cluster.md
docs/components/cloud-console/manage-clusters/delete-cluster.md
docs/components/cloud-console/manage-clusters/manage-alerts.md
docs/components/cloud-console/manage-clusters/manage-api-clients.md
docs/components/cloud-console/manage-clusters/rename-cluster.md
docs/components/cloud-console/manage-organization/manage-users.md
docs/components/cloud-console/manage-organization/organization-settings.md
docs/components/cloud-console/manage-organization/update-billing-reservations.md
docs/components/cloud-console/manage-organization/usage-history.md
docs/components/cloud-console/manage-organization/view-organization-activity.md
docs/components/cloud-console/manage-plan/available-plans.md
docs/components/cloud-console/manage-plan/upgrade-to-professional-plan.md
docs/components/cloud-console/troubleshooting/common-pitfalls.md
docs/components/cloud-console/troubleshooting/feedback-and-support.md

As part of Trello card/OKR for this quarter, I've reviewed all Cloud Console documentation within Components to ensure uniform styling across all pre-existing AND migrated Camunda Cloud documentation. Particular adjustments include incorporating admonitions on note references, general stylistic updates, next steps, descriptions, and potential document restructures (though this was not applicable within current Concepts documentation.)

style(formatting): technical review of existing Cloud Console docs

---

docs/self-managed/operate-deployment/configuration.md

* Add TLS config parameter
* Update example with TLS config parameter
Closes #606

docs(operate/tasklist): add TLS config

---

docs/components/best-practices/architecture/deciding-about-your-stack-c7.md
docs/components/cloud-console/troubleshooting/common-pitfalls.md
docs/components/concepts/processes.md
docs/components/zeebe/technical-concepts/exporters.md
docs/components/zeebe/zeebe-overview.md
docs/self-managed/optimize-deployment/setup.md
docs/self-managed/tasklist-deployment/configuration.md
versioned_docs/version-1.1/components/clients/java-client/index.md

Removing all lingering inline comments.

resolving lingering comments in documentation

---

docs/guides/getting-started-orchestrate-microservices.md
docs/guides/getting-started/deploy-your-process-and-start-process-instance.md
docs/guides/getting-started/implement-service-task.md
docs/guides/getting-started/monitor-your-process-in-operate.md
docs/guides/setting-up-development-project.md

The Web Modeler includes the concept of "Projects" which introduces a few more steps to create a new BPMN diagram.
> 1. Navigate to the **Modeler** tab at the top of the page. This opens Web Modeler to your **Projects** page in a separate browser tab.
> 2. Create a new project by clicking the blue **New project** button. Give your project a descriptive name.
> 3. Click the blue **New** button and select **BPMN Diagram**. A modal will appear to select a template, click **+ Create blank**.
Modeler opens in a new tab so Console remains open in a background tab. From the Modeler tab, you cannot obviously get to your Clusters, but navigating to the tab with Console is a relatively similar experience to what was originally documented.
> 1. The main page for Camunda Cloud Console should be open …

Updates guides for Modeler

---

docs/guides/migrating-from-Camunda-Platform.md

Resolving 404 error with migration tooling link.

updating migration tooling link

---

docs/self-managed/optimize-deployment/rest-api/dashboard/get-dashboard-ids.md

Noticed a small typo in the dashboard ID API section.

fix(dashboardAPI): fix small typo in dashboard API docs

---

docs/components/modeler/bpmn/bpmn-primer.md
docs/components/modeler/desktop-modeler/install-the-modeler.md
docs/reference/dependencies.md
docs/reference/licenses.md

* This fixes  broken links to GitHub

chore(DesktopModeler): fix broken links to GitHub

---

docs/components/modeler/desktop-modeler/connect-to-camunda-cloud.md
docs/components/modeler/desktop-modeler/model-your-first-diagram.md
docs/components/modeler/desktop-modeler/start-instance.md

* This updates and clarifies the basic tutorial texts
* No content changes, just polishing and corrections

chore(desktopModeler): polish basic tutorial texts

---

docs/components/modeler/web-modeler/collaboration.md
docs/components/modeler/web-modeler/start-instance.md

Minor adjustments to button naming according to Web Modeler UI.

minor UI tweaks according to Web Modeler

---

docs/components/modeler/desktop-modeler/plugins/plugins.md

Closes https://github.com/camunda/camunda-modeler/issues/2782

feat: updated desktop modeler plugin documentation

---

docs/components/modeler/desktop-modeler/element-templates/about-templates.md
docs/components/modeler/desktop-modeler/plugins/plugins.md

* The element template and plugin API might have breaking changes in the
future
* Since we in the past (at least for C7) guranteed stability, we should
clearly highlight, that breaking changes might occur.
* closes bpmn-io/internal-docs#491

chore(desktopModeler): add API stability claimer

---

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md

related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/584

feat(element-templates): add Feel type

---

src/theme/Footer/index.js

part of https://github.com/camunda-cloud/changes/issues/96
~do not merge until green lights from me~
coordinated push2prod scheduled for tomorrow (2022-03-23) 8:00 UTC

use mixpanel-europe

---

docs/reference/supported-environments.md
docs/self-managed/optimize-deployment/migration-update/2.3-to-2.4.md
docs/self-managed/optimize-deployment/migration-update/2.6-to-2.7.md
docs/self-managed/optimize-deployment/migration-update/2.7-to-3.0.md
docs/self-managed/optimize-deployment/migration-update/3.0-to-3.1.md
docs/self-managed/optimize-deployment/migration-update/3.1-to-3.2.md
docs/self-managed/optimize-deployment/migration-update/3.2-to-3.3.md
docs/self-managed/optimize-deployment/migration-update/3.4-to-3.5.md
docs/self-managed/optimize-deployment/migration-update/3.5-to-3.6.md
docs/self-managed/optimize-deployment/setup/installation.md
static/.htaccess

Based on internal docu and discussion.
This is a draft since we are waiting for details from Optimize.
Closes #561.

docs(supported-environments): simplify updates

---

docusaurus.config.js
src/pages/meta.md

Add meta page

---

docs/apis-clients/community-clients/index.md
docs/apis-clients/community-clients/micronaut.md
docs/guides/migrating-from-Camunda-Platform.md
docs/self-managed/optimize-deployment/rest-api/external-variable-ingestion.md
src/theme/Footer/index.js

I'm the lead developer of the Micronaut Zeebe Integration Project: https://github.com/camunda-community-hub/micronaut-zeebe-client
Please merge this PR to add the Micronaut Integration to list of community clients.

Add Micronaut Zeebe Client

---

src/css/custom.css

Adds a transition to the transformations to reduce the jumping and flickering

chore: ease transform transitions

---

docs/components/best-practices/architecture/deciding-about-your-stack-c7.md
docs/self-managed/optimize-deployment/plugins/plugin-system.md

Change to the new artifactory domain

---

docs/apis-clients/operate-api/index.md
docs/apis-clients/public-api.md
sidebars.js

* Add Operate API documentation
* Introduction, examples, and reference
* Add link for Operate API in  sidebar and public-api page
Closes #538, #513

Operate Public API documentation

---

docs/components/modeler/desktop-modeler/flags/flags.md

* heading did not match the actual flag

chore(desktopModeler/flags): correct heading

---

docs/self-managed/zeebe-deployment/kubernetes/helm/accessing-operate-tasklist.md
docs/self-managed/zeebe-deployment/kubernetes/helm/installing-helm.md
docs/self-managed/zeebe-deployment/kubernetes/index.md

docs(chore): cleanup merge conflicts

---

docs/components/cloud-console/manage-organization/manage-users.md

replaces https://github.com/camunda-cloud/camunda-cloud-documentation/pull/452

451 new roles and permissions

---

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md

related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/572

feat(element-templates): add `elementType` binding

---

docs/components/best-practices/architecture/deciding-about-your-stack-c7.md
docs/components/best-practices/architecture/deciding-about-your-stack.md
docs/components/best-practices/architecture/sizing-your-environment-c7.md
docs/components/best-practices/architecture/sizing-your-environment.md
docs/components/best-practices/development/connecting-the-workflow-engine-with-your-world.md
docs/components/best-practices/development/dealing-with-problems-and-exceptions.md
docs/components/best-practices/development/handling-data-in-processes.md
docs/components/best-practices/development/invoking-services-from-the-process-c7.md
docs/components/best-practices/development/routing-events-to-processes.md
docs/components/best-practices/development/testing-process-definitions.md
docs/components/best-practices/development/understanding-transaction-handling-c7.md
docs/components/best-practices/development/writing-good-workers.md
docs/components/best-practices/management/doing-a-proper-poc.md
docs/components/best-practices/modeling/building-flexibility-into-bpmn-models.md
docs/components/best-practices/modeling/creating-readable-process-models.md
docs/components/best-practices/modeling/modeling-with-situation-patterns.md
docs/components/best-practices/operations/operating-camunda-c7.md
docs/components/best-practices/operations/performance-tuning-camunda-c7.md
docs/components/best-practices/operations/reporting-about-processes.md
docs/components/best-practices/operations/securing-camunda-c7.md
docs/components/best-practices/operations/versioning-process-definitions.md
docs/components/best-practices/overview.md

Rename Camunda Cloud to Camunda Platform 8.
@berndruecker @christinaausley for DMN and connectors, we may want to clarify C7 vs. C8. I did **not** include this in this PR yet.

docs(best-practices): renaming

---

docs/self-managed/operate-deployment/usage-metrics.md

* document decision instance usage metric

Operate: decision usage metric

---

docs/components/zeebe/open-source/community-contributions.md
docs/components/zeebe/open-source/get-help-get-involved.md
docs/components/zeebe/technical-concepts/architecture.md
docs/components/zeebe/technical-concepts/exporters.md
docs/components/zeebe/zeebe-overview.md

Renaming zeebe c8

---

docs/components/tasklist/introduction.md
docs/components/tasklist/userguide/api/tutorial.md

docs(tasklist): renaming

---

docs/self-managed/concepts/access-control/users.md
sidebars.js

This PR introduces the final page for the initial Identity documentation, users.

feat: implement user concept page

---

docs/components/best-practices/development/handling-data-in-processes.md
docs/components/concepts/variables.md

https://github.com/camunda-cloud/camunda-cloud-documentation/issues/396

Documented max payload size

---

docs/self-managed/optimize-deployment/setup/configuration.md

feat(customer-onboarding-data): Include the data to the demo disribution

---

docs/components/modeler/desktop-modeler/flags/flags.md

Closes https://github.com/camunda/camunda-modeler/issues/2767

fix: updated flags docs with `disable-form`

---

docs/reference/dependencies.md
docs/reference/licenses.md
docs/reference/overview.md
docs/reference/status.md

Renaming Camunda Cloud to Camunda Platform 8.

docs(reference): renaming c8

---

src/pages/contact.md
src/pages/index.js
src/pages/meta.md

docs(pages): renaming c8

---

docs/reference/supported-environments.md

Adjusting environment requirement as Optimize requires at least 7.10.

Docs optimize environment fix

---

sidebars.js
versioned_docs/version-0.26/components/clients/other-clients/micronaut.md
versioned_docs/version-1.0/components/clients/other-clients/index.md
versioned_docs/version-1.0/components/clients/other-clients/micronaut.md
versioned_docs/version-1.1/components/clients/other-clients/index.md
versioned_docs/version-1.1/components/clients/other-clients/micronaut.md
versioned_docs/version-1.2/apis-clients/community-clients/index.md
versioned_docs/version-1.2/apis-clients/community-clients/micronaut.md
versioned_docs/version-1.3/apis-clients/community-clients/index.md
versioned_docs/version-1.3/apis-clients/community-clients/micronaut.md
versioned_sidebars/version-0.26-sidebars.json
versioned_sidebars/version-1.0-sidebars.json
versioned_sidebars/version-1.1-sidebars.json
versioned_sidebars/version-1.2-sidebars.json
versioned_sidebars/version-1.3-sidebars.json

* Add Micronaut to previous versions
* Add Micronaut to sidebar (current and previous versions)
* Reorder current version client overview page list & sidebar
@tobiasschaefer

docs(micronaut): add micronaut, including prev verisons

---

docs/self-managed/optimize-deployment/install-and-start.md

- see https://confluence.camunda.com/pages/viewpage.action?spaceKey=HAN&title=Product+Names

chore(optimize) align install guide section naming with guidelines

---

docs/components/best-practices/architecture/deciding-about-your-stack-c7.md
docs/components/best-practices/development/dealing-with-problems-and-exceptions.md
docs/components/modeler/bpmn/bpmn-primer.md
docs/guides/update-guide/introduction.md
docs/self-managed/zeebe-deployment/configuration/configuration.md

SiteImprove identified broken links on `latest`/`master`

Broken links on latest

---

docs/reference/supported-environments.md

add java version column

---

docs/reference/release-policy.md

Updating release policy page to point to new https://camunda.com/release-policy/

docs(release-policy): split release policy

---

docs/components/optimize/userguide/additional-features/alerts.md

Clarifying requirements for email configuration between C7/C8, and overall cleanup of Alerts doc.

revising alerts documentation

---

src/pages/index.js

Removing FEEL note from Reference icon caption.

adjusting reference icon caption to remove FEEL

---

docusaurus.config.js
src/pages/meta.md

A more logical footer rework and restructure with updated user resources.

initial footer restructure

---

docs/components/best-practices/development/dealing-with-problems-and-exceptions.md
docs/components/best-practices/development/understanding-transaction-handling-c7.md

Context https://jira.camunda.com/browse/SUPPORT-13685

Marked C7/C8 sections clearer (SUPPORT-13685)

---

.prettierignore
src/css/custom.css
src/pages/contact.md
src/pages/index.js
src/pages/meta.md
src/theme/DocVersionSuggestions/index.js
src/theme/Footer/gtag.js

Partially addresses #883. 
Enables prettier formatting for the ./src folder, and formats the files in that folder.

chore(format): enable formatting for /src, and format /src.

---

docs/apis-clients/overview.md
docs/reference/licenses.md

Per [this Slack thread](https://camunda.slack.com/archives/C026U8GBNSW/p1652683850174159), we needed to clarify the usage of the REST APIs and web apps according to our licensing.

clarifying usage of apis and web apps

---

docs/self-managed/overview.md

* I found this page via google
* Reading the intro sentence <The alternative way to use Camunda Platform 8 ...> read super strange when this is the first page to start with. I immediately asked myself "alternative to what"?
* I propose this as polishing

chore(self-managed): polish introduction

---

docs/self-managed/overview.md

* This will ensure easy discoverability and allow users to understand more, if they would like to

chore(self-managed): cross-link desktop modeler

---

docs/apis-clients/overview.md

Based on feedback from @superbeagle in [Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1654193682011569) thread.

linking to operate and tasklist usage metric APIs documentation

---

docs/components/zeebe/technical-concepts/internal-processing.md

This allows people to relate their problem to this concept better

Added "RESOURCE EXCHAUSED" exception name

---

docs/guides/automating-a-process-using-bpmn.md
docs/guides/utilizing-forms.md

According to [this Slack thread](https://camunda.slack.com/archives/C026U8GBNSW/p1653386762863739), clarifying Camunda Platform 7 and Camunda Platform 8 references (particularly deployment).

clarifying deployment in utilizing forms and adjusting UI for BPMN guide

---

docs/apis-clients/java-client-examples/data-pojo.md

adjust broken POJO GH link

---

CONTRIBUTING.MD
docs/apis-clients/overview.md
docs/components/best-practices/architecture/deciding-about-your-stack-c7.md
docs/components/best-practices/architecture/deciding-about-your-stack.md
docs/components/best-practices/development/invoking-services-from-the-process-c7.md
docs/components/concepts/processes.md
docs/components/modeler/forms/camunda-forms-reference.md
docs/components/zeebe/open-source/community-contributions.md
docs/components/zeebe/technical-concepts/protocols.md
howtos/configuration.md
howtos/documentation-workflows.MD

Changing open-source to open source.

changing open-source to open source

---

docs/guides/setup-client-connection-credentials.md

Based on [feedback for Cloud getting started](https://trello.com/c/94qVlUjK/1766-feedback-on-cloud-getting-started).

correcting text according to UI

---

docs/self-managed/optimize-deployment/version-policy.md
sidebars.js

chore(optimize): version policy

---

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md

To be merged after properties panel is released and included in the Modeler

chore(element-templates): add conditional template properties docs

---

docs/components/console/manage-clusters/manage-secrets.md
docs/components/modeler/web-modeler/connectors/available-connectors/rest.md

Clarify secrets in expressions and request header

---

docs/components/concepts/what-is-camunda-platform-8.md
docs/components/operate/userguide/basic-operate-navigation.md
docs/guides/introduction-to-camunda-cloud.md
docs/guides/introduction-to-camunda-platform-8.md
docusaurus.config.js
sidebars.js

According to https://github.com/camunda/camunda-platform-docs/issues/1037, adjusting the order of the components and adding details on the guides section regarding the getting started steps and the next steps.

fix gsg structure overview

---

docs/components/optimize/userguide/additional-features/alerts.md

Resolves https://github.com/camunda/camunda-platform-docs/issues/1054#issuecomment-1183409759

chore(optimize): update email config instructions

---

docs/guides/model-your-first-process.md

The screenshot belongs to the modeler step.

Move screenshot to correct step

---

docs/guides/model-your-first-process.md

Providing link to roles and permissions when modeling your first process and adding users.

Add link to all roles and permissions

---

product-links.txt

@pepopowitz your review is mostly for awareness and to merge when you'd like so it doesn't interrupt your link check testing. Or maybe you want to interrupt it...? 🤷‍♀️

chore(product-links): update prop panel links

---

docs/apis-clients/optimize-api/report/delete-report.md
docs/apis-clients/optimize-api/report/get-data-export.md
docs/components/optimize/userguide/collections-dashboards-reports.md
docs/components/optimize/userguide/combined-process-reports.md
docs/self-managed/optimize-deployment/migration-update/2.2-to-2.3.md
sidebars.js
static/.htaccess

Related to https://github.com/camunda/camunda-platform-docs/issues/692

decision report

---

docs/components/modeler/bpmn/timer-events/timer-events.md

Add timer cycle with start time docs.
Let's try this again @korthout 😄

Add timer cycle with start time (#1084)

---

docs/components/modeler/bpmn/timer-events/timer-events.md

Fixes the timezone description by removing the offset from the example

fix timezone description

---

docs/guides/automating-a-process-using-bpmn.md
docs/guides/create-decision-tables-using-dmn.md
docs/guides/getting-started-orchestrate-human-tasks.md
docs/guides/getting-started-orchestrate-microservices.md
docs/guides/message-correlation.md
docs/guides/setup-client-connection-credentials.md

Related to https://github.com/camunda/camunda-platform-docs/pull/1093

adjust numerical lists across guides

---

docs/self-managed/platform-deployment/kubernetes-helm.md
docs/self-managed/platform-deployment/kubernetes.md
docs/self-managed/platform-deployment/openshift-helm.md
docs/self-managed/platform-deployment/openshift.md
docs/self-managed/platform-deployment/platform-8-deployment.md

Technical review of OpenShift doc references following merge of https://github.com/camunda/camunda-platform-docs/pull/1125.

technical review of openshift docs

---

docs/apis-clients/working-with-apis-clients.md
docs/components/zeebe/open-source/community-contributions.md
versioned_docs/version-8.0/apis-clients/working-with-apis-clients.md
versioned_docs/version-8.0/components/zeebe/open-source/community-contributions.md

Updates to pages referencing community extensions or the Camunda Community Hub.

{docs}(content): {Community Extensions updates}

---

.github/workflows/sync-board.yaml

collab with @akeller 
Addresses #1154 
Attempts to configure a workflow that adds labeled PRs to the project board!

feat: attempt to add labeled pr to project

---

howtos/documentation-guidelines.md

docs(chore): update reviewers

---

docs/guides/introduction-to-camunda-platform-8.md
docusaurus.config.js
sidebars.js
static/.htaccess
versioned_docs/version-0.25/guides/introduction-to-camunda-cloud.md
versioned_docs/version-0.26/guides/introduction-to-camunda-cloud.md
versioned_docs/version-1.0/guides/introduction-to-camunda-cloud.md
versioned_docs/version-1.1/guides/introduction-to-camunda-cloud.md
versioned_docs/version-1.2/guides/introduction-to-camunda-cloud.md
versioned_docs/version-1.3/guides/introduction-to-camunda-cloud.md
versioned_docs/version-8.0/guides/introduction-to-camunda-platform-8.md
versioned_sidebars/version-0.25-sidebars.json
versioned_sidebars/version-0.26-sidebars.json
versioned_sidebars/version-1.0-sidebars.json
versioned_sidebars/version-1.1-sidebars.json
versioned_sidebars/version-1.2-sidebars.json
versioned_sidebars/version-1.3-sidebars.json
versioned_sidebars/version-8.0-sidebars.json

Updating all "Introduction to Camunda" IDs to `introduction-to-camunda`.
Resolves https://github.com/camunda/camunda-platform-docs/issues/1111#

update introduction to camunda ids

---

docs/apis-clients/community-clients/python.md

Adding the pyzeebe client to list of community clients

---

docs/self-managed/identity/user-guide/adding-a-permission.md
docs/self-managed/identity/user-guide/adding-a-role.md
docs/self-managed/identity/user-guide/adding-an-api.md
docs/self-managed/identity/user-guide/adding-an-application.md
docs/self-managed/identity/user-guide/assigning-a-permission-to-a-role.md
docs/self-managed/identity/user-guide/assigning-a-permission-to-an-application.md
docs/self-managed/identity/user-guide/assigning-a-role-to-a-user.md
docs/self-managed/identity/user-guide/managing-user-access.md
sidebars.js

Resolves https://github.com/camunda-cloud/identity/issues/894

feat: Identity read/write access

---

docs/components/integration-framework/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.0/components/integration-framework/connectors/custom-built-connectors/connector-sdk.md

feat(components): describe connnector SDK in-depth

---

docs/self-managed/platform-deployment/amazon-eks.md
docs/self-managed/platform-deployment/kubernetes-helm.md
docs/self-managed/platform-deployment/kubernetes.md

Those changes are related to camunda/distribution/issues/6.
With adding more supported platforms to C8SM we need to make sure that the docs are more intuitive and easy to go through.
No.
As soon as possible.

docs(self-managed): enhance reading flow

---

docs/apis-clients/operate-api/index.md
versioned_docs/version-8.0/apis-clients/operate-api/index.md

* Add section for Swagger UI link

docs(operate): add swagger link and description

---

versioned_docs/version-8.0/guides/getting-started-orchestrate-human-tasks.md

I found my condition wasn't working due to not explicitly setting key as the value of Meal
My conditional XOR gate was not working in the tutorial. I found that it was due to me not adding Meal as the key value. I dont think the tutorial included this.
No
Entirely up to you
- [Yes ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [Yes ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [No] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead …

Add Meal as a value for key to form implementation

---

docs/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.0/guides/getting-started-orchestrate-microservices.md

Bug fix - closes #1242 
No
Immediately.

move import statement to top of file

---

docs/components/best-practices/development/testing-process-definitions.md
versioned_docs/version-8.0/components/best-practices/development/testing-process-definitions.md

Fixing according to discussion in https://camunda.slack.com/archives/C0PPM4F46/p1662626827738149

Fixed wording around .NET testing

---

docs/components/modeler/desktop-modeler/element-templates/using-templates.md

Revisions for merged https://github.com/camunda/camunda-platform-docs/pull/1252/files.

style(formatting): technical review using templates

---

versioned_docs/version-8.0/components/best-practices/development/testing-process-definitions.md

See https://docs.camunda.io/docs/components/best-practices/modeling/naming-technically-relevant-ids/

Adjusted task ids according to our own best practices

---

docs/guides/getting-started-orchestrate-api-endpoints.md
docs/guides/getting-started-orchestrate-human-tasks.md
docs/guides/getting-started-orchestrate-microservices.md

Corrects admonition formatting in the use-case GSGs.
No.
This is a bug - ASAP.

chore(guides): fix admonition whitespace

---

docs/components/integration-framework/connectors/out-of-the-box-connectors/aws-lambda.md

Reword OOTB AWS Lambda Connector section
No
This change is for `Next`

fix(ootb connectors): re-word section for AWS Lambda

---

docs/apis-clients/community-clients/c-sharp.md
docs/apis-clients/community-clients/javascript.md
docs/apis-clients/community-clients/micronaut.md
docs/apis-clients/community-clients/python.md
docs/apis-clients/community-clients/ruby.md
docs/apis-clients/community-clients/rust.md

Alongside https://github.com/camunda/camunda-platform-docs/issues/1178, updating community clients with relevant materials.

update community clients

---

docs/guides/getting-started-orchestrate-api-endpoints.md
docs/guides/getting-started-orchestrate-human-tasks.md
docs/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.0/guides/getting-started-orchestrate-api-endpoints.md
versioned_docs/version-8.0/guides/getting-started-orchestrate-human-tasks.md
versioned_docs/version-8.0/guides/getting-started-orchestrate-microservices.md

Reverting the booking links for USS-reps in the docu as created by experiment https://github.com/camunda/product-hub/issues/375. 
no
As soon as possible but no rush!

Revert experiment #375

---

docs/self-managed/optimize-deployment/configuration/telemetry.md
versioned_docs/version-1.3/self-managed/optimize-deployment/setup/telemetry.md
versioned_docs/version-8.0/self-managed/optimize-deployment/configuration/telemetry.md

Correct broken telemetry tables.

fix broken telemetry tables

---

docs/components/modeler/forms/camunda-forms-reference.md
docs/components/tasklist/userguide/using-tasklist.md
docs/guides/migrating-from-camunda-platform-7.md
docs/guides/utilizing-forms.md
docs/self-managed/about-self-managed.md

Alongside https://github.com/camunda/camunda-platform-docs/issues/1185, ensure we've linked to Camunda Forms where appropriate. This is also supported by changes made in https://github.com/camunda/camunda-platform-docs/pull/1153/files.

clean up forms reference

---

docusaurus.config.js

Small fixes to, hopefully, positively impact SEO.
No.
Anytime, but changes may not be apparently until they are live AND crawled.

chore(docusaurus.config.js): cleanup, update main page

---

docs/apis-clients/grpc.md

Extend the gRPC API documentation for the new process instance modification API.
closes #1120 
No.
With Camunda Platform version `8.1.0`.

Add new gRPC API for process instance modification

---

howtos/documentation-guidelines.md
howtos/markdown-and-mdx-features.md
howtos/versioning.md

Part of #1116 
Updates our howto documentation based on multi-instance documentation. 
Does not include updates to the release procedure, because I'm not sure what changes are included there yet 😅

feat(docs): describe multi-instance docs in howto

---

docs/reference/dependencies.md
versioned_docs/version-8.0/reference/dependencies.md

This adds the third-party dependencies of the Connectors to the dependencies overview.
n/a
When the Connector repositories are publicly accessible. We will ping you manually.

feat: add dependencies for Connectors

---

docs/components/integration-framework/connectors/out-of-the-box-connectors/available-connectors-overview.md
docs/components/integration-framework/connectors/out-of-the-box-connectors/aws-sqs.md
versioned_docs/version-8.0/components/integration-framework/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.0/components/integration-framework/connectors/out-of-the-box-connectors/aws-sqs.md

* as suggested by @akeller in #1325

fix(connector/SQS): small description improvements

---

docs/components/console/manage-organization/external-sso.md
sidebars.js

adding a brief intro on external sso support for `next`
closes https://github.com/camunda/camunda-platform-docs/issues/1133
nothing i am aware of 
next drumbeat release

external sso

---

docs/components/modeler/desktop-modeler/connect-to-camunda-cloud.md

This fixes numeration which I noticed included multiple 1's.
No.
No need to hurry, it's just a quick fix.

fix: correct numeration

---

docusaurus.config.js

Closes #826.
No, but we should inform them via internal ask-documentation thread.
Product release day (8.1)

docs(banner): sign up banner CTA

---

optimize/self-managed/optimize-deployment/migration-update/3.9-preview-to-3.9.md
optimize/self-managed/optimize-deployment/migration-update/translation-diffs/differences_localization_390_preview_1_390.diff

Updating the localization file for the 3.9 release
No
As soon as possible, since the changes reflect changes made in the 3.9 release

chor(localization): Update localization file for 3.9 release

---

docs/self-managed/backup-restore/backup-and-restore.md
versioned_docs/version-8.1/self-managed/backup-restore/backup-and-restore.md

TaskList -> Tasklist
No
Typo, so whenever.

chore(backup-restore): lowercase list

---

docs/guides/update-guide/800-to-810.md
versioned_docs/version-8.1/guides/update-guide/800-to-810.md

A critical issue has been found in Zeebe version 8.1.1. We should recommend users to skip this version and update to version 8.1.2 instead.
With platform release 8.1.2

Add note about critical Zeebe issue in version 8.1.1

---

versioned_docs/version-1.2/apis-clients/community-clients/micronaut.md
versioned_docs/version-1.3/apis-clients/community-clients/micronaut.md
versioned_docs/version-8.0/apis-clients/community-clients/micronaut.md

Related to https://github.com/camunda/camunda-platform-docs/pull/1383.

adjust feature rename for micronaut

---

docs/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/operations/management-api.md

Retroactive review on merged changes in https://github.com/camunda/camunda-platform-docs/pull/1344 as I was OOO during the original request for review.

(retro) zeebe management api review

---

docs/self-managed/identity/user-guide/configure-external-identity-provider.md
versioned_docs/version-8.0/self-managed/identity/user-guide/configure-external-identity-provider.md
versioned_docs/version-8.1/self-managed/identity/user-guide/configure-external-identity-provider.md

Related to changes made in https://github.com/camunda/camunda-platform-docs/pull/1352 -- note that **this is a retroactive review made on an already merged PR** as I was on FTO during the original request for review.

(retro) identity external provider review

---

docs/self-managed/backup-restore/backup-and-restore.md
versioned_docs/version-8.1/self-managed/backup-restore/backup-and-restore.md

Based on changes made in https://github.com/camunda/camunda-platform-docs/pull/1350. Note that this is a **retroactive review made on an already merged PR** given I was out on FTO at the time of the original request for review.

(retro) c8 backup and restore review

---

docs/self-managed/backup-restore/optimize-backup.md
optimize/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.9.0/self-managed/optimize-deployment/configuration/system-configuration.md
versioned_docs/version-8.1/self-managed/backup-restore/optimize-backup.md

Retroactive changes made to changes merged in https://github.com/camunda/camunda-platform-docs/pull/1348. Note this is retroactive as I was OOO during the time of the original request for review.

(retro) optimize backup docs review

---

docs/reference/early-access.md
versioned_docs/version-8.1/reference/early-access.md

Retroactive technical adjustments to changes merged with https://github.com/camunda/camunda-platform-docs/pull/1304 as I was OOO during the original request for review.

(retro) early access review

---

docs/components/console/manage-organization/external-sso.md
versioned_docs/version-8.1/components/console/manage-organization/external-sso.md

Retroactive review on merged changes in https://github.com/camunda/camunda-platform-docs/pull/1338 as I was OOO during the original request for review.

(retro) external sso review

---

hacks/generateOptimizeSidebars.md
howtos/documentation-guidelines.md
howtos/versioning.md

Partially addresses #1396.
Adds documentation describing the synchronization of sidebars, now that we have multiple instances.

docs: describe multi-instance sidebars

---

docs/components/modeler/bpmn/bpmn-coverage.md
versioned_docs/version-8.1/components/modeler/bpmn/bpmn-coverage.md

feat: support lane in c8

---

.husky/pre-commit
docs/components/console/manage-organization/manage-users.md
versioned_docs/version-8.1/components/console/manage-organization/manage-users.md

Releates https://github.com/camunda-cloud/console/issues/3524
Updates `Manage users` page, adds limitations / general users as a new section.
No
asap

docs(users): add limitations/general users

---

docs/components/operate/userguide/process-instance-modification.md
versioned_docs/version-8.1/components/operate/userguide/process-instance-modification.md

Retroactive technical review on changes merged in https://github.com/camunda/camunda-platform-docs/pull/1330 as I was OOO during the original request for review.

(retro) process instance modification review

---

optimize/self-managed/optimize-deployment/migration-update/3.9-preview-to-3.9.md
optimize_versioned_docs/version-3.9.0/self-managed/optimize-deployment/migration-update/3.9-preview-to-3.9.md

chor(localization): Update 3.9 upgrade guide

---

docs/self-managed/backup-restore/zeebe-backup-and-restore.md
docs/self-managed/zeebe-deployment/operations/backups.md
optimize_sidebars.js
optimize_versioned_sidebars/version-3.9.0-sidebars.json
sidebars.js
versioned_docs/version-8.1/self-managed/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/operations/backups.md
versioned_sidebars/version-8.1-sidebars.json

Retroactive technical review on merged changes made in https://github.com/camunda/camunda-platform-docs/pull/1342 as I was OOO during the original request for review.

(retro) zeebe backup restore review

---

docs/components/integration-framework/connectors/out-of-the-box-connectors/aws-lambda.md
docs/components/integration-framework/connectors/out-of-the-box-connectors/aws-sqs.md
docs/components/integration-framework/connectors/out-of-the-box-connectors/googledrive.md
versioned_docs/version-8.1/components/integration-framework/connectors/out-of-the-box-connectors/aws-lambda.md
versioned_docs/version-8.1/components/integration-framework/connectors/out-of-the-box-connectors/aws-sqs.md
versioned_docs/version-8.1/components/integration-framework/connectors/out-of-the-box-connectors/googledrive.md

Retroactive review on changes merged in https://github.com/camunda/camunda-platform-docs/pull/1325 as I was OOO during the original request for review.

(retro) connectors review

---

docs/components/console/manage-organization/organization-settings.md
versioned_docs/version-8.1/components/console/manage-organization/organization-settings.md

org owners can now change the name of their organization
relates to https://github.com/camunda-cloud/console/issues/3551
nope
asap

console: rename organization

---

docs/guides/improve-processes-with-optimize.md
optimize/components/userguide/collections-dashboards-reports.md
optimize/components/userguide/creating-dashboards.md
optimize/components/userguide/creating-reports.md
optimize/components/userguide/user-permissions.md
optimize/components/what-is-optimize.md
optimize_sidebars.js
optimize_versioned_docs/version-3.9.0/components/userguide/collections-dashboards-reports.md
optimize_versioned_docs/version-3.9.0/components/userguide/creating-dashboards.md
optimize_versioned_docs/version-3.9.0/components/userguide/creating-reports.md
optimize_versioned_docs/version-3.9.0/components/userguide/user-permissions.md
optimize_versioned_docs/version-3.9.0/components/what-is-optimize.md
optimize_versioned_sidebars/version-3.9.0-sidebars.json
sidebars.js
versioned_docs/version-8.0/guides/improve-processes-with-optimize.md
versioned_docs/version-8.1/guides/improve-processes-with-optimize.md

Related to https://github.com/camunda/camunda-platform-docs/issues/1184 -- I've added notes on collaboration and separated user permissions into its own document to ensure users are aware that Optimize is collaborative.

note optimize collaborative capabilities

---

docs/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/slack.md

Superseding #1364 
n/a
No specific date.

chore(connectors): update slack app instructions

---

docs/apis-clients/tasklist-api/mutations/claim-task.mdx
versioned_docs/version-8.0/apis-clients/tasklist-api/mutations/claim-task.mdx
versioned_docs/version-8.1/apis-clients/tasklist-api/mutations/claim-task.mdx

Add note to ClaimTask section clarifying the usage of JWT token
N/A

docs(Tasklist API): Add note on JWT token usage

---

docs/self-managed/backup-restore/optimize-backup.md

related to OPT-6532
Document Optimize's delete backup API.
No
For the upcoming release.

doc(optBackup): add optimize delete backup API docs

---

docs/components/connectors/introduction.md
docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
optimize_sidebars.js
optimize_versioned_sidebars/version-3.8.0-sidebars.json
optimize_versioned_sidebars/version-3.9.0-sidebars.json
sidebars.js
versioned_docs/version-8.0/components/connectors/introduction.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.1/components/connectors/introduction.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_sidebars/version-8.0-sidebars.json
versioned_sidebars/version-8.1-sidebars.json

Include the **Integration Framework** term in Connectors. See the [Slack channel](https://camunda.slack.com/archives/C048KDTNHRA) for details.
n/a
As soon as possible.

feat(connectors): include Integration Framework

---

docs/apis-clients/working-with-apis-clients.md
optimize_sidebars.js
sidebars.js
versioned_docs/version-8.1/apis-clients/working-with-apis-clients.md
versioned_sidebars/version-8.1-sidebars.json

Add missing sidebar navigation links for Quarkus client

chore(community-clients): add quarkus sidebar navigation

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks.md
sidebars.js

Documenting Microsoft AKS support in Camunda Platform 8 Self-Managed.
No.
No specific date, as soon as possible.

docs(self-managed): microsoft aks support

---

docs/components/connectors/introduction.md
versioned_docs/version-8.0/components/connectors/introduction.md
versioned_docs/version-8.1/components/connectors/introduction.md

Closes https://github.com/camunda/team-connectors/issues/214
Shape difference of connector vs. element template, a topic that did pop up a couple of times already.
No.
ASAP.

feat(connector): add connector vs. element template section

---

docs/components/best-practices/architecture/sizing-your-environment.md
versioned_docs/version-8.0/components/best-practices/architecture/sizing-your-environment.md
versioned_docs/version-8.1/components/best-practices/architecture/sizing-your-environment.md

Related to https://github.com/camunda/camunda-platform-docs/issues/1485.

fix process typo in best practice

---

docs/components/connectors/custom-built-connectors/connector-sdk.md
docs/components/console/manage-clusters/manage-secrets.md
docs/self-managed/connectors-deployment/connectors-configuration.md
docs/self-managed/connectors-deployment/install-and-start.md
docs/self-managed/platform-deployment/docker.md
docs/self-managed/platform-deployment/manual.md
versioned_docs/version-8.0/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.0/components/console/manage-clusters/manage-secrets.md
versioned_docs/version-8.0/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.0/self-managed/connectors-deployment/install-and-start.md
versioned_docs/version-8.0/self-managed/platform-deployment/docker.md
versioned_docs/version-8.0/self-managed/platform-deployment/local.md
versioned_docs/version-8.1/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.1/components/console/manage-clusters/manage-secrets.md
versioned_docs/version-8.1/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.1/self-managed/connectors-deployment/install-and-start.md
versioned_docs/version-8.1/self-managed/platform-deployment/docker.md
versioned_docs/version-8.1/self-managed/platform-deployment/manual.md

Adjust Connectors documentation to `0.3.0`.
Closes https://github.com/camunda/connector-sdk/issues/203
n/a
15th November (will be provided by branch `connector-sdk-0.3`)

feat: update Connectors to 0.3.0

---

docs/self-managed/platform-deployment/helm-kubernetes/overview.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/overview.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks.md
versioned_sidebars/version-8.1-sidebars.json

Documenting Microsoft AKS support in Camunda Platform 8 Self-Managed for 8.1 and tidying up Amazon EKS.
No.
No specific date, as soon as possible.

docs(self-managed): microsoft aks support - continue

---

docs/self-managed/backup-restore/optimize-backup.md

related to OPT-6533
Update the backup documentation to the most recent changes.
No
With the next release (3.10.0-alpha2)

chore(backup): document get backup API changes

---

docs/self-managed/platform-deployment/docker.md
versioned_docs/version-8.1/self-managed/platform-deployment/docker.md

and ensure people don't think the list is complete.

docs(docker): add link to Zeebe env vars

---

docs/components/best-practices/architecture/sizing-your-environment.md
versioned_docs/version-8.1/components/best-practices/architecture/sizing-your-environment.md

We adjusted our cluster size in SaaS due to learnings - this change brings those updates to this page.
No
no specific date needed, can go live asap

Updated cluster sizing to latest SaaS

---

docs/reference/licenses.md
versioned_docs/version-8.0/reference/licenses.md
versioned_docs/version-8.1/reference/licenses.md

Add Connectors to the license reference.
n/a
No specific date, can go live as soon as possible.

feat: add Connectors to license reference

---

docs/components/connectors/out-of-the-box-connectors/googledrive.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/googledrive.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/googledrive.md

Clarified snippets usage as per customer request.
---
---
---
N/A
N/A, ready to release anytime

docs(google drive ootbc): clarified snippets usage

---

docs/components/concepts/data-retention.md
sidebars.js
versioned_docs/version-8.1/components/concepts/data-retention.md
versioned_sidebars/version-8.1-sidebars.json

This adds the documentation for the data retention concepts in SaaS. It would be great if someone could check whether I did all the necessary work - this is my first time contributing here. I tried to stick to the [review process](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process).
@felix-mueller @menski I'm not sure if there needs to be more information about this topic in general. Feel free to add things / mention what should be explained more. 
@christinaausley I would be super happy for any kind of suggestions and improvements. I'm not familiar with our wording etc. so If I use any incorrect terms let me know. 
_Are there any marketing activities related to the related feature or component? If so, please briefly describe …

docs(saas): data-retention

---

docs/components/modeler/bpmn/bpmn-coverage.md

Indicate all elements supported for modeling.
Closes #1506
Not aware of.
December 12th.

feat(modeler): update BPMN coverage

---

optimize/apis-clients/optimize-api/optimize-api-authorization.md
optimize_versioned_docs/version-3.8.0/apis-clients/optimize-api/optimize-api-authorization.md
optimize_versioned_docs/version-3.9.0/apis-clients/optimize-api/optimize-api-authorization.md

Improving the documentation on how to get a valid token for C8 SaaS mode
No
The feature is already existent, this is an improvement of the docs, so immediately

chor(docs): Improved Optimize Public API Documentation

---

docs/guides/setup-client-connection-credentials.md
versioned_docs/version-8.1/guides/setup-client-connection-credentials.md

This adds a console link to the documentation, so that user understand the context a bit better. 
No
No

Provide link to the console in the docs

---

docs/guides/automating-a-process-using-bpmn.md
versioned_docs/version-8.1/guides/automating-a-process-using-bpmn.md

Little change that removes empty list element
No
No

Remove unnecessary list element

---

docs/self-managed/zeebe-deployment/operations/disk-space.md
docs/self-managed/zeebe-deployment/operations/rebalancing.md
src/pages/contact.md
versioned_docs/version-0.25/components/zeebe/operations/setting-up-a-cluster.md
versioned_docs/version-0.26/components/modeler/cloud-modeler/launch-cloud-modeler.md
versioned_docs/version-1.0/components/zeebe/deployment-guide/kubernetes/helm/installing-helm.md
versioned_docs/version-1.0/components/zeebe/deployment-guide/kubernetes/operator/zeebe-operator.md
versioned_docs/version-1.1/components/clients/java-client/testing.md
versioned_docs/version-1.1/components/zeebe/deployment-guide/getting-started/deploy-a-process.md
versioned_docs/version-1.1/components/zeebe/deployment-guide/kubernetes/operator/zeebe-operator.md
versioned_docs/version-1.3/components/best-practices/development/handling-data-in-processes.md
versioned_docs/version-1.3/components/best-practices/development/service-integration-patterns.md
versioned_docs/version-1.3/components/best-practices/development/writing-good-workers.md
versioned_docs/version-1.3/components/best-practices/management/following-the-customer-success-path.md

Based on Microsoft Bing Webmaster error reports, this PR is a monthly review and correction of issues flagged. This PR largely included descriptions, a spare H1 tag, and images without alt text.

correct bing errors

---

optimize/components/userguide/additional-features/export-import.md

relates to OPT-6674
We no longer limit this feature to superusers, so our documentation should reflect this.
N/A
Next release is fine :)

chore(docs): remove limitation of superusers importing/exporting json

---

docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/microsoft-teams.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/microsoft-teams.md

added  info about protected Microsoft teams APIs
(some of methods use protected APIs)
https://github.com/camunda/camunda-platform-docs/issues/1596#issuecomment-1378480417

chore(connectors): add info about protected microsoft teams apis

---

docs/apis-clients/web-modeler-api/index.md
docs/self-managed/modeler/web-modeler/api.md

Fix incorrect curl statements
no
asap

chore: fix curl statement

---

docs/components/modeler/forms/form-element-library/forms-element-library-image.md
docs/components/modeler/forms/form-element-library/forms-element-library-textarea.md

In reference to unresolved comments in https://github.com/camunda/camunda-platform-docs/pull/1570, this PR cleans up any lingering typos following its merge.

adjust form elements typos

---

docs/components/tasklist/userguide/using-tasklist.md
versioned_docs/version-8.0/components/tasklist/userguide/using-tasklist.md
versioned_docs/version-8.1/components/tasklist/userguide/using-tasklist.md

related to camunda/tasklist#2387

chore(tasklist): clarify access privileges of tasklist user

---

docs/components/console/manage-organization/manage-users.md
versioned_docs/version-8.1/components/console/manage-organization/manage-users.md

adding a note about the possibility to restrict hostnames for invites in C8 SaaS - related [pdp](https://github.com/camunda/product-hub/issues/839), [console-ticket](https://github.com/camunda-cloud/console/issues/3875)
nope
~as soon as the feature is on prod - will keep the PR in draft as long as this is not done~ nao

saas-invites: restrict hostnames

---

docs/components/modeler/forms/form-element-library/forms-element-library-select.md

To describe the new optional search functionality we've added to searchable selects
No
The functionality will be available in the next Tasklist alpha.

feat(forms): add searchable select setting

---

docs/reference/announcements.md
versioned_docs/version-8.1/reference/announcements.md

Closes #1607. Reverse list in announcements
Nope
No hard requirement, this will just help users not have to scroll so much.

docs(announcement): reverse list

---

docs/guides/update-guide/connectors/030-to-040.md
docs/self-managed/connectors-deployment/connectors-configuration.md
docs/self-managed/connectors-deployment/install-and-start.md
versioned_docs/version-8.0/guides/update-guide/connectors/030-to-040.md
versioned_docs/version-8.0/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.0/self-managed/connectors-deployment/install-and-start.md
versioned_docs/version-8.1/guides/update-guide/connectors/030-to-040.md
versioned_docs/version-8.1/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.1/self-managed/connectors-deployment/install-and-start.md

Keeping connectors doc up-to-date.
No.
Any time but no rush; the change is related to released code.

docs: update connectors related docs

---

docs/self-managed/platform-deployment/manual.md
versioned_docs/version-8.1/self-managed/platform-deployment/manual.md

Add hint on testing Zeebe with zbctl

---

docs/components/concepts/clusters.md
versioned_docs/version-8.1/components/concepts/clusters.md

Remove unclear lines from clusters page.
No, but Jakob is likely keen to use this page 😄 
This is a fix.

docs(cluster): remove unclear SLA language

---

docs/self-managed/platform-deployment/helm-kubernetes/upgrade.md
docs/self-managed/zeebe-deployment/operations/rebalancing.md
versioned_docs/version-8.0/self-managed/platform-deployment/openshift-helm.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/upgrade.md

Resolves descriptions too long/missing, and spare H1 tags flagged by Bing. Minor adjustments this month 👍

resolve bing flagged errors for february

---

docs/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.0/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.1/components/connectors/custom-built-connectors/connector-sdk.md

Keep docs up-to-date
No
Anytime

docs(connector-sdk): updated release version

---

package-lock.json
package.json

Updates docusaurus dependencies to version 2.3.1
No screenshots, as there are no visible changes. (I ran some regression snapshots locally to confirm.)

chore(deps): update docusaurus deps to 2.3.1

---

versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/available-connectors-overview.md

Adding missing connectors to older versions of documentation.
No.

docs(connectros): adding missing connectors to list

---

howtos/documentation-guidelines.md

Remove Menski, add Connectors team.
No marketing activities.
Rolled into the next group of changes is fine.

Update reviewer list

---

docs/self-managed/platform-deployment/manual.md
versioned_docs/version-8.1/self-managed/platform-deployment/manual.md

Previously linked to Zeebe releases, which was incorrect.
No
Could be considered a bug fix, but not tied to a specific release.

docs(manual): link to camunda-platform release page

---

docs/components/connectors/introduction.md
versioned_docs/version-8.1/components/connectors/introduction.md

Context: https://camunda.slack.com/archives/C0350959WG1/p1677751015177729
Fix the heasdline structure that was wrong

Fix headline structure

---

docs/components/zeebe/technical-concepts/clustering.md
versioned_docs/version-8.0/components/zeebe/technical-concepts/clustering.md
versioned_docs/version-8.1/components/zeebe/technical-concepts/clustering.md

A commit can be done when it is replicated to a majority of nodes, this includes leader AND follower.

Replace followers

---

docs/apis-clients/community-clients/index.md
versioned_docs/version-8.0/apis-clients/community-clients/index.md
versioned_docs/version-8.1/apis-clients/community-clients/index.md

Based on [Slack conversation](https://camunda.slack.com/archives/C026U8GBNSW/p1677655248190249), collaborated with @xomiamoore to add a message to the community-supported client docs.

add note to community clients

---

docs/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.0/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.1/self-managed/operate-deployment/operate-configuration.md

While the Elasticsearch exporter does not yet support self-signed certificates explicitly, we want to document the workaround described by @vctrmn in https://github.com/camunda/camunda-platform-helm/issues/473.
This may help users that have to connect using a self-signed certificate, for example, those using Elastic Cloud.
The note describes what must be done and provides an example for those using k8s to deploy their Zeebe instances.
I've chosen to add this documentation to 8.2 (next), 8.1, and 8.0, as I believe it is relevant in all those cases.
resolves #1490 
Not that I'm …

docs: describe self-signed certificates workaround

---

docs/components/best-practices/operations/performance-tuning-camunda-c7.md
versioned_docs/version-8.1/components/best-practices/operations/performance-tuning-camunda-c7.md

Update a non-working link

---

docs/components/best-practices/operations/performance-tuning-camunda-c7.md
versioned_docs/version-8.1/components/best-practices/operations/performance-tuning-camunda-c7.md

This change will update the Best Practices Guide regarding the connection pool defaults of Spring Boot 2 (and Camunda Run)
no
asap

Update description about connection pools

---

docs/reference/supported-environments.md
versioned_docs/version-8.1/reference/supported-environments.md

Closes #1808. 
No, but helpful for support.
When ready, again to help clarify for support.

Add ES 7.17.x to Supported Environment

---

optimize/components/userguide/instant-preview-dashboards.md

Technical review for https://github.com/camunda/camunda-platform-docs/pull/1835.

technical review of instant preview dashboards

---

docs/components/console/manage-plan/upgrade-to-professional-plan.md
versioned_docs/version-8.1/components/console/manage-plan/upgrade-to-professional-plan.md

found during https://github.com/camunda/product-hub/issues/1048
* update button description to reflect reality
* you cannot request access to PP, you can just swipe your credit card
no
i guess it does not matter

update wording on CC checkout

---

docs/components/connectors/out-of-the-box-connectors/power-automate.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/power-automate.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/power-automate.md

In the Power Automate documentation it was not clear enough that this connector is only for desktop flows. With and additional sentence, and a small clarification, hopefully we made that more straightforward. 
Not that I know of.
Can go live asap, since it is a fix for a current version.

fix(connectors): PowerAutomate doc clarification

---

docs/reference/supported-environments.md
docs/self-managed/operate-deployment/operate-configuration.md
docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
docs/self-managed/zeebe-deployment/exporters/exporters.md
docs/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
sidebars.js

The exporters are officially supported by us. Currently they are documented in READMEs in the Zeebe repo. It makes sense to have officially supported components documented in the official documentation. Because of this I have copied the contents of the READMEs to these docs.
When this is merged I will change the READMEs in the Zeebe repo to link to the official docs instead.
closes #1828 
closes #178 
Note: Even though the Elasticsearch Exporter is an older thing and is supported in previous versions, I chose not to add them to the older docs version. Reasoning behind this is that I don't know exactly which configuration option was added when. I can't copy it as-is as not all options would be …

Document Opensearch and Elasticsearch exporters

---

docs/self-managed/tasklist-deployment/taskslist-api.md
docs/self-managed/zeebe-deployment/operations/disk-space.md
docs/self-managed/zeebe-deployment/operations/rebalancing.md

Based on monthly Bing reports, adjusts missing descriptions and flagged headers for April.
CC @dlevy-camunda

testing a few small description changes for bing

---

docs/reference/regions.md
versioned_docs/version-8.1/reference/regions.md

We are releasing a new datacenter in Canada region as described here
https://github.com/camunda/product-hub/issues/995
@felix-mueller can answer this
SRE part is done and can be released any time soon (https://github.com/camunda-cloud/team-sre/issues/399)

New available GCP region: northamerica-northeast2

---

docs/guides/update-guide/elasticsearch/7-to-8.md
sidebars.js

Adds a page to describe how to upgrade from ES7 to ES8. This only covers the Zeebe part of this upgrade.
N/A
8.2

Add update guide for ElasticSearch 7 to 8

---

docs/guides/update-guide/810-to-820.md
docs/self-managed/tasklist-deployment/tasklist-authentication.md

Unbreaking main
Sadly no
The most ASAP that ever ASAP'ed.

Correcting links for build errors

---

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
versioned_docs/version-8.0/components/modeler/desktop-modeler/element-templates/defining-templates.md
versioned_docs/version-8.1/components/modeler/desktop-modeler/element-templates/defining-templates.md

Small typo was fixed resolves #1912 

docs(typo): Fix typo reuqest to request

---

static/.htaccess

Missed a redirect yesterday for Identity content in my merge party yesterday.
No
ASAP, it's broken on main and making people sad.

docs(.htaccess): add Identity redirect

---

optimize_sidebars.js

Synchronizes the sidebars for the APIs & Tools documentation, versions 8.1/3.9.0.
This is the final step in sidebar synchronization for this release!

chore(sidebars): synchronize next/apis-clients sidebars

---

versioned_docs/version-8.2/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.2/self-managed/operate-deployment/operate-authentication.md
versioned_docs/version-8.2/self-managed/tasklist-deployment/tasklist-authentication.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/security/client-authorization.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/security/security.md
versioned_docs/version-8.2/self-managed/zeebe-gateway-deployment/the-zeebe-gateway.md
versioned_sidebars/version-8.2-sidebars.json

Backport of #1917 to the 8.2 docs.

feat(zeebe-8.2): identity token validation in gateway

---

docs/apis-tools/web-modeler-api/index.md
docs/self-managed/modeler/web-modeler/api.md
versioned_docs/version-8.2/apis-tools/web-modeler-api/index.md
versioned_docs/version-8.2/self-managed/modeler/web-modeler/api.md

Describe the limitations of Web Modeler Public API beta as of completing Milestone 2
no
As soon as convenient.

docs: describe limitations of Web Modeler public API beta

---

docs/components/connectors/out-of-the-box-connectors/asana.md
docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
optimize_sidebars.js
sidebars.js
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/asana.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/asana.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/asana.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_sidebars/version-8.0-sidebars.json
versioned_sidebars/version-8.1-sidebars.json
versioned_sidebars/version-8.2-sidebars.json

Introduce Asana connector.
No
Any time

docs(connectors): add Asana connector doc

---

product-links.txt

Adjusting product links as Console adjustments are in prod. Related to https://github.com/camunda-cloud/camunda-cloud-management-apps/pull/253.

adjust product links

---

docs/reference/notices.md
versioned_docs/version-8.2/reference/notices.md

feat(notices): add security notice 11

---

docs/reference/notices.md
versioned_docs/version-8.2/reference/notices.md

feat(notices): add additional detail for sec note

---

docs/reference/notices.md
versioned_docs/version-8.2/reference/notices.md

Slight language correction of the recent sec note

chore(notices): grammar correction

---

docs/reference/notices.md
versioned_docs/version-8.2/reference/notices.md

Technical review of https://github.com/camunda/camunda-platform-docs/pull/1972.
Looking like today.

technical review of notice note

---

docs/reference/notices.md
versioned_docs/version-8.2/reference/notices.md

Technical review of https://github.com/camunda/camunda-platform-docs/pull/1971.
Today.

technical review of notice

---

docusaurus.config.js
package-lock.json
package.json

Addresses https://github.com/camunda/developer-experience/issues/60.
Introduces `swc-loader` as an alternative webpack JS loader to `babel-loader`, with the intention of speeding up builds (as described [in this conversation](https://github.com/facebook/docusaurus/issues/4765)). 
🤷 Unfortunately, there is not much hard data on that. Most (if not all) of the feedback in the above linked issue is anecdotal. 
From our recent successes, it looks like it might not even speed things up at all! Here's a screenshot of our last n successful builds -- this one took on-the-low-side of time, but it wasn't the fastest.
My intention is to run the build for this PR a few more times over the next day, at various times, preferably as I see other builds _also_ running, to get more data points.
Anecdotally, …

dx: speed up builds by using swc-loader instead of babel

---

docs/components/best-practices/architecture/deciding-about-your-stack.md
docs/components/console/manage-plan/available-plans.md
docs/components/operate/operate-introduction.md
docs/components/tasklist/introduction-to-tasklist.md
docs/guides/create-account.md
docusaurus.config.js
src/pages/index.js
versioned_docs/version-8.0/components/best-practices/architecture/deciding-about-your-stack.md
versioned_docs/version-8.0/components/console/manage-plan/available-plans.md
versioned_docs/version-8.0/components/operate/operate-introduction.md
versioned_docs/version-8.0/components/tasklist/introduction-to-tasklist.md
versioned_docs/version-8.0/guides/create-account.md
versioned_docs/version-8.1/components/best-practices/architecture/deciding-about-your-stack.md
versioned_docs/version-8.1/components/console/manage-plan/available-plans.md
versioned_docs/version-8.1/components/operate/operate-introduction.md
versioned_docs/version-8.1/components/tasklist/introduction-to-tasklist.md
versioned_docs/version-8.1/guides/create-account.md
versioned_docs/version-8.2/components/best-practices/architecture/deciding-about-your-stack.md
versioned_docs/version-8.2/components/console/manage-plan/available-plans.md
versioned_docs/version-8.2/components/operate/operate-introduction.md
versioned_docs/version-8.2/components/tasklist/introduction-to-tasklist.md
versioned_docs/version-8.2/guides/create-account.md

Resolves https://github.com/camunda/camunda-platform-docs/issues/1993.

adjust signup page links

---

docs/components/connectors/out-of-the-box-connectors/uipath.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/uipath.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/uipath.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/uipath.md

Clarify docs for a specific connector
No
Any time

docs(connectors,uipath): updated secrets usage

---

docs/apis-tools/working-with-apis-tools.md

A nod to the Node SDK. I threw this change together at the very end of my day, so I'm confident it needs more eyes and word-smithing. 
Maybe link to this in the blog?
Certainly when the blog is out this should be live.

add node sdk to next

---

optimize/apis-tools/optimize-api/dashboard/export-dashboard-definitions.md
optimize/apis-tools/optimize-api/import-entities.md

relates to OPT-6884
Adds a new description field to reports
N/A
Just an 8.3 change

feat(reports): add description field to reports

---

docs/components/modeler/forms/form-element-library/forms-element-library-checkbox.md
docs/components/modeler/forms/form-element-library/forms-element-library-checklist.md
docs/components/modeler/forms/form-element-library/forms-element-library-taglist.md
versioned_docs/version-8.2/components/modeler/forms/form-element-library/forms-element-library-checkbox.md
versioned_docs/version-8.2/components/modeler/forms/form-element-library/forms-element-library-checklist.md
versioned_docs/version-8.2/components/modeler/forms/form-element-library/forms-element-library-taglist.md

Related to https://github.com/camunda/camunda-modeler/issues/3529

docs(form-element-library): add required for checkbox, checklist and taglist

---

docs/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.0/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.1/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.2/components/connectors/custom-built-connectors/connector-sdk.md

Update Connectors SDK reference
No
Any time

docs(connectors): update SDK entry

---

versioned_docs/version-8.2/apis-tools/community-clients/micronaut.md

Fix broken link (Feature will be shown as red in Micronaut Launch because it is unknown)
No
ASAP - Link is broken
Note: I'm unsure about the following checklist. The fix applies to all released and future version of the docs. Please merge as appropriate.

Fix broken link to camunda-zeebe feature

---

docs/guides/update-guide/introduction.md
versioned_docs/version-8.2/guides/update-guide/introduction.md

Closes #2064 
No
This is a bug. The sooner, the better.

docs(update-guide): add 8.1 to 8.2 to intro

---

optimize/self-managed/optimize-deployment/migration-update/3.9-to-3.10.md
optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/migration-update/3.9-to-3.10.md

relates to OPT-6895
Clarifying wording on deprecation vs. removal of config options
N/A
No urgency

chore(docs): clarify deprecation of white label config for Optimize

---

docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/twilio.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/twilio.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_sidebars/version-8.0-sidebars.json
versioned_sidebars/version-8.1-sidebars.json

Follow up to #1978 
No.
This could be consider a bug and should prompt a docs release to fix.

Follow up 1978, add Twilio Connector

---

docs/reference/supported-environments.md
versioned_docs/version-8.2/reference/supported-environments.md

Self-explanatory
Nope
When you next release :)

chore(docs): Add Optimize 3.10 to the supported environments matrix

---

howtos/documentation-guidelines.md
howtos/redirect-rules.md

!! This PR is currently based on an open PR, to avoid noise in the diff. We should probably merge that PR before this one, and then rely on GitHub to point it at the correct base. !!
Inspired by [a recent comment](https://github.com/camunda/camunda-platform-docs/pull/2058#discussion_r1187957017), I thought it'd be useful to more formally provide guidance for writing redirect rules.
It's very possible this is too much detail. I tried my best to avoid discussing things that are explained better elsewhere (linking to Apache docs especially), and focus on the things that are specific to our docs, while providing enough detail to be informative. Let me know if I totally missed the mark!

feat: extract & expand a Guide to Writing Redirect Rules

---

src/pages/index.js

Rename hero buttons and adjust columns to prevent overlap of buttons.
Yes, this is an acquisition team experiment for the joint KR. Please inform #top-rapid-adoption-acquisition when the change is merged and live.
This experiment will run Monday, May 15 - Monday, May 29. **This change should go live on Monday, May 15th.**

[Acquisition Team Experiment] docs(index.js): rename hero buttons and adjust columns

---

docusaurus.config.js

Closes #2101 
This is a marketing request!
Not urgent.

docs(config): fix try free link

---

optimize/apis-tools/optimize-api/dashboard/export-dashboard-definitions.md
optimize/apis-tools/optimize-api/import-entities.md

relates to OPT-6885
Documents the new dashboard descriptions features for Optimize dashboards
N/A
Just with the next release

feat(dashboards): include documentation for dashboard descriptions

---

docs/components/modeler/desktop-modeler/troubleshooting.md
sidebars.js
versioned_docs/version-8.2/components/modeler/desktop-modeler/troubleshooting.md
versioned_sidebars/version-8.2-sidebars.json

This introduces a dedicated troubleshooting page (https://github.com/bpmn-io/internal-docs/issues/760) to help users debug common desktop modeler issues. 
No.
Once approved.
----
Closes https://github.com/bpmn-io/internal-docs/issues/760

feat(desktop-modeler): initial take on troubleshooting page

---

docs/components/connectors/out-of-the-box-connectors/github-webhook.md
docs/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/github-webhook.md
versioned_docs/version-8.0/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/github-webhook.md
versioned_docs/version-8.1/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/github-webhook.md
versioned_docs/version-8.2/components/connectors/protocol/http-webhook.md

Adds the documentation for newly released intermediate webhook connectors (regular + GitHub)

docs(connectors): document intermediate webhooks

---

docs/apis-tools/go-client/index.md
docs/apis-tools/java-client/index.md
docs/components/modeler/desktop-modeler/connect-to-camunda-cloud.md
docs/components/modeler/desktop-modeler/element-templates/configuring-templates.md
docs/components/modeler/desktop-modeler/search-paths/search-paths.md
docs/self-managed/zeebe-deployment/security/client-authorization.md
docs/self-managed/zeebe-deployment/zeebe-gateway/zeebe-gateway-overview.md
versioned_docs/version-8.0/self-managed/tasklist-deployment/taskslist-api.md
versioned_docs/version-8.2/apis-tools/go-client/index.md
versioned_docs/version-8.2/apis-tools/java-client/index.md
versioned_docs/version-8.2/components/modeler/desktop-modeler/connect-to-camunda-cloud.md
versioned_docs/version-8.2/components/modeler/desktop-modeler/element-templates/configuring-templates.md
versioned_docs/version-8.2/components/modeler/desktop-modeler/search-paths/search-paths.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/security/client-authorization.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/zeebe-gateway/zeebe-gateway-overview.md

Based on monthly Bing reports, adjusts missing descriptions and flagged headers for March.
CC @dlevy-camunda

adjust descriptions flagged by bing

---

docs/reference/announcements.md
versioned_docs/version-8.2/reference/announcements.md

Closes #1801 
No
Not urgent or critical

Add release note and blog links to Announcements page

---

docs/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.2/components/connectors/custom-built-connectors/connector-sdk.md

Found some broken links in the documentation, this PR corrects those links.
N/A
Whenever possible!

fix: broken anchor links

---

docs/components/best-practices/modeling/building-flexibility-into-bpmn-models.md
versioned_docs/version-8.0/components/best-practices/modeling/building-flexibility-into-bpmn-models.md
versioned_docs/version-8.1/components/best-practices/modeling/building-flexibility-into-bpmn-models.md
versioned_docs/version-8.2/components/best-practices/modeling/building-flexibility-into-bpmn-models.md

Closes https://github.com/camunda/developer-experience/issues/14.
Sort of kind of, need web marketing to adjust https://camunda.com/bpmn/reference/.
No rush here.

adjust termination references

---

src/pages/index.js

This partially reverts #2099. 
This is an Acquisition Team Experiment conclusion.
Not urgent, but when it is live, inform https://camunda.slack.com/archives/C03NEE32Y2F/p1683733933920659

[Acquisition Team Experiment] - revert button, try free -> sign up

---

hacks/isolateVersion/1-reduceVersionManifest.sh
hacks/isolateVersion/2-deleteOtherVersions.sh
hacks/isolateVersion/3-preventCrawling.sh
hacks/isolateVersion/4-fixDockerfile.sh
hacks/isolateVersion/allSteps.sh

Part of #1173.
Provides a set of scripts to begin the process of archiving a version of the docs.
The steps performed by the script are: 
1. Remove other versions from the version manifest file
2. Delete source for all other versions, including sidebars
3. Add a robots.txt file to prevent crawling of the extracted site
4. Update the Dockerfile to allow for local debugging of the extracted site
The main script also provides a list after completion of all the remaining manual work. Long term, I will automate some (if not most) of these steps. I'll probably do a little bit each version that I archive.
Here is a (poor quality) video of me running the script for version 0.25:
https://github.com/camunda/camunda-platform-docs/assets/1627089/1abb85df-fe17-450b-951e-df21a5fca1b2

feat: a set of bash scripts to do the least complex steps of archiving a version

---

docs/components/connectors/out-of-the-box-connectors/github.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/github.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/github.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/github.md

Relates to https://github.com/camunda/team-connectors/issues/426

Fix spelling GitLab/GitHub

---

optimize/components/userguide/creating-reports.md
optimize/components/userguide/edit-mode.md
optimize/components/userguide/process-analysis/report-analysis/view-mode.md
optimize/components/userguide/view-mode.md

docs(optimize): implement gramatical suggestions

---

docs/components/modeler/forms/form-element-library/forms-element-library-button.md
docs/components/modeler/forms/form-element-library/forms-element-library-checkbox.md
docs/components/modeler/forms/form-element-library/forms-element-library-checklist.md
docs/components/modeler/forms/form-element-library/forms-element-library-datetime.md
docs/components/modeler/forms/form-element-library/forms-element-library-number.md
docs/components/modeler/forms/form-element-library/forms-element-library-radio.md
docs/components/modeler/forms/form-element-library/forms-element-library-select.md
docs/components/modeler/forms/form-element-library/forms-element-library-taglist.md
docs/components/modeler/forms/form-element-library/forms-element-library-textarea.md
docs/components/modeler/forms/form-element-library/forms-element-library-textfield.md
docs/components/modeler/forms/sidebar-schema.js

Related to https://github.com/camunda/team-hto/issues/247

Update forms library

---

docusaurus.config.js

Closes #2219 with a new blog link

New blog link

---

docs/components/concepts/backups.md
sidebars.js
versioned_docs/version-8.2/components/concepts/backups.md
versioned_sidebars/version-8.2-sidebars.json

"Hot" Backups documentation. 
@felix-mueller , it would be great if you can contribute to this. Especially on the purpose of the backups. E.g. "it is not for data archival" - I unfortunately have not found the section were we discussed this already. 
@ColRad, is there something for the Console API where we should link to? 
@hisImminence, I could also use your special wording magic to push this one through and make it good for the release.

feat(concepts): backups

---

docs/reference/release-notes.md
versioned_docs/version-8.1/reference/release-notes.md
versioned_docs/version-8.2/reference/release-notes.md

Closes #2220. There is also a redirect on the old URL.

Update link for release notes (on blog)

---

docs/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.2/components/modeler/desktop-modeler/troubleshooting.md

Quick addition to the Desktop Modeler Troubleshooting page to add a link to the forum if people have questions that aren't answered in the FAQ.

add link to forum

---

docs/components/components-overview.md
docs/components/concepts/what-is-camunda-platform-8.md
docs/components/modeler/about-modeler.md
docs/self-managed/platform-deployment/docker.md
docs/self-managed/platform-deployment/overview.md
versioned_docs/version-8.2/components/components-overview.md
versioned_docs/version-8.2/components/concepts/what-is-camunda-platform-8.md
versioned_docs/version-8.2/components/modeler/about-modeler.md
versioned_docs/version-8.2/self-managed/platform-deployment/docker.md
versioned_docs/version-8.2/self-managed/platform-deployment/overview.md

https://github.com/camunda/developer-experience/issues/74
Adds keywords to some page metadata (keywords defined by Acquisition that support ATUs)

[Acquisition Team Experiment] add keywords metadata

---

docs/components/zeebe/technical-concepts/protocols.md
docs/self-managed/zeebe-deployment/configuration/gateway.md
docs/self-managed/zeebe-deployment/zeebe-gateway/interceptors.md
sidebars.js
static/.htaccess
versioned_docs/version-8.2/components/zeebe/technical-concepts/protocols.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/configuration/gateway.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/zeebe-gateway/interceptors.md
versioned_sidebars/version-8.2-sidebars.json

Closes #1987! This orphaned page finds a home.

add interceptors to sidebar, fix link

---

docs/self-managed/platform-deployment/troubleshooting.md
versioned_docs/version-8.2/self-managed/platform-deployment/troubleshooting.md

There is a new section required about database configuration.
@christinaausley  If this place is not sufficient, please provide me with a better place for this hint.

Add Database configuration issue to troubleshooting

---

optimize/self-managed/optimize-deployment/migration-update/instructions.md
optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/migration-update/instructions.md

fix(migration): fix migration guide table in docs

---

docs/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.2/components/modeler/desktop-modeler/troubleshooting.md

fix(desktop-modeler): correct deep link

---

src/css/custom.css
src/theme/Navbar/Search/index.js

Add create account btn to navbar

Add create account btn to navbar

---

docs/self-managed/platform-deployment/troubleshooting.md
versioned_docs/version-8.1/self-managed/platform-deployment/troubleshooting.md
versioned_docs/version-8.2/self-managed/platform-deployment/troubleshooting.md

Retroactive technical review of https://github.com/camunda/camunda-platform-docs/pull/2218.

technical review of identity contextpath

---

docs/components/modeler/desktop-modeler/troubleshooting.md
docs/self-managed/modeler/web-modeler/configuration/logging.md
docs/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-database-connection.md
docs/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md
docs/self-managed/platform-deployment/troubleshooting.md
sidebars.js
versioned_docs/version-8.2/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.2/self-managed/modeler/web-modeler/configuration/logging.md
versioned_docs/version-8.2/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-database-connection.md
versioned_docs/version-8.2/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md
versioned_docs/version-8.2/self-managed/platform-deployment/troubleshooting.md
versioned_sidebars/version-8.2-sidebars.json

Part of https://github.com/camunda/web-modeler/issues/3874 (Create a troubleshooting guide for Web Modeler Self-Managed installation and deployment).
Closes https://github.com/camunda/web-modeler/issues/4780.

chore(web-modeler): first iteration of Web Modeler troubleshooting guide

---

src/theme/Navbar/Search/index.js

Corrects link to `https://signup.camunda.com/accounts`.
https://camunda.slack.com/archives/C03NEE32Y2F/p1688572728090759
Closes #2102

remove GA from signup link

---

docusaurus.config.js

The remaining item to close out #2102 - remove the banner.

Remove banner over nav

---

docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
docs/components/connectors/out-of-the-box-connectors/google-sheets.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/google-sheets.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/google-sheets.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/google-sheets.md

Retroactive technical review for https://github.com/camunda/camunda-platform-docs/pull/2178.

retroactive review google sheets connector

---

docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
docs/components/connectors/out-of-the-box-connectors/aws-sns-inbound.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/aws-sns-inbound.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/aws-sns-inbound.md

Retroactive review of https://github.com/camunda/camunda-platform-docs/pull/2187.

retro technical review aws sns inbound

---

src/theme/Navbar/Search/index.js

https://camunda.slack.com/archives/C026U8GBNSW/p1689193964701489

Adjust nav link URL for PMM

---

docs/reference/supported-environments.md
versioned_docs/version-8.2/reference/supported-environments.md

Documents Web Modeler support for Amazon Aurora PostgreSQL 13.x and 15.x (again)
The original change (https://github.com/camunda/camunda-platform-docs/pull/2296) was overridden by https://github.com/camunda/camunda-platform-docs/pull/2268, cc @johanwelgemoed @akeller

docs(web-modeler): support for Amazon Aurora PostgreSQL 13.x & 15.x

---

docs/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.2/components/modeler/desktop-modeler/troubleshooting.md

This adds mentions of ALPN and improves our HTTPS debug logging statement (aligns with web modeler).

docs(desktop-modeler): mention ALPN

---

docs/reference/supported-environments.md
docs/self-managed/operate-deployment/operate-configuration.md
docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
docs/self-managed/zeebe-deployment/exporters/opensearch-exporter.md

* In line with https://github.com/camunda/product-hub/issues/997

chore(reference): update supported environments

---

optimize/apis-tools/optimize-api/report/get-data-export.md

relates to OPT-7034
From 8.3, we will add flow node instance data to the JSON export.

improve(export): include flow node data in json export

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/irsa.md

Switches the suggested `Dockerfile` of the AWS IRSA documentation for a more automated way by utilizing Gradle.

docs(irsa): switch keycloak to automated docker way

---

docs/components/modeler/forms/form-element-library/forms-element-library-spacer.md
docs/components/modeler/forms/form-element-library/forms-element-library.md
static/img/form-icons/form-spacer.svg

This PR documents the new spacer component in forms, which is a simple way to create spacing between existing components.

feat: document new forms spacer component

---

docs/components/best-practices/development/invoking-services-from-the-process-c7.md
docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
docs/guides/migrating-from-camunda-platform-7/adjusting-source-code.md
docs/guides/migrating-from-camunda-platform-7/conceptual-differences.md
docs/guides/migrating-from-camunda-platform-7/migration-readiness.md
versioned_docs/version-8.0/components/best-practices/development/invoking-services-from-the-process-c7.md
versioned_docs/version-8.0/components/modeler/desktop-modeler/element-templates/defining-templates.md
versioned_docs/version-8.0/guides/migrating-from-camunda-platform-7/adjusting-source-code.md
versioned_docs/version-8.0/guides/migrating-from-camunda-platform-7/conceptual-differences.md
versioned_docs/version-8.0/guides/migrating-from-camunda-platform-7/migration-readiness.md
versioned_docs/version-8.1/components/best-practices/development/invoking-services-from-the-process-c7.md
versioned_docs/version-8.1/components/modeler/desktop-modeler/element-templates/defining-templates.md
versioned_docs/version-8.1/guides/migrating-from-camunda-platform-7/adjusting-source-code.md
versioned_docs/version-8.1/guides/migrating-from-camunda-platform-7/conceptual-differences.md
versioned_docs/version-8.1/guides/migrating-from-camunda-platform-7/migration-readiness.md
versioned_docs/version-8.2/components/best-practices/development/invoking-services-from-the-process-c7.md
versioned_docs/version-8.2/components/modeler/desktop-modeler/element-templates/defining-templates.md
versioned_docs/version-8.2/guides/migrating-from-camunda-platform-7/adjusting-source-code.md
versioned_docs/version-8.2/guides/migrating-from-camunda-platform-7/conceptual-differences.md
versioned_docs/version-8.2/guides/migrating-from-camunda-platform-7/migration-readiness.md

Closes https://github.com/camunda/developer-experience/issues/82.

adjust java delegate casing

---

optimize/apis-tools/optimize-api/dashboard/delete-dashboard.md
optimize_versioned_docs/version-3.10.0/apis-tools/optimize-api/dashboard/delete-dashboard.md

docs(api): remove c7 only badge from endpoint working in c8saas

---

docs/components/modeler/reference/sidebar-schema.js
sidebars.js

This introduces relevant categories for parent pages. As a result:
* Breadcrumbs are meaningful
* Unnecessary "About" pages and nesting in the sitebar is avoided
----
Adds necessary meta-data to turn sections into categories, fix the breadcrumbs, and avoid unnecessary nesting + about pages in the sidebar.
----
Related to https://github.com/camunda/developer-experience/issues/109

feat: introduce modeler categories

---

code-of-conduct.md
docs/self-managed/platform-deployment/overview.md
docs/self-managed/zeebe-deployment/zeebe-installation.md
docusaurus.config.js
optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/migration-update/translation-diffs/differences_localization_390_3100.diff
src/pages/contact.md
versioned_docs/version-8.0/components/zeebe/open-source/get-help-get-involved.md
versioned_docs/version-8.0/self-managed/platform-deployment/platform-8-deployment.md
versioned_docs/version-8.0/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.1/self-managed/platform-deployment/overview.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.2/self-managed/platform-deployment/overview.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/zeebe-installation.md

Closes https://github.com/camunda/developer-experience/issues/100, follow up of https://github.com/camunda/camunda-platform-docs/issues/1708.

remove references to C8 Slack

---

docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
docs/components/connectors/out-of-the-box-connectors/whatsapp.md
optimize_sidebars.js
sidebars.js
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.0/components/connectors/out-of-the-box-connectors/whatsapp.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/whatsapp.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/whatsapp.md
versioned_sidebars/version-8.0-sidebars.json
versioned_sidebars/version-8.1-sidebars.json
versioned_sidebars/version-8.2-sidebars.json

feat: introduce whatsapp connector

---

docs/reference/supported-environments.md
versioned_docs/version-8.2/reference/supported-environments.md

Follow up to https://github.com/camunda/product-hub/issues/1117

Addition to ES statement

---

docs/self-managed/zeebe-deployment/operations/metrics.md

Updates the metrics endpoint for Zeebe 8.3.0. This change is already documented in the update guide.

refactor(zeebe): update metrics route for 8.3.0

---

optimize/self-managed/optimize-deployment/migration-update/3.10-to-3.11.md
optimize/self-managed/optimize-deployment/migration-update/3.9-to-3.10.md
optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/migration-update/3.9-to-3.10.md

Let me know if you have a more elegant way of phrasing this 😬 
related to OPT-7208

chore(optimize): add note about unusual ES support

---

src/pages/meta.md

Closes https://github.com/camunda/camunda-platform-docs/issues/2538.

adjust meta header h1

---

docs/components/zeebe/technical-concepts/architecture.md
docs/components/zeebe/zeebe-overview.md
versioned_docs/version-8.1/components/zeebe/technical-concepts/architecture.md
versioned_docs/version-8.1/components/zeebe/zeebe-overview.md
versioned_docs/version-8.2/components/zeebe/technical-concepts/architecture.md
versioned_docs/version-8.2/components/zeebe/zeebe-overview.md

Gold medal 🥇  to the @camunda/zeebe team for making this the easiest section for renaming 😄

zeebe renaming

---

docs/components/operate/operate-introduction.md
docs/components/tasklist/introduction-to-tasklist.md
docs/components/tasklist/userguide/starting-processes.md
versioned_docs/version-8.1/components/operate/operate-introduction.md
versioned_docs/version-8.1/components/tasklist/introduction-to-tasklist.md
versioned_docs/version-8.2/components/operate/operate-introduction.md
versioned_docs/version-8.2/components/tasklist/introduction-to-tasklist.md

Given how few changes I needed to make, renamed in both Operate and Tasklist for this PR 🥳

operate and tasklist rename

---

docs/self-managed/zeebe-deployment/operations/health.md
versioned_docs/version-8.0/self-managed/zeebe-deployment/operations/health.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/operations/health.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/health.md

Closes https://github.com/camunda/camunda-platform-docs/issues/2478. 🐞

fix status response typo

---

docs/self-managed/about-self-managed.md
docs/self-managed/platform-architecture/overview.md
optimize_sidebars.js
optimize_versioned_sidebars/version-3.10.0-sidebars.json
optimize_versioned_sidebars/version-3.9.0-sidebars.json
versioned_docs/version-8.1/self-managed/about-self-managed.md
versioned_docs/version-8.1/self-managed/platform-architecture/overview.md
versioned_docs/version-8.2/self-managed/about-self-managed.md
versioned_docs/version-8.2/self-managed/platform-architecture/overview.md

Self-Managed architecture section renaming 🦖

self managed architecture renaming

---

docs/components/tasklist/userguide/starting-processes.md

Follow up review to https://github.com/camunda/camunda-platform-docs/pull/2425.

retro review starting processes

---

docs/components/connectors/out-of-the-box-connectors/github-webhook.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/github-webhook.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/github-webhook.md

Fixes the following:
**Old**
**New**

fix(github-webhook): fix enumeration mistake

---

docs/self-managed/operate-deployment/operate-configuration.md
docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
docs/self-managed/operational-guides/troubleshooting/log-levels.md
docs/self-managed/zeebe-deployment/configuration/gateway.md
docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
docs/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
docs/self-managed/zeebe-deployment/operations/management-api.md
docs/self-managed/zeebe-deployment/security/client-authorization.md
docs/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.1/self-managed/backup-restore/backup-and-restore.md
versioned_docs/version-8.1/self-managed/troubleshooting/log-levels.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/interceptors.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/security/client-authorization.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.1/self-managed/zeebe-gateway-deployment/the-zeebe-gateway.md
versioned_docs/version-8.2/self-managed/backup-restore/backup-and-restore.md
versioned_docs/version-8.2/self-managed/troubleshooting/log-levels.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/configuration/gateway.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/security/client-authorization.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/zeebe-installation.md

Self-Managed Operate and Zeebe renaming 🍔

operate and zeebe sm renaming

---

docs/apis-tools/operate-api/overview.md

Related to [#2590](https://github.com/camunda/camunda-platform-docs/issues/2590), documentation update clarifying usage of parentKey and parentProcessInstanceKey fields in process instance filtering
Code fix is going into 8.3 release

Add documentation clarifying usage of parentKey and parentProcessInstanceKey fields when filtering process instances

---

docs/components/connectors/connector-types.md
docs/components/connectors/custom-built-connectors/connector-sdk.md
docs/components/connectors/use-connectors/inbound.md
docs/components/connectors/use-connectors/index.md
docs/reference/glossary.md
versioned_docs/version-8.0/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.0/components/connectors/use-connectors/index.md
versioned_docs/version-8.1/components/connectors/connector-types.md
versioned_docs/version-8.1/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.1/components/connectors/use-connectors/inbound.md
versioned_docs/version-8.1/components/connectors/use-connectors/index.md
versioned_docs/version-8.2/components/connectors/connector-types.md
versioned_docs/version-8.2/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.2/components/connectors/use-connectors/inbound.md
versioned_docs/version-8.2/components/connectors/use-connectors/index.md
versioned_docs/version-8.2/reference/glossary.md

Inbound Connectors documentation improvements:
- Added more details on inbound connector types, updated the existing info about configuring inbound connectors
- Added a note that Operate is required for inbound connectors and an Operate configuration example (Docker)
- Removed the false deprecation warning

feat: improve inbound connector documentation

---

docs/apis-tools/java-client/index.md
versioned_docs/version-8.0/apis-tools/java-client/index.md
versioned_docs/version-8.1/apis-tools/java-client/index.md
versioned_docs/version-8.2/apis-tools/java-client/index.md

Closes #2622. Removes from all supported versions.

Remove Spring section from Java client docs

---

docs/components/concepts/clusters.md
versioned_docs/version-8.2/components/concepts/clusters.md

Correct limits on clusters available.

---

docs/apis-tools/grpc.md

Update `DeployResource` gRPC page to include form deployment response
closes #2579

Update DeployResource gRPC page to include form deployment response

---

docs/guides/host-custom-connector.md
versioned_docs/version-8.0/guides/host-custom-connector.md
versioned_docs/version-8.1/guides/host-custom-connector.md
versioned_docs/version-8.2/guides/host-custom-connector.md

Partially closes https://github.com/camunda/developer-experience/issues/130.

adjust connectors sdk

---

docs/components/best-practices/architecture/sizing-your-environment.md
versioned_docs/version-8.0/components/best-practices/architecture/sizing-your-environment.md
versioned_docs/version-8.1/components/best-practices/architecture/sizing-your-environment.md
versioned_docs/version-8.2/components/best-practices/architecture/sizing-your-environment.md

See https://camunda.slack.com/archives/C026U8GBNSW/p1696336332286769

adjust best practice bug

---

hacks/cutNewVersions.sh
static/.htaccess

Addresses #2673 and #1246.
1. Adds redirect rules that temporarily redirect any path which specifies the current main docs version (8.2) or current optimize docs version (3.10.0).
2. Updates the version release script to swap those version numbers according to the newly released numbers.
I tested the redirect rules two ways: indirectly with https://htaccess.madewithlove.com/, and directly [by running locally via Docker](https://github.com/camunda/camunda-docs/blob/0958fb2d677d6ea6c4ad8e6a449a59d31f71ee91/howtos/moving-content.md#testing-redirect-rules).

feat: redirect current versions

---

docs/self-managed/platform-deployment/helm-kubernetes/deploy.md

Adjusts the documentation to state the correct helm configuration parameters as adapted in https://github.com/camunda/camunda-platform-helm/pull/748

chore(web-modeler): use current helm config for database connectivity

---

docs/reference/supported-environments.md
versioned_docs/version-8.0/reference/supported-environments.md
versioned_docs/version-8.1/reference/supported-environments.md
versioned_docs/version-8.2/reference/supported-environments.md

From support - https://camunda.slack.com/archives/C026U8GBNSW/p1696363213234819?thread_ts=1695300917.342669&cid=C026U8GBNSW
Remove 
> See more community-maintained Camunda 8 clients [here](https://docs.camunda.io/docs/apis-tools/community-clients/).
from the [Supported environments](https://docs.camunda.io/docs/reference/supported-environments/) page?

Remove community-maintained clients from supported environments page

---

optimize_versioned_sidebars/version-3.10.0-sidebars.json

This PR synchronizes sidebars for the 8.2 version of the docs. 
- Synchronization for <= 8.1. If that needs to happen, it will come in a separate PR.

chore: synchronize sidebars for v8.2

---

docs/apis-tools/operate-api/overview.md
versioned_docs/version-8.2/apis-tools/operate-api/overview.md

Typo fix operate

---

docs/self-managed/operational-guides/update-guide/820-to-830.md

With the introduction of generalized command distribution we've had some breaking changes for custom exporterd that consume distribution records. This section explains what it's been replaced by.
with the 8.3 release

feat: document changes to exported records

---

docs/apis-tools/grpc.md

Document multi-tenancy for Zeebe gRPC.
:information_source: This PR is merged into the https://github.com/camunda/camunda-docs/tree/2561-multitenancy-sm branch where all multi-tenancy-related docs should be agregated before they are merged with `main`.
Closes #2686

Document multi-tenancy for Zeebe gRPC

---

docs/reference/supported-environments.md

Follow-up for https://github.com/camunda/camunda-docs/pull/2715

docs(web-modeler): correct Optimize version for 8.3.x

---

docs/self-managed/operational-guides/update-guide/820-to-830.md
docs/self-managed/platform-deployment/helm-kubernetes/upgrade.md
versioned_docs/version-8.3/self-managed/operational-guides/update-guide/820-to-830.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/upgrade.md

add migration warning

---

howtos/configuration.md

Update config page (docs on docs!) to include info about CLA Assistant

Add CLA assistant info

---

optimize/self-managed/optimize-deployment/migration-update/translation-diffs/differences_localization_310_311.diff
optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/migration-update/translation-diffs/differences_localization_310_311.diff

chore(optimize): update translation to match final release

---

docs/apis-tools/tasklist-api-rest/schemas/requests/task-search-request.mdx
docs/apis-tools/tasklist-api-rest/schemas/responses/form-response.mdx
docs/apis-tools/tasklist-api-rest/schemas/responses/task-response.mdx
docs/apis-tools/tasklist-api-rest/schemas/responses/task-search-response.mdx
docs/apis-tools/tasklist-api-rest/schemas/responses/variable-response.mdx
docs/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.3/apis-tools/tasklist-api-rest/schemas/requests/task-search-request.mdx
versioned_docs/version-8.3/apis-tools/tasklist-api-rest/schemas/responses/form-response.mdx
versioned_docs/version-8.3/apis-tools/tasklist-api-rest/schemas/responses/task-response.mdx
versioned_docs/version-8.3/apis-tools/tasklist-api-rest/schemas/responses/task-search-response.mdx
versioned_docs/version-8.3/apis-tools/tasklist-api-rest/schemas/responses/variable-response.mdx
versioned_docs/version-8.3/self-managed/tasklist-deployment/tasklist-configuration.md

Closes: https://github.com/camunda/tasklist/issues/3431
In this PR we are documenting changes done during implementing multi-tenancy for Tasklist application.

docs(MT:tasklist): document MT-related changes for Tasklist

---

docs/reference/supported-environments.md
versioned_docs/version-8.3/reference/supported-environments.md

Update supported environment for `8.3` and `next`.

update keycloak supported environment

---

docs/reference/announcements.md
versioned_docs/version-8.2/reference/announcements.md
versioned_docs/version-8.3/reference/announcements.md

chore(announcements): correct OpenSearch note

---

docs/reference/supported-environments.md
versioned_docs/version-8.3/reference/supported-environments.md

I noticed this mistake, but no related ticket as its a quick fix
No urgency, but the sooner the better in case users run into an issue trying to run Optimize on an old JDK

chore(docs): update minimum supported JDK for Optimize to 17

---

docs/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.3/self-managed/connectors-deployment/connectors-configuration.md

There is an [open PR](https://github.com/camunda/connectors/pull/1298) to enable stackdriver logging on connectors.
This is the documentation for this.

Added a section about connectors stackdriver logging configuration

---

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md

This PR adds documentation for new Element template options.
related to https://github.com/camunda/camunda-modeler/issues/3807
This should not be merged before the funcitonality is integrated into the modeler, cf. https://github.com/camunda/camunda-modeler/issues/3807

chore(element-templates): add new group options

---

docs/components/connectors/custom-built-connectors/connector-sdk.md
docs/components/connectors/use-connectors/index.md

Relates to https://github.com/camunda/connectors/issues/1322

chore(connectors): Add error variable support

---

docs/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
versioned_docs/version-8.3/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md

Solves #2769 
- I want to share the guide next week in the release presentation, and already shared with 2 customers in the last week who asked for it.

chore(guides): update modeler API reference to v1

---

docs/reference/announcements.md
docs/self-managed/operational-guides/update-guide/820-to-830.md
versioned_docs/version-8.3/reference/announcements.md
versioned_docs/version-8.3/self-managed/operational-guides/update-guide/820-to-830.md

chore: hint to multi-tenancy in migration note

---

versioned_docs/version-8.2/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md

Follow-up for https://github.com/camunda/camunda-docs/pull/2770, see https://github.com/camunda/camunda-docs/pull/2770#issuecomment-1777891039.

chore(guides): update Web Modeler CI/CD guide for 8.2

---

docs/self-managed/operational-guides/update-guide/820-to-830.md
versioned_docs/version-8.3/self-managed/operational-guides/update-guide/820-to-830.md

Fixes the header from changed to changes
Whenever 🤷

Fix typo in header

---

docs/reference/announcements.md
versioned_docs/version-8.3/reference/announcements.md

Related to https://github.com/camunda/camunda-docs/pull/2803.

adjust elasticsearch note

---

docs/components/best-practices/development/service-integration-patterns.md
docs/reference/announcements.md
docs/reference/early-access.md
docs/reference/status.md
src/pages/contact.md
versioned_docs/version-8.0/components/best-practices/development/service-integration-patterns.md
versioned_docs/version-8.0/components/console/console-troubleshooting/feedback-and-support.md
versioned_docs/version-8.0/components/zeebe/open-source/get-help-get-involved.md
versioned_docs/version-8.0/reference/status.md
versioned_docs/version-8.0/self-managed/platform-deployment/platform-8-deployment.md
versioned_docs/version-8.0/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.1/components/best-practices/development/service-integration-patterns.md
versioned_docs/version-8.1/components/console/console-troubleshooting/feedback-and-support.md
versioned_docs/version-8.1/reference/early-access.md
versioned_docs/version-8.1/reference/status.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/deploy.md
versioned_docs/version-8.1/self-managed/platform-deployment/overview.md
versioned_docs/version-8.1/self-managed/web-modeler/configuration.md
versioned_docs/version-8.1/self-managed/web-modeler/installation.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.2/components/best-practices/development/service-integration-patterns.md
versioned_docs/version-8.2/reference/early-access.md
versioned_docs/version-8.2/reference/status.md
versioned_docs/version-8.2/self-managed/platform-deployment/overview.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.3/components/best-practices/development/service-integration-patterns.md
versioned_docs/version-8.3/reference/announcements.md
versioned_docs/version-8.3/reference/early-access.md
versioned_docs/version-8.3/reference/status.md

Closes https://github.com/camunda/developer-experience/issues/129.

Docs feedback support links

---

docs/self-managed/zeebe-deployment/exporters/opensearch-exporter.md

Similar to [how we documented ILM for the Elasticsearch Exporter](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/exporters/elasticsearch-exporter/#retention), this documents ISM for the OpenSearch Exporter.
closes #2810

Add ISM to OpenSearch exporter configuration

---

versioned_docs/version-8.3/apis-tools/cli-client/cli-get-started.md
versioned_docs/version-8.3/self-managed/concepts/multi-tenancy.md

Increase the visibility of unsupported multi-tenancy features and clients in Camunda 8.3.
This includes signal broadcasting and resource deletion, as well as the GO and CLI clients.
closes #2781

Improve docs for unsupported multi-tenancy features in 8.3

---

docs/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md

Current guide does not reflect all required images. Additionally I included a statement to give users some guidance to identify images that are required for a concrete deployment.
Customers already reported the missing updates.

docs(guide): Adjust Air Gapped Installation Guide for 8.3 Release

---

docs/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.3/components/connectors/custom-built-connectors/connector-sdk.md

Correct connector links and versions

Remove pre 8.3.x note

---

versioned_docs/version-8.2/guides/update-guide/100-to-110.md

itty bitty bing adjustment

---

docs/guides/create-account.md
versioned_docs/version-8.1/guides/create-account.md
versioned_docs/version-8.2/guides/create-account.md
versioned_docs/version-8.3/guides/create-account.md

Resolves https://github.com/camunda/camunda-docs/issues/2889
Related to https://github.com/camunda/product-hub/issues/890

feat(guides): add experimentation disclaimer

---

docs/self-managed/modeler/web-modeler/configuration/configuration.md
docs/self-managed/modeler/web-modeler/configuration/identity.md
optimize_sidebars.js
optimize_versioned_sidebars/version-3.11.0-sidebars.json
sidebars.js
versioned_docs/version-8.3/self-managed/modeler/web-modeler/configuration/configuration.md
versioned_docs/version-8.3/self-managed/modeler/web-modeler/configuration/identity.md
versioned_sidebars/version-8.3-sidebars.json

Describes how to set up secure connections to Identity in Web Modeler.
Closes https://github.com/camunda/web-modeler/issues/6086.
- The feature is part of the `8.4.0-alpha1` release and will be mentioned in the blog post.
- It was also backported to 8.3 and will be available with Web Modeler's `8.3.1` patch release.

docs(web-modeler): document how to set up secure connections to Identity

---

optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/migration-update/3.10-to-3.11_8.3.md

related to OPT-7421
Also adding the changes from [this PR](https://github.com/camunda/camunda-docs/pull/2914) to the versioned docs, overlooked that in the last PR.

chore(upgrade): add known migration issue to versioned docs

---

docs/self-managed/platform-deployment/docker.md
versioned_docs/version-8.2/self-managed/platform-deployment/docker.md
versioned_docs/version-8.3/self-managed/platform-deployment/docker.md

Web Modeler only introduced multi-platform Docker images with the latest patch/alpha releases. This PR makes this clearer in the docs.
Relates to https://github.com/camunda/product-hub/issues/1013
- Multi-platform support for Web Modeler will be mentioned in the release blog post for `8.4.0-alpha1`.

docs(docker): add note on multi-platform support for Web Modeler

---

docs/self-managed/zeebe-deployment/operations/zeebe-in-production.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/operations/zeebe-in-production.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/zeebe-in-production.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/operations/zeebe-in-production.md

Overview page mentions rolling updates. However, rolling updates are not yet officially supported.
Also, the linked guide describes a cold update procedure.
https://github.com/camunda/product-hub/issues/256

docs(operations): Fix wrong information about update procedure

---

docs/self-managed/operational-guides/update-guide/820-to-830.md
versioned_docs/version-8.3/self-managed/operational-guides/update-guide/820-to-830.md

Add webhook connector changes to the update-guide

---

docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
docs/self-managed/zeebe-deployment/exporters/opensearch-exporter.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/exporters/opensearch-exporter.md

docs(zeebe-exporters): add form index infos

---

docs/components/best-practices/architecture/sizing-your-environment.md
docs/components/best-practices/architecture/understanding-human-tasks-management.md
docs/components/best-practices/best-practices-overview.md
docs/components/best-practices/development/connecting-the-workflow-engine-with-your-world.md
docs/components/best-practices/development/routing-events-to-processes.md
docs/components/best-practices/development/understanding-transaction-handling-c7.md
docs/components/best-practices/management/doing-a-proper-poc.md
docs/components/best-practices/management/following-the-customer-success-path.md
docs/components/best-practices/modeling/creating-readable-process-models.md
docs/components/best-practices/modeling/modeling-beyond-the-happy-path.md
docs/components/best-practices/modeling/modeling-with-situation-patterns.md
docs/components/best-practices/modeling/naming-bpmn-elements.md
docs/components/best-practices/modeling/naming-technically-relevant-ids.md

Docs review of BP, where I largely cleaned up the landing page. Are there additional adjustments you have been wanting to make @berndruecker? Let me know what you think of the new cards, as shown below. 🎄

technical review best practices

---

docs/components/connectors/protocol/http-webhook.md
docs/components/connectors/protocol/rest.md
docs/components/connectors/use-connectors/inbound.md
versioned_docs/version-8.1/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.1/components/connectors/protocol/rest.md
versioned_docs/version-8.1/components/connectors/use-connectors/inbound.md
versioned_docs/version-8.2/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.2/components/connectors/protocol/rest.md
versioned_docs/version-8.2/components/connectors/use-connectors/inbound.md
versioned_docs/version-8.3/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.3/components/connectors/protocol/rest.md
versioned_docs/version-8.3/components/connectors/use-connectors/inbound.md

Doing some refreshing of the connectors docs.
Anytime.

feat(connectors): refreshing docs

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/terraform-setup.md

Infex 10 Update

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eksctl.md

First review

---

docs/self-managed/operational-guides/update-guide/820-to-830.md
versioned_docs/version-8.3/self-managed/operational-guides/update-guide/820-to-830.md

Related to https://github.com/camunda/camunda-docs/pull/2932.

retro review of 2932

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eksctl.md

This PR is just preliminary and targeting a separate branch, not main! It's just a PR to get a technical review.
This does not follow writing best practices and will be reworked in the future when creating a PR from INFEX-6 to main.
It's an overlay of `INFEX-11` to contain helm specific changes required for the setup to work.
DevEx / Christina does not require a review from your side atm, but thanks 🙇!

chore(aws): add helm iteration to eksctl guide

---

docs/apis-tools/cli-client/index.md
versioned_docs/version-8.3/apis-tools/cli-client/index.md

Update CLI commands

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eksctl.md
optimize_sidebars.js
sidebars.js

This PR is just preliminary and targeting a separate branch, not main! It's just a PR to get a technical review.
This does not follow writing best practices and will be reworked in the future when creating a PR from `INFEX-6` to `main`.

chore(aws): add first iteration on eksctl usage

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/amazon-eks.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/terraform-setup.md
optimize_sidebars.js
sidebars.js

This PR is just preliminary and targeting a separate branch, not main! It's just a PR to get a technical review.
This does not follow writing best practices and will be reworked in the future when creating a PR from `INFEX-6` to `main`.

chore(aws): add first iteration on aws eks tf docs

---

docs/guides/create-decision-tables-using-dmn.md
versioned_docs/version-8.2/guides/create-decision-tables-using-dmn.md

Follow up to #2951 - fixes a typo BPMN --> DMN

DMN Guide typo

---

docs/apis-tools/grpc.md
versioned_docs/version-8.3/apis-tools/grpc.md

Update the GRPC docs for form deployment and deletion
Closes #2792 
Closes #2578

Form deployment and deletion GRPC

---

docs/guides/use-connectors-in-hybrid-mode.md
docs/self-managed/connectors-deployment/connectors-configuration.md
docs/self-managed/platform-deployment/helm-kubernetes/deploy.md
docs/self-managed/platform-deployment/manual.md
versioned_docs/version-8.1/guides/use-connectors-in-hybrid-mode.md
versioned_docs/version-8.1/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/deploy.md
versioned_docs/version-8.1/self-managed/platform-deployment/manual.md
versioned_docs/version-8.2/guides/use-connectors-in-hybrid-mode.md
versioned_docs/version-8.2/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/deploy.md
versioned_docs/version-8.2/self-managed/platform-deployment/manual.md
versioned_docs/version-8.3/guides/use-connectors-in-hybrid-mode.md
versioned_docs/version-8.3/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/deploy.md
versioned_docs/version-8.3/self-managed/platform-deployment/manual.md

Closes https://github.com/camunda/developer-experience/issues/113. See https://camunda.slack.com/archives/C0589TC88UU/p1700605301790419.

adjust references of connectors runtime

---

docs/reference/supported-environments.md
docs/self-managed/platform-deployment/overview.md
versioned_docs/version-8.1/reference/supported-environments.md
versioned_docs/version-8.1/self-managed/platform-deployment/overview.md
versioned_docs/version-8.2/reference/supported-environments.md
versioned_docs/version-8.2/self-managed/platform-deployment/overview.md
versioned_docs/version-8.3/reference/supported-environments.md
versioned_docs/version-8.3/self-managed/platform-deployment/overview.md

Missing Identity. Context: https://camunda.slack.com/archives/C03UR0V2R2M/p1701447510294469

chore(docs): add Identity as requirement for Optimize

---

docs/self-managed/zeebe-deployment/security/client-authorization.md

Related to https://github.com/camunda/camunda-docs/pull/2969.

retro review of 2969

---

docs/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md

Updated and improved a few things in our Air-gapped guide. [Issues-1081](https://github.com/camunda/distribution/issues/149)
- Elasticsearch Helm chart link pointed to deprecated repository updated to proper bitnami repository.
- Camunda Helm chart link updated to helm repository
- Added notes on how the charts should be installed and pointed them to our supported versions.
- Added Artifacthub.io reference
- ([EDIT](https://github.com/camunda/camunda-docs/pull/2931#issuecomment-1833650436)) Docker images hosted in Camunda's DockerHub organization are now mirrored in Camunda's Docker Registry.
No rush just a nice improvement.

updated air-gapped guide

---

optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/configuration/multi-tenancy.md
optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/configuration/system-configuration-platform-8.md

Adding backporting of Optimize MT docs to 8.3. 
Context: Because of merging into the MT docs branch earlier, the Optimize docs were not backported since8.3 was not yet released at the time. However, since the MT docs branch itself was merged late, backporting was required but overlooked.

chore(MT): backport optimize MT docs

---

docs/self-managed/concepts/multi-tenancy.md
versioned_docs/version-8.3/self-managed/concepts/multi-tenancy.md

Ensures users have a chance to learn about multi-tenancy limitations, on the main feature landing page:
* Only self-managed
* Only along the use of identity
This attempts to address feedback I gave in [two](https://camunda.slack.com/archives/C0555930H7F/p1702027932366439) [places](https://camunda.slack.com/archives/C0693F1NFK5/p1702030043265609?thread_ts=1701964504.521999&cid=C0693F1NFK5).

docs(self-managed): clearly layout limitations

---

docs/components/modeler/web-modeler/token-simulation.md
versioned_docs/version-8.3/components/modeler/web-modeler/token-simulation.md

This PR updates the token simulation documentation as per [this feedback](https://camunda.slack.com/archives/C032H77434N/p1702032295163309?thread_ts=1702022400.860369&cid=C032H77434N).
We don't want to delude users into thinking that token simulation simulates Camunda execution. In fact it simulates BPMN execution, and is a BPMN learning tool, not a Camunda learning tool. It does not intend to simulate Camunda, nor to be a full BPMN 2.0 engine.

docs(modeler): clearly scope token simulation purpose

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/amazon-eks.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/amazon-eks.md

Following reworks the Load Balancer insights of AWS a bit as the current docs were a bit vague.
Essentially the differentiation between Application and Network Load Balancer and what that means for TLS termination.
Additionally, 2 recommendations on how to get either one going.
For the reviewers, reviewing `/next` should be sufficient as the rest is copy & paste for the backport.

docs(aws): clarify on load balancer tls requirements

---

docs/reference/announcements.md
docs/self-managed/zeebe-deployment/configuration/gateway.md
docs/self-managed/zeebe-deployment/security/client-authorization.md

Deprecate the Zeebe configuration properties for Camunda Identity. Zeebe now integrates the identity-spring-boot-autoconfiguration module which picks up any Identity-specific configuration properties and provides them as an IdentityConfiguration instance to Zeebe.
closes #2980

refactor(self-managed): deprecate zeebe config props for identity

---

docs/reference/announcements.md
docs/reference/supported-environments.md

* Related to https://github.com/camunda/camunda-docs/issues/2886
* Follow-up potentially needed: rewie update guide to nudge users

Update es to 89+

---

docs/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.1/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.2/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.3/components/connectors/protocol/http-webhook.md

Add new feature doc.
With minor release (12th of December)

Webhook verification expression

---

docs/components/connectors/out-of-the-box-connectors/amazon-sqs.md
docs/components/connectors/out-of-the-box-connectors/rabbitmq-outbound.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/amazon-sqs.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/rabbitmq-outbound.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/amazon-sqs.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/rabbitmq-outbound.md
versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/amazon-sqs.md
versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/rabbitmq-outbound.md

docs(connectors): added notes to AMPQ and SQS connectors
Anytime, preferably with the next build since we have several customer requests related to this.

docs(connectors): added notes to AMPQ and SQS connectors

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/irsa.md

Adjusts the IAM Roles for Service Accounts docs for the 8.4 release with the latest required changes.
These changes are solely based on an Infra project to set up the current snapshot for QA. I'd potentially wait for the teams to have updated their docs to really confirm that this is the only required changed for IRSA.
Related to https://github.com/camunda/team-infrastructure-experience/issues/23

docs(aws): adjust irsa page to contain new info from 8.4 release

---

docs/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md

See https://camunda.slack.com/archives/C06112NS4GJ/p1702389469906659?thread_ts=1702379708.859659&cid=C06112NS4GJ

correct oidc meta and sidebar

---

docs/self-managed/operate-deployment/operate-configuration.md

* Add OpenSearch configuration for Operate

chore(operate): add OpenSearch configuration

---

docs/reference/announcements.md
versioned_docs/version-8.1/self-managed/identity/troubleshooting/common-problems.md
versioned_docs/version-8.2/self-managed/identity/troubleshooting/common-problems.md

Closes https://github.com/camunda/developer-experience/issues/200.

add known issue for keycloak

---

docs/self-managed/modeler/desktop-modeler/deploy-to-self-managed.md
versioned_docs/version-8.3/self-managed/modeler/desktop-modeler/deploy-to-self-managed.md

Related to https://github.com/camunda/camunda-modeler/issues/3966

feat(self-managed): add note about tenant ID

---

docs/reference/supported-environments.md

* related to camunda/product-hub#997

feat(supportedEnvs): add AWS OS 2.5 support note

---

docs/self-managed/operational-guides/update-guide/830-to-840.md
docs/self-managed/operational-guides/update-guide/introduction.md
optimize_sidebars.js
sidebars.js

Page created, added to intro, and both sidebars files. Component teams can now add their update instructions.

Add 8.4 update guide

---

docs/apis-tools/tasklist-api-rest/schemas/requests/task-search-request.mdx
versioned_docs/version-8.3/apis-tools/tasklist-api-rest/schemas/requests/task-search-request.mdx

Add stringfy on tasklist variables serch
Fix - Ready to go live

fix: tasklist stringfy request

---

docs/apis-tools/web-modeler-api/authentication.md
docs/apis-tools/web-modeler-api/index.md
docs/apis-tools/working-with-apis-tools.md
docs/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
optimize_sidebars.js
static/.htaccess
versioned_docs/version-8.2/apis-tools/web-modeler-api/index.md
versioned_docs/version-8.2/apis-tools/working-with-apis-tools.md
versioned_docs/version-8.3/apis-tools/working-with-apis-tools.md

Correcting sidebar, which decided to freak out after authentication/authorization changes.

resolve web modeler api sidebar

---

docs/reference/announcements.md

fix(announcements): fix indentation

---

docs/self-managed/identity/what-is-identity.md
versioned_docs/version-8.1/self-managed/identity/what-is-identity.md
versioned_docs/version-8.2/self-managed/identity/what-is-identity.md
versioned_docs/version-8.3/self-managed/identity/what-is-identity.md

Remove IAM admonition

---

docs/components/concepts/process-instance-migration.md
docs/components/operate/userguide/process-instance-migration.md

Removed the danger banner because it will be fixed in Zeebe with PR https://github.com/camunda/zeebe/pull/15621.

Update Process Instance Migration concept for 8.4 release

---

docs/reference/announcements.md
docs/self-managed/operate-deployment/data-retention.md
docs/self-managed/operate-deployment/operate-configuration.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/irsa.md
docs/self-managed/tasklist-deployment/data-retention.md
docs/self-managed/tasklist-deployment/tasklist-configuration.md

feat(announcements): create clarity of OS support

---

docs/self-managed/platform-deployment/helm-kubernetes/deploy.md
docs/self-managed/platform-deployment/helm-kubernetes/guides/accessing-components-without-ingress.md
docs/self-managed/platform-deployment/helm-kubernetes/guides/using-existing-keycloak.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
docs/self-managed/platform-deployment/helm-kubernetes/upgrade.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/deploy.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/accessing-components-without-ingress.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/guides/using-existing-keycloak.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
versioned_docs/version-8.1/self-managed/platform-deployment/helm-kubernetes/upgrade.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/deploy.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/accessing-components-without-ingress.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/using-existing-keycloak.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/upgrade.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/deploy.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/accessing-components-without-ingress.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/using-existing-keycloak.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/upgrade.md

Unify the example deployment name and use a real name instead of a placeholder.
Any time.

docs(self-managed): unify example deployment name

---

docs/components/connectors/out-of-the-box-connectors/amazon-sqs.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/amazon-sqs.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/amazon-sqs.md
versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/amazon-sqs.md

Add more understandable examples for SQS inbound connector
TBD

docs(ootbc): improve sqs connector docs

---

docs/self-managed/operational-guides/update-guide/820-to-830.md
docs/self-managed/operational-guides/update-guide/830-to-840.md
versioned_docs/version-8.3/self-managed/operational-guides/update-guide/820-to-830.md

feat(updateGuides): add note for supported environments

---

docs/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.1/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.2/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.3/self-managed/tasklist-deployment/tasklist-configuration.md

Relates to https://github.com/camunda/tasklist/issues/3124
As we have updated Docker build framework in latest Tasklist versions, we need to update configuration files location.
Can be merged along with the next releases train, or before if it is more convenient

chore(tasklist): Update Tasklist configuration files locations

---

docs/self-managed/platform-deployment/helm-kubernetes/guides/aws-marketplace.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/aws-marketplace.md

This fixes a bug inside the AWS Marketplace yaml.  I was on a call with AWS Marketplace team, and this seems to be the last thing we need before we can make our release published. This PR is a blocker, and should be released after merging if we want to go live on the AWS Marketplace by the end of the year (the current goal).
ASAP

fix: aws marketplace fixes required before publishing

---

docs/components/operate/userguide/process-instance-migration.md

feat(pim): deeplink limitations

---

docs/self-managed/zeebe-deployment/operations/cluster-scaling.md

docs(zeebe): update cluster scaling docs

---

docs/components/connectors/protocol/http-webhook.md
docs/components/connectors/use-connectors/index.md
docs/components/connectors/use-connectors/outbound.md
versioned_docs/version-8.1/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.1/components/connectors/use-connectors/index.md
versioned_docs/version-8.1/components/connectors/use-connectors/outbound.md
versioned_docs/version-8.2/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.2/components/connectors/use-connectors/index.md
versioned_docs/version-8.2/components/connectors/use-connectors/outbound.md
versioned_docs/version-8.3/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.3/components/connectors/use-connectors/index.md
versioned_docs/version-8.3/components/connectors/use-connectors/outbound.md

Some minor adjustments
Anytime

docs(connectors): explained several fields

---

docs/guides/automating-a-process-using-bpmn.md
docs/guides/configuring-out-of-the-box-connector.md
docs/guides/getting-started-orchestrate-apis.md
docs/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.1/guides/getting-started-orchestrate-apis.md
versioned_docs/version-8.2/guides/automating-a-process-using-bpmn.md
versioned_docs/version-8.2/guides/configuring-out-of-the-box-connector.md
versioned_docs/version-8.2/guides/getting-started-orchestrate-apis.md
versioned_docs/version-8.2/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.3/guides/automating-a-process-using-bpmn.md
versioned_docs/version-8.3/guides/configuring-out-of-the-box-connector.md
versioned_docs/version-8.3/guides/getting-started-orchestrate-apis.md
versioned_docs/version-8.3/guides/getting-started-orchestrate-microservices.md

Based on UI change: https://github.com/camunda/camunda-docs/issues/2661#issuecomment-1794709773

adjust camunda apps UI

---

docs/self-managed/modeler/web-modeler/configuration/configuration.md
docs/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md
versioned_docs/version-8.2/self-managed/modeler/web-modeler/configuration/configuration.md
versioned_docs/version-8.2/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md
versioned_docs/version-8.3/self-managed/modeler/web-modeler/configuration/configuration.md
versioned_docs/version-8.3/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md

Closes camunda/web-modeler#7357

docs(web-modeler):document zeebe client configuration

---

docs/self-managed/concepts/multi-tenancy.md
docs/self-managed/identity/user-guide/tenants/managing-tenants.md
versioned_docs/version-8.3/self-managed/concepts/multi-tenancy.md
versioned_docs/version-8.3/self-managed/identity/user-guide/tenants/managing-tenants.md

Closes https://github.com/camunda/camunda-docs/issues/2992.

link tenants and multi tenancy docs

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/amazon-eks.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eks-helm.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eksctl.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/terraform-setup.md

Based on internal discussions, we wanted to add an overview tiles pages on the new guides for easier linking in announcements etc. Target is for the announcement for customers of the 8.4 release.
We cut the titles a bit to look better on the main page.

docs(aws): add guidance tiles page for external reference

---

docs/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md

Relates to https://github.com/camunda/web-modeler/issues/7077

docs(web-modeler): document helm values for custom OIDC

---

docusaurus.config.js
spec/regression/versionMapping.spec.ts
src/versions.js
static/.htaccess
versioned_docs/version-8.1/components/best-practices/development/dealing-with-problems-and-exceptions.md
versioned_docs/version-8.1/components/best-practices/development/routing-events-to-processes.md
versioned_docs/version-8.1/self-managed/platform-deployment/troubleshooting.md
versioned_docs/version-8.2/apis-tools/working-with-apis-tools.md
versioned_docs/version-8.2/components/concepts/backups.md
versioned_docs/version-8.2/self-managed/platform-deployment/troubleshooting.md
versioned_docs/version-8.3/apis-tools/working-with-apis-tools.md
versioned_docs/version-8.3/self-managed/platform-deployment/troubleshooting.md
versioned_docs/version-8.4/apis-tools/working-with-apis-tools.md

The more reviewable part of #3151.
This PR includes some smaller changes for cutting versions 8.4/3.12.0, so that they are more easily reviewed.
Once this is merged, #3183 can be reviewed/merged.
There will likely be broken redirects on this one, until I can sniff them all out.

feat: versions 8.4/3.12.0, reviewable steps

---

docs/components/console/manage-clusters/resume-cluster.md
docs/components/console/manage-organization/usage-history.md
sidebars.js
versioned_docs/version-8.4/components/console/manage-clusters/resume-cluster.md
versioned_docs/version-8.4/components/console/manage-organization/usage-history.md
versioned_sidebars/version-8.4-sidebars.json

Add dev and prod clusters callout + resuming cluster page

---

docs/reference/announcements.md
versioned_docs/version-8.4/reference/announcements.md

* This makes the docs more easy to consume

chore(announcements): deeplink install guide from limitations

---

docs/reference/announcements.md
versioned_docs/version-8.4/reference/announcements.md

* Necessary after another round of hot fixes yesterday night

chore(announcements): correct affected versions

---

docs/reference/supported-environments.md
versioned_docs/version-8.4/reference/supported-environments.md

Update app matrix for 8.4

---

docs/self-managed/operate-deployment/data-retention.md
versioned_docs/version-8.4/self-managed/operate-deployment/data-retention.md

This just adds a small note to the documentation to make it clearer for users that the lifecyle management settings needed for OpenSearch ISM is exactly the same as for Elasticsearch.

Operate ISM configuration

---

docs/guides/migrating-from-cawemo.md
versioned_docs/version-8.4/guides/migrating-from-cawemo.md

Related to https://github.com/camunda/camunda-docs-static/pull/429.
@marcellobarile When can this actually be merged in and live? Placing a `hold` label for now.

add note on cawemo end of life

---

docs/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
versioned_docs/version-8.3/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
versioned_docs/version-8.4/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md

docs(web-modeler): document collaborator endpoints in CI/CD guide

---

sidebars.js

Low-effort way to start restructuring SM sidebar content. This change is only in `/next/` and may be merged and released to gather feedback.
Goes from this, with each component at the top level of the side bar:
To this, with component docs/config in a single group:

Add Components grouping to SM

---

docs/components/connectors/protocol/rest.md
versioned_docs/version-8.2/components/connectors/protocol/rest.md
versioned_docs/version-8.3/components/connectors/protocol/rest.md
versioned_docs/version-8.4/components/connectors/protocol/rest.md

Closes https://github.com/camunda/developer-experience/issues/221. Thank you for the catch @alessandrocavalli!

style(formatting): fix 404ing link

---

docs/components/components-overview.md
optimize_sidebars.js
optimize_versioned_sidebars/version-3.10.0-sidebars.json
optimize_versioned_sidebars/version-3.11.0-sidebars.json
optimize_versioned_sidebars/version-3.12.0-sidebars.json
optimize_versioned_sidebars/version-3.7.0-sidebars.json
optimize_versioned_sidebars/version-3.9.0-sidebars.json
versioned_docs/version-8.2/components/components-overview.md
versioned_docs/version-8.3/components/components-overview.md
versioned_docs/version-8.4/components/components-overview.md

Closes https://github.com/camunda/camunda-docs/issues/3127.

adjust components naming

---

docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
docs/self-managed/operational-guides/backup-restore/modeler-backup-and-restore.md
sidebars.js
versioned_docs/version-8.2/self-managed/backup-restore/backup-and-restore.md
versioned_docs/version-8.2/self-managed/backup-restore/modeler-backup-and-restore.md
versioned_docs/version-8.3/self-managed/operational-guides/backup-restore/backup-and-restore.md
versioned_docs/version-8.3/self-managed/operational-guides/backup-restore/modeler-backup-and-restore.md
versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/backup-and-restore.md
versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/modeler-backup-and-restore.md
versioned_sidebars/version-8.2-sidebars.json
versioned_sidebars/version-8.3-sidebars.json
versioned_sidebars/version-8.4-sidebars.json

docs(web-modeler): document Web Modeler backup & restore

---

docs/guides/automating-a-process-using-bpmn.md
sidebars.js

Based on feedback collected internally - https://miro.com/app/board/uXjVMq9qN3E=/
@christinaausley there is some awkwardness introduced here with the naming of guides, including "Automate a process using BPMN" now sitting in the **Design** section. Can you look at the names of these guides and propose changes? Remember that we can change the page title or sidebar title in the metadata. We don't necessarily need to change the URL. 
We should also evaluate what's in the docs issues as known changes to SaaS guides to see if we can properly sort future content into these buckets. Speaking of, I will add @christian-konrad as a reviewer since he's writing a lot of content and may want to float the SDLC/DevOps lifecycle group up one level. 
Closes #2614.

Add design, automate, improve to group guides

---

docs/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/zeebe-installation.md

A quick win for #2987, but will not close out the issue entirely.

Add warning for NFS + Zeebe

---

versioned_docs/version-8.2/guides/automating-a-process-using-bpmn.md
versioned_docs/version-8.3/guides/automating-a-process-using-bpmn.md
versioned_docs/version-8.4/guides/automating-a-process-using-bpmn.md
versioned_sidebars/version-8.2-sidebars.json
versioned_sidebars/version-8.3-sidebars.json
versioned_sidebars/version-8.4-sidebars.json

Backport 3239 - Design, Automate, Improve

Backport 3239 - Guides groupings for sidebar

---

docs/reference/supported-environments.md
versioned_docs/version-8.1/reference/supported-environments.md
versioned_docs/version-8.2/reference/supported-environments.md
versioned_docs/version-8.3/reference/supported-environments.md
versioned_docs/version-8.4/reference/supported-environments.md

[There was a question in the bpmn.io forums](https://forum.bpmn.io/t/camunda-forms-to-form-js-version-mapping/10621) about the support matrix of `form-js` and noticed that even though we have the [linting rules in the web/desktop modelers](https://github.com/camunda/form-linting/blob/main/lib/config/formVersion.js) we don't really document this anywhere else, so I added this to the supported envs sections.
I'm not really sure if there is the best place to put  it, so let me know if you think I should move @christinaausley or @akeller .
Closes https://github.com/camunda/team-hto/issues/502
- [ x I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.

feat: Add form-js to support matrix

---

docusaurus.config.js

Closes https://github.com/camunda/camunda-docs/issues/3271.

fix footer link to modeler

---

versioned_docs/version-8.1/components/operate/userguide/resolve-incidents-update-variables.md
versioned_docs/version-8.2/components/operate/userguide/resolve-incidents-update-variables.md
versioned_docs/version-8.3/components/operate/userguide/resolve-incidents-update-variables.md

Closes https://github.com/camunda/developer-experience/issues/121.

backport resolve incident fixme

---

docs/reference/status.md
src/pages/contact.md
versioned_docs/version-8.1/reference/status.md
versioned_docs/version-8.2/reference/status.md
versioned_docs/version-8.3/reference/status.md
versioned_docs/version-8.4/reference/status.md

Closes https://github.com/camunda/camunda-docs/issues/3319.

replace enterprise link

---

docs/reference/announcements.md
versioned_docs/version-8.4/reference/announcements.md

Added a caution banner due to a bug in Zeebe https://github.com/camunda/zeebe/issues/16311 and it is expected to fix in 8.4.3.

Update Camunda 8.4 Announcement For Form Linking Bug

---

versioned_sidebars/version-8.3-sidebars.json
versioned_sidebars/version-8.4-sidebars.json

Backport Component grouping in SM

---

docs/guides/host-custom-connector.md
docs/self-managed/connectors-deployment/connectors-configuration.md
docs/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md
versioned_docs/version-8.4/guides/host-custom-connector.md
versioned_docs/version-8.4/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md

Connectors now support different OIDC providers via Identity and use a different configuration format for Operate authentication. This PR replaces the old config format in the examples throughout the docs and provides info about variables required to run Connectors with a custom OIDC provider.
The change applies to 8.4 and 8.5-alpha.

feat(connectors): OIDC support

---

docs/reference/announcements.md
versioned_docs/version-8.1/reference/announcements.md
versioned_docs/version-8.2/reference/announcements.md
versioned_docs/version-8.3/reference/announcements.md
versioned_docs/version-8.4/reference/announcements.md

Announcement on a blocking bug in recent 8.1 and 8.2 patches.
We need to release this asap.

announcement: camunda/zeebe#16406 announcement

---

docs/reference/supported-environments.md
versioned_docs/version-8.4/reference/supported-environments.md

docs(web-modeler): add Web Modeler 8.5.0 to app version matrix

---

docs/self-managed/operational-guides/configure-multi-tenancy.md
versioned_docs/version-8.3/self-managed/operational-guides/configure-multi-tenancy.md
versioned_docs/version-8.4/self-managed/operational-guides/configure-multi-tenancy.md

Partially addresses #3301. 
Thread on Slack - https://camunda.slack.com/archives/CSQ2E3BT4/p1708120198687759?thread_ts=1707403002.934849&cid=CSQ2E3BT4

Add warning for disabling MT

---

docs/components/best-practices/management/doing-a-proper-poc.md
versioned_docs/version-1.3/components/best-practices/management/doing-a-proper-poc.md
versioned_docs/version-8.3/components/best-practices/management/doing-a-proper-poc.md
versioned_docs/version-8.4/components/best-practices/management/doing-a-proper-poc.md

Related to https://github.com/camunda/camunda-docs/pull/3384.
CC @tobiasschaefer

adjust Camunda typo

---

docs/apis-tools/zeebe-api/gateway-service.md
docs/components/concepts/process-instance-creation.md
versioned_docs/version-8.1/apis-tools/grpc.md
versioned_docs/version-8.1/components/concepts/process-instance-creation.md
versioned_docs/version-8.2/apis-tools/grpc.md
versioned_docs/version-8.2/components/concepts/process-instance-creation.md
versioned_docs/version-8.3/apis-tools/grpc.md
versioned_docs/version-8.3/components/concepts/process-instance-creation.md
versioned_docs/version-8.4/apis-tools/zeebe-api/gateway-service.md
versioned_docs/version-8.4/components/concepts/process-instance-creation.md

Closes https://github.com/camunda/camunda-docs/issues/3327.

add note to concepts section

---

docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/amazon-eks.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/google-gke.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/amazon-eks.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/google-gke.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/amazon-eks.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/google-gke.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks.md

Outcome of a working session - shifting the sentence structure to imply this is an example or option.

Subtle phrasing for Kubernetes flavors

---

howtos/documentation-guidelines.md

Closes https://github.com/camunda/camunda-docs/issues/3340

Add Identity contact

---

howtos/documentation-guidelines.md

Closes https://github.com/camunda/camunda-docs/issues/3341

Add InfEx contact

---

src/pages/contact.md

Partially addresses https://github.com/camunda/developer-experience/issues/251#issuecomment-1978118799 via quick win.

Direct link to C7 support page

---

docs/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.1/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/zeebe-installation.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/zeebe-installation.md

Add "other volume storage types" to NFS admonition

---

docs/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.1/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.2/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.4/components/connectors/out-of-the-box-connectors/slack.md

docs(ootbc,slack): updated Slack doc with new property
Should go around next patch release - around 13th of March

docs(ootbc,slack): updated Slack doc with new property

---

docs/apis-tools/tasklist-api-rest/migrate-to-zeebe-user-tasks.md

feat: add alpha availability hint to migration guide

---

docs/guides/migrating-from-camunda-7/adjusting-bpmn-models.md
docs/guides/migrating-from-camunda-7/adjusting-dmn-models.md
docs/guides/migrating-from-cawemo.md

Closes https://github.com/camunda/web-modeler/issues/7708

docs: update information about improved C7 support

---

docs/self-managed/concepts/exporters.md
versioned_docs/version-8.1/self-managed/concepts/exporters.md
versioned_docs/version-8.2/self-managed/concepts/exporters.md
versioned_docs/version-8.3/self-managed/concepts/exporters.md
versioned_docs/version-8.4/self-managed/concepts/exporters.md

A follow up to backport #3468. Thanks @jangalinski!

Update Exporter GitHub links

---

docs/components/modeler/desktop-modeler/troubleshooting.md
docs/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md
docs/self-managed/operational-guides/troubleshooting/troubleshooting.md
docs/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/amazon-eks.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/google-gke.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks.md
docs/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
sidebars.js
static/.htaccess
versioned_docs/version-8.4/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-zeebe-connection.md

Part of the SM restructure. This only adjusts `/next/` where the bulk of the restructuring will take place.

Consolidate troubleshooting in SM

---

docs/components/connectors/out-of-the-box-connectors/github.md

Documents:
* https://github.com/camunda/connectors/issues/2022
* https://github.com/camunda/connectors/issues/2024
* https://github.com/camunda/connectors/issues/2025
* https://github.com/camunda/connectors/issues/2158

docs(connectors): add new GitHub connector operations

---

docs/reference/supported-environments.md
versioned_docs/version-8.3/reference/supported-environments.md
versioned_docs/version-8.4/reference/supported-environments.md

docs(reference): Add Connectors information to supported environments

---

docs/guides/use-connectors-in-hybrid-mode.md

docs(connectors): Add hybrid secret docs

---

docs/guides/create-account.md
versioned_docs/version-8.2/guides/create-account.md
versioned_docs/version-8.3/guides/create-account.md

Related to https://github.com/camunda/camunda-docs/pull/3520.

3520 backport

---

docs/components/modeler/forms/form-element-library/forms-element-library.md

Related to https://github.com/camunda/camunda-docs/pull/3528.

3528 follow up

---

optimize/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/configuration/system-configuration.md

This is not new config, it is just not something that we documented previously
No huge urgency, just whenever the docs are next released is fine

chore(docs): document email server checking configuration option

---

docs/self-managed/zeebe-deployment/security/secure-client-communication.md

This PR documents how to configure SSL/TLS for the REST API server.
Should go live with 8.5.0.

docs: SSL configuration for REST API

---

docs/components/operate/userguide/process-instance-migration.md

docs(operate): update supported elements in migration guide

---

api/generate-api-docs.js
api/zeebe/generation-strategy.js
api/zeebe/post-generate.sh
howtos/interactive-api-explorers.md
package-lock.json
package.json

* Refactors some developer tooling for generating API explorers, so that it makes sense for all known API explorers. 
Steps that were previously chained sequentially in the package.json are now formalized in a JavaScript file, with the ability for each API Explorer to specify its custom needs. 
* Converts the Zeebe REST API Explorer to use this new generation workflow as an example.
* Documents this updated generation workflow.
* Conversion of Tasklist and Operate APIs to use this new generation workflow. Those will be coming in two separate follow-up PRs.

refactor: generalize the strategy for generating API Explorers

---

docs/apis-tools/spring-zeebe-sdk/configuration.md
docs/apis-tools/spring-zeebe-sdk/getting-started.md
docs/apis-tools/working-with-apis-tools.md
sidebars.js

Related to https://github.com/camunda/product-hub/issues/2148.

draft spring zeebe sdk

---

docs/apis-tools/tasklist-api-rest/migrate-to-zeebe-user-tasks.md
docs/components/modeler/bpmn/user-tasks/user-tasks.md
docs/components/tasklist/introduction-to-tasklist.md

feat(user-tasks): remove notes for Zeebe task availability in alpha

---

docs/apis-tools/working-with-apis-tools.md
docs/apis-tools/zeebe-api-rest/zeebe-api-rest-overview.md

feat(apis-tools): add entry card to Zeebe REST API

---

docs/apis-tools/spring-zeebe-sdk/getting-started.md

Eating own dogfood I stumbled over this invalid annotation and misleading section name (it also described SM setup not just SaaS)

fix: spring zeebe sdk doc improvements

---

versioned_docs/version-8.4/components/components-overview.md
versioned_docs/version-8.4/components/console/introduction-to-console.md
versioned_docs/version-8.4/guides/introduction-to-camunda-8.md
versioned_docs/version-8.4/guides/setup-client-connection-credentials.md
versioned_docs/version-8.4/self-managed/about-self-managed.md

Closes https://github.com/camunda/developer-experience/issues/287.

clarify console saas/sm

---

docs/reference/release-policy.md

Closes https://github.com/camunda/developer-experience/issues/281.

add versioning details to release policy

---

docs/apis-tools/tasklist-api-rest/tasklist-api-rest-tutorial.md

Fixes broken link from SM restructure.

might as well call myself broken link betty at this point

---

docs/apis-tools/java-client/zeebe-process-test.md
versioned_docs/version-8.4/apis-tools/java-client/zeebe-process-test.md

Zeebe process test requires java 21+ 

---

optimize_versioned_sidebars/version-3.11.0-sidebars.json
versioned_sidebars/version-8.3-sidebars.json

Synchronizes sidebars for **v8.3**.
* There are many whitespace changes in this PR. In the past I've not included whitespace changes for sidebar synchronization, but since they are generated by the script consistently every time, we realized it makes more sense to commit them....so that in the future, all we see during synchronization are meaningful changes.
* There are no significant changes in the main instance's sidebars.json file! 
* There are many significant changes in the Optimize instance's optimize_sidebars.json file. We made a big folder for all the Components in the Self-Managed documentation.

chore(sidebars): sync sidebars in v8.3/3.11.0

---

optimize_versioned_sidebars/version-3.10.0-sidebars.json
versioned_sidebars/version-8.2-sidebars.json

Synchronizes sidebars for **v8.2**.
* There are many whitespace changes in this PR. In the past I've not included whitespace changes for sidebar synchronization, but since they are generated by the script consistently every time, we realized it makes more sense to commit them....so that in the future, all we see during synchronization are meaningful changes.
* There are no significant changes in the main instance's sidebars.json file! 
* There are a few significant changes in the Optimize instance's optimize_sidebars.json file.

chore(sidebars): sync sidebars in v8.2/3.10.0

---

optimize_versioned_sidebars/version-3.9.0-sidebars.json
versioned_sidebars/version-8.1-sidebars.json

Synchronizes sidebars for **v8.1**.
* There are many whitespace changes in this PR. In the past I've not included whitespace changes for sidebar synchronization, but since they are generated by the script consistently every time, we realized it makes more sense to commit them....so that in the future, all we see during synchronization are meaningful changes.
* There are no significant changes in the main instance's sidebars.json file! 
* There are a few significant changes in the Optimize instance's optimize_sidebars.json file.

chore(sidebars): sync sidebars in v8.1/3.9.0

---

optimize_versioned_sidebars/version-3.7.0-sidebars.json

Synchronizes sidebars for **v1.3**.
* There are some whitespace changes in this PR. In the past I've not included whitespace changes for sidebar synchronization, but since they are generated by the script consistently every time, we realized it makes more sense to commit them....so that in the future, all we see during synchronization are meaningful changes.
* There are no changes at all in the main instance's sidebars.json file! 
* There is one significant change in the Optimize instance's optimize_sidebars.json file.

chore(sidebars): sync sidebars in v1.3/3.7.0

---

docusaurus.config.js

In #3630, I added a new version to the Optimize docs, but forgot to remove the "unsupported" banner that appears for Optimize version 3.12. 
This PR turns the "unsupported" banner off for Optimize version 3.12.
How it looked when it was broken:
How it looks with this fix:

fix: remove the 'unsupported' banner from the optimize 3.12 docs

---

docs/reference/announcements.md
docs/self-managed/operational-guides/update-guide/840-to-850.md
docs/self-managed/setup/upgrade.md
versioned_docs/version-8.5/reference/announcements.md
versioned_docs/version-8.5/self-managed/operational-guides/update-guide/840-to-850.md
versioned_docs/version-8.5/self-managed/setup/upgrade.md

This announcements change notes that there are some deprecated options in our helm values.yaml which will be removed in the 8.6 release.  We hope for this change to be merged with 8.5 so that customers who upgrade will change their values.yaml syntax during the 8.5 release instead of 8.6 when we will remove the compatibility layer.

docs(self-managed): add helm chart section in 8.5 announcements

---

docs/components/modeler/desktop-modeler/flags/flags.md
versioned_docs/version-1.3/components/modeler/desktop-modeler/flags/flags.md
versioned_docs/version-8.1/components/modeler/desktop-modeler/flags/flags.md
versioned_docs/version-8.2/components/modeler/desktop-modeler/flags/flags.md
versioned_docs/version-8.3/components/modeler/desktop-modeler/flags/flags.md
versioned_docs/version-8.4/components/modeler/desktop-modeler/flags/flags.md

Related to https://github.com/camunda/camunda-docs/pull/3570.

match text and code snippet

---

docs/apis-tools/spring-zeebe-sdk/configuration.md
docs/components/best-practices/operations/operating-camunda-c7.md
docs/self-managed/setup/guides/ingress-setup.md
docs/self-managed/setup/upgrade.md
versioned_docs/version-8.1/components/best-practices/operations/operating-camunda-c7.md
versioned_docs/version-8.2/components/best-practices/operations/operating-camunda-c7.md
versioned_docs/version-8.3/components/best-practices/operations/operating-camunda-c7.md
versioned_docs/version-8.4/components/best-practices/operations/operating-camunda-c7.md
versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.5/components/best-practices/operations/operating-camunda-c7.md
versioned_docs/version-8.5/self-managed/setup/guides/ingress-setup.md
versioned_docs/version-8.5/self-managed/setup/upgrade.md

Originally a quick fix after @theburi flagged https://docs.camunda.io/docs/next/self-managed/setup/upgrade/, but caught a few others along the way.

bug fix admonitions

---

docs/reference/announcements.md
docs/self-managed/setup/upgrade.md
versioned_docs/version-8.5/reference/announcements.md
versioned_docs/version-8.5/self-managed/setup/upgrade.md

Warning for customer to not upgrade as 10.0.0 and 10.0.1 are broken.

Add a warning message to not Update upgrade until major 10.0.1 issues are fixed.

---

docs/reference/announcements.md
docs/self-managed/operational-guides/update-guide/840-to-850.md
docs/self-managed/setup/upgrade.md
versioned_docs/version-8.5/reference/announcements.md
versioned_docs/version-8.5/self-managed/operational-guides/update-guide/840-to-850.md
versioned_docs/version-8.5/self-managed/setup/upgrade.md

We fixed the issue with the severe issue in the HCs and users should upgrade directly to 10.0.2, see [#inc-grpc-port-is-not-exposed-on-sm-helm-10001](https://camunda.slack.com/archives/C06U15BDARF) for more context. He also added this warning to the [release notes of 10.0.2](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-10.0.2).

Update warning caution message for HC v10 upgrade guide

---

docs/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md

Spring Zeebe SDK users should add a repo into their Maven `settings.xml` file in order to make it works

docs(spring-zeebe-sdk): add repo for identity sdk

---

docs/self-managed/operational-guides/update-guide/850-to-860.md
sidebars.js

8.6.0 let's gooooo. 
This will only be available in `/next/`. No backporting necessary.

Add 860 update guide

---

docs/reference/announcements.md
versioned_docs/version-8.5/reference/announcements.md

* Related follow-up (low-prio): #3668

feat(announcements): document upcoming change to generation naming

---

docs/self-managed/concepts/opensearch-privileges.md
sidebars.js
versioned_docs/version-8.4/self-managed/concepts/opensearch-privileges.md
versioned_docs/version-8.5/self-managed/concepts/opensearch-privileges.md
versioned_sidebars/version-8.4-sidebars.json
versioned_sidebars/version-8.5-sidebars.json

Related to https://github.com/camunda/operate/issues/6227
* Add OpenSearch privileges page in concepts 
* Add page entry in side bar menu
* Testing of the privileges/permissions is described in https://github.com/camunda/operate/issues/6227#issuecomment-1954607823
* Add OpenSearch privileges page to `8.4` and `8.5`
Closes #3343

operate-6227-opensearch-permissions

---

docs/reference/release-notes/850.md
versioned_docs/version-8.5/reference/release-notes/850.md

Follow up from comment in #3455 - https://github.com/camunda/camunda-docs/pull/3455#discussion_r1561840152

Follow up on 8.5 release notes - Zeebe API

---

docs/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.5/self-managed/connectors-deployment/connectors-configuration.md

Connectors: Fix broken code snippet

---

optimize_versioned_sidebars/version-3.13.0-sidebars.json

No changes to sidebar.js, just a bunch of whitespace.

sync sidebars 8.5/3.13

---

optimize_versioned_sidebars/version-3.12.0-sidebars.json

sync sidebars 8.4/3.12

---

docs/apis-tools/community-clients/spring.md
versioned_docs/version-8.5/apis-tools/community-clients/spring.md

See [Slack discussion](https://camunda.slack.com/archives/C026U8GBNSW/p1712929779231069).

note spring sdk in community client

---

docs/components/console/manage-organization/manage-users.md
versioned_docs/version-8.1/components/console/manage-organization/manage-users.md
versioned_docs/version-8.2/components/console/manage-organization/manage-users.md
versioned_docs/version-8.3/components/console/manage-organization/manage-users.md
versioned_docs/version-8.4/components/console/manage-organization/manage-users.md
versioned_docs/version-8.5/components/console/manage-organization/manage-users.md

Closes https://github.com/camunda/camunda-docs/issues/3469.

rephrase personal organization

---

docs/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/management-api.md

Retro review of https://github.com/camunda/camunda-docs/pull/3720.

retro review 3720

---

docs/reference/glossary.md
docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
versioned_docs/version-8.2/reference/glossary.md
versioned_docs/version-8.2/self-managed/backup-restore/backup-and-restore.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.3/reference/glossary.md
versioned_docs/version-8.3/self-managed/operational-guides/backup-restore/backup-and-restore.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.4/reference/glossary.md
versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/backup-and-restore.md
versioned_docs/version-8.5/reference/glossary.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/backup-and-restore.md

This PR changes the protocol for backup and restore using the hot backups. https://docs.camunda.io/docs/next/self-managed/operational-guides/backup-restore/backup-and-restore/
Now using the soft pause for the exporter the record to ES will continue to be exported, so the exported records backup needs to be performed first and completed before initializing the zeebe backup. 
closes https://github.com/camunda/zeebe/issues/17425

Hot Backups: Document changes in protocol for backup and restore.

---

docs/reference/supported-environments.md
optimize/self-managed/optimize-deployment/migration-update/3.13_8.5-to-3.14_8.6.md
versioned_docs/version-8.5/reference/supported-environments.md

Optimize is dropping the support for Java 17 and 20, in favor of Java 21.
With this PR, the documentation will be updated accordingly.
Issue: https://github.com/camunda/camunda-optimize/issues/12541
Contextually with the release of Optimize 3.14 (scheduled for 8th of October 2024)

docs(requirements): update optimize requirement with Java 21

---

docs/self-managed/setup/guides/connect-to-an-oidc-provider.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md
versioned_docs/version-8.5/self-managed/setup/guides/connect-to-an-oidc-provider.md

Whilst working through an issue with @McAlm I noticed that there was a missing env variable in the docs along with a missing link to our mapping rule page. I've now added these both in and applied to previous versions.

docs(general): add missing link back and variable to the oidc docs

---

docs/self-managed/setup/deploy/amazon/amazon-eks/irsa.md
docs/self-managed/setup/guides/using-existing-opensearch.md
docs/self-managed/setup/install.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/irsa.md
versioned_docs/version-8.5/self-managed/setup/guides/using-existing-opensearch.md
versioned_docs/version-8.5/self-managed/setup/install.md

Changed wording in `8.5` docs to include the opensearch guide on the install page.

Change openserach wording

---

docs/apis-tools/tasklist-api-rest/tasklist-api-rest-tutorial.md
versioned_docs/version-8.5/apis-tools/tasklist-api-rest/tasklist-api-rest-tutorial.md

The Tasklist REST API tutorial uses the community-supported Spring Zeebe project. This is potentially confusing and can risk increasing support tickets.

Add community-supported disclaimer to Tasklist tutorial

---

docs/components/modeler/web-modeler/camunda-marketplace.md
docs/guides/automating-a-process-using-bpmn.md
docs/guides/configuring-out-of-the-box-connector.md
docs/guides/create-decision-tables-using-dmn.md
docs/guides/getting-started-orchestrate-apis.md
docs/guides/getting-started-orchestrate-human-tasks.md
docs/guides/getting-started-orchestrate-microservices.md
docs/guides/model-your-first-process.md
docs/guides/utilizing-forms.md
versioned_docs/version-8.5/components/modeler/web-modeler/camunda-marketplace.md
versioned_docs/version-8.5/guides/automating-a-process-using-bpmn.md
versioned_docs/version-8.5/guides/configuring-out-of-the-box-connector.md
versioned_docs/version-8.5/guides/create-decision-tables-using-dmn.md
versioned_docs/version-8.5/guides/getting-started-orchestrate-apis.md
versioned_docs/version-8.5/guides/getting-started-orchestrate-human-tasks.md
versioned_docs/version-8.5/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.5/guides/model-your-first-process.md
versioned_docs/version-8.5/guides/utilizing-forms.md

Update documentation to reflect changes from https://github.com/camunda/web-modeler/issues/2096 and https://github.com/camunda/web-modeler/issues/8244.

chore(web-modeler): fix names of "create new" menu and menu items

---

docs/components/connectors/protocol/http-webhook.md

https://github.com/camunda/connectors/issues/2060
With the next alpha of 8.6

feat(connectors): Response expression

---

docs/components/connectors/use-connectors/index.md
versioned_docs/version-1.3/components/best-practices.md
versioned_docs/version-8.4/components/connectors/use-connectors/index.md
versioned_docs/version-8.5/components/connectors/use-connectors/index.md

Follow up to https://github.com/camunda/camunda-docs/pull/3775. Thanks @tobiasschaefer!

fix bmpn errors

---

docs/self-managed/concepts/multi-region/dual-region.md
docs/self-managed/operational-guides/multi-region/dual-region-ops.md
docs/self-managed/setup/deploy/amazon/amazon-eks/dual-region.md
versioned_docs/version-8.5/self-managed/concepts/multi-region/dual-region.md
versioned_docs/version-8.5/self-managed/operational-guides/multi-region/dual-region-ops.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/dual-region.md

Improve phrasing around supported environments as per this discussion: https://camunda.slack.com/archives/C0486FPV076/p1713528935569049?thread_ts=1713370090.038159&cid=C0486FPV076
Mainly around removing the point that k8s is the only possible option for dual-region and putting k8s as the recommended installation method only.

chore(dual-region): Improve phrasing around supported envrionments

---

docs/components/modeler/web-modeler/camunda-marketplace.md

Follow up to correct UI in https://github.com/camunda/camunda-docs/pull/3763.

update UI references

---

docs/reference/release-notes/860.md

Based on DMs, we need to add https://github.com/camunda/product-hub/issues/1983 to the 8.6.0-alpha1 release notes.

Add to alpha1 release notes

---

docs/self-managed/zeebe-deployment/operations/resource-planning.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/resource-planning.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/operations/resource-planning.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/resource-planning.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/resource-planning.md

This pr removes reference to the maximum number of snapshots in the resource planing doc, since this is always one.
Closes: https://github.com/camunda/camunda-docs/issues/3777

Remove references to max number of snapshots.

---

docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
docs/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eks-helm.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/terraform-setup.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md

Bumps a couple of versions in the EKS guides for 8.4 and 8.5.
Tested it on AWS.

chore(docs): bump aws eks guide versions

---

docs/apis-tools/spring-zeebe-sdk/configuration.md
docs/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md

Links that use `/docs` route users to the `/next/` docs, not the proper version. We need to remove these.

Remove `/docs` from Spring Zeebe docs

---

docs/apis-tools/administration-api/authentication.md
docs/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
docs/reference/usage-metrics.md
versioned_docs/version-8.2/apis-tools/administration-api-reference.md
versioned_docs/version-8.2/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
versioned_docs/version-8.2/reference/usage-metrics.md
versioned_docs/version-8.3/apis-tools/administration-api-reference.md
versioned_docs/version-8.3/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
versioned_docs/version-8.3/reference/usage-metrics.md
versioned_docs/version-8.4/apis-tools/administration-api/authentication.md
versioned_docs/version-8.4/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
versioned_docs/version-8.4/reference/usage-metrics.md
versioned_docs/version-8.5/apis-tools/administration-api/authentication.md
versioned_docs/version-8.5/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
versioned_docs/version-8.5/reference/usage-metrics.md

When I was addressing #3804, I noticed we had a few instances where we have fully qualified URLs in the docs, including ones referencing 8.1 😱. We don't want this! Docusaurus cannot map the versions correctly when fully qualified URLs are used.

Remove fully qualified URLs from docs

---

docs/reference/release-notes/850.md
docs/reference/release-notes/860.md
versioned_docs/version-8.5/reference/release-notes/850.md

Add release dates for alphas and minor 8.5+. EOMs are also included for minors. Related to https://github.com/camunda/developer-experience/issues/304.

Add release date and EOM to release notes

---

docs/self-managed/setup/deploy/other/docker.md
optimize/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/configuration/system-configuration.md
versioned_docs/version-8.2/self-managed/platform-deployment/docker.md
versioned_docs/version-8.3/self-managed/platform-deployment/docker.md
versioned_docs/version-8.4/self-managed/platform-deployment/docker.md
versioned_docs/version-8.5/self-managed/setup/deploy/other/docker.md

Context:
https://github.com/camunda/camunda-optimize/issues/11941
With this PR, we are adding the documentation about the option to enable or disable the SNI check.

docs(optimize): document SNI configuration options

---

docs/reference/announcements.md
versioned_docs/version-8.2/reference/announcements.md
versioned_docs/version-8.3/reference/announcements.md
versioned_docs/version-8.4/reference/announcements.md
versioned_docs/version-8.5/reference/announcements.md

From https://camunda.slack.com/archives/C072UPGHUL9 via https://camunda.slack.com/archives/C072UPGHUL9/p1716303055451519.
I have backported this change to all supported versions since it's a breaking change happening outside of a specific version.

Announce repo rename impact to Go Client

---

docs/self-managed/zeebe-deployment/configuration/configuration.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/configuration/configuration.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/configuration/configuration.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/configuration/configuration.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/configuration/configuration.md

Relates to https://github.com/camunda/camunda-docs/issues/3744.

fix configuration file links

---

docs/components/best-practices/development/testing-process-definitions.md
versioned_docs/version-8.2/components/best-practices/development/testing-process-definitions.md
versioned_docs/version-8.3/components/best-practices/development/testing-process-definitions.md
versioned_docs/version-8.4/components/best-practices/development/testing-process-definitions.md
versioned_docs/version-8.5/components/best-practices/development/testing-process-definitions.md

https://camunda.slack.com/archives/C026U8GBNSW/p1715108598770169

Remove extra annotation - @SpringBootTest

---

docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
docs/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
docs/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eks-helm.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eksctl.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/terraform-setup.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md

Based on customer feedback, adding more explicit statements on PostgreSQL usage for KeyCloak. Explicitly mention export of required values for the follow up guide on deploying C8.
Lastly use the latest helm chart values for 8.5 and next. While the former values are still supported, it may confuse customers as they're not documented anymore.
Postgres change concerning 8.4/8.5/next.
Helm chart value updates concerning 8.5/next.

chore(doc): use latest 8.5 helm values and explicitly state postgres usage

---

docs/self-managed/operational-guides/multi-region/dual-region-ops.md
versioned_docs/version-8.5/self-managed/operational-guides/multi-region/dual-region-ops.md

Follow-up on https://github.com/camunda/camunda-docs/pull/3756, one place was missing to align the wording on (dual region ops procedure as well)

chore(dual-region): Address old wording for operational procedure

---

docs/guides/migrating-from-camunda-7/migration-readiness.md
versioned_docs/version-8.2/guides/migrating-from-camunda-7/migration-readiness.md
versioned_docs/version-8.3/guides/migrating-from-camunda-7/migration-readiness.md
versioned_docs/version-8.4/guides/migrating-from-camunda-7/migration-readiness.md
versioned_docs/version-8.5/guides/migrating-from-camunda-7/migration-readiness.md

This statement is misleading:
https://github.com/camunda/camunda-docs/blob/baddf89bfbc49b8e99c19e93f540d7a762bfb0c5/versioned_docs/version-8.5/guides/migrating-from-camunda-7/migration-readiness.md?plain=1#L33
Due to the Modelers setting the execution platform explicitly in a model, all DMN files need adjustments:
https://docs.camunda.io/docs/guides/migrating-from-camunda-7/adjusting-dmn-models/
The links may require adjustment and the changes should be backported.

Fix: replace misleading statements on DMN migration with links to pages with more information

---

docs/self-managed/concepts/multi-region/dual-region.md
versioned_docs/version-8.5/self-managed/concepts/multi-region/dual-region.md

* Task assignment data is not propagated to the respective other ES instance. Hence task assignments are lost for completed and uncompleted tasks.

fix(dual-region): more precise language for tasklist limitations

---

docs/components/operate/userguide/process-instance-migration.md
versioned_docs/version-8.5/components/operate/userguide/process-instance-migration.md

docs(operate): add call activities to supported elements in instance migration guide

---

docs/reference/announcements.md
versioned_docs/version-8.2/reference/announcements.md
versioned_docs/version-8.3/reference/announcements.md
versioned_docs/version-8.4/reference/announcements.md
versioned_docs/version-8.5/reference/announcements.md

We found out that this is not an issue for users, as they can still request the old release and versions.
See related message https://camunda.slack.com/archives/C06HTSPD5AP/p1716792823991149

Remove go module announcement changes

---

optimize/apis-tools/optimize-api/tutorial.md
optimize_versioned_docs/version-3.13.0/apis-tools/optimize-api/tutorial.md

This PR fixes `main`. 
In #3708, we somehow managed to sneak in a broken link (I don't exactly know how it wasn't caught by CI).
This PR corrects some links from that PR.

fix: link to actual create-cluster page

---

optimize_sidebars.js
optimize_versioned_sidebars/version-3.13.0-sidebars.json

Reported internally - https://camunda.slack.com/archives/C026U8GBNSW/p1716820664357739

Add orphaned page to Optimize sidebars

---

docs/apis-tools/go-client/go-get-started.md
docs/reference/announcements.md

Following up to the Go client `camunda/zeebe` -> `camunda/camunda` repo rename, specifically for 8.6+ projects.

Add Go client repo rename changes to 8.6

---

docs/reference/release-notes/850.md
docs/reference/release-notes/860.md
versioned_docs/version-8.5/reference/release-notes/850.md

fix(releaseNotes): correct table header row

---

optimize/self-managed/optimize-deployment/configuration/history-cleanup.md
optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/configuration/history-cleanup.md
optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/configuration/history-cleanup.md
optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/configuration/history-cleanup.md
optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/configuration/history-cleanup.md
optimize_versioned_docs/version-3.7.0/self-managed/optimize-deployment/setup/history-cleanup.md

Oops, this never made it to the backlog. But here is is now!
From internal Slack thread - https://camunda.slack.com/archives/C026U8GBNSW/p1712197115109369

processDataCleanupMode -> cleanupMode

---

docs/components/console/manage-clusters/manage-ip-allowlists.md
versioned_docs/version-8.2/components/console/manage-clusters/manage-ip-allowlists.md
versioned_docs/version-8.3/components/console/manage-clusters/manage-ip-allowlists.md
versioned_docs/version-8.4/components/console/manage-clusters/manage-ip-allowlists.md
versioned_docs/version-8.5/components/console/manage-clusters/manage-ip-allowlists.md

Brief docs for https://github.com/camunda/product-hub/issues/2184

Add web modeler note for allowlist

---

docs/components/concepts/access-control/user-task-access-restrictions.md
docs/self-managed/concepts/access-control/user-task-access-restrictions.md
versioned_docs/version-8.5/components/concepts/access-control/user-task-access-restrictions.md
versioned_docs/version-8.5/self-managed/concepts/access-control/user-task-access-restrictions.md

I'm adding more information about APIs as we got feedback from a customer that this wasn't clear here: https://jira.camunda.com/browse/SUPPORT-21876?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D
This change can go live at any moment.

docs: adding info on task access restrictions and APIs

---

docs/apis-tools/zeebe-api/gateway-service.md

Update zeebe gateway-service docs to include `operationReference` field in the appropriate grpc requests
Related to: 
https://github.com/camunda/camunda/pull/18669
closes: https://github.com/camunda/camunda/issues/19080

docs(zeebe): update zeebe gateway-service docs to include `operationReference` field in the appropriate grpc requests

---

optimize/components/userguide/additional-features/alerts.md
optimize_versioned_docs/version-3.12.0/components/userguide/additional-features/alerts.md
optimize_versioned_docs/version-3.13.0/components/userguide/additional-features/alerts.md

A customer was struggling to get Optimize alerts working with an email address that didn't belong to a known user and got the error message:
> Users with the following email addresses are not available for receiving alerts: ...
Related issue: https://github.com/camunda/camunda-optimize/issues/10592

Document that Optimize alert emails only allow known users

---

docs/components/connectors/out-of-the-box-connectors/amazon-sagemaker.md

See https://github.com/camunda/product-hub/issues/2325#issuecomment-2147879406

Add info admonition for SageMaker

---

optimize/self-managed/optimize-deployment/plugins/elasticsearch-header.md
optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/plugins/elasticsearch-header.md
optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/plugins/elasticsearch-header.md
optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/plugins/elasticsearch-header.md
optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/plugins/elasticsearch-header.md
optimize_versioned_docs/version-3.7.0/self-managed/optimize-deployment/plugins/elasticsearch-header.md

related to [OPT #13374](https://github.com/camunda/camunda-optimize/issues/13374)
The C7 only header was missing from the ES plugin docs even though this plugin is not available in C8.

chore(optimize): add missing c7 only note to ES plugin docs

---

docs/apis-tools/spring-zeebe-sdk/configuration.md
docs/apis-tools/spring-zeebe-sdk/getting-started.md
docs/components/best-practices/architecture/deciding-about-your-stack.md
docs/components/best-practices/development/connecting-the-workflow-engine-with-your-world.md
docs/components/best-practices/development/testing-process-definitions.md
docs/guides/migrating-from-camunda-7/adjusting-source-code.md
docs/guides/migrating-from-camunda-7/conceptual-differences.md

- Updated configuration properties
- Improved docs, removed reference to old configuration (with .properties file) in favor of yaml file
- Removed links to Spring Zeebe community project
closes: #3748

Adjust Spring Zeebe SDK docs

---

versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md

Added missing Spring SDK properties
Added configuration for SaaS and SM cluster connections
closes: #3709

docs(spring-zeebe-sdk): add missing spring sdk properties

---

docs/components/modeler/desktop-modeler/search-paths/search-paths.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/search-paths/search-paths.md

Related to https://github.com/camunda/camunda-modeler/issues/4350
This PR documents `search-paths` on MacOS, to date undocumented.

feat(modeler): clarify search path on MacOS

---

docs/components/modeler/desktop-modeler/flags/flags.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/flags/flags.md

This attempts to improve our existing flags documentation; to date it was not clear that restart is required to recognize `flags.json` changes.
Related to https://github.com/camunda/camunda-modeler/issues/4350

Desktop Modeler Flags improvements

---

docs/components/modeler/desktop-modeler/search-paths/search-paths.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/search-paths/search-paths.md

Retro review of https://github.com/camunda/camunda-docs/pull/3900.

adjust macos reference

---

versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/kafka.md
versioned_docs/version-8.4/components/connectors/out-of-the-box-connectors/kafka.md
versioned_docs/version-8.5/components/connectors/out-of-the-box-connectors/kafka.md

Review and backport https://github.com/camunda/camunda-docs/pull/3893.

review and backport 3893

---

docs/apis-tools/web-modeler-api/authentication.md
versioned_docs/version-8.3/apis-tools/web-modeler-api/index.md
versioned_docs/version-8.4/apis-tools/web-modeler-api/authentication.md
versioned_docs/version-8.5/apis-tools/web-modeler-api/authentication.md

Updating UI references in Web Modeler API auth.
**Could hold this. Potential changes to come based on https://camunda.slack.com/archives/CKZK2E7RP/p1717790824638359.**

update web modeler api ui

---

docs/components/connectors/out-of-the-box-connectors/kafka.md

Add https://github.com/camunda/camunda-docs/pull/3913 to next 👍

add 3913 to next

---

docs/reference/announcements.md
versioned_docs/version-8.2/reference/announcements.md
versioned_docs/version-8.3/reference/announcements.md
versioned_docs/version-8.4/reference/announcements.md
versioned_docs/version-8.5/reference/announcements.md

From https://camunda.slack.com/archives/C06UEFRQC12/p1717742517851739
Open questions/comments
* The **Update cluster** page does not exist in 8.2. Should we add a brief statement about how to update clusters or point to the docs in another version?
* I have backported this change to all supported versions
* I modified the order and formatting found in the email

Add update announcement for SaaS clusters

---

docs/reference/announcements.md

Describe the change in URLs and announce the future plan
Related to https://github.com/camunda/product-hub/issues/1989
With the epic https://github.com/camunda/product-hub/issues/1989

no-cloud URL announcement

---

docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
docs/components/connectors/protocol/soap.md
optimize_sidebars.js
sidebars.js
versioned_docs/version-8.5/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_docs/version-8.5/components/connectors/protocol/soap.md
versioned_sidebars/version-8.5-sidebars.json

feat(connectors, soap): added SOAP connector doc
Ready to be merged once @crobbins215 confirms that the doc is sufficient. The feature has been release in 8.5 as close-beta for several users. Now it's ready to go public.
Only for self-managed!

feat(connectors, soap): added SOAP connector doc

---

docs/components/operate/userguide/process-instance-migration.md
versioned_docs/version-8.5/components/operate/userguide/process-instance-migration.md

Adds child instances to supported elements in instance migration guide.
relates to https://github.com/camunda/camunda/issues/18594
closes #3924

docs(operate): add child instances to supported elements in instance migration guide

---

docs/reference/release-notes/860.md

Looks like my commit with the blog post got lost. I've added it and link into the docs to one epic. 
Docs for https://github.com/camunda/product-hub/issues/2157 don't appear to be complete, so I can't link to anything there yet.

Add links to release notes for 8.6.0-alpha2

---

docs/reference/announcements.md
versioned_docs/version-8.5/reference/announcements.md

Retro review https://github.com/camunda/camunda-docs/pull/3604.

retro review of 3604

---

docs/self-managed/setup/deploy/local/local-kubernetes-cluster.md
versioned_docs/version-8.5/self-managed/setup/deploy/local/local-kubernetes-cluster.md

update ingress indentation for local k8s yaml file

---

docs/apis-tools/java-client/job-worker.md
docs/components/connectors/custom-built-connectors/update-guide/020-to-030.md
docs/guides/use-connectors-in-hybrid-mode.md
docs/self-managed/setup/upgrade.md
docs/self-managed/zeebe-deployment/operations/cluster-scaling.md
docs/self-managed/zeebe-deployment/zeebe-gateway/zeebe-gateway-overview.md
versioned_docs/version-8.2/guides/update-guide/connectors/020-to-030.md
versioned_docs/version-8.2/guides/use-connectors-in-hybrid-mode.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/upgrade.md
versioned_docs/version-8.2/self-managed/zeebe-deployment/zeebe-gateway/zeebe-gateway-overview.md
versioned_docs/version-8.3/apis-tools/java-client/job-worker.md
versioned_docs/version-8.3/components/connectors/custom-built-connectors/update-guide/020-to-030.md
versioned_docs/version-8.3/guides/use-connectors-in-hybrid-mode.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/upgrade.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/zeebe-gateway/zeebe-gateway-overview.md
versioned_docs/version-8.4/apis-tools/java-client/job-worker.md
versioned_docs/version-8.4/components/connectors/custom-built-connectors/update-guide/020-to-030.md
versioned_docs/version-8.4/guides/use-connectors-in-hybrid-mode.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/upgrade.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/cluster-scaling.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/zeebe-gateway/zeebe-gateway-overview.md
versioned_docs/version-8.5/apis-tools/java-client/job-worker.md
versioned_docs/version-8.5/components/connectors/custom-built-connectors/update-guide/020-to-030.md
versioned_docs/version-8.5/guides/use-connectors-in-hybrid-mode.md
versioned_docs/version-8.5/self-managed/setup/upgrade.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/cluster-scaling.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/zeebe-gateway/zeebe-gateway-overview.md

Tidying up third party links via monthly review.

clean up third party links

---

versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/metrics.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/operations/metrics.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/metrics.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/metrics.md

version the link to the grafana dashboard config

---

docs/reference/release-notes/860.md

Fixes a minor formatting error in the 8.6.0-alpha2 release notes.

fix(release-notes): fix formatting error in 8.6 release notes

---

docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md

A customer needed to add the certificate of the GCS api to a truststore. For this, they require to know which api is utilized after all.

Added link to api docs of gcs

---

docs/self-managed/zeebe-deployment/operations/cluster-scaling.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/cluster-scaling.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/cluster-scaling.md

docs(guide): typo in scale statefulset commands

---

optimize/self-managed/optimize-deployment/configuration/logging.md
optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/configuration/logging.md
optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/configuration/logging.md
optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/configuration/logging.md
optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/configuration/logging.md

Spelling fix in logging.md

---

docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md

Addresses https://camunda.slack.com/archives/C026U8GBNSW/p1718705447735869

add azure to list of zeebe backup store options

---

docs/self-managed/setup/install.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/deploy.md
versioned_docs/version-8.5/self-managed/setup/install.md

add a missing backslash in the shell command of the section "Configuring Enterprise components and Connectors"

docs (setup SM): add missing backslash

---

docs/components/modeler/web-modeler/milestones.md
docs/components/modeler/web-modeler/process-applications.md

Related to https://github.com/camunda/web-modeler/issues/9808.

document process application milestone versioning

---

optimize/apis-tools/optimize-api/optimize-api-authentication.md
optimize_versioned_docs/version-3.12.0/apis-tools/optimize-api/optimize-api-authentication.md
optimize_versioned_docs/version-3.13.0/apis-tools/optimize-api/optimize-api-authentication.md

Fix Optimize Postman link

---

docs/components/modeler/dmn/dmn.md
versioned_docs/version-8.5/components/modeler/dmn/dmn.md

Added proto-documentation for BKMs

feat: add business knowledge model documentation

---

docs/guides/utilizing-forms.md
versioned_docs/version-8.5/guides/utilizing-forms.md

Remove minimal feature set note for forms

---

docs/components/console/manage-organization/enable-alpha-features.md
versioned_docs/version-8.5/components/console/manage-organization/enable-alpha-features.md

Introduce process for adding AI feature management to the docs via https://confluence.camunda.com/display/HAN/Accepting+the+Terms+for+AI+Usage+in+Camunda+Console.

Add AI-powered alpha features management

---

docs/components/modeler/feel/language-guide/feel-context-expressions.md
versioned_docs/version-8.2/components/modeler/feel/language-guide/feel-context-expressions.md
versioned_docs/version-8.3/components/modeler/feel/language-guide/feel-context-expressions.md
versioned_docs/version-8.4/components/modeler/feel/language-guide/feel-context-expressions.md
versioned_docs/version-8.5/components/modeler/feel/language-guide/feel-context-expressions.md

The example in https://docs.camunda.io/docs/components/modeler/feel/language-guide/feel-context-expressions/#filter is not correct, because a filter on a list will always return a list, not a single item. This PR fixes this.

docs: result of filtering is always a list, not a single item

---

docs/self-managed/operational-guides/update-guide/840-to-850.md
versioned_docs/version-8.5/self-managed/operational-guides/update-guide/840-to-850.md

Due to the following [bug](https://github.com/camunda/camunda/issues/19984), users should skip 8.5.4 and update directly from 8.5.3 to 8.5.5.

Add note to update guide cautioning against Zeebe 8.5.4 usage

---

docs/self-managed/setup/install.md

Follow-up for https://github.com/camunda/camunda-docs/pull/3887

chore(web-modeler): remove mention of pull secret

---

.github/workflows/preview-env-deploy.yml
.github/workflows/preview-env-teardown.yml

This pr aims to make the link in the comment which notifies a user for the deployment of a preview environment clickable. I researched and found out that for this to work, the invisible tag has to be put at the end of the comment otherwise the markdown formatting breaks and the link shows as plan string.
I am attaching here screenshots of the messages.
On **deployment**:
On **teardown**:

chore(preview-link): Make link to preview environment linkable

---

docs/components/modeler/web-modeler/milestones.md

Typo adjustment based on https://github.com/camunda/camunda-docs/pull/3967/files#r1671789817.

minor typo adjustment
