docs/reference/notices.md
versioned_docs/version-8.2/reference/notices.md
versioned_docs/version-8.3/reference/notices.md
versioned_docs/version-8.4/reference/notices.md
versioned_docs/version-8.5/reference/notices.md

This notice concerns Camunda Identity affected by CVE-2024-34750.

docs: add security notice 13

---

docs/self-managed/zeebe-deployment/configuration/broker.md

Documents new configuration added in https://github.com/camunda/camunda/issues/17547.
Closes https://github.com/camunda/camunda/issues/20275

feat(zeebe): document new flow control configuration

---

howtos/documentation-guidelines.md

Follow-up to #3960 -- adds docs on publishing a preview site for a PR.

docs: describe preview sites

---

docs/reference/supported-environments.md
versioned_docs/version-8.5/reference/supported-environments.md

As discussed [in Slack](https://camunda.slack.com/archives/C06MPP9DQ21/p1719832558823779?thread_ts=1719004235.153929&cid=C06MPP9DQ21), we clarify the supported JDK versions for the Spring Zeebe SDK on [its own docs page](https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/#version-compatibility), but not on the [Supported Environments](https://docs.camunda.io/docs/reference/supported-environments/#clients) page. 
This PR adds that clarification.

docs: clarify supported environment for spring-zeebe sdk

---

docs/apis-tools/community-clients/index.md
versioned_docs/version-8.5/apis-tools/community-clients/index.md

Via https://camunda.slack.com/archives/C026U8GBNSW/p1721754891250499

Remove archived node clients

---

docs/reference/glossary.md
versioned_docs/version-8.2/reference/glossary.md
versioned_docs/version-8.3/reference/glossary.md
versioned_docs/version-8.4/reference/glossary.md
versioned_docs/version-8.5/reference/glossary.md

See https://github.com/camunda/camunda-docs/pull/4049#pullrequestreview-2186425604 (and fixed spelling error)

Add Ingress to glossary

---

src/theme/DocItem/Footer/index.js

Removing email field from thumbs down for PushFeedback.
Thanks @mesellings for the catch!

hide email from pushfeedback

---

howtos/documentation-guidelines.md

Closes https://github.com/camunda/camunda-docs/issues/4007.
Updates Operate screenshot links following move to the monorepo.

update operate screenshot links

---

docs/self-managed/concepts/exporters.md

Update to https://github.com/camunda/camunda-docs/pull/4082, related to https://github.com/camunda/camunda-docs/pull/4082#discussion_r1701902904.

update exporter configure

---

docs/apis-tools/tasklist-api-rest/migrate-to-zeebe-user-tasks.md
versioned_docs/version-8.5/apis-tools/tasklist-api-rest/migrate-to-zeebe-user-tasks.md

We shouldn't commit to releases for new features in docs. TL functionality won't be delivered with 8.6 but is currently planned for 8.7 ([ref](https://github.com/camunda/product-hub/issues/1316)). 
We can release this at any time to fix the commitment and be true on expectations.

Remove 8.6 references for Task Listeners

---

docs/self-managed/operational-guides/backup-restore/optimize-backup.md
versioned_docs/version-8.2/self-managed/backup-restore/optimize-backup.md
versioned_docs/version-8.3/self-managed/operational-guides/backup-restore/optimize-backup.md
versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/optimize-backup.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/optimize-backup.md

related to [OPT#13970](https://github.com/camunda/camunda-optimize/issues/13970)
Adjust backup API docs to reflect the correct take backup response.

fix(optimizeBackup): adjust backup api response

---

docusaurus.config.js

Correct the "Sign-Up" text in the docs site announcement banner to "Sign up".
**Note:** As this is in the main docusaurus config file, it is version-agnostic and is changed for the whole site, regardless of which docs version you select.
Linked Issue: https://github.com/camunda/camunda-docs/issues/4093

Edit sign up announcement banner

---

docs/guides/getting-started-orchestrate-apis.md
docs/guides/getting-started-orchestrate-human-tasks.md
docs/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.2/guides/getting-started-orchestrate-apis.md
versioned_docs/version-8.2/guides/getting-started-orchestrate-human-tasks.md
versioned_docs/version-8.2/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.3/guides/getting-started-orchestrate-apis.md
versioned_docs/version-8.3/guides/getting-started-orchestrate-human-tasks.md
versioned_docs/version-8.3/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.4/guides/getting-started-orchestrate-apis.md
versioned_docs/version-8.4/guides/getting-started-orchestrate-human-tasks.md
versioned_docs/version-8.4/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.5/guides/getting-started-orchestrate-apis.md
versioned_docs/version-8.5/guides/getting-started-orchestrate-human-tasks.md
versioned_docs/version-8.5/guides/getting-started-orchestrate-microservices.md

Closes https://github.com/camunda/camunda-docs/issues/4068.
Replaces `/tutorial/` links with relevant Marketplace links.

update tutorial links with marketplace

---

docs/apis-tools/java-client/job-worker.md
docs/apis-tools/spring-zeebe-sdk/configuration.md
docs/self-managed/operate-deployment/operate-configuration.md
docs/self-managed/operational-guides/configure-multi-tenancy.md
docs/self-managed/setup/deploy/openshift/redhat-openshift.md
docs/self-managed/zeebe-deployment/security/client-authorization.md
versioned_docs/version-8.3/apis-tools/java-client/job-worker.md
versioned_docs/version-8.3/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.3/self-managed/operational-guides/configure-multi-tenancy.md
versioned_docs/version-8.4/apis-tools/java-client/job-worker.md
versioned_docs/version-8.4/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.4/self-managed/operational-guides/configure-multi-tenancy.md
versioned_docs/version-8.5/apis-tools/java-client/job-worker.md
versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.5/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.5/self-managed/operational-guides/configure-multi-tenancy.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/security/client-authorization.md

Third-party link corrections for August docs housekeeping.

august third party link corrections

---

docs/self-managed/setup/deploy/openshift/redhat-openshift.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift.md
versioned_docs/version-8.5/self-managed/setup/deploy/openshift/redhat-openshift.md

removing post-renderer from OpenShift docs

---

docs/reference/supported-environments.md

⬇️ https://camunda.slack.com/archives/C026U8GBNSW/p1723035606847889
* Reordered the component version matrix, latest on top
* Removed older versions, including unsupported versions of C8
* Reordered the form-js table
* Added - to separate Design column between Modelers (personally, I think it's easier to read/parse)
We can backport if we want or ship this with 8.6.

Rework component version matrix

---

docs/apis-tools/java-client/job-worker.md
docs/components/zeebe/technical-concepts/protocols.md
docs/guides/migrating-from-camunda-7/migration-readiness.md
docs/self-managed/concepts/multi-tenancy.md
docs/self-managed/zeebe-deployment/configuration/gateway.md
docs/self-managed/zeebe-deployment/zeebe-gateway/filters.md
docs/self-managed/zeebe-deployment/zeebe-gateway/interceptors.md
sidebars.js

Document support for REST API middleware for the Zeebe Gateway and the (Zeebe) Java client and Spring SDK.
closes #4109
closes #4108

Document REST API middleware

---

docs/components/modeler/forms/form-element-library/forms-element-library-table.md
versioned_docs/version-8.4/components/modeler/forms/form-element-library/forms-element-library-table.md
versioned_docs/version-8.5/components/modeler/forms/form-element-library/forms-element-library-table.md

Link to the table data binding where it is most needed. It took me a second careful read through the entire page to find the most important information on how to use the Table component.

Link table data binding to data source

---

docs/components/modeler/web-modeler/process-applications.md

Relates to https://github.com/camunda/web-modeler/issues/9958.
Details how to select a default cluster for process applications.

add selecting a default cluster

---

docs/components/modeler/web-modeler/git-sync.md

As reported [here](https://camunda.slack.com/archives/C0693F1NFK5/p1723469751081119?thread_ts=1723460964.010189&cid=C0693F1NFK5) the previous version might have been confusing, leading the user to think that all the projects will synced; while that's true only for process applications

chore(docs): fix unclear introduction

---

docs/reference/release-notes/860.md

Fix blog URL, month was incorrect 🙃

fix typo in blog url

---

docs/apis-tools/spring-zeebe-sdk/getting-started.md

This PR adds a row to the SpringSDK version compatibility table
related [slack thread](https://camunda.slack.com/archives/C07CQC289JP/p1723134131346529)

docs(spring-sdk): add row to version compatibility table

---

docs/components/concepts/data-retention.md
versioned_docs/version-8.2/components/concepts/data-retention.md
versioned_docs/version-8.3/components/concepts/data-retention.md
versioned_docs/version-8.4/components/concepts/data-retention.md
versioned_docs/version-8.5/components/concepts/data-retention.md

This PR should update the [retention time in Optimize](https://docs.camunda.io/docs/next/components/concepts/data-retention/) (version independent --> should be reflected in all prior versions as well).
This change is already life and updated in [our internal documentation](https://confluence.camunda.com/pages/viewpage.action?spaceKey=HAN&title=Custom+Data+Retention+in+SaaS) since June 6th ;) 
ASAP (but no urgency)!
> - [x] This is already available but undocumented and should be released within a week.
I marked it within a week as I got paged 2 times already about it in the last 2 weeks.

update optimize retention times

---

docs/components/modeler/web-modeler/token-simulation.md

Relates to https://github.com/camunda/web-modeler/issues/6847

chore(web-modeler): adjust for sentence case in UI

---

docs/components/modeler/web-modeler/camunda-marketplace.md

As suggested by QA Engineer @slolatte , specify what files are currently supported by blueprints.
Also remove usage of older term "application" in this context.

doc(marketplace): mention file types supported in Blueprints

---

docs/components/concepts/data-retention.md
versioned_docs/version-8.2/components/concepts/data-retention.md
versioned_docs/version-8.3/components/concepts/data-retention.md
versioned_docs/version-8.4/components/concepts/data-retention.md
versioned_docs/version-8.5/components/concepts/data-retention.md

This reverts commit fadd568d8e894bd76945e5683a14a1ff816c42df.
Sorry team! I actually need to revert this change. I confused this section and the **default** for Optimize is still 180. What changed is that the max. retention time can be set to 720 days - but this is not the default.
Would be good to merge it before the next release.

Revert "update optimize retention times"

---

docs/components/modeler/bpmn/user-tasks/user-tasks.md
versioned_docs/version-8.5/components/modeler/bpmn/user-tasks/user-tasks.md

Closes https://github.com/camunda/camunda-docs/issues/3820 -- adjusts wording and removes any suggestion of editing BPMN XML.

clean up bpmn zeebe user task section

---

docs/self-managed/console-deployment/telemetry.md
versioned_docs/version-8.5/self-managed/console-deployment/telemetry.md

Discussed [in Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1724234114734109).
Replaces a relative link to a `.json` asset with an absolute link to the GitHub source.
The relative link was emitted as a non-existent path, with a trailing slash after `.json`. This is a known issue in Docusaurus.

fix: link to telemetry sample asset via absolute github URL

---

docs/components/best-practices/modeling/choosing-the-resource-binding-type.md
docs/components/modeler/bpmn/business-rule-tasks/business-rule-tasks.md
docs/components/modeler/bpmn/call-activities/call-activities.md

Follow-up for https://github.com/camunda/camunda-docs/pull/4132. In particular, addresses the following comments:
- https://github.com/camunda/camunda-docs/pull/4132#discussion_r1714983766
- https://github.com/camunda/camunda-docs/pull/4132#discussion_r1715012106
Related issue: https://github.com/camunda/camunda-docs/issues/4124
<details><summary>After this change</summary>
<p>
</p>
</details> 
<details><summary>Previously</summary>
<p>
</p>
</details>

docs: improve description of binding type 'latest' + fix XML examples

---

versioned_sidebars/version-8.5-sidebars.json

Related to https://github.com/camunda/developer-experience/issues/98. Adds Zeebe REST tutorial to 8.5 sidebar.

add zeebe tutorial to 8.5 sidebar

---

docs/reference/announcements.md
docs/self-managed/setup/guides/ingress-setup.md
docs/self-managed/setup/upgrade.md

As part of 
https://github.com/camunda/distribution/issues/290
https://github.com/camunda/camunda-platform-helm/issues/1838
There are some things we want to remove from the helm chart in v8.7 that we want to announce for 8.6. 
1. separated ingresses
2. There were also some things that we planned on dropping support for in v8.6, however, we have decided to keep compatibility with those options until v8.7.
Those items were listed here:  https://docs.camunda.io/docs/self-managed/setup/upgrade/#deprecation-notes
This PR adds an announcement, helm upgrade note, and will put a notice on top of the Combined and Separated Ingress Guide that Separated ingresses will no longer be supported.
Our internal tickets on this topic are scheduled for 8.6-alpha5

fix(self-managed): include deprecation notice for separated ingress

---

docs/reference/supported-environments.md

Bugfix: clarifies OpenSearch version to avoid confusion.
Clarification: added note on OR1 instance usage

fix: clarified OS version

---

versioned_docs/version-8.5/components/connectors/use-connectors/index.md

body was ignored and went straight to the property

Corrected path to variable in mapping

---

docs/components/connectors/use-connectors/index.md
versioned_docs/version-8.2/components/connectors/use-connectors/index.md
versioned_docs/version-8.3/components/connectors/use-connectors/index.md
versioned_docs/version-8.4/components/connectors/use-connectors/index.md

Backports #4188, a community contribution.

Backport #4188

---

docs/self-managed/setup/upgrade.md
versioned_docs/version-8.5/self-managed/setup/upgrade.md

There is no longer a `camunda-postgresql` secret as of 8.5. Here's a suggestion to improve this page: 
https://docs.camunda.io/docs/self-managed/setup/upgrade/#secrets-extraction
I also updated the `Note`. Many of the components are customizable, and so this secrets extraction script will be different for each environment. So, rather than adding comments such as ("uncomment if using console"), I suggest we give a script including everything with a Note to remind folks to customize it as needed.

docs(sm) - update secrets extraction for version 8.5

---

docs/self-managed/setup/guides/configure-db-custom-headers.md

docs: updated to up-to-date lib reference
Can be merged anytime.

docs: updated to up-to-date lib reference

---

docs/components/connectors/manage-connector-templates.md
docs/components/modeler/web-modeler/collaboration.md

Closes https://github.com/camunda/web-modeler/issues/10639, closes https://github.com/camunda/web-modeler/issues/10238

feat(web-modeler): organization-public connector templates in SM

---

docs/components/modeler/feel/builtin-functions/feel-built-in-functions-list.md
docs/components/modeler/feel/builtin-functions/feel-built-in-functions-string.md

Extend the FEEL documentation with the following new built-in functions:
- https://github.com/camunda/feel-scala/issues/805
- https://github.com/camunda/feel-scala/issues/815
- https://github.com/camunda/feel-scala/issues/796
- https://github.com/camunda/feel-scala/issues/846
The new functions will be available for version `8.6`.

feat(feel): Add new built-in functions

---

versioned_docs/version-8.5/self-managed/operational-guides/multi-region/dual-region-ops.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/dual-region.md

Adjusts 8.5 docs for the dual-region topic to select the appropriate 8.5 stable branch for scripts and active references.
It also removes a temporary `legacy` mode that was required as we had everything on a single branch prior.
While I don't think it requires a tech-writer review, I've had instances in the past where I did minor changes and was asked afterwards to always double check, so here we are! 😁 
related to https://github.com/camunda/team-infrastructure-experience/issues/241 on the InfraEx side.

docs(dual-region): update base branch for 8.5 release scripts

---

docs/reference/dependencies.md

* For Connectors and Modeler (others to follow)
* Related to camunda/engineering-leadership-team#68

feat(dependencies): harmonize linkage to dependencies

---

docs/reference/release-notes/860.md

* camunda/zeebe was renamed to camunda/camunda

feat(release-notes): link to camunda/camunda

---

docs/self-managed/operational-guides/troubleshooting/troubleshooting.md
docs/self-managed/setup/deploy/amazon/amazon-eks/amazon-eks.md
docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
docs/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
docs/self-managed/setup/deploy/local/local-kubernetes-cluster.md

Quick win to standardize on Ingress as a proper noun. Closes https://github.com/camunda/camunda-docs/issues/4030

standardize Ingress as capitalized

---

docs/components/modeler/web-modeler/play-your-process.md

closes https://github.com/camunda/play/issues/622

docs(play): include billing information in play docs

---

docs/apis-tools/camunda-api-rest/specifications/sidebar.js

fix c8 api sidebar

---

docs/self-managed/setup/guides/configure-db-custom-headers.md

feat: updated plugin feature usage docs
Any time. Preparing for next.

feat: updated plugin feature usage docs

---

docs/self-managed/console-deployment/configuration.md
versioned_docs/version-8.4/self-managed/console-deployment/configuration.md
versioned_docs/version-8.5/self-managed/console-deployment/configuration.md

Closes https://github.com/camunda/camunda-docs/issues/4318.

fix monitoring typo

---

docs/components/modeler/web-modeler/play-your-process.md

closes https://github.com/camunda/play/issues/593

docs: update play permissions

---

docs/apis-tools/testing/getting-started.md

We changed the implementation and replaced the Zeebe, Operate, and Tasklist containers with the single Camunda container.
Update the docs accordingly.

docs(cpt): Replace Zeebe/Operate/Tasklist container with Camunda

---

docs/reference/announcements.md
docs/reference/release-notes/860.md
docs/self-managed/operational-guides/configure-flow-control/configure-flow-control.md

This PR request adds links and additional info to flow control announcements and releases. 
Namely:
- Specify that the flow control is enabled by default in saas in the announcements and in the operational guide.
- Links the release notes to the operational guide.
closes https://github.com/camunda/camunda-docs/issues/4283
closes https://github.com/camunda/camunda-docs/issues/4285
closes https://github.com/camunda/camunda-docs/issues/4282

Add links and additional info to Flow Control announcements

---

docs/components/modeler/web-modeler/play-your-process.md

closes https://github.com/camunda/play/issues/271

docs(play): document connector secret limitation in SM

---

docs/components/modeler/web-modeler/play-your-process.md

closes https://github.com/camunda/play/issues/659

docs(play): mention feature limitations in Play

---

docs/reference/announcements.md
docs/self-managed/operational-guides/configure-flow-control/configure-flow-control.md

Retro review of https://github.com/camunda/camunda-docs/pull/4310.

retro review of 4310

---

docs/guides/react-components/install-c8run.md
docs/self-managed/setup/deploy/local/c8run.md

Incorporating some feedback to the C8Run docs:
- clarify that this is a local installation script to reduce confusion with fat jar installations 
- add links to download desktop modeler 
This does not yet add the C8run instructions to the getting started guides, which will be addressed in a follow-up ticket.

(c8run) add modeler links, clean up introduction

---

docs/apis-tools/java-client-examples/cluster-topology-request.md
versioned_docs/version-8.2/apis-tools/java-client-examples/cluster-topology-request.md
versioned_docs/version-8.3/apis-tools/java-client-examples/cluster-topology-request.md
versioned_docs/version-8.4/apis-tools/java-client-examples/cluster-topology-request.md
versioned_docs/version-8.5/apis-tools/java-client-examples/cluster-topology-request.md

These look like random chars or a random URL/path... right?

Remove chars before link

---

docs/components/modeler/web-modeler/launch-web-modeler.md
docs/reference/release-notes/860.md
versioned_docs/version-8.5/components/modeler/web-modeler/launch-web-modeler.md

Closes https://github.com/camunda/developer-experience/issues/389 -- lowercasing a few cases of blueprints.

lowercase blueprints

---

docs/components/concepts/clusters.md
docs/components/console/manage-clusters/create-cluster-include.md
docs/components/console/manage-clusters/manage-cluster.md
versioned_docs/version-8.3/components/concepts/clusters.md
versioned_docs/version-8.4/components/concepts/clusters.md
versioned_docs/version-8.5/components/concepts/clusters.md
versioned_docs/version-8.5/components/console/manage-clusters/create-cluster-include.md
versioned_docs/version-8.5/components/console/manage-clusters/manage-cluster.md

As part of the work in https://github.com/camunda/camunda-docs/pull/4202, some auto-pause warnings were merged back in.
> note
> Cluster auto-pause is not yet available and only applies to non-Enterprise clusters. Development clusters will be paused if they go unused for two hours. When a cluster is paused, not all functionality is limited. For example, you may still execute BPMN timers and BPMN message catch events. To resume your cluster, review [how to resume a cluster](https://docs.camunda.io/docs/next/components/console/manage-clusters/manage-cluster/#resume-a-cluster).
These need to be removed from the following pages, and anywhere else for all versions:
https://docs.camunda.io/docs/next/components/concepts/clusters/
https://docs.camunda.io/docs/next/components/console/manage-cluster …

Remove auto-pause note

---

optimize_sidebars.js

Synchronizes sidebars for vNext.
* There are no changes in the main instance's sidebars.js file, because any Optimize restructuring was already proactively copied into the main instance. Good job, us!
* There are many changes in the Optimize instance's optimize_sidebars.js file, but this isn't unusual. We made significant API changes, and this tends to be the direction we forget to duplicate structural changes.

chore(sidebars): sync sidebars in vNext

---

docs/reference/dependencies.md

fix: fix broken 3rd party deps disclosure

---

optimize_versioned_sidebars/version-3.12.0-sidebars.json

Synchronizes sidebars for v8.4/3.12.0.
There are not many meaningful changes here. This is expected, as structural changes in previous versions of the docs happen far less frequently.

chore(sidebars): sync sidebars in v8.4/3.12.0

---

docs/self-managed/setup/guides/connect-to-an-oidc-provider.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md
versioned_docs/version-8.5/self-managed/setup/guides/connect-to-an-oidc-provider.md

ms entra integration: added identity to list of platforms

---

docs/reference/licenses.md
docs/self-managed/react-components/components.md

Resolves https://github.com/camunda/camunda-docs/issues/4356
Licensing has been updated for 8.6. This PR updates the 8.6 license page according to the [internal draft](https://docs.google.com/document/d/14GbgxWseQ4-5iIuGCWIbq2JpulHp4OBozSe169Fwzzg/edit?usp=sharing).

update licensing information for 8.6

---

docs/reference/dependencies.md

This PR addresses the minor edits suggested in https://github.com/camunda/camunda-docs/pull/4340.
Additionally, included tidying up the various different references to "CycloneDX SBOM".

Dependency edits from PR 4340

---

optimize/self-managed/optimize-deployment/advanced-features/engine-data-deletion.md
optimize/self-managed/optimize-deployment/configuration/getting-started.md
optimize/self-managed/optimize-deployment/configuration/security-instructions.md
optimize/self-managed/optimize-deployment/configuration/shared-elasticsearch-cluster.md
optimize/self-managed/optimize-deployment/configuration/system-configuration.md
optimize/self-managed/optimize-deployment/install-and-start.md
optimize/self-managed/optimize-deployment/migration-update/camunda-7/3.13-to-3.14.md
optimize/self-managed/optimize-deployment/migration-update/camunda-8/3.13_8.5-to-8.6.md

Adding documentation for OpenSearch installations. 
C7 epic: https://github.com/camunda/product-hub/issues/2233
C8 epic: https://github.com/camunda/product-hub/issues/1908
Relates to https://github.com/camunda/camunda/issues/23087

feat: Adding documentation for OpenSearch installations

---

docs/self-managed/setup/guides/air-gapped-installation.md
versioned_docs/version-8.2/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
versioned_docs/version-8.5/self-managed/setup/guides/air-gapped-installation.md

Related to https://github.com/camunda/product-hub/issues/1075 and https://github.com/camunda/team-infrastructure/issues/689.
Bitnami (third-party) images can now be pulled from  Camunda's Docker Registry (pull-through cache) as well.

docs(self-managed): bitnami images can be pulled from Camunda's Docker Registry

---

docs/guides/getting-started-java-spring.md
docs/guides/react-components/install-c8run.md
docs/self-managed/setup/deploy/local/c8run.md

Relates to https://github.com/camunda/camunda-docs/pull/4301, which is still on hold and unlikely to be resolved for 8.6. 
In the interest of using C8Run in this guide for the release, this PR does not include all the changes made in #4301, but only replaces the existing Java guide with the C8Run install. Additional content updates/edits/etc should be included in the more comprehensive #4301.

Use C8Run in the Spring getting started guide

---

.github/workflows/preview-env-deploy.yml

It appears the docuactions GitHub org is no more (https://github.com/docuactions currently returns a 404). I haven't seen any information on the internet about if this is accidental or if it's been moved somewhere. 
This PR removes the docuactions/cache action from our preview deployment workflow. If we find that the action returns, we can put this back in.

fix: remove docuactions/cache

---

docs/components/connectors/out-of-the-box-connectors/amazon-bedrock.md
docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md

Add Bedrock to Connectors overview and remove SageMaker typo.

clean up bedrock connector

---

versioned_docs/version-8.6/reference/announcements.md

Backporting https://github.com/camunda/camunda-docs/pull/4329.

backport deprecation notice for some message start event templates

---

docs/guides/getting-started-java-spring.md
versioned_docs/version-8.6/guides/getting-started-java-spring.md

Follow up to https://github.com/camunda/camunda-docs/pull/4301#discussion_r1791921288.

add links to spring guide

---

docs/guides/getting-started-java-spring.md
versioned_docs/version-8.6/guides/getting-started-java-spring.md

This code snippet/dependency was not updated in other PRs. There might be other places this needs to be updated. @conceptualshark please review.
Raised by @felix-mueller via Slack.

Update Spring Boot to 8.6.0

---

versioned_docs/version-8.6/self-managed/operational-guides/multi-region/dual-region-ops.md
versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/dual-region.md

For the versioned 8.6 docs this change adjusts dual-region related links to go to the stable branch on our side as `main` is for the next release.
After the release, nothing dramatic as `main` is still 8.6 practically but for longevity to persist this.

docs(dual-region): update base branch for 8.6 release scripts

---

docs/apis-tools/camunda-api-rest/camunda-api-rest-overview.md
versioned_docs/version-8.6/apis-tools/camunda-api-rest/camunda-api-rest-overview.md

This PR adds an explanation on how to properly configure Camunda for Resource Deployment REST endpoint.
closes: #4442

docs: document file size configuration for deploy endpoint

---

docs/reference/announcements.md
versioned_docs/version-8.6/reference/announcements.md

Related to https://github.com/camunda/camunda-docs/pull/4341#issuecomment-2396385576.

add sm detail to flow control announcement

---

docs/components/concepts/clusters.md
docs/components/console/manage-clusters/create-cluster-include.md
docs/components/modeler/web-modeler/play-your-process.md
docs/components/react-components/create-cluster.md
versioned_docs/version-8.2/components/concepts/clusters.md
versioned_docs/version-8.2/components/console/manage-plan/update-creditcard.md
versioned_docs/version-8.2/components/console/manage-plan/upgrade-to-starter-plan.md
versioned_docs/version-8.2/guides/assets/react-components/create-cluster.md
versioned_docs/version-8.3/components/concepts/clusters.md
versioned_docs/version-8.3/components/console/manage-clusters/create-cluster-include.md
versioned_docs/version-8.3/guides/assets/react-components/create-cluster.md
versioned_docs/version-8.4/components/concepts/clusters.md
versioned_docs/version-8.4/components/console/manage-clusters/create-cluster-include.md
versioned_docs/version-8.4/guides/assets/react-components/create-cluster.md
versioned_docs/version-8.5/components/concepts/clusters.md
versioned_docs/version-8.5/components/console/manage-clusters/create-cluster-include.md
versioned_docs/version-8.5/guides/assets/react-components/create-cluster.md
versioned_docs/version-8.6/components/concepts/clusters.md
versioned_docs/version-8.6/components/console/manage-clusters/create-cluster-include.md
versioned_docs/version-8.6/components/modeler/web-modeler/play-your-process.md
versioned_docs/version-8.6/components/react-components/create-cluster.md

Closes https://github.com/camunda/developer-experience/issues/256. Lowercases "plan".
Notified in [Slack](https://camunda.slack.com/archives/C02AWA0RF8A/p1728601913973369). To add to WCoE release.

lowercase plan

---

docs/apis-tools/spring-zeebe-sdk/getting-started.md
docs/guides/getting-started-java-spring.md
docs/self-managed/setup/deploy/local/c8run.md
versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.6/guides/getting-started-java-spring.md
versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md

Bump Spring SDK to 3.6.0

---

docs/components/tasklist/userguide/using-tasklist.md
versioned_docs/version-8.6/components/tasklist/userguide/using-tasklist.md

It was not clear in the docs that the on Tasklist when trying to check Process Diagrams related to tasks, only diagrams deployed after 8.6 are going to work due to a technical restriction, so I'm adding in the notes.

docs: adding restriction to tasklist process diagram view

---

versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md

Revert 8.5 changes for https://github.com/camunda/camunda-docs/pull/4473

Backout/revert changes for 8.5 to SDK scope

---

docs/self-managed/setup/upgrade.md
versioned_docs/version-8.5/self-managed/setup/upgrade.md
versioned_docs/version-8.6/self-managed/setup/upgrade.md

We have postponed the removal date of the deprecated keys, but the date wasn't changed for all documents.

docs(self-managed): fix the removal date of the deprecated keys

---

docs/self-managed/zeebe-deployment/configuration/broker.md
docs/self-managed/zeebe-deployment/configuration/gateway.md

Added docs for newly added options "configManager.gossip"  in zeebe.broker.cluster
closes #4395

feat: add docs for cluster configManager configuration

---

docs/self-managed/operational-guides/backup-restore/operate-tasklist-backup.md
versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/operate-tasklist-backup.md

This closes issue https://github.com/camunda/camunda-docs/issues/4487.
> Starting version 8.6, the actuator endpoints, including backup, were moved to port 9600.
> However, the documentation for 8.6 still mentions the old port, 8080: https://docs.camunda.io/docs/self-managed/operational-guides/backup-restore/operate-tasklist-backup/
Updated documentation for Next and 8.6:
- Changed port 8080 to 9600 in page.
- Changed to a breaking changes warning and added as an item.

Update backup and restore actuator endpoint port

---

docs/components/connectors/protocol/rest.md
versioned_docs/version-8.6/components/connectors/protocol/rest.md

Add some documentation about how the REST Connector handles errors.

docs(rest): Describe error handling

---

.github/workflows/publish-prod.yaml
.github/workflows/publish-stage.yaml

This PR targets `unsupported/1.3`, and will not make it into `main`!
Part of #2189.
The scripts to reconfigure the publish workflows of an unsupported website were invalidated when we introduced preview releases.
This PR modifies the workflows in the unsupported/1.3 branch, so that this specific version can be deployed.
It **does not** include corrections to the archival scripts. I will update those in another PR, when I do the 8.2 archival.

fix(ci): pass base URL settings as env variables in publish workflows

---

.github/workflows/auto-assign-pr.yml

Automatically add PR author as assignee.
Closes https://github.com/camunda/camunda-docs/issues/3227.

Add GHA to auto assign PR author as assignee

---

versioned_docs/version-8.2/self-managed/zeebe-deployment/operations/metrics.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/configuration.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/operations/metrics.md

Updates links following minor based on [this sheet](https://docs.google.com/spreadsheets/d/1q2F308phdRotistKaCW1qa1NmL96BRLn9ttarWDfOto/edit?usp=sharing).

update links for 8.6 minor

---

docs/components/best-practices/architecture/sizing-your-environment.md
docs/components/concepts/clusters.md
docs/components/console/manage-clusters/manage-cluster.md
versioned_docs/version-8.6/components/best-practices/architecture/sizing-your-environment.md
versioned_docs/version-8.6/components/concepts/clusters.md
versioned_docs/version-8.6/components/console/manage-clusters/manage-cluster.md

Closes https://github.com/camunda/developer-experience/issues/409.
Add content for how to resize a cluster as part of the new update cluster size feature.
**Note:** This will need to be backported for 8.6 once initial Engineering review is complete.

Add cluster resize

---

docs/self-managed/operational-guides/update-guide/860-to-870.md

Follow up to typo in #4412. 
@camunda/tech-writers please do a retro review on #4412. You can adjust this PR if you'd like to capture any additional changes.

Fix typo in #4412

---

versioned_docs/version-8.6/apis-tools/community-clients/cli-client/cli-get-started.md
versioned_docs/version-8.6/apis-tools/community-clients/cli-client/index.md
versioned_docs/version-8.6/apis-tools/community-clients/go-client/go-get-started.md
versioned_docs/version-8.6/apis-tools/community-clients/go-client/index.md
versioned_docs/version-8.6/apis-tools/community-clients/go-client/job-worker.md

As discussed on [Slack](https://camunda.slack.com/archives/C0484UFR2VA/p1729859726832219).
I specifically did not add this to `/next/`.

Add link to deprecation announcement for CLI & Go

---

docs/self-managed/operational-guides/troubleshooting/troubleshooting.md
versioned_docs/version-8.5/self-managed/operational-guides/troubleshooting/troubleshooting.md
versioned_docs/version-8.6/self-managed/operational-guides/troubleshooting/troubleshooting.md

Related to a Support case on [Slack](https://camunda.slack.com/archives/C07CXDTSW6N) and [Jira](https://jira.camunda.com/browse/SUPPORT-22744).
It's an addition to the troubleshooting page as an infrastructure-related problem can cause issues with Zeebe, and it may seem like Zeebe is the culprit.
Theoretically, it can happen for any Zeebe version, as it depends on the Infrastructure. I've added it to the troubleshooting page for self-managed, which exists since 8.5.

docs(sm): add troubleshooting on k8s issues affecting zeebe

---

docs/self-managed/operational-guides/application-configs.md
versioned_docs/version-8.5/self-managed/operational-guides/application-configs.md
versioned_docs/version-8.6/self-managed/operational-guides/application-configs.md

The provided documentation for default Helm values uses `cpt` to represent the release name, but no release name is provided in the `helm template` command. This can be misleading when attempting to follow along.
This update adds the recommendation to provide a release name with `helm template <your-release-name>`, and updates the resulting config to more clearly show where the release name would appear. This also updates the /next docs to a more recent output from this command.

update SM app config with latest configmap, release name

---

docs/self-managed/tasklist-deployment/tasklist-authentication.md
versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-authentication.md

This PR fixes a link where the GraphQL API was referenced despite being deprecated.

fix: reference the up-to-date REST API instead of the deprecated GraphQL API

---

docs/apis-tools/community-clients/cli-client/cli-get-started.md
docs/apis-tools/community-clients/go-client/go-get-started.md
docs/apis-tools/working-with-apis-tools.md
docs/components/concepts/job-workers.md
docs/components/modeler/bpmn/timer-events/timer-events.md
docs/components/modeler/feel/what-is-feel.md

October 2024 Bing Webmaster fixes as follows:
- High: The description is missing in the head section of the page.
- Moderate: Meta descriptions on many of your pages are too short.
To follow up on: H1 on meta page, as part of https://github.com/camunda/camunda-docs/issues/4001

October 2024 bing fixes

---

versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/configuration.md

fix: link to the actual properties

---

docs/apis-tools/spring-zeebe-sdk/configuration.md

Updating properties link to point to the actual properties.
Related to: [this PR](https://github.com/camunda/camunda-docs/pull/4535#pullrequestreview-2405243123)

Update property link

---

optimize/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.14.0/self-managed/optimize-deployment/configuration/system-configuration.md

Remove the suggestion that Optimize YAML options can be converted in a standard way to environment variables.

Remove suggestion to convert from YAML to env vars for optimize config

---

docs/components/modeler/web-modeler/play-your-process.md
versioned_docs/version-8.6/components/modeler/web-modeler/play-your-process.md

Execution listeners are currently not supported in Play. Until we fix this, we will add a note mentioning this limitation.

docs(play): mention limitation for execution listeners

---

docs/self-managed/concepts/exporters.md
versioned_docs/version-8.6/self-managed/concepts/exporters.md

Give an example of how to use the given meter registry to configure custom exporter metrics

Export metrics example

---

docs/self-managed/setup/guides/connect-to-an-oidc-provider.md
versioned_docs/version-8.6/self-managed/setup/guides/connect-to-an-oidc-provider.md

Until now, Console was simply ignored in this oidc connection guide. But starting with 8.6, console is supported.

fix: mention console

---

docs/components/connectors/out-of-the-box-connectors/amazon-comprehend.md

[issue](https://github.com/camunda/connectors/issues/3551)
**Description**
I just removed redundant parts of the documentation and changed the name of the fields
**When should this change go live?**
This is part of a scheduled alpha or minor. (apply alpha or minor label)
**PR Checklist**
My changes are for the next minor and are in /docs directory (aka /next/).

docs: update comprehend doc

---

src/css/custom.css

This PR addresses the issue where H3 and H4 fonts do not use the IBM Plex Sans font-family.
This is now fixed so that Plex-Sans (and approved font-family hierarchy) is applied to all heading fonts through the global variable: `--ifm-heading-font-family`.

Change heading fonts

---

docs/apis-tools/testing/getting-started.md
versioned_docs/version-8.6/apis-tools/testing/getting-started.md

fix typo Testconainers

---

docs/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.3/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.4/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.5/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.6/components/connectors/out-of-the-box-connectors/slack.md

Related to #4560 & #2719 - acorn expression issues

Add backticks to example 

---

docs/components/connectors/protocol/rest.md
versioned_docs/version-8.2/components/connectors/protocol/rest.md
versioned_docs/version-8.3/components/connectors/protocol/rest.md
versioned_docs/version-8.4/components/connectors/protocol/rest.md
versioned_docs/version-8.5/components/connectors/protocol/rest.md
versioned_docs/version-8.6/components/connectors/protocol/rest.md

Add backticks

---

docs/reference/supported-environments.md
versioned_docs/version-8.6/reference/supported-environments.md

Reported internally - https://camunda.slack.com/archives/C026U8GBNSW/p1730729265222839

Remove deprecated zbctl and Go from supported env page

---

docs/components/concepts/encryption-at-rest.md
versioned_docs/version-8.6/components/concepts/encryption-at-rest.md

Remove `/docs` from page links so that they work correctly in docs versioning.

Fix encryption links for versioning

---

docs/self-managed/setup/guides/configure-db-custom-headers.md
docs/self-managed/zeebe-deployment/configuration/broker.md
docs/self-managed/zeebe-deployment/exporters/camunda-exporter.md
docs/self-managed/zeebe-deployment/exporters/exporters.md
sidebars.js

Initial documentation page for Camunda Exporter.
**PS: some of the content in the elasticsearch exporter page was not relevant for this one. And I had to write it from my own understanding. Like, for example, the whole paragraph in the beginning of the page. Please review it both technically and the editorially for any mistakes** 
closes #4491

docs: initial docs page for camunda-exporter

---

docs/apis-tools/administration-api/tutorial.md
docs/apis-tools/web-modeler-api/tutorial.md
optimize/apis-tools/optimize-api/tutorial.md
optimize_versioned_docs/version-3.13.0/apis-tools/optimize-api/tutorial.md
optimize_versioned_docs/version-3.14.0/apis-tools/optimize-api/tutorial.md
versioned_docs/version-8.5/apis-tools/administration-api/tutorial.md
versioned_docs/version-8.5/apis-tools/web-modeler-api/tutorial.md
versioned_docs/version-8.6/apis-tools/administration-api/tutorial.md
versioned_docs/version-8.6/apis-tools/web-modeler-api/tutorial.md

Closes https://github.com/camunda/camunda-docs/issues/3915.
**Will backport upon approval.**

add details on env variables to api tutorials

---

docs/guides/react-components/_install-c8run.md
docs/self-managed/setup/deploy/local/c8run.md
versioned_docs/version-8.6/guides/react-components/_install-c8run.md
versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md

Updates the C8Run partials and pages to the latest release.

Update c8run release version

---

docs/reference/announcements.md

Adds the 8.7 section to the Announcements page, with both release and EOM dates as TBD

Add 8.7 section to Announcements page

---

docs/reference/release-notes/870.md

Update the 8.7.0 alpha 1 release notes to include the release notes blog URL:
https://camunda.com/blog/2024/11/camunda-alpha-release-november-2024/
**Note: Awaiting confirmation that this is live and the correct URL.**
- [X My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

Update release blog URL in release notes

---

docs/components/modeler/web-modeler/play-your-process.md
versioned_docs/version-8.6/components/modeler/web-modeler/play-your-process.md

Explicitly stating that multitenancy is not yet supported to resolve:
https://jira.camunda.com/browse/SUPPORT-24511?focusedCommentId=380430&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-380430

docs(modeler): update Play limitations

---

.github/workflows/publish-prod.yaml
.github/workflows/publish-stage.yaml
docusaurus.config.js
hacks/isolateVersion/6-updateCIWorkflows.sh
hacks/isolateVersion/7-updateDocusaurusConfig.sh

Part of #4527 (or at least, preparation for it).
When we introduced preview sites, there were changes made to the docusaurus config & publishing workflows, which I had not yet accounted for in the version archival process.
This PR adjusts the version archival process to account for these changes.
I've run the changes through a test run, to confirm that I got things right....as I work through #4527, if I find more changes, I will likely handle those in a follow-up PR.

chore: update version archival process to account for infrastructure changes

---

docs/reference/announcements.md
docs/reference/regions.md
versioned_docs/version-8.2/reference/regions.md
versioned_docs/version-8.3/reference/regions.md
versioned_docs/version-8.4/reference/regions.md
versioned_docs/version-8.5/reference/regions.md
versioned_docs/version-8.6/reference/regions.md

See: https://github.com/camunda/product-hub/issues/2556

feat(saas): document the upcoming Singapore region

---

docs/reference/supported-environments.md
versioned_docs/version-8.6/reference/supported-environments.md

Via Slack - https://camunda.slack.com/archives/C026U8GBNSW/p1732264531703819

Add 8.6 to supported env page

---

docs/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/configuration.md

This PR documents ways to configure the auto-completion of jobs.

fix: mention auto-complete configuration options

---

docs/reference/release-notes/860.md
versioned_docs/version-8.6/reference/release-notes/860.md

Lowercasing copilot based on https://camunda.slack.com/archives/C0484UFR2VA/p1732199501883129.

lowercase copilot

---

docs/self-managed/operational-guides/update-guide/introduction.md
versioned_docs/version-8.3/self-managed/operational-guides/update-guide/introduction.md
versioned_docs/version-8.4/self-managed/operational-guides/update-guide/introduction.md
versioned_docs/version-8.5/self-managed/operational-guides/update-guide/introduction.md
versioned_docs/version-8.6/self-managed/operational-guides/update-guide/introduction.md

Closes https://github.com/camunda/camunda-docs/issues/4653
- Removes the note about pre-Camunda 8 versions/Camunda Cloud 
- Adds the 8.5 -> 8.6 links to the 8.6 version, and adds 8.5 -> 8.6 and 8.6 -> 8.7 to /next

Add missing SM update guides to introduction

---

docs/self-managed/tasklist-deployment/data-retention.md
versioned_docs/version-8.6/self-managed/tasklist-deployment/data-retention.md

fix: remove unintentional code block

---

docs/self-managed/tasklist-deployment/data-retention.md
versioned_docs/version-8.6/self-managed/tasklist-deployment/data-retention.md

chore: apply suggestion

---

versioned_docs/version-8.5/self-managed/setup/upgrade.md

ASAP
support: https://jira.camunda.com/browse/SUPPORT-24713

fix: removing webModelerPostgresql from 8.5 upgrade guide

---

docs/components/concepts/workflow-patterns.md
versioned_docs/version-8.5/components/concepts/workflow-patterns.md
versioned_docs/version-8.6/components/concepts/workflow-patterns.md

Remove outdated note from https://docs.camunda.io/docs/next/components/concepts/workflow-patterns/#compensation.
This looks like it was available in 8.5, so backported the changes to 8.6, and 8.5 docs versions as well.

Remove compensation event note

---

docs/apis-tools/java-client/index.md
versioned_docs/version-8.6/apis-tools/java-client/index.md

Via https://camunda.slack.com/archives/C026U8GBNSW/p1733493903003619

Adjust Java client bootstrapping example

---

docs/reference/release-notes/870.md

Via https://camunda.slack.com/archives/C03NFMH4KC6/p1733836608718009?thread_ts=1733124496.418139&cid=C03NFMH4KC6

Bump Connectors to alpha2.1 in release notes

---

docs/self-managed/console-deployment/configuration.md
versioned_docs/version-8.6/self-managed/console-deployment/configuration.md

As of 8.6, Console is no longer limited to Enterprise installations. This PR removes the note from the config pages of 8.6 and /next.
Any other impacted areas will be addressed in the follow-up issue: https://github.com/camunda/camunda-docs/issues/4732

remove the enterprise limitation fron console config docs

---

docs/reference/release-notes/870.md

This PR provides a notification in the docs for customers affected by the bug: https://github.com/camunda/camunda-platform-helm/issues/2662
This requires changes to the release notes, and possibly announcements and SM docs.

DO NOT MERGE Bug notification for Operate login issue in alpha-2

---

docs/guides/react-components/_install-c8run.md
docs/self-managed/setup/deploy/local/c8run.md
versioned_docs/version-8.6/guides/react-components/_install-c8run.md
versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md

task(c8run)-update-guides-after-8.6.6-and-alpha2-release

---

versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/deploy.md
versioned_docs/version-8.5/self-managed/setup/install.md

This heading was removed at some point - just backporting the link removal. 8.3 is unaffected, and 8.6 and /next will be handled by changes in the original PR: https://github.com/camunda/camunda-docs/pull/4763

update Web Modeler database link on helm install page

---

docs/components/modeler/feel/builtin-functions/feel-built-in-functions-string.md

Add documentation for the new string built-in function `is blank()`.
Implemented by https://github.com/camunda/feel-scala/pull/927.
Related to https://github.com/camunda/camunda/issues/22380. 
Closes https://github.com/camunda/camunda/issues/22380.

feat(feel): Add new built-in function `is blank()`

---

docs/components/modeler/desktop-modeler/use-connectors.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/use-connectors.md
versioned_docs/version-8.6/components/modeler/desktop-modeler/use-connectors.md

This was related to a piece of feedback given on PushFeedback. Related to [internal thread](https://camunda.slack.com/archives/C0693F1NFK5/p1734377313082039).

clarify when automatic fetch occurs

---

versioned_docs/version-8.3/components/modeler/bpmn/bpmn-coverage.md
versioned_docs/version-8.4/components/modeler/bpmn/bpmn-coverage.md
versioned_docs/version-8.5/components/modeler/bpmn/bpmn-coverage.md
versioned_docs/version-8.6/components/modeler/bpmn/bpmn-coverage.md

Relates to https://github.com/camunda/camunda-docs/pull/4155#issuecomment-2559735149.

backport bpmn coverage changes

---

docs/apis-tools/frontend-development/03-forms/01-introduction-to-forms.md
versioned_docs/version-8.5/apis-tools/frontend-development/03-forms/01-introduction-to-forms.md
versioned_docs/version-8.6/apis-tools/frontend-development/03-forms/01-introduction-to-forms.md

Fix the [dead link](https://docs.camunda.io/docs/next/components/modeler/bpmn/user-tasks//#user-task-forms) on [introduction to forms](https://docs.camunda.io/docs/next/apis-tools/frontend-development/forms/introduction-to-forms/) when clicking on the linked 'user tasks'.

Fix form introduction link

---

docs/components/connectors/out-of-the-box-connectors/box.md
optimize_sidebars.js
sidebars.js

This is a new Connector that will officially be released with 8.7
Product hub epic: https://github.com/camunda/product-hub/issues/2399
Connectors issue: https://github.com/camunda/team-connectors/issues/958
- [ x] I included my new page in the sidebar file(s).

feat(box): Add box connector docs

---

docs/components/concepts/user-task-listeners.md
docs/reference/glossary.md
sidebars.js

Scope:
- Created `Ufser task listener` page in the `components/concepts` section.
- Described the main concepts for user task listeners.
- Registered `user-task-listeners` page in `sidebars.js`.
- Add `User task listener` to the Glossary page.
These changes were made together by @ana-vinogradova-camunda and @ce-dmelnych so they don't require additional Engineering review. A Technical writer review is appreciated.
closes https://github.com/camunda/camunda/issues/26342

Crete concept page for user task listeners

---

docs/components/modeler/web-modeler/fix-problems-in-your-diagram.md
versioned_docs/version-8.3/components/modeler/web-modeler/fix-problems-in-your-diagram.md
versioned_docs/version-8.4/components/modeler/web-modeler/fix-problems-in-your-diagram.md
versioned_docs/version-8.5/components/modeler/web-modeler/fix-problems-in-your-diagram.md
versioned_docs/version-8.6/components/modeler/web-modeler/fix-problems-in-your-diagram.md

Web Modeler doesn't allow ids greater than 255 chars, but doesn't lint for this or throw an intuitive error. This is a bit of a bandaid fix and feedback was provided to the team to improve the linting and/or a more intuitive error experience.
Related to https://camunda.slack.com/archives/C087LHSPR5X.

Add note for id length in Web Modeler

---

docs/self-managed/setup/upgrade.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/upgrade.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/upgrade.md
versioned_docs/version-8.5/self-managed/setup/upgrade.md
versioned_docs/version-8.6/self-managed/setup/upgrade.md

The supported version of Elasticsearch in 8.3 is listed as 8.8. This PR updates the version listed in the upgrade guide to ensure there is no confusion, and uses 8.8.2 per this comment:
In an upgrade path from 8.2. to 8.3 you would leverage helm chart 8.3.21, which uses tag: 8.8.2 for elasticsearch. https://artifacthub.io/packages/helm/camunda/camunda-platform/8.3.21?modal=values.
Internal slack thread: https://camunda.slack.com/archives/C03UR0V2R2M/p1731939844839799

Update the Camunda 8.3 elasticsearch tag to 8.8.2

---

docs/components/zeebe/technical-concepts/partitions.md
docs/self-managed/zeebe-deployment/operations/resource-planning.md
versioned_docs/version-8.3/components/zeebe/technical-concepts/partitions.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/operations/resource-planning.md
versioned_docs/version-8.4/components/zeebe/technical-concepts/partitions.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/operations/resource-planning.md
versioned_docs/version-8.5/components/zeebe/technical-concepts/partitions.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/resource-planning.md
versioned_docs/version-8.6/components/zeebe/technical-concepts/partitions.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/operations/resource-planning.md

https://zeebe-io.github.io/zeebe-chaos/ has been moved to https://camunda.github.io/zeebe-chaos/ --  https://camunda.slack.com/archives/C026U8GBNSW/p1736763560582699.

update zeebe chaos links

---

docs/reference/release-notes/870.md

Update the alpha release blog URL to: 
https://camunda.com/blog/2025/01/camunda-alpha-release-january-2025

Update alpha release blog URL

---

docs/reference/release-notes/870.md

In the release notes for alpha 3, update Connectors URL to: https://github.com/camunda/connectors/releases/tag/8.7.0-alpha3.2

Update connectors URL

---

docs/self-managed/setup/deploy/local/c8run.md

Per https://camunda.slack.com/archives/C03NFMH4KC6/p1736947708579689.

Update C8Run to 8.7.0-alpha3

---

versioned_docs/version-8.3/reference/regions.md
versioned_docs/version-8.4/reference/regions.md
versioned_docs/version-8.5/reference/regions.md
versioned_docs/version-8.6/reference/regions.md

Backport the changes made in https://github.com/camunda/camunda-docs/pull/4721 to 8.6-8.3.

Backport AWS region changes

---

docs/reference/announcements/860.md
versioned_docs/version-8.6/reference/announcements.md

Fix a typo on the Announcements page introduced in https://github.com/camunda/camunda-docs/pull/4845#issuecomment-2594975485.

Fix typo on Announcements page 

---

docs/apis-tools/testing/getting-started.md
versioned_docs/version-8.6/apis-tools/testing/getting-started.md

Change the wording in the disclaimer note of Camunda Process Test to refer to Zeebe Process Test as a "mature" testing library instead of a "full-featured" testing library because it is also missing features, such as the new REST API and native user tasks.
This is a follow-up task of an [support case](https://app.incident.io/camunda/incidents/2204?tab=post-incident&follow_up_id=01JHFHA4QJ76KP11SPJ44XZY58).

docs(testing): Rephrase disclaimer note

---

docs/self-managed/identity/getting-started/install-identity.md
docs/self-managed/identity/troubleshooting/troubleshoot-identity.md
docs/self-managed/identity/user-guide/configuration/configure-external-identity-provider.md
versioned_docs/version-8.3/self-managed/identity/user-guide/configuration/connect-to-an-existing-keycloak.md
versioned_docs/version-8.4/self-managed/identity/user-guide/configuration/connect-to-an-existing-keycloak.md
versioned_docs/version-8.5/self-managed/identity/getting-started/install-identity.md
versioned_docs/version-8.5/self-managed/identity/troubleshooting/troubleshoot-identity.md
versioned_docs/version-8.5/self-managed/identity/user-guide/configuration/configure-external-identity-provider.md
versioned_docs/version-8.5/self-managed/identity/user-guide/configuration/connect-to-an-existing-keycloak.md
versioned_docs/version-8.6/self-managed/identity/getting-started/install-identity.md
versioned_docs/version-8.6/self-managed/identity/troubleshooting/troubleshoot-identity.md
versioned_docs/version-8.6/self-managed/identity/user-guide/configuration/configure-external-identity-provider.md
versioned_docs/version-8.6/self-managed/identity/user-guide/configuration/connect-to-an-existing-keycloak.md

Docs housekeeping for January.

update broken third party links to latest

---

docs/reference/announcements.md

Fix 8.7 announcements date to 8 April 2025.

Fix 8.7 announcements date

---

docs/apis-tools/camunda-api-rest/camunda-api-rest-authentication.md
docs/apis-tools/camunda-api-rest/camunda-api-rest-overview.md
docs/apis-tools/operate-api/overview.md
docs/apis-tools/spring-zeebe-sdk/getting-started.md
docs/apis-tools/tasklist-api-rest/tasklist-api-rest-overview.md
docs/components/connectors/out-of-the-box-connectors/amazon-eventbridge.md
docs/components/connectors/out-of-the-box-connectors/amazon-sns.md
docs/components/connectors/out-of-the-box-connectors/github.md
docs/components/connectors/out-of-the-box-connectors/operate.md
docs/components/connectors/out-of-the-box-connectors/slack.md
docs/components/connectors/out-of-the-box-connectors/twilio.md
docs/components/connectors/protocol/http-webhook.md
docs/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.6/apis-tools/camunda-api-rest/camunda-api-rest-authentication.md
versioned_docs/version-8.6/apis-tools/camunda-api-rest/camunda-api-rest-overview.md
versioned_docs/version-8.6/apis-tools/operate-api/overview.md
versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.6/apis-tools/tasklist-api-rest/tasklist-api-rest-overview.md
versioned_docs/version-8.6/apis-tools/zeebe-api-rest/zeebe-api-rest-overview.md
versioned_docs/version-8.6/components/connectors/out-of-the-box-connectors/amazon-sns.md
versioned_docs/version-8.6/components/connectors/out-of-the-box-connectors/github.md
versioned_docs/version-8.6/components/connectors/out-of-the-box-connectors/operate.md
versioned_docs/version-8.6/components/connectors/out-of-the-box-connectors/slack.md
versioned_docs/version-8.6/components/connectors/out-of-the-box-connectors/twilio.md
versioned_docs/version-8.6/components/connectors/protocol/http-webhook.md
versioned_docs/version-8.6/guides/getting-started-orchestrate-microservices.md

Closes https://github.com/camunda/camunda-docs/issues/2493, and relates to https://github.com/camunda/product-hub/issues/1391 and https://github.com/camunda-cloud/camunda-cloud-management-apps/pull/1064.
This adjusts references of the updated UI reading "region Id" rather than "region".

adjust references of region to regionid

---

docs/components/modeler/reference/modeling-guidance/rules/history-time-to-live.md
versioned_docs/version-8.5/components/modeler/reference/modeling-guidance/rules/history-time-to-live.md
versioned_docs/version-8.6/components/modeler/reference/modeling-guidance/rules/history-time-to-live.md

Related to a piece of PushFeedback and [this thread](https://camunda.slack.com/archives/C6M6X3EKZ/p1737481852675499). User requested additional details on possible values for HTTL.

add values details for httl

---

docs/reference/announcements.md
docs/reference/announcements/870.md

Removes items shipped in 8.8 and adds items shipped in 8.7 (as identified https://github.com/camunda/product-hub/issues/2618 in the docs section).
‼️ Once reviewed, this can be merged and iterated on to add new topics or adjust language, but priority topics should be mostly correct and accurate before merging. ‼️

Adjust 8.7 announcements

---

docs/apis-tools/community-clients/cli-client/index.md
versioned_docs/version-8.5/apis-tools/cli-client/index.md
versioned_docs/version-8.6/apis-tools/community-clients/cli-client/index.md

Related to a piece of PushFeedback and [Slack thread](https://camunda.slack.com/archives/CSQ2E3BT4/p1737481747595059). Adds example SM address for CLI client.

add sm address details for cli client

---

versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md

fix: misleading message size

---

versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md

fix: wrong property mapping

---

docs/self-managed/setup/guides/connect-to-an-oidc-provider.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider.md
versioned_docs/version-8.5/self-managed/setup/guides/connect-to-an-oidc-provider.md
versioned_docs/version-8.6/self-managed/setup/guides/connect-to-an-oidc-provider.md

This PR is related to the comment in the this ticket: https://github.com/camunda/camunda-docs/issues/4619#issue-2671518040.
Tltr: Its adds an or statement to the oidc configuration as it was not clear to users it both, envVars and/or helm values need to be set. Changes to back to 8.4 guides (no guide for OIDC in 8.3).
However, this ticket is not closed as another question related to oidc came up.

add xor to oidc configuration

---

versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md

chore(c8run): point to latest patch

---

docs/components/connectors/protocol/rest.md

connectors add hint to skip encoding for rest outbound

---

docs/components/modeler/web-modeler/git-sync.md
docs/self-managed/zeebe-deployment/operations/cluster-scaling.md
docs/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/operations/cluster-scaling.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/operations/management-api.md

I am uncertain how these didn't break in other branches, but they break in #4872.
I'm fixing them here in main, and then porting to that branch.

fix: remove terminating slash from .md links

---

versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md

fix: misleading config

---

versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/configuration.md

This PR removes an unnecessary section from the docs.
Context: https://camunda.slack.com/archives/CSQ2E3BT4/p1737977906277909

fix: basic auth is not available in 8.6

---

docs/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.3/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.4/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.5/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.6/guides/getting-started-orchestrate-microservices.md

During the onboarding I've spotted this small inaccuracy.

fix: update path in guide to the relevant one

---

docs/reference/supported-environments.md
versioned_docs/version-8.6/reference/supported-environments.md

docs: update supported environments for web modeler

---

docs/self-managed/zeebe-deployment/configuration/broker.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/configuration/broker.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/configuration/broker.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/configuration/broker.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/broker.md

fix: zeebe broker raft section

---

docs/self-managed/operational-guides/update-guide/850-to-860.md
docs/self-managed/setup/upgrade.md
versioned_docs/version-8.6/self-managed/operational-guides/update-guide/850-to-860.md
versioned_docs/version-8.6/self-managed/setup/upgrade.md

The information regarding Operate and Tasklist URL changes was included in the 8.6 announcements, but could be missed if a customer was moving through the SM-specific update/upgrade pages. This PR updates the update and upgrade guides for SM 8.6 and 8.6 in /next to include an overview of the change and link to the detailed announcements description.

Add Operate/Tasklist path changes to SM upgrade and update guides 

---

howtos/interactive-api-explorers.md

Describes the features added to API doc generation in #4799. (Basically, the ability to generate numbered versions of API docs.)

docs: update OpenAPI generation docs

---

docs/self-managed/modeler/web-modeler/configuration/configuration.md

Contains a small follow-up for https://github.com/camunda/camunda-docs/pull/4954 fixing the wording.

docs(web-modeler): fix wording in cluster configuration

---

docs/self-managed/setup/install.md
versioned_docs/version-8.5/self-managed/setup/install.md
versioned_docs/version-8.6/self-managed/setup/install.md

Customers get errors running C8 due to docker Hub imposing limits on pulls. This note will help to avoid this. 
- [ x ] This is already available but undocumented and should be released within a week. (add `available & undocumented` label)
- [ X ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ X ] I added a DRI, team, or delegate as a reviewer for technical accuracy and grammar/style:
- [ X ] [Engineering team review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process)
- [ X ] [Technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process) via `@camunda/tech-writers` unless working with an embedded writer.

Adding note about Docker Hub limits

---

docs/apis-tools/zeebe-api/grpc.md
versioned_docs/version-8.5/apis-tools/zeebe-api/grpc.md
versioned_docs/version-8.6/apis-tools/zeebe-api/grpc.md

Add a section at the top of the [gRPC docs](https://docs.camunda.io/docs/apis-tools/grpc/) to encourage the positive aspects of gRPC (vs. REST) to help customers understand "why gRPC". Closes https://github.com/camunda/camunda-docs/issues/2649.

add details to grpc overview page

---

api/camunda/version-8.6/camunda-openapi.yaml
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/activate-jobs.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/broadcast-signal.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/correlate-a-message.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/create-process-instance.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/deploy-resources.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/evaluate-decision.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/find-all-users.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/get-incident-by-key-alpha.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/migrate-process-instance.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/modify-process-instance.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/publish-a-message.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/query-decision-definitions-alpha.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/query-decision-instances-alpha.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/query-decision-requirements-alpha.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/query-flow-node-instances-alpha.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/query-incidents-alpha.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/query-process-instances-alpha.api.mdx
versioned_docs/version-8.6/apis-tools/camunda-api-rest/specifications/query-user-tasks-alpha.api.mdx

Updates the 8.6 C8 REST API docs based on https://github.com/camunda/camunda/blob/8.6.8/zeebe/gateway-protocol/src/main/proto/rest-api.yaml.

chore: update 8.6 c8 rest api docs

---

versioned_docs/version-8.3/self-managed/operate-deployment/importer-and-archiver.md
versioned_docs/version-8.3/self-managed/tasklist-deployment/importer-and-archiver.md
versioned_docs/version-8.4/self-managed/operate-deployment/importer-and-archiver.md
versioned_docs/version-8.4/self-managed/tasklist-deployment/importer-and-archiver.md
versioned_docs/version-8.5/self-managed/operate-deployment/importer-and-archiver.md
versioned_docs/version-8.5/self-managed/tasklist-deployment/importer-and-archiver.md
versioned_docs/version-8.6/self-managed/operate-deployment/importer-and-archiver.md
versioned_docs/version-8.6/self-managed/tasklist-deployment/importer-and-archiver.md
versioned_docs/version-8.7/self-managed/operate-deployment/importer-and-archiver.md
versioned_docs/version-8.7/self-managed/tasklist-deployment/importer-and-archiver.md

This PR adds a warning that multiple importers on the same partition may result in faulty usage metrics.
Context: https://camunda.slack.com/archives/C9B5270DA/p1725858331879579

Warning about importer configuration and usage metrics

---

docs/self-managed/identity/deployment/configuration-variables.md
versioned_docs/version-8.3/self-managed/identity/deployment/configuration-variables.md
versioned_docs/version-8.4/self-managed/identity/deployment/configuration-variables.md
versioned_docs/version-8.5/self-managed/identity/deployment/configuration-variables.md
versioned_docs/version-8.6/self-managed/identity/deployment/configuration-variables.md
versioned_docs/version-8.7/self-managed/identity/deployment/configuration-variables.md

This PR documents the json logging in identity.
The text was copied over from the connectors component and adjusted.
Source: https://github.com/camunda-cloud/identity/blob/main/management-api/src/main/resources/log4j2-spring.xml#L31

Identity: document stackdriver logging feature

---

src/css/custom.css

Add the text underline class back for admonition links (removed in Docusaurus 3 transition).

Add admonition link underline

---

docs/components/early-access/alpha/bpmn-copilot/bpmn-copilot.md
versioned_docs/version-8.7/components/early-access/alpha/bpmn-copilot/bpmn-copilot.md

docs(bpmn-copilot): add disclaimers

---

static/.htaccess

Adding redirects for Modeler's "current" link to ad-hoc docs. https://camunda.slack.com/archives/C026U8GBNSW/p1737963258846589

add ad hoc redirects for modeler team

---

versioned_docs/version-8.6/guides/getting-started-java-spring.md

https://camunda.slack.com/archives/C026U8GBNSW/p1739280071253199

Adjust 8.6 JDK version for SDK

---

docs/guides/react-components/_install-c8run.md
docs/guides/react-components/_install-plain-java.md
versioned_docs/version-8.7/guides/react-components/_install-c8run.md
versioned_docs/version-8.7/guides/react-components/_install-plain-java.md

Bumps react components to [8.7.0-alpha3](https://github.com/camunda/camunda/releases/tag/8.7.0-alpha3) ([alpha4](https://github.com/camunda/camunda/releases/tag/8.7.0-alpha4) isn't ready and is missing assets, or in a place I don't expect it!) 
[C8 Run for 8.8.0-alpha1](https://github.com/camunda/camunda/releases/tag/8.8.0-alpha1) is also not yet available. 
@conceptualshark please add bumping these values manually to the docs release manager checklist. We could automate in the future.

bump to alpha3

---

docs/self-managed/setup/deploy/local/c8run.md
versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md
versioned_docs/version-8.7/self-managed/setup/deploy/local/c8run.md

Mac users fail to run c8run as the mac artifact is not signed yet, see https://github.com/camunda/camunda/issues/25177. 
Until we have the artifact signed, we should inform the user on how to work around this.

fix: add a workaround to open non signed c8run artifact on mac

---

docs/guides/react-components/_install-c8run.md
versioned_docs/version-8.6/guides/react-components/_install-c8run.md
versioned_docs/version-8.7/guides/react-components/_install-c8run.md

Adds the warning from https://github.com/camunda/camunda-docs/pull/5003 to the reused C8Run react components in Guides.

add mac warning to reused c8run component

---

docs/guides/react-components/_install-c8run.md
docs/self-managed/setup/deploy/local/c8run.md
versioned_docs/version-8.6/guides/react-components/_install-c8run.md
versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md
versioned_docs/version-8.7/guides/react-components/_install-c8run.md
versioned_docs/version-8.7/self-managed/setup/deploy/local/c8run.md

Update C8Run to latest releases (as they are finally out):
* [8.7.0-alpha4](https://github.com/camunda/camunda/releases/tag/8.7.0-alpha4)
* [8.6.9](https://github.com/camunda/camunda/releases/tag/8.6.9)

update c8run to latest releases

---

docs/reference/release-notes/870.md
docs/reference/release-notes/880.md
versioned_docs/version-8.7/reference/release-notes/870.md

This blog post doesn't appear live at this time, but this link was confirmed - will merge once it's released. 👍

Add release blog to 8.7, 8.8 release notes

---

docs/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/getting-started.md

docs(spring-sdk): update bundled spring boot version

---

docs/reference/release-notes/870.md
versioned_docs/version-8.7/reference/release-notes/870.md

- Process instance migration was missing the moved from 8.7 -> 8.8 label
- The new version of the 8.7 release notes were missing the moved labels (present in 8.8)
This PR rectifies each. Note that the 8.7 version of the docs specifically links to the unversioned /docs links.

Add moved note to process instance migration, backport changes to 8.7 release notes

---

howtos/setup.md

Closes https://github.com/camunda/developer-experience/issues/272 -- notes the `deploy` label for building the docs from GitHub, and additional troubleshooting concern.

add deploy options and troubleshooting note to howtos

---

docs/self-managed/zeebe-deployment/exporters/camunda-exporter.md

The archiver and retention configuration was merged in https://github.com/camunda/camunda/pull/27674, this PR involves restructuring the documentation to reflect this and also adding archiver configuration which previously didn't exist.

Merged archiver config

---

static/.htaccess

related to slack message: https://camunda.slack.com/archives/C026U8GBNSW/p1739780692925049
to allow pdf exemption for trailing slashes.
We're using it to link to diagrams in full size to allow customer a more detailed access.

chore: add pdf exemption to .htaccess for trailing slashes

---

versioned_docs/version-8.7/apis-tools/zeebe-api-rest/sidebar-schema.js
versioned_docs/version-8.7/apis-tools/zeebe-api-rest/specifications/assign-a-user-task.api.mdx
versioned_docs/version-8.7/apis-tools/zeebe-api-rest/specifications/complete-a-user-task.api.mdx
versioned_docs/version-8.7/apis-tools/zeebe-api-rest/specifications/get-cluster-topology.api.mdx
versioned_docs/version-8.7/apis-tools/zeebe-api-rest/specifications/sidebar.ts
versioned_docs/version-8.7/apis-tools/zeebe-api-rest/specifications/unassign-a-user-task.api.mdx
versioned_docs/version-8.7/apis-tools/zeebe-api-rest/specifications/update-a-user-task.api.mdx
versioned_docs/version-8.7/apis-tools/zeebe-api-rest/specifications/zeebe-rest-api.info.mdx
versioned_docs/version-8.7/apis-tools/zeebe-api-rest/tutorial.md
versioned_docs/version-8.7/apis-tools/zeebe-api-rest/zeebe-api-rest-authentication.md
versioned_docs/version-8.7/apis-tools/zeebe-api-rest/zeebe-api-rest-overview.md
versioned_sidebars/version-8.7-sidebars.json

Based on my understanding of the 8.7/8.8 split, I think we need to add the Zeebe REST API backed to the deprecated section in the API docs (as it is in 8.6). This PR does that.

Add back Zeebe REST API to deprecated section in 8.7

---

docs/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/configuration.md

The current link is broken because the package name changed for 8.8:
https://github.com/camunda/camunda/blob/main/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/properties/CamundaClientProperties.java
Since this class is used as a reference for available configuration properties, the link should also be versioned:
8.6: https://github.com/camunda/camunda/blob/stable/8.6/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/properties/CamundaClientProperties.java
8.7: https://github.com/camunda/camunda/blob/stable/8.7/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/properties/CamundaClientProperties.java
Bonus: List/describe all available properties in the docs to make them searchable and …

Fix broken link to CamundaClientProperties.java

---

optimize_versioned_docs/version-3.15.0/self-managed/optimize-deployment/configuration/system-configuration.md
versioned_docs/version-8.7/reference/supported-environments.md
versioned_docs/version-8.7/self-managed/setup/guides/using-existing-opensearch.md

The opensearch functionality was moved from 8.7 to 8.8, and this warning should be added back into the appropriate 8.7 docs.

move opensearch warning back into 8.7 docs

---

src/css/custom.css

Fixes a few CSS styles that were changed in the Docusaurus 3 migration:
- Add padding back above the PushFeedback widget.
- Remove extra padding above H2 elements.

Fix CSS styles from D3 migration

---

docs/apis-tools/zeebe-api-rest/sidebar-schema.js
docs/apis-tools/zeebe-api-rest/specifications/assign-a-user-task.api.mdx
docs/apis-tools/zeebe-api-rest/specifications/complete-a-user-task.api.mdx
docs/apis-tools/zeebe-api-rest/specifications/get-cluster-topology.api.mdx
docs/apis-tools/zeebe-api-rest/specifications/sidebar.ts
docs/apis-tools/zeebe-api-rest/specifications/unassign-a-user-task.api.mdx
docs/apis-tools/zeebe-api-rest/specifications/update-a-user-task.api.mdx
docs/apis-tools/zeebe-api-rest/specifications/zeebe-rest-api.info.mdx
docs/apis-tools/zeebe-api-rest/tutorial.md
docs/apis-tools/zeebe-api-rest/zeebe-api-rest-authentication.md
docs/apis-tools/zeebe-api-rest/zeebe-api-rest-overview.md
sidebars.js

Based on my understanding of the 8.7/8.8 split, I think we need to add the Zeebe REST API backed to the deprecated section in the API docs (as it is in 8.6). This PR does that.

Add back Zeebe REST API to deprecated section in 8.8

---

docs/apis-tools/java-client/index.md
docs/guides/getting-started-java-spring.md
versioned_docs/version-8.5/apis-tools/java-client/index.md
versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.5/guides/getting-started-java-spring.md
versioned_docs/version-8.6/apis-tools/java-client/index.md
versioned_docs/version-8.6/guides/getting-started-java-spring.md
versioned_docs/version-8.7/apis-tools/java-client/index.md
versioned_docs/version-8.7/guides/getting-started-java-spring.md

closes https://github.com/camunda/camunda-docs/issues/4370

docs(sdk): add notes about grpcAddress and restAddress client properties

---

docs/components/modeler/web-modeler/collaborate-with-modes.md
docs/components/modeler/web-modeler/play-your-process.md
docs/components/modeler/web-modeler/process-application-versioning.md
docs/components/modeler/web-modeler/versions.md
versioned_docs/version-8.6/components/modeler/web-modeler/collaborate-with-modes.md
versioned_docs/version-8.6/components/modeler/web-modeler/play-your-process.md
versioned_docs/version-8.7/components/modeler/web-modeler/collaborate-with-modes.md
versioned_docs/version-8.7/components/modeler/web-modeler/play-your-process.md
versioned_docs/version-8.7/components/modeler/web-modeler/process-application-versioning.md
versioned_docs/version-8.7/components/modeler/web-modeler/versions.md

This PR addresses the following
- Include limitation of OIDC auth with Play
- Remove Play alpha reference
- Fix invalid anchor urls in web modeler docs

docs(play): Add play limitation and minor fixes

---

docs/reference/release-notes/880.md

Update the 8.8-alpha1 release date.

Update the alpha1 release date

---

versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/sendgrid.md

feat(sendgrid): update documentation with attachments feature 8.7

---

docs/self-managed/zeebe-deployment/exporters/install-zeebe-exporters.md
versioned_docs/version-8.3/self-managed/zeebe-deployment/exporters/install-zeebe-exporters.md
versioned_docs/version-8.4/self-managed/zeebe-deployment/exporters/install-zeebe-exporters.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/exporters/install-zeebe-exporters.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/exporters/install-zeebe-exporters.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/install-zeebe-exporters.md

Closes #5066. Removes from all versions.

Remove Kafka exporter

---

sidebars.js

Moves Operate and Tasklist REST APIs to deprecated in 8.8 as described in the updated [blog](https://camunda.com/blog/2024/12/api-changes-in-camunda-8-a-unified-and-streamlined-experience/).

Move Operate and Tasklist REST APIs to deprecated section in 8.8

---

optimize_versioned_docs/version-3.15.0/self-managed/optimize-deployment/configuration/shared-elasticsearch-cluster.md
optimize_versioned_docs/version-3.15.0/self-managed/optimize-deployment/configuration/system-configuration.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/optimize-backup.md

Full Optimize OpenSearch functionality was originally intended for 8.7, but was moved to 8.8. However, the 8.7 documentation had already been updated to remove OpenSearch warnings/add feature availability. 
This PR reverts these changes (orginally made in https://github.com/camunda/camunda-docs/pull/4750/). This PR does not restore removed Optimize 7 content (removed in https://github.com/camunda/camunda-docs/pull/4854).

Revert the removal of OpenSearch warnings from the 8.7 docs

---

src/pages/index.js

Fix title on landing page for Best Practices.
Closes https://github.com/camunda/camunda-docs/issues/5060.

Fix Best Practice title

---

docs/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md

In this PR, we are updating the environment variables used to run Connectors in a self-managed setup.
The changes only apply to versions 8.7 and 8.8, but the specifics are different between versions, so the changes are adjusted accordingly.
closes https://github.com/camunda/team-connectors/issues/1010

chore: update connectors SM config for 8.7 and 8.8

---

docs/reference/supported-environments.md
versioned_docs/version-8.3/reference/supported-environments.md
versioned_docs/version-8.4/reference/supported-environments.md
versioned_docs/version-8.5/reference/supported-environments.md
versioned_docs/version-8.6/reference/supported-environments.md
versioned_docs/version-8.7/reference/supported-environments.md

Remove `form-js` compat table since it's out of date and now we have the `form-linting` library that embeds the compat information into the modelers
[Slack thread referece](https://camunda.slack.com/archives/C0693F1NFK5/p1740599733072029)

docs: remove form-js compat table

---

docs/reference/announcements/860.md
docs/self-managed/setup/upgrade.md
versioned_docs/version-8.5/self-managed/setup/upgrade.md
versioned_docs/version-8.6/reference/announcements.md
versioned_docs/version-8.6/self-managed/setup/upgrade.md
versioned_docs/version-8.7/reference/announcements/860.md
versioned_docs/version-8.7/self-managed/setup/upgrade.md

The 8.7 release was listed for January in a few areas of the docs. Additionally, the Optimize OpenSearch support was moved to 8.8.

Correct mentions of 8.7 release

---

docs/reference/release-notes/870.md
versioned_docs/version-8.7/reference/release-notes/870.md

Resolves https://github.com/camunda/camunda-docs/issues/5100#event-16496700980
The query API was not entirely removed from the 8.7 release, but still exists as an alpha feature. The release note warning about its removal has been updated to reflect this.

Update query API release note

---

docs/reference/announcements/860.md
docs/reference/announcements/880.md
docs/reference/supported-environments.md
versioned_docs/version-8.6/reference/announcements.md
versioned_docs/version-8.6/reference/supported-environments.md
versioned_docs/version-8.7/reference/announcements/860.md
versioned_docs/version-8.7/reference/supported-environments.md

* closes camunda/camunda-docs#5077
* This is a DRAFT for discussions, required clean-up
* If we go for this, then what is still needed:
* Update: done with @theburi

feat(supportedEnv): update compatability matrix

---

versioned_docs/version-8.6/self-managed/concepts/elasticsearch-without-cluster-privileges.md

feat: Update documentation for Schema Manager

---

docs/self-managed/setup/deploy/other/docker.md
versioned_docs/version-8.6/self-managed/setup/deploy/other/docker.md
versioned_docs/version-8.7/self-managed/setup/deploy/other/docker.md

With the introduction of license keys, the Optimize `_ENTERPRISE` variables should no longer be required.
Resolves https://github.com/camunda/camunda-docs/issues/4131

Remove `_ENTERPRISE` vars from 8.6+

---

docs/reference/announcements/860.md
docs/self-managed/operational-guides/update-guide/850-to-860.md
docs/self-managed/setup/upgrade.md
versioned_docs/version-8.6/reference/announcements.md
versioned_docs/version-8.6/self-managed/operational-guides/update-guide/850-to-860.md
versioned_docs/version-8.6/self-managed/setup/upgrade.md
versioned_docs/version-8.7/reference/announcements/860.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/850-to-860.md
versioned_docs/version-8.7/self-managed/setup/upgrade.md

Several areas in the docs specified deprecated items would be fully removed in the 8.7 Camunda release. These items will now be removed in 8.8. This PR updates the removal for changed keys and separated ingress availability to 8.8 in the update/upgrade guides, and in announcements.
Reverting the Ingress doc removal will be handled separately: https://github.com/camunda/camunda-docs/issues/5116
Slack convo for confirmation: https://camunda.slack.com/archives/C03UR0V2R2M/p1740674890099049

Adjust deprecations/removals for 8.7 to 8.8

---

docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
docs/self-managed/setup/deploy/openshift/redhat-openshift.md
versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.6/self-managed/setup/deploy/openshift/redhat-openshift.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.7/self-managed/setup/deploy/openshift/redhat-openshift.md

This deprecation notice is incorrect. It should be removed.

fix: removing incorrect deprecation notice

---

optimize_versioned_docs/version-3.14.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.15.0/self-managed/optimize-deployment/configuration/system-configuration.md
versioned_docs/version-8.6/reference/supported-environments.md
versioned_docs/version-8.6/self-managed/setup/guides/using-existing-opensearch.md
versioned_docs/version-8.7/reference/supported-environments.md
versioned_docs/version-8.7/self-managed/setup/guides/using-existing-opensearch.md

Because we list currently supported features in the Opensearch docs, it can be easy to miss that backups and other features are not yet supported. This adds in mention of backups explicitly to reduce confusion.
Open to wording suggestions, as I think this line might scan too _inclusively_ (as in, backups _are_ supported).

update opensearch warning to call out backups clearly

---

docs/guides/utilizing-forms.md
versioned_docs/version-8.3/guides/utilizing-forms.md
versioned_docs/version-8.4/guides/utilizing-forms.md
versioned_docs/version-8.5/guides/utilizing-forms.md
versioned_docs/version-8.6/guides/utilizing-forms.md
versioned_docs/version-8.7/guides/utilizing-forms.md

A one-liner add to acknowledge the AI Form Builder option on the palette for building forms. As far as I can tell, this feature was released for 8.2+, but we only support 8.3+. 
This is urgent for @amyjohnston. See https://camunda.slack.com/archives/C026U8GBNSW/p1741198223147579.

Add one-liner to forms guide for AI Form Builder

---

versioned_docs/version-8.7/apis-tools/camunda-api-rest/camunda-api-rest-overview.md

Closes #5099.
Rewrites the 8.7 C8 rest overview to better align with the 8.6 overview.

docs: rewrite 8.7 rest overview to better align with 8.6

---

docs/reference/announcements.md
docs/reference/announcements/870.md
docs/self-managed/operational-guides/update-guide/860-to-870.md
versioned_docs/version-8.7/reference/announcements.md
versioned_docs/version-8.7/reference/announcements/870.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md

This PR adds a section to both the 8.7 and 8.8 announcements pages relating to the upgrade of Keycloak. Additionally I have noted down two known changes we have made to our helm charts to support this upgrade (I wasn't sure if this was required but I can always rework it if required).

docs(identity): add keycloak upgrade to the announcements for 8.7 and 8.8

---

docs/reference/dependencies.md
versioned_docs/version-8.6/reference/dependencies.md
versioned_docs/version-8.7/reference/dependencies.md

As discussed with @MaxTru, due to the current process of SBOM generation not done automatically, and FOSSA becoming the SBOM solution in the future to auto-generate the SBOMs in the future as a part of the release process (TBD), it makes sense to replace the confusing SBOM links for the `camunda/camunda` with the disclaimer that they can be generated on demand.
The SBOMs for `camunda/connectors` are still generated the old way (still to be converted to FOSSA generation in the future), so I kept the text there as is.

Update SBOM reference to monorepo and connectors to be on demand

---

docs/self-managed/setup/deploy/local/docker-compose.md
docs/self-managed/setup/overview.md
src/components/CamundaDistributions/DockerCompose.jsx
versioned_docs/version-8.3/self-managed/platform-deployment/overview.md
versioned_docs/version-8.4/self-managed/platform-deployment/docker.md
versioned_docs/version-8.4/self-managed/platform-deployment/overview.md
versioned_docs/version-8.5/self-managed/setup/deploy/local/docker-compose.md
versioned_docs/version-8.5/self-managed/setup/overview.md
versioned_docs/version-8.6/self-managed/setup/deploy/local/docker-compose.md
versioned_docs/version-8.6/self-managed/setup/overview.md
versioned_docs/version-8.7/self-managed/setup/deploy/local/docker-compose.md
versioned_docs/version-8.7/self-managed/setup/overview.md

For unified naming, we rename [camunda/camunda-self-managed](https://github.com/camunda/camunda-self-managed) to `camunda/camunda-distributions` (with s).

docs(self-managed): rename camunda distros repo

---

docs/apis-tools/java-client/index.md
docs/reference/announcements/860.md
docs/reference/announcements/870.md
docs/reference/announcements/880.md
versioned_docs/version-8.6/apis-tools/java-client/index.md
versioned_docs/version-8.6/reference/announcements.md
versioned_docs/version-8.7/apis-tools/java-client/index.md
versioned_docs/version-8.7/reference/announcements/860.md
versioned_docs/version-8.7/reference/announcements/870.md

As java client replacement is postponed to 8.8, updating the client replacement notes and announcements.
closes https://github.com/camunda/camunda-docs/issues/4046

docs(sdk): update java client replacement versions

---

versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/getting-started.md

relates to https://github.com/camunda/camunda/issues/28698
Springboot version of the Spring SDK 8.5 was bumped to 3.3 starting from 8.5.16. It will be released on March 11th

docs(spring sdk): update bundled spring boot versions for spring sdk 8.5

---

versioned_docs/version-8.7/self-managed/operational-guides/production-guide/helm-chart-production-guide.md

closes https://github.com/camunda/distribution/issues/436
The disclaimer can be removed as the last issue around oidc + multi namepsace setup is fixed now.

fix: remove note from production guide as issue fixed

---

docs/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/getting-started.md

Fix broken link in Spring SDK

---

docs/self-managed/concepts/multi-region/dual-region.md
versioned_docs/version-8.6/self-managed/concepts/multi-region/dual-region.md
versioned_docs/version-8.7/self-managed/concepts/multi-region/dual-region.md

Resolves https://github.com/camunda/camunda-docs/issues/5187 by removing the cut-off sentence. The section on regional failures was moved to a separate part of this guide: https://docs.camunda.io/docs/next/self-managed/concepts/multi-region/dual-region/#region-loss

Remove cut off sentence in dual region docs

---

docs/reference/announcements.md
docs/reference/announcements/870.md
docs/reference/announcements/880.md
versioned_docs/version-8.7/reference/announcements.md
versioned_docs/version-8.7/reference/announcements/870.md

The links have gotten out of sync in the announcement pages and their various subpages - this updates them all to match again.

Reconcile 8.7 and 8.8 announcement pages, summary

---

versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md

This is a small follow-up PR to https://github.com/camunda/camunda-docs/pull/5204, to add in an edit missed from 8.7 in the original PR.
- [] This is already available but undocumented and should be released within a week. (add `available & undocumented` label)

IDP file size limit

---

docs/reference/release-notes/870.md
versioned_docs/version-8.7/reference/release-notes/870.md

Adding a sentence to the RPA release notes.

tweak rpa release note

---

docs/reference/release-notes/870.md
docs/reference/release-notes/880.md
versioned_docs/version-8.7/reference/release-notes/870.md

@conceptualshark I did a retro-review of the release notes for you, have made the following edits:
- Reworded BPMN Copilot BPMN-to-text entry
- Spaced out Camunda 8 Run advanced configuration options for easier scanning
- Added content for Console cluster health and capacity monitoring (docs now live)
- Removed the extraneous entry for Document extraction for unstructured data as this is the IDP entry basically.
Feel free to revert any changes you don't like 😊

TW review edits

---

docs/reference/release-notes/870.md
versioned_docs/version-8.7/reference/release-notes/870.md

https://github.com/camunda/camunda-docs/pull/5184#issuecomment-2714758155 - BPMN to text docs are good to go live, so adding this release note back in 👍

Add bpmn-to-text release note

---

docs/components/modeler/web-modeler/idp/idp-configuration.md
docs/components/modeler/web-modeler/intelligent-document-processing.md
docs/reference/release-notes/870.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-configuration.md
versioned_docs/version-8.7/components/modeler/web-modeler/intelligent-document-processing.md
versioned_docs/version-8.7/reference/release-notes/870.md

Edits to IDP for the alpha-5 release configuration.

IDP release note edit

---

docs/reference/notices.md
versioned_docs/version-8.3/reference/notices.md
versioned_docs/version-8.4/reference/notices.md
versioned_docs/version-8.5/reference/notices.md
versioned_docs/version-8.6/reference/notices.md
versioned_docs/version-8.7/reference/notices.md

Relates to https://jira.camunda.com/browse/SUPPORT-26275 - adds the SaaS fix timeline to the security notice. See also [related Slack discussion](https://camunda.slack.com/archives/G01EAM4M0HK/p1741777654734569?thread_ts=1741693605.578429&cid=G01EAM4M0HK).

docs(web-modeler): clarify security notice 14 for SaaS

---

docs/guides/react-components/_install-c8run.md
docs/self-managed/setup/deploy/local/c8run.md
versioned_docs/version-8.6/guides/react-components/_install-c8run.md
versioned_docs/version-8.6/self-managed/setup/deploy/local/c8run.md
versioned_docs/version-8.7/guides/react-components/_install-c8run.md
versioned_docs/version-8.7/self-managed/setup/deploy/local/c8run.md

Unlike my previous PR #5220 , this is an alternative which will update the links manually.

fix: update c8run links manually

---

docs/components/connectors/protocol/rest.md
versioned_docs/version-8.6/components/connectors/protocol/rest.md
versioned_docs/version-8.7/components/connectors/protocol/rest.md

Adding this table to the docs:
- [xx] are in the `/docs` directory (version 8.8).

fix(rest-connector): Add proxy table

---

docs/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/configuration.md

This PR adds the docs for a missing configuration option:
8.6: https://github.com/camunda/camunda/blob/stable/8.6/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/properties/common/AuthProperties.java#L25
8.7: https://github.com/camunda/camunda/blob/stable/8.7/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring/client/properties/common/AuthProperties.java#L35
8.8: https://github.com/camunda/camunda/blob/main/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/spring/client/properties/CamundaClientAuthProperties.java#L43

added undocumented property

---

docs/self-managed/setup/guides/add-extra-manifests.md
sidebars.js
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/add-extra-manifests.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/add-extra-manifests.md
versioned_docs/version-8.5/self-managed/setup/guides/add-extra-manifests.md
versioned_docs/version-8.6/self-managed/setup/guides/add-extra-manifests.md
versioned_docs/version-8.7/self-managed/setup/guides/add-extra-manifests.md
versioned_sidebars/version-8.3-sidebars.json
versioned_sidebars/version-8.4-sidebars.json
versioned_sidebars/version-8.5-sidebars.json
versioned_sidebars/version-8.6-sidebars.json
versioned_sidebars/version-8.7-sidebars.json

closes: https://github.com/camunda/camunda-platform-helm/issues/2999

feat: adding extra manifests

---

docs/components/modeler/bpmn/message-events/message-events.md
docs/components/modeler/bpmn/signal-events/signal-events.md
versioned_docs/version-8.5/components/modeler/bpmn/message-events/message-events.md
versioned_docs/version-8.5/components/modeler/bpmn/signal-events/signal-events.md
versioned_docs/version-8.6/components/modeler/bpmn/message-events/message-events.md
versioned_docs/version-8.6/components/modeler/bpmn/signal-events/signal-events.md
versioned_docs/version-8.7/components/modeler/bpmn/message-events/message-events.md
versioned_docs/version-8.7/components/modeler/bpmn/signal-events/signal-events.md

Closes https://github.com/camunda/camunda-docs/issues/5054.
- Message Events are used if a single process instance needs to wait for a message from a secondary process or an external system. This is (usually) a 1 sender to 1 recipient relationship (1:1).
- Signal Events are used if you want to communicate with (potentially) multiple listeners. For intermediate events a signal will trigger all process instances that have a token waiting at a corresponding catch event, even across different processes. For start events a signal will start one instance per process that has a corresponding signal start. Thus signals form a 1 sender to N recipients relationship (1:N).
Both event types are methods of collaboration within BPMN.
We have received PushFeedback that users are having a difficult time …

differentiate between signal and message events

---

docs/components/connectors/out-of-the-box-connectors/amazon-bedrock.md
versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/amazon-bedrock.md

Add information about the supported file formats for the Amazon Bedrock connector.
Prompted by https://github.com/camunda/camunda-docs/issues/4823, and closes https://github.com/camunda/camunda-docs/issues/5254.

Amazon Bedrock connector supported file formats

---

docs/self-managed/operational-guides/update-guide/860-to-870.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md

This PR documents log pattern changes which will be done from 8.6 to 8.7, which could be a breaking change for some users (e.g. log based alerts), but most likely is not for the majority.

docs: document log pattern changes

---

versioned_docs/version-8.7/self-managed/concepts/elasticsearch-without-cluster-privileges.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/backup-and-restore.md
versioned_sidebars/version-8.7-sidebars.json

Apply https://github.com/camunda/camunda-docs/pull/5101 and https://github.com/camunda/camunda-docs/pull/5203 to 8.7

doc: add elasticsearch-without-cluster-privileges page in 8.7

---

docs/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-other-problems.md
optimize_sidebars.js
optimize_versioned_sidebars/version-3.11.0-sidebars.json
optimize_versioned_sidebars/version-3.12.0-sidebars.json
optimize_versioned_sidebars/version-3.13.0-sidebars.json
optimize_versioned_sidebars/version-3.14.0-sidebars.json
optimize_versioned_sidebars/version-3.15.0-sidebars.json
sidebars.js
versioned_docs/version-8.3/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-other-problems.md
versioned_docs/version-8.4/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-other-problems.md
versioned_docs/version-8.5/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-other-problems.md
versioned_docs/version-8.6/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-other-problems.md
versioned_docs/version-8.7/self-managed/modeler/web-modeler/troubleshooting/troubleshoot-other-problems.md
versioned_sidebars/version-8.3-sidebars.json
versioned_sidebars/version-8.4-sidebars.json
versioned_sidebars/version-8.5-sidebars.json
versioned_sidebars/version-8.6-sidebars.json
versioned_sidebars/version-8.7-sidebars.json

Closes https://github.com/camunda/web-modeler/issues/10085

docs(web-modeler): add troubleshooting for WAF problems

---

docs/reference/announcements/860.md
docs/self-managed/operational-guides/update-guide/850-to-860.md
versioned_docs/version-8.6/components/connectors/protocol/rest.md
versioned_docs/version-8.6/reference/announcements.md
versioned_docs/version-8.6/self-managed/operational-guides/update-guide/850-to-860.md
versioned_docs/version-8.7/reference/announcements/860.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/850-to-860.md

I fixed the version when this feature flag is available

fix(rest-connector): Fix header grouping feature version number

---

versioned_docs/version-8.3/self-managed/platform-deployment/docker.md
versioned_docs/version-8.4/self-managed/platform-deployment/docker.md
versioned_docs/version-8.5/guides/getting-started-java-spring.md
versioned_docs/version-8.5/self-managed/setup/deploy/local/docker-compose.md
versioned_docs/version-8.7/guides/react-components/_install-docker-compose.md

related: https://github.com/camunda/camunda-distributions/issues/83
Only enterprise customers can now run the main docker-compose file for versions previous to 8.6
Also, it is not possible anymore to run web modeler standalone on docker-compose for version previous to 8.6

fix: docker compose setup changes for versions previous to 8.6

---

.github/workflows/check-format.yaml

Fixes vale linting by downgrading vale. Also pins the vale-action to a numbered version.
Vale issued a release that included a new peer dependency, mdx2vast, in https://github.com/errata-ai/vale/releases/tag/v3.10.0.

downgrade vale

---

docs/components/best-practices/development/writing-good-workers.md
versioned_docs/version-8.6/components/best-practices/development/writing-good-workers.md
versioned_docs/version-8.7/components/best-practices/development/writing-good-workers.md

Replace references to community Spring client with Spring SDK

---

docs/guides/migrating-from-camunda-7/migration-tooling.md
versioned_docs/version-8.6/guides/migrating-from-camunda-7/migration-tooling.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-tooling.md

This PR fixes the release date of the 8.8 release in our migraiton guide

correct date fo 8.8 release

---

docs/guides/getting-started-java-spring.md

Outcome of #5246.
Adds context to the Spring Getting Started guide. I noticed these things could use more information while stepping through the guide. 
I'm opening this PR against v8.8 to solicit feedback. Once I've received/addressed the feedback, I'll backport the changes to previous versions of the guide, as part of this PR.

docs: add context in the spring getting started guide

---

docs/components/best-practices/development/writing-good-workers.md
versioned_docs/version-8.6/components/best-practices/development/writing-good-workers.md
versioned_docs/version-8.7/components/best-practices/development/writing-good-workers.md

make spring sdk spring zeebe sdk again

---

docs/components/modeler/web-modeler/idp/idp-configuration.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-configuration.md

Update the Docker Compose file URL as it has changed.

Update Docker URL

---

docs/components/modeler/web-modeler/run-or-publish-your-process.md
versioned_docs/version-8.3/components/modeler/web-modeler/run-or-publish-your-process.md
versioned_docs/version-8.4/components/modeler/web-modeler/run-or-publish-your-process.md
versioned_docs/version-8.5/components/modeler/web-modeler/run-or-publish-your-process.md
versioned_docs/version-8.6/components/modeler/web-modeler/run-or-publish-your-process.md
versioned_docs/version-8.7/components/modeler/web-modeler/run-or-publish-your-process.md

I came across this page and noticed the url list looks a bit weird, and I thought this was not intentional. If I am mistaken, just ignore and close my PR 😄

docs(web-modeler): remove unnecessary links from publish process options

---

docs/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/operations/management-api.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/operations/management-api.md

Adding a small detail to the exporters API service and port based on PushFeedback.

add note on service and port for exporters api

---

versioned_docs/version-8.6/guides/getting-started-java-spring.md
versioned_docs/version-8.7/guides/getting-started-java-spring.md

I got merge-happy in #5248, and forgot to backport to 8.6 & 8.7. This resolves that mistake, adding context to the Spring Getting Started Guide.

chore: backport #5248 to 8.6 & 8.7

---

docs/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.3/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.4/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.5/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.6/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.7/self-managed/operate-deployment/operate-configuration.md

Fix for Felix! Closes https://github.com/camunda/camunda-docs/issues/5340.

Remove Operate config for all versions

---

product-links.txt
static/.htaccess

This ensures that things linked from our modelers as part of [modeling guidance](https://docs.camunda.io/docs/next/components/modeler/reference/modeling-guidance/) are not accidentally unbuilt. This otherwise leads to dead links (https://github.com/camunda/camunda-modeler/issues/4873).
----
Related to https://github.com/camunda/camunda-modeler/issues/4873

chore(product-links): link modeling guidance

---

docs/self-managed/reference-architecture/kubernetes.md
docs/self-managed/setup/deploy/openshift/redhat-openshift.md
sidebars.js
versioned_docs/version-8.7/self-managed/reference-architecture/kubernetes.md
versioned_docs/version-8.7/self-managed/setup/deploy/openshift/redhat-openshift.md
versioned_sidebars/version-8.7-sidebars.json

@theburi and I had a quick chat on what's still missing for 8.7.
For 8.8 will likely do another restructuring of the whole self-managed section but for now double link in 8.7 to the references as fake subpages of ref arch.
Also pulled in Openshift as distro of K8s on the single page to complete it.

docs: restructure navbar of ref arch & pull in Openshift to single k8s page

---

optimize/self-managed/optimize-deployment/migration-update/camunda-8/8.6-to-8.7.md
optimize_versioned_docs/version-3.15.0/self-managed/optimize-deployment/migration-update/camunda-8/8.6-to-8.7.md

There are no translation changes between Optimize 8.6 and Optimize 8.7, there is no need for a section about localization changes

docs: remove translation TODO, there are no translation differences for optimize

---

versioned_docs/version-8.6/self-managed/concepts/elasticsearch-without-cluster-privileges.md

* Several properties were missing or not documented to connect to the right ES, and specific SSL configs
* While we shouldn't document all possible configs here, we should at least have mentioned the necessary configs, that are likely to be changed (for better UX)
* Added additional note and links to the configuration documentation of each component, to highlight there are more options available (not only what is part of the example).

docs: add missing ES connection config

---

docs/apis-tools/tasklist-api-rest/tasklist-api-rest-authentication.md
versioned_docs/version-8.5/apis-tools/tasklist-api-rest/tasklist-api-rest-authentication.md
versioned_docs/version-8.6/apis-tools/tasklist-api-rest/tasklist-api-rest-authentication.md
versioned_docs/version-8.7/apis-tools/tasklist-api-rest/tasklist-api-rest-authentication.md

Follow up to https://github.com/camunda/camunda-docs/pull/5258 -- adding cookie auth to Tasklist REST API.

add cookie auth to tasklist rest api

---

docs/components/best-practices/development/routing-events-to-processes.md
versioned_docs/version-8.3/components/best-practices/development/routing-events-to-processes.md
versioned_docs/version-8.4/components/best-practices/development/routing-events-to-processes.md
versioned_docs/version-8.5/components/best-practices/development/routing-events-to-processes.md
versioned_docs/version-8.6/components/best-practices/development/routing-events-to-processes.md
versioned_docs/version-8.7/components/best-practices/development/routing-events-to-processes.md

C7 code is used in C8 examples on the "Routing events" page. Updating the examples to use C8 code. This was pointed out by a community member in the forums: https://forum.camunda.io/t/message-correlation-example-for-camunda-8-has-reference-of-camunda-7-code/60868
Of the choices below, I marked what I felt was the most appropriate one ... I'd say deploy when possible but don't have to drop everything for it :)

fix: update C7 code used in C8 examples

---

docs/components/modeler/web-modeler/idp/idp-configuration.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-configuration.md

Add a 'known limitations' section to IDP documentation.
Closes https://github.com/camunda/camunda-docs/issues/5329.

IDP known limitations

---

docs/reference/announcements-release-notes/870/870-announcements.md
docs/self-managed/connectors-deployment/connectors-configuration.md
docs/self-managed/operational-guides/update-guide/860-to-870.md
versioned_docs/version-8.7/reference/announcements-release-notes/870/870-announcements.md
versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md

I updated the SM connectors doc with more examples of YAML configuration. The 8.8 property names have been changed - e.g. from `CAMUNDA_CLIENT_ZEEBE_RESTADDRESS` to `CAMUNDA_CLIENT_RESTADDRESS` - this is intentional.
I also added an announcement and an entry in the update guide for 8.7 due to these potentially breaking changes.

chore: document changes in connectors properties in 8.7+

---

docs/apis-tools/migration-manuals/migrate-to-camunda-user-tasks.md
versioned_docs/version-8.7/apis-tools/migration-manuals/migrate-to-camunda-user-tasks.md

Relates to https://github.com/camunda/camunda/issues/29292. Adjusts incorrect wording for 8.7 and 8.8 intro of Camunda user tasks.
CC @tmetzke @marcosgvieira, though I don't think you need to additionally review here.

fix zeebe camunda user task wording

---

docs/components/modeler/bpmn/assets/bpmn-symbols/ad-hoc.svg
docs/components/modeler/bpmn/assets/bpmn-symbols/compensation.svg
docs/components/modeler/bpmn/assets/bpmn-symbols/lane.svg
docs/components/modeler/bpmn/assets/bpmn-symbols/multi-instance-parallel.svg
docs/components/modeler/bpmn/assets/bpmn-symbols/multi-instance-sequential.svg
docs/components/modeler/bpmn/assets/bpmn-symbols/pool.svg
versioned_docs/version-8.6/components/modeler/bpmn/assets/bpmn-symbols/compensation.svg
versioned_docs/version-8.6/components/modeler/bpmn/assets/bpmn-symbols/lane.svg
versioned_docs/version-8.6/components/modeler/bpmn/assets/bpmn-symbols/multi-instance-parallel.svg
versioned_docs/version-8.6/components/modeler/bpmn/assets/bpmn-symbols/multi-instance-sequential.svg
versioned_docs/version-8.6/components/modeler/bpmn/assets/bpmn-symbols/pool.svg
versioned_docs/version-8.7/components/modeler/bpmn/assets/bpmn-symbols/ad-hoc.svg
versioned_docs/version-8.7/components/modeler/bpmn/assets/bpmn-symbols/compensation.svg
versioned_docs/version-8.7/components/modeler/bpmn/assets/bpmn-symbols/lane.svg
versioned_docs/version-8.7/components/modeler/bpmn/assets/bpmn-symbols/multi-instance-parallel.svg
versioned_docs/version-8.7/components/modeler/bpmn/assets/bpmn-symbols/multi-instance-sequential.svg
versioned_docs/version-8.7/components/modeler/bpmn/assets/bpmn-symbols/pool.svg

On the BPMN coverage page, some BPMN symbols are not fully colored. This PR updates the SVGs for the symbols and adds color. :rainbow: 
---
---

fix: Color BPMN coverage symbols

---

docs/guides/host-custom-connector.md
docs/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.3/guides/host-custom-connector.md
versioned_docs/version-8.3/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.4/guides/host-custom-connector.md
versioned_docs/version-8.4/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.5/guides/host-custom-connector.md
versioned_docs/version-8.5/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.6/guides/host-custom-connector.md
versioned_docs/version-8.6/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.7/guides/host-custom-connector.md
versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md

Two small updates to connectors SM docs:
- renamed "operate secret" to "connectors secret" to avoid confusion
- replaced dashes with underscores in env var names
closes https://github.com/camunda/connectors/issues/4396
closes https://github.com/camunda/camunda-docs/issues/4618

fix: connector env var names 

---

docs/reference/announcements-release-notes/870/870-announcements.md
docs/reference/supported-environments.md
versioned_docs/version-8.7/reference/announcements-release-notes/870/870-announcements.md
versioned_docs/version-8.7/reference/supported-environments.md

As [discussed](https://github.com/camunda/camunda-docs/issues/3339#issuecomment-2761710882) in the stale issue, macOS 12 can be removed since it was EOL'd in Nov 2024. I also corrected the casing to reflect Apple's website. 
With that, we can close #3339.

Remove support for macOS 12

---

docs/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.6/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md

docs(self-managed): add a precision on a specific env variables

---

docs/components/modeler/web-modeler/idp/idp-configuration.md
docs/components/modeler/web-modeler/idp/idp-example.md
docs/components/modeler/web-modeler/idp/idp-integrate.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-configuration.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-example.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-integrate.md

This small PR adds a few extra pieces of information for IDP.

Small edits for IDP

---

optimize/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.14.0/self-managed/optimize-deployment/configuration/system-configuration.md
optimize_versioned_docs/version-3.15.0/self-managed/optimize-deployment/configuration/system-configuration.md
versioned_docs/version-8.3/self-managed/optimize-deployment/configuration/system-configuration.md
versioned_docs/version-8.4/self-managed/optimize-deployment/configuration/system-configuration.md
versioned_docs/version-8.5/self-managed/optimize-deployment/configuration/system-configuration.md

Taking the easy part of out https://github.com/camunda/camunda-docs/pull/5233, in lieue of having time to make the linked one mergeable

docs: add missing Optimize import configuration

---

static/.htaccess

Fix a bad URL rewrite rule in my previous PR. This a bug fix but does not need urgent release; just roll it into the next one.
https://camunda.slack.com/archives/C026U8GBNSW/p1743190180989909

fix(htaccess): fix incorrect rewrite rule

---

docs/self-managed/operational-guides/multi-region/dual-region-ops.md
versioned_docs/version-8.6/self-managed/operational-guides/multi-region/dual-region-ops.md
versioned_docs/version-8.7/self-managed/operational-guides/multi-region/dual-region-ops.md

Customer us confused about the changed replication factor in the example output.
This pull request should clarify the confusion.
See the Slack discussion here: https://camunda.slack.com/archives/C03UR0V2R2M/p1743428622347779
Whenever you have time to merge it. No other dependcies.

Clarify replication factor change for dual region failover

---

docs/self-managed/concepts/multi-region/dual-region.md
versioned_docs/version-8.6/self-managed/concepts/multi-region/dual-region.md
versioned_docs/version-8.7/self-managed/concepts/multi-region/dual-region.md

A customer set up a dual region cluster with numbering 0,1,2 in region 1 and 3,4,5 in region 2 and replication factor 4.
This leads to an uneven distribution.
More background is required to explain the way to reach an even and scalable dual region setup and convince the customer to change their configuration.
The additional paragraph gives the required background information.

Clarify the cluster installation internals for partition distribution

---

docs/components/best-practices/architecture/understanding-human-tasks-management.md
versioned_docs/version-8.6/components/best-practices/architecture/understanding-human-tasks-management.md
versioned_docs/version-8.7/components/best-practices/architecture/understanding-human-tasks-management.md

This PR moves the best practice from graphql to rest.
Starting with version 8.8, the best practice will make use of the new rest api.

moved from graphql to rest api in description

---

docs/components/modeler/web-modeler/idp/idp-applications.md
docs/components/modeler/web-modeler/idp/idp-configuration.md
docs/components/modeler/web-modeler/idp/idp-integrate.md
docs/components/modeler/web-modeler/idp/idp-reference.md
docs/components/modeler/web-modeler/idp/react-components/_idp-card-data.js
docs/components/modeler/web-modeler/intelligent-document-processing.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-applications.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-configuration.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-integrate.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/react-components/_idp-card-data.js
versioned_docs/version-8.7/components/modeler/web-modeler/intelligent-document-processing.md

Finalise the IDP Self-Managed configuration instructions.

IDP Self-Managed configuration

---

docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
docs/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eks-helm.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eksctl.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/terraform-setup.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
versioned_docs/version-8.5/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md

The following PR is just updating versions to their latest releases.
For newer versions, it will be less as we outsource it to our repo and use github code references instead.

chore: version bumps of external dependencies

---

docs/guides/getting-started-java-spring.md
versioned_docs/version-8.7/guides/getting-started-java-spring.md

Closes https://github.com/camunda/camunda-docs/issues/4925. Very small tweak to Spring guide.

small spring guide update

---

docs/self-managed/setup/deploy/local/docker-compose.md
versioned_docs/version-8.5/self-managed/setup/deploy/local/docker-compose.md
versioned_docs/version-8.6/self-managed/setup/deploy/local/docker-compose.md
versioned_docs/version-8.7/self-managed/setup/deploy/local/docker-compose.md

Downgrade the `danger` to a `note` style for docker compose. 
cc @conceptualshark

fix: change danger to note for docker compose

---

docs/self-managed/setup/deploy/local/c8run.md
versioned_docs/version-8.7/self-managed/setup/deploy/local/c8run.md

The Windows start command seems to be missing from 8.7 and 8.8 (although the Windows stop command is in the docs).

Add Windows start to Camunda 8 Run

---

docs/self-managed/concepts/document-handling/configuration.md
versioned_docs/version-8.7/self-managed/concepts/document-handling/configuration.md

I'm adding docker compose section and some limitations of using in-memory + local storage.

Adding docker compose and doc handling limitations

---

docs/self-managed/operational-guides/multi-region/dual-region-ops.md
versioned_docs/version-8.6/self-managed/operational-guides/multi-region/dual-region-ops.md
versioned_docs/version-8.7/self-managed/operational-guides/multi-region/dual-region-ops.md

The existing dual-region operational procedure guide claims to provide only generic commands regardless of which region had failed but at one point it uses a command as an example that is specific to one region's failure. While this is mentioned, for ease of use I have included example commands for both cases/

fix: add another command and some elaboration to ops procedure so it is more general

---

docs/self-managed/operational-guides/monitoring/metrics.md
versioned_docs/version-8.6/self-managed/operational-guides/monitoring/metrics.md
versioned_docs/version-8.7/self-managed/operational-guides/monitoring/metrics.md

This PR clarifies that metrics are in-memory only in Camunda 8, and must be aggregated externally to be used meaningfully.
closes #1375

Clarify that metrics are in-memory and must be aggregated externally

---

docs/components/modeler/desktop-modeler/index.md
docs/components/modeler/desktop-modeler/install-the-modeler.md
versioned_docs/version-8.3/components/modeler/desktop-modeler/index.md
versioned_docs/version-8.3/components/modeler/desktop-modeler/install-the-modeler.md
versioned_docs/version-8.4/components/modeler/desktop-modeler/index.md
versioned_docs/version-8.4/components/modeler/desktop-modeler/install-the-modeler.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/index.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/install-the-modeler.md
versioned_docs/version-8.6/components/modeler/desktop-modeler/index.md
versioned_docs/version-8.6/components/modeler/desktop-modeler/install-the-modeler.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/index.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/install-the-modeler.md

Add instructions for file association wiring of desktop modeler

---

docs/self-managed/concepts/access-control/resource-authorizations.md
versioned_docs/version-8.4/self-managed/concepts/access-control/resource-authorizations.md
versioned_docs/version-8.5/self-managed/concepts/access-control/resource-authorizations.md
versioned_docs/version-8.6/self-managed/concepts/access-control/resource-authorizations.md
versioned_docs/version-8.7/self-managed/concepts/access-control/resource-authorizations.md

Corrects deep-links to point to respective tab (otherwise hard to find)

fix(identity): correct deeplinks to respective tabs

---

docs/guides/use-shared-project-for-organization-wide-collaboration.md
versioned_docs/version-8.6/components/modeler/web-modeler/git-sync.md
versioned_docs/version-8.7/guides/use-shared-project-for-organization-wide-collaboration.md

Provides improvements to the e2e org process landscape guide based on [feedback](https://github.com/camunda/product-hub/issues/2611#issuecomment-2761525582).

update shared project guide

---

docs/self-managed/operational-guides/troubleshooting/troubleshooting.md
docs/self-managed/setup/guides/ingress-setup.md
versioned_docs/version-8.7/self-managed/operational-guides/troubleshooting/troubleshooting.md
versioned_docs/version-8.7/self-managed/setup/deploy/local/local-kubernetes-cluster.md
versioned_docs/version-8.7/self-managed/setup/guides/ingress-setup.md
versioned_docs/version-8.7/self-managed/setup/install.md

Closes #5116 
In preparation for the original 8.7 release, the separated ingress guide was removed: https://github.com/camunda/camunda-docs/pull/4508
Based on this [Slack discussion](https://camunda.slack.com/archives/C03UR0V2R2M/p1740674890099049), this removal has been delayed to 8.8. This PR reverts the above and adds the separated Ingress information back into only 8.7.

Revert ingress changes

---

docs/components/concepts/processes.md
versioned_docs/version-8.6/components/concepts/processes.md
versioned_docs/version-8.7/components/concepts/processes.md

Closes https://github.com/camunda/camunda-docs/issues/4831 -- revamps processes concepts page.

improve processes documentation

---

docs/reference/announcements-release-notes/870/870-release-notes.md
versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md

* Draft PR, mschoe will take over

docs: document known issues for 8.7 release

---

docs/guides/react-components/_install-c8run.md
versioned_docs/version-8.6/guides/react-components/_install-c8run.md
versioned_docs/version-8.7/guides/react-components/_install-c8run.md

This uses the code added in https://github.com/camunda/camunda-docs/pull/5220 to make the C8Run link dynamic in the reused components in the Guides.

Update the C8Run components to use the dynamic link

---

docs/self-managed/setup/deploy/amazon/openshift/terraform-setup-dual-region.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/dual-region.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eksctl.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/irsa.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/openshift/terraform-setup-dual-region.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/openshift/terraform-setup.md
versioned_docs/version-8.7/self-managed/setup/deploy/openshift/redhat-openshift.md

related to https://github.com/camunda/team-infrastructure-experience/issues/614.
Checked with lychee for dead links and adjusted some links, that were too quickly merged, to their related branch.
```
lychee --include-verbatim
```
@leiicamundi those will need to be adjusted after the related PR on the deployment-ref has been merged, can easily be found via `feature/migrate-dual-region-rosa` and need to be adjusted to `main` and `stable/8.7` depending on their version.
The following PR adjusts branch reference for `versioned-8.7` to `stable/8.7` on our side.
Some items in `docs` were also adjusted where it made sense as some were and still are pinned to a feature branch due to active work on it. The docs PR was merged a slight bit too early.

Infraex 8.7 docs adjustments v2/99

---

docs/guides/document-handling.md
versioned_docs/version-8.7/guides/document-handling.md

Fixes feedback reported [here](https://github.com/camunda/camunda-docs/pull/5382#discussion_r2031773669)

Fix links on document-handling guide

---

docs/guides/migrating-from-camunda-7/technical-details.md

task listeners are supported with 8.8

---

docs/self-managed/setup/deploy/amazon/openshift/terraform-setup-dual-region.md
docs/self-managed/setup/deploy/openshift/dual-region.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/openshift/terraform-setup-dual-region.md
versioned_docs/version-8.7/self-managed/setup/deploy/openshift/dual-region.md

Hopefully the last update from our side for the 8.7 docs to update the remaining links of a former feature branch to stable branches.
This does not change any content, just link updates.
Checked with `lychee --include-verbatim` that those are working.

docs: last adjustments removing a feature branch

---

docs/reference/announcements-release-notes/870/870-release-notes.md
versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md

This PR is a first iteration to improve the Known Bugs section in the 8.7.0 release notes.
- Work-around changed to workaround
- Changed from list > table
- Title used instead of GitHub link
Note: Perhaps further work required on the ordering of the items and even grouping by component? Also, link to relevant bug/issue policy?

Known bugs format

---

docs/components/modeler/desktop-modeler/process-applications.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/process-applications.md

* two small adjustments based on feedback
* rename decision tables to decisions
* move .process-application file in example

fix: adjust desktop modeler process application docs

---

docs/components/modeler/web-modeler/idp/idp-reference.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md

Fix a small (but important) typo in the IDP model region docs.

Fix IDP region typo

---

versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.5/reference/supported-environments.md
versioned_docs/version-8.6/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.6/reference/supported-environments.md
versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/getting-started.md
versioned_docs/version-8.7/reference/supported-environments.md

relates to https://github.com/camunda/camunda/issues/28554 and https://github.com/camunda/camunda/issues/28698
Springboot version was bumped in the mono-repo from 3.3 to 3.4 for 8.5. 8.6 versions
Thus, Camunda Spring SDK will be bundled with springboot 3.4.X starting from 8.5.18 and 8.6.14 patch versions (May patch releases, unless if there is another special patch release created beforehand)

docs: update bundled springboot version for 8.5 and 8.6 spring SDK

---

docs/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.3/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.4/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.5/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.6/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md

fix: Add debug logging config to the Connectors doc

---

docusaurus.config.js

Renames the "Release cycle" link in the footer to "Release policy".

Change footer link to Release policy

---

docs/reference/announcements-release-notes/overview.md
versioned_docs/version-8.6/reference/announcements-release-notes/overview.md
versioned_docs/version-8.7/reference/announcements-release-notes/overview.md

Optimize 3.7 was (is?) only supported for very specific customers (<5), so we can remove this for the majority of folks.

Remove Optimize 3.7 admonition

---

versioned_docs/version-8.3/reference/supported-environments.md
versioned_docs/version-8.4/reference/supported-environments.md
versioned_docs/version-8.5/reference/supported-environments.md
versioned_docs/version-8.6/reference/supported-environments.md

Closes https://github.com/camunda/camunda-docs/issues/5413

macOS not Mac OS

---

docs/reference/announcements-release-notes/870/870-release-notes.md
versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md

Adding follow up release note for Self-Managed issue.

add self managed release note

---

docs/self-managed/optimize-deployment/configuration/logging.md

docs: optimize logging system

---

docs/reference/supported-environments.md
versioned_docs/version-8.3/reference/supported-environments.md
versioned_docs/version-8.4/reference/supported-environments.md
versioned_docs/version-8.5/reference/supported-environments.md
versioned_docs/version-8.6/reference/supported-environments.md
versioned_docs/version-8.7/reference/supported-environments.md

This PR defines our basic support policy for the Camunda Orchestration Cluster, and the specific way we handle Spring's shorter EOL cycle.
I wasn't sure where this should go since we don't really mention anything about this anywhere, _and_ we don't have anything about our own support policy. Please suggest otherwise.
Additionally, it would have been good to add some timeline visualization to show the difference between our support policy and Spring's, but I am terrible at this, so if you have some idea, go for it.

Define dependency maintenance policy (incl. Spring)

---

versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/gateway.md
versioned_docs/version-8.7/self-managed/operational-guides/configure-flow-control/configure-flow-control.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/configuration.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/gateway.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/operations/backpressure.md

Based on https://docs.google.com/spreadsheets/d/1q2F308phdRotistKaCW1qa1NmL96BRLn9ttarWDfOto/edit?usp=sharing, updates versioned links for 8.7.

update versioned links for 8.7

---

docs/components/console/manage-clusters/cluster-backups.md
docs/components/console/manage-clusters/manage-ip-allowlists.md
docs/self-managed/zeebe-deployment/security/client-authorization.md
versioned_docs/version-8.3/components/console/manage-clusters/manage-ip-allowlists.md
versioned_docs/version-8.4/components/console/manage-clusters/cluster-backups.md
versioned_docs/version-8.4/components/console/manage-clusters/manage-ip-allowlists.md
versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.5/components/console/manage-clusters/cluster-backups.md
versioned_docs/version-8.5/components/console/manage-clusters/manage-ip-allowlists.md
versioned_docs/version-8.6/components/console/manage-clusters/cluster-backups.md
versioned_docs/version-8.6/components/console/manage-clusters/manage-ip-allowlists.md
versioned_docs/version-8.7/components/console/manage-clusters/cluster-backups.md
versioned_docs/version-8.7/components/console/manage-clusters/manage-ip-allowlists.md
versioned_docs/version-8.7/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/security/client-authorization.md

April docs housekeeping. 
The largest change is that https://camunda.com/enterprise/ now redirects to https://camunda.com/platform-7/editions/, which I am not sure is what we want to do? I will [follow up with web marketing](https://camunda.slack.com/archives/C034F8NA1G8/p1744385420259599). I have subbed in https://camunda.com/pricing/ which lists out the different editions for SaaS and SM.

docs housekeeping april

---

versioned_docs/version-8.6/reference/supported-environments.md
versioned_docs/version-8.6/self-managed/optimize-deployment/configuration/shared-elasticsearch-cluster.md
versioned_docs/version-8.6/self-managed/optimize-deployment/configuration/system-configuration.md
versioned_docs/version-8.6/self-managed/setup/guides/using-existing-opensearch.md
versioned_docs/version-8.7/reference/supported-environments.md
versioned_docs/version-8.7/self-managed/optimize-deployment/configuration/system-configuration.md
versioned_docs/version-8.7/self-managed/setup/guides/using-existing-opensearch.md

Backups support was added later, so we should remove this clarification.

fix: remove warning about non-supported backups for 8.7

---

docs/apis-tools/zeebe-api/gateway-service.md
versioned_docs/version-8.4/apis-tools/zeebe-api/gateway-service.md
versioned_docs/version-8.5/apis-tools/zeebe-api/gateway-service.md
versioned_docs/version-8.6/apis-tools/zeebe-api/gateway-service.md
versioned_docs/version-8.7/apis-tools/zeebe-api/gateway-service.md

This PR documents the default gRPC service config, which is also loaded by the Camunda Java SDK.
It documents its purpose, but does not show the file (as it may be changed), and only links to it.
closes #2939

docs: document default gRPC service config

---

docs/reference/announcements-release-notes/870/870-announcements.md
versioned_docs/version-8.7/reference/announcements-release-notes/870/870-announcements.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/860-to-870.md

Based on https://camunda.slack.com/archives/C026U8GBNSW/p1742310500475559 -- 8.7 and lower versions should only reference the Spring Zeebe SDK -- Camunda Spring Boot SDK will be adjusted with https://github.com/camunda/camunda-docs/pull/5349.

adjust 8.7 spring zeebe references

---

docs/components/rpa/getting-started.md
docs/components/rpa/overview.md
docs/reference/announcements-release-notes/870/870-release-notes.md
versioned_docs/version-8.7/components/rpa/getting-started.md
versioned_docs/version-8.7/components/rpa/overview.md
versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md

Relates to https://camunda.slack.com/archives/C07DA2WBMAL/p1744112325074499.

add known issue link to rpa docs

---

docs/components/modeler/web-modeler/git-sync.md
versioned_docs/version-8.7/components/modeler/web-modeler/git-sync.md

docs(git-sync): add Markdown file clarification

---

static/.htaccess

Based on https://github.com/camunda/camunda-docs/pull/5312#discussion_r2041590675 -- /next/ redirect for 8.8.

add next redirects for c7 only modeler content

---

docs/self-managed/operational-guides/update-guide/introduction.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/introduction.md

Closes https://github.com/camunda/camunda-docs/issues/5548.

add release blog to update guides

---

.github/workflows/check-versions/version-config.json

The nudge wasn't updated for the 8.7 minor yet, so I _think_ this takes care of it, and brings us back to one current and one next version 🎉 
Changes to **docs infra**, including updates to workflows and adding new npm packages, must be first discussed via issue or #ask-c8-documentation and linked for context.

Update version suggestion for 8.7/8.8

---

docs/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md

This PR changes code snippets that refer to the `/actuator` API of Tasklist as with 8.6, the port is 9600.

fix: tasklist actuator port is 9600

---

docs/components/console/manage-clusters/manage-connectors.md
docs/components/modeler/web-modeler/idp/idp-example.md
docs/components/modeler/web-modeler/idp/idp-integrate.md
docs/components/modeler/web-modeler/idp/idp-key-concepts.md
docs/components/modeler/web-modeler/idp/idp-reference.md
docs/components/modeler/web-modeler/intelligent-document-processing.md
docs/reference/regions.md
src/css/custom.css
versioned_docs/version-8.3/reference/regions.md
versioned_docs/version-8.4/reference/regions.md
versioned_docs/version-8.5/reference/regions.md
versioned_docs/version-8.6/reference/regions.md
versioned_docs/version-8.7/components/console/manage-clusters/manage-connectors.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-example.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-integrate.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-key-concepts.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-reference.md
versioned_docs/version-8.7/components/modeler/web-modeler/intelligent-document-processing.md
versioned_docs/version-8.7/reference/regions.md

Fixes some image issues introduced by Docusaurus 3 (image margin) and also introduces some image classes to control width and border, as follows:
**Width: img-[600,700,800,900]**
Set image width. For example, if you need an image in the docs to be 600px wide, apply the "img-600" class, rather than using inline styling.
**Border: img-noborder**
Remove the border and associated padding from an image.
**Transparency: img-transparent**
Make the background of an image transparent.
Additionally, this PR removes the inline styling added to recent topics that ahd temporary inline styling applied until these fixes could be added, sucha s the IDP documentation.

CSS enhancements

---

docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
docs/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md
versioned_docs/version-8.6/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/terraform-setup.md

We're utilizing the scripts to be tested regularly and during development. So we can ensure the docs are passing.
Therefore they're moved to an external repository, also allows us to keep versions up2date by utilizing Renovate.
Not every little code execution was exported since we have to trust to some degree that upstream tools work the same way, they always do (mostly k8s related).
It's also a balance between what makes sense to export and not, otherwise we end up with a lot of little code snippets.
Final review, as always from the reviewer side after internal review has passed.
before merge:

[AWS EKS][>8.7] Outsource additional scripts to reference repo

---

docs/self-managed/optimize-deployment/migration-update/camunda-8/instructions.md
versioned_docs/version-8.6/self-managed/optimize-deployment/migration-update/camunda-8/instructions.md
versioned_docs/version-8.7/self-managed/optimize-deployment/migration-update/camunda-8/instructions.md

Closes https://github.com/camunda/camunda-docs/issues/5588

docs: clarify update instructions for optimize

---

docs/apis-tools/spring-zeebe-sdk/configuration.md
versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/configuration.md

This PR adds documentation about the Spring SDK modes as there were some issues around how they work.

document spring sdk modes

---

docs/self-managed/zeebe-deployment/operations/cluster-scaling.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/operations/cluster-scaling.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/operations/cluster-scaling.md

Found a bit of time after all to fix this.
It was still showing zbctl usage and output.
- Fix wrong port
- Fix wrong output schema
- wrapped the output in a `details` block

fix: zeebe cluster-scale documentation still based on zbctl

---

docs/apis-tools/operate-api/overview.md
versioned_docs/version-8.3/apis-tools/operate-api/overview.md
versioned_docs/version-8.4/apis-tools/operate-api/overview.md
versioned_docs/version-8.5/apis-tools/operate-api/overview.md
versioned_docs/version-8.6/apis-tools/operate-api/overview.md
versioned_docs/version-8.7/apis-tools/operate-api/overview.md

* document Swagger UI limitation for Operate API v.1
* mention that Camunda API v.2 won't have this limitation
Fixes https://github.com/camunda/camunda/issues/29928

fix: document Swagger UI limitation for Operate API v.1

---

versioned_docs/version-8.7/self-managed/setup/upgrade.md

Relates to https://camunda.slack.com/archives/C03UR0V2R2M/p1744721330804649.

add note for 8.7 helm update

---

docs/reference/glossary.md
versioned_docs/version-8.4/reference/glossary.md
versioned_docs/version-8.5/reference/glossary.md
versioned_docs/version-8.6/reference/glossary.md
versioned_docs/version-8.7/reference/glossary.md

Adds glossary entries for `flow node` and `element` for better distinction.
closes #5568

Add glossary for element and flow node

---

docs/self-managed/setup/deploy/local/docker-compose.md
docs/self-managed/setup/guides/air-gapped-installation.md
versioned_docs/version-8.3/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/guides/air-gapped-installation.md
versioned_docs/version-8.5/self-managed/setup/deploy/local/docker-compose.md
versioned_docs/version-8.5/self-managed/setup/guides/air-gapped-installation.md
versioned_docs/version-8.6/self-managed/setup/deploy/local/docker-compose.md
versioned_docs/version-8.6/self-managed/setup/guides/air-gapped-installation.md
versioned_docs/version-8.7/self-managed/setup/deploy/local/docker-compose.md
versioned_docs/version-8.7/self-managed/setup/guides/air-gapped-installation.md

In https://github.com/camunda/camunda-distributions/issues/110 we removed Kibana from Docker Compose as it's not a necessary part to run the Camunda stack. So I removed it from the docs too.

docs(self-managed): remove kibana section from docker compose

---

docs/self-managed/modeler/web-modeler/configuration/configuration.md
docs/self-managed/modeler/web-modeler/configuration/logging.md
docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
docs/self-managed/operational-guides/monitoring/log-levels.md
docs/self-managed/operational-guides/monitoring/metrics.md
docs/self-managed/setup/deploy/amazon/aws-ec2.md
versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/configuration.md
versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/logging.md
versioned_docs/version-8.6/self-managed/operational-guides/monitoring/log-levels.md
versioned_docs/version-8.6/self-managed/operational-guides/monitoring/metrics.md
versioned_docs/version-8.7/self-managed/modeler/web-modeler/configuration/configuration.md
versioned_docs/version-8.7/self-managed/modeler/web-modeler/configuration/logging.md
versioned_docs/version-8.7/self-managed/operational-guides/monitoring/log-levels.md
versioned_docs/version-8.7/self-managed/operational-guides/monitoring/metrics.md

This is a retro TW review of the content in https://github.com/camunda/camunda-docs/pull/5214. 
A large number of content edits are included, such as:
- Rewording and grammar
- Formatting changes (lists to tables for example)
- Readability and conciseness
This closes https://github.com/camunda/camunda-docs/issues/5245.

Micrometer metrics

---

docs/reference/announcements-release-notes/880/880-announcements.md
docs/self-managed/operational-guides/update-guide/870-to-880.md

closes #5321
In 8.7 -> 8.8 migration document that several Elasicsearch/Opensearch instances must be merged to one.

docs(exporter): migration to single Elastic instance

---

docs/reference/announcements-release-notes/860/860-release-notes.md
versioned_docs/version-8.6/reference/announcements-release-notes/860/860-release-notes.md
versioned_docs/version-8.7/reference/announcements-release-notes/860/860-release-notes.md

Rephrase the release note on TLS-encrypted communication between the Web Modeler components (the current version is a bit imprecise).
See also this [Slack thread](https://camunda.slack.com/archives/C0693F1NFK5/p1744720538505639?thread_ts=1744719796.828279&cid=C0693F1NFK5).

docs: rephrase release note on encrypted communication between Web Modeler components

---

docs/self-managed/operational-guides/update-guide/870-to-880.md
docs/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
docs/self-managed/zeebe-deployment/exporters/opensearch-exporter.md

Document the new introduced `includeEnabledRecords` property for Zeebe Elasticsearch & Opensearch exporter, that enables the exporting into old `zeebe-record` indices for Camunda 8.8 and onwards. By default this property is false.

docs: includeEnabledRecords property documentation

---

src/css/custom.css

Quick PR to add some styling to the mini-TOC on pages to indicate where you are on a page:

CSS for mini-TOC

---

static/.htaccess

While investigating #5566, I noticed these two rules in the htaccess, which shouldn't be necessary anymore.

cleanup: remove unnecessary optimize redirects in htaccess

---

docs/apis-tools/migration-manuals/migrate-to-camunda-api.md

feat: Add migration guide for decision definition endpoints

---

docs/components/connectors/out-of-the-box-connectors/google-gemini.md
versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/google-gemini.md

Based on https://camunda.slack.com/archives/C02JLRNQQ05/p1745239202161689.

update gemini connectors link

---

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/element-templates/defining-templates.md

This PR adds missing line break:

fix: add missing line break

---

docs/self-managed/setup/upgrade.md
versioned_docs/version-8.7/self-managed/setup/upgrade.md

Making the information of no changes needed in the HC to upgrade from 8.6 to 8.7 explicit, as it was reported 2 times already
* see [here](https://camunda.slack.com/archives/C03UR0V2R2M/p1744721330804649)
* and [here](https://camunda.slack.com/archives/C03UR0V2R2M/p1745521636396889) 
closes https://github.com/camunda/team-distribution/issues/494
- x ] My changes are for **an upcoming minor release** and are in the `/docs` directory (version 8.8).

add update tab for 8.7 to make clear no changes needed

---

docs/apis-tools/migration-manuals/migrate-to-camunda-api.md

feat: Migration guide for decision instance endpoints

---

package-lock.json
package.json

Replaces #5185.
Playwright requires multiple deps updated at the same time.
Successful update confirmed locally by running `npm run test:regression`:
```sh
camunda-docs on  main [$!] via  v22.11.0 took 14s 
❯ npm run test:regression
> camunda-cloud-documentation@0.0.0 test:regression
> playwright test spec/
Running 1 test using 1 worker
✓  1 spec/regression/smoke.spec.ts:3:5 › homepage has title and links to intro page (2.5s)
1 passed (3.9s)
```

chore: update playwright deps to 1.52.0

---

package-lock.json
package.json

Bumps mixpanel-browser to 2.64.0.
This dependency can only be tested in production, by confirming that a mixpanel event is sent from [the footer](https://github.com/camunda/camunda-docs/blob/main/src/theme/Footer/index.js#L81).

chore: bump mixpanel-browser to 2.64.0

---

package-lock.json
package.json

Confirmed locally by interacting with a form on /docs/next/apis-tools/frontend-development/forms/embed-forms/form-js-concepts.

chore: bump form-js to 1.15.1

---

package-lock.json
package.json

Bumps the pushfeedback-react dependency to 0.1.63.
Confirmed locally by submitting a pushfeedback response successfully.

chore: bump pushfeedback-react to 0.1.63

---

docs/reference/data-collection/usage-metrics.md
docs/self-managed/console-deployment/usage-metrics.md
sidebars.js
versioned_docs/version-8.5/self-managed/console-deployment/usage-metrics.md
versioned_docs/version-8.6/reference/data-collection/usage-metrics.md
versioned_docs/version-8.6/self-managed/console-deployment/usage-metrics.md
versioned_docs/version-8.7/reference/data-collection/usage-metrics.md
versioned_docs/version-8.7/self-managed/console-deployment/usage-metrics.md
versioned_sidebars/version-8.5-sidebars.json
versioned_sidebars/version-8.6-sidebars.json
versioned_sidebars/version-8.7-sidebars.json

feat(console): add section about usage metrics

---

docs/apis-tools/spring-zeebe-sdk/configuration.md

This PR documents the Spring SDKs latest feature which has been added here: https://github.com/camunda/camunda/pull/31356

feat: jobError in spring sdk

---

docs/self-managed/operational-guides/update-guide/introduction.md
docs/self-managed/zeebe-deployment/operations/update-zeebe.md
versioned_docs/version-8.4/self-managed/operational-guides/update-guide/introduction.md
versioned_docs/version-8.5/self-managed/operational-guides/update-guide/introduction.md
versioned_docs/version-8.5/self-managed/zeebe-deployment/operations/update-zeebe.md
versioned_docs/version-8.6/self-managed/operational-guides/update-guide/introduction.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/operations/update-zeebe.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/introduction.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/operations/update-zeebe.md

* This is a follow-up action from Post-Mortem #inc-2602 - see https://docs.google.com/document/d/120qb7PVdg4shMJWwH6zSF27EwarrKGO4weACNBMbp3s/edit?tab=t.0
* With this change, we aim to further increase quality 
* With this change, we harmonize update process in SM and SaaS
* Simplify docs by removing the redundant update instruction from Zeebe docs section

docs(update-guide): make update guidance more strict

---

howtos/moving-content.md

A follow-up to https://github.com/camunda/camunda-docs/pull/5628#discussion_r2063992140.

docs: add guidance for frequent redirect patterns

---

.github/workflows/sync-rest-api-docs.yaml

Removes me from reviewers of C8 REST API spec sync PRs.

chore: Remove myself from api spec sync PRs

---

docusaurus.config.js

https://camunda.slack.com/archives/C026U8GBNSW/p1746049044937659.
Technically Kapa could be used as a workaround, but let's get this fixed ASAP.

Update Algolia Key

---

docs/apis-tools/migration-manuals/migrate-to-camunda-api.md

closes https://github.com/camunda/camunda/issues/23745

feat: Add migration guide for decision requirements endpoints

---

docs/self-managed/console-deployment/configuration/ssl.md
versioned_docs/version-8.7/self-managed/console-deployment/configuration/ssl.md

related support ticket: https://jira.camunda.com/browse/SUPPORT-27000
The docs do not have the currently supported way of assigning console a self-signed cert.

fix: tls console

---

versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/blueprism.md

This simple change fixes dead links for documentation of the Blue Prism API Endpoints (404 pages) in the Blue Prism Connector Docs page.

fix: update broken links in blue prism connector page

---

docs/components/modeler/web-modeler/play-your-process.md
docs/guides/host-custom-connector.md
versioned_docs/version-8.4/guides/host-custom-connector.md
versioned_docs/version-8.5/guides/host-custom-connector.md
versioned_docs/version-8.6/components/modeler/web-modeler/play-your-process.md
versioned_docs/version-8.6/guides/host-custom-connector.md
versioned_docs/version-8.7/components/modeler/web-modeler/play-your-process.md
versioned_docs/version-8.7/guides/host-custom-connector.md

There are a couple of Camunda Self-Managed repos URLs that are not correct, so I'm updating them.

fix: update camunda self-managed repos urls

---

docs/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.4/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.6/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/troubleshooting.md

Closes https://github.com/camunda/camunda-modeler/issues/4899
Adds `NO_PROXY` configuration documentation based on a recent[ support case](https://jira.camunda.com/browse/SUPPORT-26057).

feat: mention no proxy config in troubleshooting guide

---

docs/components/connectors/out-of-the-box-connectors/blueprism.md

Ports https://github.com/camunda/camunda-docs/pull/5579 to 8.8.
Does not include a strategy for updating Blueprism docs to the next version or backport.

Port #5579 to 8.8 - Connector Blueprism docs

---

docs/guides/configuring-out-of-the-box-connector.md
docs/guides/devops-lifecycle/integrate-web-modeler-in-ci-cd.md
docs/guides/document-handling.md
docs/guides/getting-started-orchestrate-apis.md
docs/guides/host-custom-connector.md
docs/guides/introduction-to-camunda-8.md
docs/guides/migrating-from-camunda-7/conceptual-differences.md
docs/guides/migrating-from-camunda-7/migration-journey.md
docs/guides/migrating-from-camunda-7/technical-details.md
docs/guides/use-connectors-in-hybrid-mode.md
versioned_docs/version-8.7/guides/configuring-out-of-the-box-connector.md
versioned_docs/version-8.7/guides/document-handling.md
versioned_docs/version-8.7/guides/getting-started-orchestrate-apis.md
versioned_docs/version-8.7/guides/host-custom-connector.md
versioned_docs/version-8.7/guides/introduction-to-camunda-8.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/conceptual-differences.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-journey.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/technical-details.md
versioned_docs/version-8.7/guides/use-connectors-in-hybrid-mode.md

This PR is part of tackling the monumental task of changing Connector > connector casing throughout the docs.
See https://github.com/camunda/documentation-team/issues/429.
For example, Email Connector > Email connector.
Due to the size of this change, this PR only focuses on:
- The Guides section itself.
- 8.7 and 8.8 docs.

Connector casing (wave 3 - guides)

---

docs/apis-tools/testing/connectors.md
docs/apis-tools/testing/getting-started.md
versioned_docs/version-8.7/apis-tools/testing/connectors.md
versioned_docs/version-8.7/apis-tools/testing/getting-started.md

This PR is part of tackling the monumental task of changing Connector > connector casing throughout the docs.
See https://github.com/camunda/documentation-team/issues/429.
For example, Email Connector > Email connector.
Due to the size of this change, this PR only focuses on:
- The API section itself.
- 8.7 and 8.8 docs.

Connector casing (wave 6 - API)

---

docs/apis-tools/migration-manuals/migrate-to-camunda-user-tasks.md
versioned_docs/version-8.7/apis-tools/migration-manuals/migrate-to-camunda-user-tasks.md

docs: correct tasklist API deprecation note

---

docusaurus.config.js

Partially addresses https://github.com/camunda/camunda-docs/issues/5688, does not adjust URLs or directories, only labels and order.

Adjust top nav for 8.8

---

docs/reference/data-collection/usage-metrics.md
docs/self-managed/console-deployment/usage-metrics.md
versioned_docs/version-8.5/self-managed/console-deployment/usage-metrics.md
versioned_docs/version-8.6/reference/data-collection/usage-metrics.md
versioned_docs/version-8.6/self-managed/console-deployment/usage-metrics.md
versioned_docs/version-8.7/reference/data-collection/usage-metrics.md
versioned_docs/version-8.7/self-managed/console-deployment/usage-metrics.md

Retro review of Console usage metrics documentation. https://github.com/camunda/camunda-docs/pull/5663

retro review of console usage metrics

---

docs/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md

Closes https://github.com/camunda/camunda-docs/issues/4866

Add Helm guide link to Connectors config

---

docs/components/modeler/bpmn/ad-hoc-subprocesses/ad-hoc-subprocesses.md
docs/components/modeler/bpmn/subprocesses.md
docs/reference/announcements-release-notes/870/870-release-notes.md
media-pre-src/docs/components/modeler/bpmn/ad-hoc/ad-hoc-subprocess-activate.bpmn
media-pre-src/docs/components/modeler/bpmn/ad-hoc/ad-hoc-subprocess-demo.bpmn
versioned_docs/version-8.7/components/modeler/bpmn/ad-hoc-subprocesses/ad-hoc-subprocesses.md
versioned_docs/version-8.7/components/modeler/bpmn/subprocesses.md
versioned_docs/version-8.7/reference/announcements-release-notes/870/870-release-notes.md

This PR updates **ad-hoc subprocess** references to **ad-hoc sub-process**, as per https://github.com/camunda/documentation-team/issues/461.
Note that the following are not included:
- References to ad-hoc subprocess in the API reference documentation (follow-up with Engineering for this).
- 8.8 release notes occurrences (this will be tackled in the [open PR](https://github.com/camunda/camunda-docs/pull/5638) for this page).
Note that also no redirects are needed as a result of the page title being changed - it is probably better to leave the file name unchanged for https://docs.camunda.io/docs/components/modeler/bpmn/ad-hoc-subprocesses/.

Update ad-hoc subprocess to ad-hoc sub-process

---

src/pages/index.js

Updates the main landing page to reflect the changes in the top nav structure.
Components > Using Camunda
Closes https://github.com/camunda/camunda-docs/issues/5689.

Landing page restructuring update

---

docs/apis-tools/migration-manuals/migrate-to-camunda-api.md

Closes https://github.com/camunda/camunda/issues/23748

feat: Migration guide for variable endpoints

---

versioned_docs/version-8.5/self-managed/setup/guides/using-existing-postgres.md
versioned_docs/version-8.6/self-managed/setup/guides/using-existing-postgres.md
versioned_docs/version-8.7/self-managed/setup/guides/using-existing-postgres.md
versioned_sidebars/version-8.5-sidebars.json
versioned_sidebars/version-8.6-sidebars.json
versioned_sidebars/version-8.7-sidebars.json

closes: https://github.com/camunda/camunda-platform-helm/issues/3323?reload=1
I created a guide for connecting to an external PostgreSQL instance using the camunda Helm chart.

guide for external postgresql on self-managed Helm chart

---

docs/guides/migrating-from-camunda-7/code-conversion.md
docs/guides/migrating-from-camunda-7/migration-tooling.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/code-conversion.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-tooling.md

- as soon as possible (before CamundaCon)
-

Added link to API Mapping Guide

---

docs/components/zeebe/technical-concepts/internal-processing.md
versioned_docs/version-8.4/components/zeebe/technical-concepts/internal-processing.md
versioned_docs/version-8.5/components/zeebe/technical-concepts/internal-processing.md
versioned_docs/version-8.6/components/zeebe/technical-concepts/internal-processing.md
versioned_docs/version-8.7/components/zeebe/technical-concepts/internal-processing.md

This documents the banned process instance concept, a technical safeguard against incorrect process execution and preventing a single error from blocking the execution of other process instances.
While this feature is not fully supported across the Camunda 8 suite (e.g. not displayed in Operate/Optimize, not available in the Orchestration Cluster REST API), it is crucial that we document it, because:
- we expect that it happens
- we use in our communication (e.g. support cases)
- it is part of the Zeebe Grafana dashboard, that customers/users use for monitoring
- and it is confusing to users, support and engineers if they cannot find any docs around this behavior
I chose to place this description under the technical-concepts of Zeebe in the internal processing section because it's very …

Describe banned process instance concept

---

docs/guides/migrating-from-camunda-7/migration-tooling.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-tooling.md

- Ideally ASAP before CamundaCon
-

Added link to now public repo around data migrator

---

docs/apis-tools/working-with-apis-tools.md
docs/components/components-overview.md
docs/guides/introduction-to-camunda-8.md
docs/reference/overview.md
docusaurus.config.js
versioned_docs/version-8.4/apis-tools/working-with-apis-tools.md
versioned_docs/version-8.4/components/components-overview.md
versioned_docs/version-8.4/guides/introduction-to-camunda-8.md
versioned_docs/version-8.4/reference/overview.md
versioned_docs/version-8.5/apis-tools/working-with-apis-tools.md
versioned_docs/version-8.5/components/components-overview.md
versioned_docs/version-8.5/guides/introduction-to-camunda-8.md
versioned_docs/version-8.5/reference/overview.md
versioned_docs/version-8.6/apis-tools/working-with-apis-tools.md
versioned_docs/version-8.6/components/components-overview.md
versioned_docs/version-8.6/guides/introduction-to-camunda-8.md
versioned_docs/version-8.6/reference/overview.md
versioned_docs/version-8.7/apis-tools/working-with-apis-tools.md
versioned_docs/version-8.7/components/components-overview.md
versioned_docs/version-8.7/guides/introduction-to-camunda-8.md
versioned_docs/version-8.7/reference/overview.md

This PR is in response to the changes made to the top nav, specifically:
Change the title/sidebar title for each of the main landing pages to match/align with the top nav headings:
- Introduction to Camunda 8 > Get started with Camunda 8
- Introduction to Components > Using Camunda 8
- Working with APIs & tools > APIs & tools
- Overview > Reference
Change the casing for the top nav menu to Apis & **t**ools (instead of **T**ools) - not sure how we missed this, but I think this needs doing.
@akeller @christinaausley I know this wasn't in the scope of the wave 1 work, but I felt it was worth a quick PR to tidy this gap up - wdyt? Do you agree with the new titles? I've only made the changes for 8.8 until we're happy, but will backport once we've settled on the changes.

Update landing pages and menu

---

docs/components/concepts/document-handling.md
docs/self-managed/concepts/document-handling/configuration.md
versioned_docs/version-8.7/components/concepts/document-handling.md
versioned_docs/version-8.7/self-managed/concepts/document-handling/configuration.md

Clarify how the 10MB limit applies.
It was not clear what was meant with one or multiple files.

Update configuration.md to help clarify how the 10MB limit works

---

docs/self-managed/identity/deployment/configuration-variables.md

This PR adds the Identity SDK configuration to the 8.8 docs.
closes #5616

Forward Identity SDK properties to 8.8

---

docs/guides/migrating-from-camunda-7/migration-journey.md
versioned_docs/version-8.6/guides/migrating-from-camunda-7/migration-journey.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-journey.md

Remove the version target for the `business key` as it's not yet committed for 8.9.
Trggered by [this discussion](https://camunda.slack.com/archives/C02AWA0RF8A/p1746781761120669). `Business key` target release is not yet committed and should not be communicated in the docs.
This needs to be backported to 8.7

Remove business key target

---

docs/components/connectors/out-of-the-box-connectors/email.md
versioned_docs/version-8.6/components/connectors/out-of-the-box-connectors/email.md
versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/email.md

replaces `header` by `key` was not conform to the reality

docs(email): make a correction, replaces header by key, was not conform to the reality

---

docs/guides/migrating-from-camunda-7/migration-journey.md
versioned_docs/version-8.6/guides/migrating-from-camunda-7/migration-journey.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/migration-journey.md

Fix a URL, as prompted by TW review of https://github.com/camunda/camunda-docs/pull/5751.

Fix Roadmap URL in Migration Journey

---

docs/self-managed/setup/deploy/local/manual.md
versioned_docs/version-8.5/self-managed/setup/deploy/local/manual.md
versioned_docs/version-8.6/self-managed/setup/deploy/local/manual.md
versioned_docs/version-8.7/self-managed/setup/deploy/local/manual.md

https://camunda.slack.com/archives/C026U8GBNSW/p1746799791537059
If we need to point to specific releases or tags, this PR doesn't do that.
Given the note on the [README](https://github.com/camunda/camunda-platform/blob/main/README.md), this isn't urgent but is an experience issue.

Update manual instructions to camunda/camunda for 8.6+

---

docs/apis-tools/spring-zeebe-sdk/configuration.md
docs/self-managed/connectors-deployment/connectors-configuration.md
src/components/PageDescription.jsx
src/css/custom.css
src/theme/DocVersionBanner/index.tsx

This PR refactors the spring sdk configuration page to better match the user journey.
At the same time, it adds the newly introduced `camunda.client.auth.method` property.

Spring SDK: configuration refactor

---

docs/components/modeler/desktop-modeler/install-the-modeler.md
versioned_docs/version-8.4/components/modeler/desktop-modeler/install-the-modeler.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/install-the-modeler.md
versioned_docs/version-8.6/components/modeler/desktop-modeler/install-the-modeler.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/install-the-modeler.md

In Desktop Modeler v5.35.0 `rpa` files can also be directly opened. 
Should go live with v5.35.0 release today

Mention rpa for file association

---

docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md

In line with this [FR](https://github.com/camunda/camunda/issues/30503) that adds the following features and configurations:
- [Add optionality for the creation of container during initialisation ](https://github.com/camunda/camunda/issues/31372)
- [Allow configuration via SAS token in Azure Backups. ](https://github.com/camunda/camunda/issues/31373)
We need to add these configurations to the docs. 
This feature is intended to be released in the next patch release, namely 8.7.2, and it will not be backported for now.

Add new configs to Azure backup configuration.

---

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
versioned_docs/version-8.4/components/modeler/desktop-modeler/element-templates/c7-defining-templates.md
versioned_docs/version-8.4/components/modeler/desktop-modeler/element-templates/defining-templates.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/element-templates/defining-templates.md
versioned_docs/version-8.6/components/modeler/desktop-modeler/element-templates/defining-templates.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/element-templates/defining-templates.md

Related to https://github.com/camunda/camunda-modeler/issues/4853

Document new keywords property in element-templates

---

docs/reference/supported-environments.md
versioned_docs/version-8.7/reference/supported-environments.md

With 8.7 we moved the contents of AWS / Azure / GCP to a central page. These references weren't 404 broken but the content itself had moved.

fix: broken identifiers of support env volume links

---

docs/reference/announcements-release-notes/880/880-release-notes.md

Added blog per internal thread - https://camunda.slack.com/archives/C05FTL0DHKP/p1747045844127409

Add 8.8.0-alpha4 blog

---

docs/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.4/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.5/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.6/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md

Update documentation on shard and replica configuration for Tasklist 8.4+ as per https://github.com/camunda/camunda-docs/issues/5624

fix: Improve docs on shard and replica configuration

---

docs/apis-tools/migration-manuals/migrate-to-camunda-api.md

fix: Improve the API migration guide

---

versioned_docs/version-8.7/components/modeler/feel/builtin-functions/feel-built-in-functions-string.md

The `is blank` FEEL function is planned for release with 8.8, but was accidentally documented as an 8.7 feature due to the changed 8.7 release scope.
This was noted by a customer in a support case:
- https://jira.camunda.com/browse/SUPPORT-27369
For more context on the discovery check:
- https://camunda.slack.com/archives/C08SRV91H8S/p1747399533254369?thread_ts=1747396877.555549&cid=C08SRV91H8S

fix: remove unreleased `is blank` feel function

---

docs/components/connectors/out-of-the-box-connectors/embeddings-vector-db.md
sidebars.js

Adds documentation to a new Connector: Vector DB Connector
It's for next minor (alpha5, sorry there is no tag existing like that) / 8.8.

docs: added vector DB support

---

docs/components/connectors/out-of-the-box-connectors/embeddings-vector-db.md

fix: corrected document handling link
Raised by: https://camunda.slack.com/archives/C026U8GBNSW/p1747656791429319

fix: corrected document handling link

---

.github/workflows/add-to-project.yaml

fix: use dynamically generated app token instead of PAT
The workflow cannot be replaced with built-in GitHub Projects workflow automation.

fix: use app token instead of PAT

---

docs/self-managed/operational-guides/backup-restore/optimize-backup.md
versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/optimize-backup.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/optimize-backup.md
versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/optimize-backup.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/optimize-backup.md

As per feedback from [Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1747431646801889), the `GET actuator/backup` should be changed to `GET actuator/backups`.
https://docs.camunda.io/docs/self-managed/operational-guides/backup-restore/optimize-backup/#get-backup-info-api

Fix API request endpoint

---

docs/reference/announcements-release-notes/870/870-announcements.md
docs/self-managed/modeler/web-modeler/configuration/configuration.md
versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/configuration.md
versioned_docs/version-8.7/reference/announcements-release-notes/870/870-announcements.md
versioned_docs/version-8.7/self-managed/modeler/web-modeler/configuration/configuration.md

Clarifies that `CLIENT_CREDENTIALS` also should be used as cluster authentication method when using a generic identity provider. 
When using a generic provider, the mappings between a JWT claim and a C8 component permission are defined within Identity instead of the JWT audience claim itself leading to Zeebe rejecting bearer tokens.

docs(web-modeler): clarify usage of CLIENT_CREDENTIALS cluster auth

---

docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md
versioned_docs/version-8.7/self-managed/setup/deploy/amazon/amazon-eks/eks-helm.md

In 8.7 and 8.8 the link is to the wrong file. This PR aims to fix this issue.
Noticed it as part of a different review when comparing the items.
I'll merge after engineering approval that I'm not making this up.
This does not require a tech writer review.

fix: link to correct secret file

---

docs/components/modeler/web-modeler/play-your-process.md

As advertised here: https://camunda.com/blog/2025/05/camunda-alpha-release-may-2025/#h.92nqr9l3cmt8:~:text=Scenarios%20support%20(Self,the%20Web%20Modeler.
Removed a limitation that's published in our docs

Remove scenarios limitation for SM

---

versioned_docs/version-8.7/self-managed/identity/user-guide/configuration/alternative-db.md
versioned_sidebars/version-8.7-sidebars.json

port of this PR to 8.7: https://github.com/camunda/camunda-docs/pull/5574
We pushed out the 8.6 docs page on a quicker timeline than we might have otherwise, and supposedly this information will be irrelevant in 8.8, however, it should still be relevant for 8.7.

feat: port identity alternative-database docs to 8.7

---

docs/reference/notices.md
versioned_docs/version-8.4/reference/notices.md
versioned_docs/version-8.5/reference/notices.md
versioned_docs/version-8.6/reference/notices.md
versioned_docs/version-8.7/reference/notices.md

Security notice for https://github.com/camunda/web-modeler/issues/14890

docs(web-modeler): notice for CVE-2025-23166

---

api/camunda/generation-strategy.js
api/make-server-dynamic.js
api/remove-duplicate-version-badge.js
api/tasklist/generation-strategy.js
api/zeebe/generation-strategy.js
package-lock.json
package.json

deps: drop `replace-in-file` in favor of plain `fs`
`replace-in-file` v8 (https://github.com/camunda/camunda-docs/pull/5823/ - which will be covered by this PR) does not work as simple with (sync) CJS and is overall additionally overhead package to have.
testing locally:
- run
```
npm run api:generate:adminsm
npm run api:generate:camunda
npm run api:generate:operate
npm run api:generate:tasklist
npm run api:generate:zeebe
```
- there should be no local diff.

deps: drop `replace-in-file` in favor of plain `fs`

---

docs/self-managed/operational-guides/update-guide/830-to-840.md
docs/self-managed/operational-guides/update-guide/840-to-850.md
versioned_docs/version-8.4/self-managed/operational-guides/update-guide/830-to-840.md
versioned_docs/version-8.5/self-managed/operational-guides/update-guide/830-to-840.md
versioned_docs/version-8.5/self-managed/operational-guides/update-guide/840-to-850.md
versioned_docs/version-8.6/self-managed/operational-guides/update-guide/830-to-840.md
versioned_docs/version-8.6/self-managed/operational-guides/update-guide/840-to-850.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/830-to-840.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/840-to-850.md

Add warnings for broken Tasklist 8.5.15 and 8.4.20 images in update guides for 8.3 -> 8.4 and 8.4 -> 8.5 for all versions where it's being referenced.

docs: document broken upgrade version for tasklist

---

docs/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md

Based on https://camunda.slack.com/archives/C026U8GBNSW/p1747673738908129 -- looks like this was accidentally misplaced?

adjust connectors config instructions

---

docs/components/connectors/protocol/rest.md
versioned_docs/version-8.7/components/connectors/protocol/rest.md

feat(rest-connector): Add hint about multipart/form-data

---

docs/apis-tools/migration-manuals/migrate-to-camunda-api.md

We re-added support for filtering by `resourceName` also for v2
See [PR](https://github.com/camunda/camunda/pull/32379) and [Issue](https://github.com/camunda/camunda/issues/31495)

feat: allow resource name filter for decision requirements

---

package-lock.json
package.json

fix: drop unneeded docusaurus v1 package and the dependencies it brings in (and potential vulnerabilities).
As a part of upgrading Docusaurus to v2 and v3, v1 has never been removed.
`docusaurus` is `@docusaurus-core` in v3.
`package-lock.json` regenerated after removing the `docusaurus` package.
See the link to the preview environment below to check it's working correctly.

fix: drop unneeded docusaurus v1 package

---

docs/components/modeler/web-modeler/token-simulation.md
versioned_docs/version-8.7/components/modeler/web-modeler/token-simulation.md

A PushFeedback user wasn't sure how to change between modes in https://docs.camunda.io/docs/components/modeler/web-modeler/token-simulation/ -- I have linked to this doc on first reference of design mode.

link to modes from token sim

---

howtos/documentation-guidelines.md

Remove @akeller as the documentation and documentation infra DRI. Add @MaxTru as fallback.

Remove akeller from documentation-guidelines.md

---

docs/apis-tools/testing/utilities.md

Adds documentation for new CPT mocking utilities such as `mockJobWorker`, `mockChildProcess` and `mockDmnDecision`
8.8.0 release
#closes [#5714](https://github.com/camunda/camunda-docs/issues/5714)

docs(utilities): mocking utilities for CPT

---

docs/components/modeler/desktop-modeler/install-the-modeler.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/install-the-modeler.md

The only thumbs down we had last week with PushFeedback was a user who didn't understand exactly where to go to actually install Desktop Modeler. Gave this page a 30-min cleanup and tried to make this section more obvious in case they miss the link at the top.

tidy install desktop modeler page

---

docs/components/best-practices/operations/versioning-process-definitions.md
versioned_docs/version-8.6/components/best-practices/operations/versioning-process-definitions.md
versioned_docs/version-8.7/components/best-practices/operations/versioning-process-definitions.md

The Process versioning best practice was copied over from Camunda 7 before process instance migration was available in Camunda 8. It is available now and the leftovers to reference Camunda 7 specific implementation details can be removed.
Resolves #3987

Change migration specifics from Camunda 7 description to Camunda 8 description

---

docs/reference/regions.md
versioned_docs/version-8.7/reference/regions.md

Remove known limitation for 8.7 and 8.8 regions documentation.
https://docs.camunda.io/docs/reference/regions/
Closes https://github.com/camunda/camunda-docs/issues/5896

Remove limitation for 8.7 and 8.8

---

docs/components/modeler/web-modeler/git-sync.md
docs/self-managed/modeler/web-modeler/configuration/configuration.md

This is part of: https://github.com/camunda/product-hub/issues/2580 
Closes #5880 
Closes https://github.com/camunda/web-modeler/issues/14334
Closes https://github.com/camunda/web-modeler/issues/14331
Closes https://github.com/camunda/web-modeler/issues/14245
Today we merged the azure git sync support which enables users to connect a process application with an Azure DevOps backed repository.
Main changes in this PR are:
- Add new tab for azure 
- Document the steps required to register an app in microsoft entra and azure devops by providing links to the official documentation (we don't provide all details for each step)
- Document relevant ENV variables that can be used in self-managed instances to connect to an Azure DevOps Server and also other National clouds (link to external docs …

chore(docs): document how use gitsync with an azure repository

---

versioned_docs/version-8.7/components/modeler/web-modeler/play-your-process.md

Play Scenarios are available in Self-Managed starting in 8.7.1.

docs(play): remove scenarios SaaS-only badge

---

docs/reference/announcements-release-notes/880/880-release-notes.md

Closes https://github.com/camunda/camunda-docs/pull/5892/files#r2120436017.

Fix versions typo in release notes

---

docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/backup-and-restore.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/backup-and-restore.md
versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/backup-and-restore.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/backup-and-restore.md

The current docs do not mention that the zeebe disk needs to be empty for a restore. This PR adds this detail.
This change needs to be moved to other versions as well after being accepted

fix: restore procedure does not cover deletion of zeebe data

---

docs/components/connectors/out-of-the-box-connectors/openai.md
versioned_docs/version-8.4/components/connectors/out-of-the-box-connectors/openai.md
versioned_docs/version-8.5/components/connectors/out-of-the-box-connectors/openai.md
versioned_docs/version-8.6/components/connectors/out-of-the-box-connectors/openai.md
versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/openai.md

A docs bug with the admonition -- https://camunda.slack.com/archives/C026U8GBNSW/p1748882543363909

fix admonition bug for open ai connector

---

docs/guides/migrating-from-camunda-7/code-conversion.md
docs/guides/migrating-from-camunda-7/conceptual-differences.md
versioned_docs/version-8.4/guides/migrating-from-camunda-7/conceptual-differences.md
versioned_docs/version-8.5/guides/migrating-from-camunda-7/conceptual-differences.md
versioned_docs/version-8.6/guides/migrating-from-camunda-7/code-conversion.md
versioned_docs/version-8.6/guides/migrating-from-camunda-7/conceptual-differences.md
versioned_docs/version-8.6/guides/migrating-from-camunda-7/migration-journey.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/code-conversion.md
versioned_docs/version-8.7/guides/migrating-from-camunda-7/conceptual-differences.md

PushFeedback -- The text is: see this code in the diagram converter as a starting point, the link is broken, the repo changed. Old link: https://github.com/camunda-community-hub/camunda-7-to-8-migration/blob/main/backend-diagram-converter/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformer.java new link: https://github.com/camunda-community-hub/camunda-7-to-8-migration-analyzer/blob/d6fda97d00f27b23fc87fd741134225a527f3de1/core/src/main/java/org/camunda/community/migration/converter/expression/ExpressionTransformer.java#L4

fix broken migration link

---

versioned_docs/version-8.7/self-managed/operational-guides/production-guide/helm-chart-production-guide.md

Fix broken link to examples section

fix: update helm-chart-production-guide.md link

---

docs/reference/glossary.md
versioned_docs/version-8.4/reference/glossary.md
versioned_docs/version-8.5/reference/glossary.md
versioned_docs/version-8.6/reference/glossary.md
versioned_docs/version-8.7/reference/glossary.md

Minor, not super important change.
I noticed that element template, a term often misunderstood, was missing from glossary, even though it was used in the "Connectors" terms.  Opportunistic improvement.

docs(glossary): introduce element template to glossary

---

docs/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
sidebars.js
versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/available-connectors-overview.md
versioned_sidebars/version-8.7-sidebars.json

fix(available-connectors-overview): fix marketplace spelling

---

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md

Related to https://github.com/camunda/camunda-modeler/issues/4582

docs(desktop-modeler): add `zeebe:userTask` binding

---

docs/reference/announcements-release-notes/850/850-announcements.md
docs/reference/announcements-release-notes/850/850-release-notes.md
docs/reference/announcements-release-notes/860/860-announcements.md
docs/reference/announcements-release-notes/870/870-announcements.md
docs/reference/announcements-release-notes/880/880-announcements.md
versioned_docs/version-8.6/reference/announcements-release-notes/850/850-announcements.md
versioned_docs/version-8.6/reference/announcements-release-notes/850/850-release-notes.md
versioned_docs/version-8.6/reference/announcements-release-notes/860/860-announcements.md
versioned_docs/version-8.7/reference/announcements-release-notes/850/850-announcements.md
versioned_docs/version-8.7/reference/announcements-release-notes/850/850-release-notes.md
versioned_docs/version-8.7/reference/announcements-release-notes/860/860-announcements.md
versioned_docs/version-8.7/reference/announcements-release-notes/870/870-announcements.md

This PR formats the recent changes to the announcements pages for 8.8 - 8.6, and also removes a typo.

Announcements admonitions

---

docs/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.4/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.5/components/connectors/custom-built-connectors/connector-sdk.md
versioned_docs/version-8.6/components/connectors/custom-built-connectors/connector-sdk.md

Porting based on https://github.com/camunda/camunda-docs/pull/5893.

backport connectors sdk type and property

---

versioned_docs/version-8.7/self-managed/concepts/exporters.md

Relates to https://github.com/camunda/camunda-docs/pull/5921.
This PR moves the customer exporter content from the in-flight PR above, so it can be published.

Add custom exporter section

---

versioned_docs/version-8.7/apis-tools/spring-zeebe-sdk/configuration.md

This PR moves some configurations to the source code of camunda to guarantee alignment.
This PR relies on https://github.com/camunda/camunda/pull/33195 and its backport to `stable/8.7` to get the correct references from the stable branch.

fix: move configuration to source

---

docs/reference/notices.md
versioned_docs/version-8.6/reference/notices.md
versioned_docs/version-8.7/reference/notices.md

Closes https://github.com/camunda/web-modeler/issues/15550

docs(web-modeler): security notice 21

---

docs/self-managed/operational-guides/update-guide/870-to-880.md

Adjust API DTOs renamed again by https://github.com/camunda/camunda/issues/33912.
closes #6001

docs: adjust API DTO names in update guide

---

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md

Related to https://github.com/camunda/camunda-modeler/issues/5036
Introduces a custom category that can be applied to semantically organize element templates.
⚠️ ~~Before merging, let's wait for https://github.com/camunda/element-templates-json-schema/pull/168 to be released.~~
👌 done

docs(modeler): introduce element templates custom category

---

docs/components/modeler/feel/feel-playground.md

Context is not pre-filled at this time.
The user can enter variables in JSON format, but they need to do this manually.
This feature is only available in 8.8, so I did not apply these changes to other versions.

docs(feel-playground): remove pre-filled

---

docs/components/modeler/web-modeler/git-sync.md
docs/self-managed/modeler/web-modeler/configuration/configuration.md

Closes: #5975
Closes https://github.com/camunda/web-modeler/issues/15167
Closes https://github.com/camunda/web-modeler/issues/15165
Closes https://github.com/camunda/web-modeler/issues/15160

feat(webmodeler): document how to setup gitsync with bitbucket

---

src/components/CamundaDistributions/DockerCompose.jsx

fixes https://github.com/camunda/camunda-docs/issues/6029

fix: adjust compose link for 8.8

---

docs/components/modeler/desktop-modeler/index.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/index.md

The Desktop Modeler is not meant to be used as a standalone tool, but alongside our users favorite IDE, in the professional software development environment of their choice ([ref](https://camunda.com/platform/modeler/), [ref](https://miro.com/app/board/uXjVIWEM7Rc=/?moveToWidget=3458764628969419271&cot=14)).
This PR aims to clarify that.
Related to https://github.com/bpmn-io/internal-docs/issues/1202

feat(desktop-modeler): hint on desktop modeler <> IDE interplay

---

docs/apis-tools/java-client/job-worker.md
docs/components/concepts/job-workers.md
docs/reference/announcements-release-notes/880/880-announcements.md
versioned_docs/version-8.7/apis-tools/java-client/job-worker.md
versioned_docs/version-8.7/components/concepts/job-workers.md

Keep deprecated 'zeebe.*' job worker metric names until 8.10 removal.
Introduce new metric names with 'camunda.*' naming convention
Added:
**WARNING** blocks at 8.8 concept/job worker metrics and java-client/job worker metrics
**INFO** blocks at 8.7 concept/job worker metrics and java-client/job worker metrics
Mentioned deprecation in 8.8 Release Announcements
Version 8.8
Version 8.7
Announcements
Related to Issue: https://github.com/camunda/camunda/issues/28599 
Related to PR: https://github.com/camunda/camunda/pull/34068/files

docs: deprecated job worker metrics and replacements

---

docs/self-managed/setup/deploy/local/c8run.md

This ass docs for a new c8run parameter added with https://github.com/camunda/camunda/pull/34340 recently and to be released with 8.8.0-alpha6.

feat: c8run startup url parameter docs

---

docs/self-managed/setup/deploy/local/c8run.md

@megglos, based on @gbetances089 feedback lets add an example on how to use it.
--> Add an example for the c8run startup-url

add example to c8run startup-url

---

docs/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.4/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.6/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/troubleshooting.md

Related to https://github.com/camunda/camunda-modeler/issues/2876
This PR adds a troubleshooting section on paused clusters so that the customers are not left in the wild.

feat: add troubleshooting for a paused cluster

---

docs/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.4/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.6/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/troubleshooting.md

Related to https://github.com/camunda/camunda-modeler/issues/5114
We want to help users with onboarding.

feat: troubleshoot local connection problem

---

docs/components/modeler/desktop-modeler/element-templates/defining-templates.md

This small PR fixes some incorrect admonition syntax introduced in a recent PR.

Fix admonitions

---

docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.4/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md

Document workaround for using Dell EMC ECS as an S3 compliant backup storage. Dell EMC ECS is falling behind on changes regarding hash checksum signing done by the updated AWS S3 client we are using. 
Support case: [#inc-support-27852-zeebe-backup-failing-8-7-5](https://camunda.slack.com/archives/C092A4C8JP9)

docs: dell emc ecs signing workaround

---

docs/reference/announcements-release-notes/880/880-release-notes.md
docs/reference/regions.md
versioned_docs/version-8.4/reference/regions.md
versioned_docs/version-8.5/reference/regions.md
versioned_docs/version-8.6/reference/regions.md
versioned_docs/version-8.7/reference/regions.md

In https://github.com/camunda/team-sre/issues/1393, we deployed a new AWS region in Singapore (`ap-southeast-1`) which is now ready.
This PR adds this region in the different regions list.
However I don't know if there should be an announcement like it was done for [GCP Singapore region](https://github.com/camunda/camunda-docs/blob/main/docs/reference/announcements-release-notes/870/870-release-notes.md#singapore-region-available-for-saas-saas).
cf also [Slack discussion](https://camunda.slack.com/archives/C026U8GBNSW/p1751970796730889)
There's apparently no issue in https://github.com/camunda/product-hub/ for that, I'm checking with our PM.

New AWS region in Singapore

---

docs/self-managed/installation-methods/helm/upgrade/helm-820-830.md
docs/self-managed/installation-methods/helm/upgrade/helm-830-840.md
docs/self-managed/installation-methods/helm/upgrade/helm-840-850.md
docs/self-managed/installation-methods/helm/upgrade/helm-850-860.md
docs/self-managed/installation-methods/helm/upgrade/helm-860-870.md
docs/self-managed/installation-methods/helm/upgrade/helm-870-880.md

Moving the helm upgrade tabs to pages.
P.s. I did not update the sidebar nor removed the old page to not cause conflicts ;)

refactor upgrade to pages

---

docs/self-managed/installation-methods/helm/index.md
docs/self-managed/installation-methods/helm/install.md

Correct install and overview page of HC installation.

fix: swap install and index page of hc installation

---

docs/self-managed/installation-methods/helm/install.md

fix typo in helm install

---

docs/self-managed/identity/configuration/alternative-db.md
versioned_docs/version-8.6/self-managed/identity/configuration/alternative-db.md
versioned_docs/version-8.7/self-managed/identity/configuration/alternative-db.md

This PR replaces references to `Identity OIDC` in the alternative DB page to simply refer to `Management Identity` (for 8.8+), and `Identity` for previous versions.

fix: refer to the right product and not Identity OIDC

---

docs/guides/getting-started-example.md

Fix windows command.
Resolves https://github.com/camunda/camunda-8-get-started/issues/9

Fix Getting Started Guide Windows stop command

---

api/camunda/generation-strategy.js

This adapts the sync ot the rename that happened upstream with: https://github.com/camunda/camunda/pull/34169
closes #6167

ci: adapt sync-rest-api-docs to renaming

---

src/components/CamundaSelfManaged/Introduction.jsx

Follow up to https://github.com/camunda/camunda-docs/pull/6149 -- adding in Immi's comments.

incorporate immis sm comments

---

src/theme/DocItem/Metadata/determineCanonical.spec.js

test: fix test suite (outdated jest function)

---

docs/components/best-practices/development/dealing-with-problems-and-exceptions.md
versioned_docs/version-8.4/components/best-practices/development/dealing-with-problems-and-exceptions.md
versioned_docs/version-8.5/components/best-practices/development/dealing-with-problems-and-exceptions.md
versioned_docs/version-8.6/components/best-practices/development/dealing-with-problems-and-exceptions.md
versioned_docs/version-8.7/components/best-practices/development/dealing-with-problems-and-exceptions.md

Update link to @berndruecker's "Lost in transaction" talk to a Youtube recording as the original article is not available anymore.

fix: update link to Bernd's "Lost in transaction" talk

---

docs/self-managed/installation-methods/helm/configure/database/using-existing-postgres.md
sidebars.js

Adding back the guide: 
* using-existing-postgres

add using postgres guide again to 8.8

---

docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/eksctl.md
docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/irsa.md
docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/terraform-setup.md
sidebars.js

Restructuring the amazon EKS folder as discussed in the workshop:
* Introducing a subfolder for quickstart + troubleshooting
* Remove the "intention" of the guide from the title:
* Removing Troubleshooting, (quickstart), (advanced)

refactor: restruture the 8.8 amazon eks folder

---

sidebars.js

Moving folder sections over single files (move ingress on level up).

refactor: refactor hc configure section

---

docs/self-managed/operational-guides/backup-restore/backup.md
docs/self-managed/operational-guides/backup-restore/restore.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/backup.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/restore.md
versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/backup.md
versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/restore.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/backup.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/restore.md

related to https://github.com/camunda/camunda-docs/issues/6202
- Explicitly mentions the word `crashloop` for Zeebe restore.
- Explicitly mention `wait_for_restore` part for ES / OS

docs: backup and restore further adjustments

---

spec/regression/smoke.spec.ts

This PR is to fix the Playwright regression test that is now failing, making the `npm run test:regression` failing too

fix: update the title page to what is actually there

---

docs/guides/migrating-from-camunda-7/migration-journey.md

I updated the workshop link to reflect the new resource. @berndruecker I saw the <TODO> comment for the scoping workshop listed below the evaluation workshop -- is this related?

Update workshop link

---

docs/components/modeler/web-modeler/git-sync.md
docs/reference/announcements-release-notes/880/880-release-notes.md
docs/self-managed/modeler/web-modeler/configuration/configuration.md

Closes #6216 
We discovered that self-hosted bitbucket instances are not supported by our current implementation and we are making it explicit in our docs that we don't support it.

chore(webmodeler): update web modeler bitbucket documentation

---

docs/apis-tools/migration-manuals/migrate-to-camunda-api.md

The `parentKey` in the Operate V1 API is practically a duplicate of the `parentProcessInstanceKey`. The V2 API migration guide reflects this.

docs: correct PI search API migration

---

docs/self-managed/orchestration-identity/configuration.md

@epollum pointed out that this documentation page refers to "Helm properties" but these options are not even helm properties! they are intended to be set within the application itself, or the configmap. 
So the 2 sections will be "Spring properties" and "Env vars", so that users will know what to do with them.

style(identity): rename Helm properties to Spring properties

---

docs/self-managed/zeebe-deployment/exporters/camunda-exporter.md

This PR adds a tab for existing content.

fix(exporter): added missing tab

---

docs/components/connectors/react-components/_connectors-table.js
versioned_docs/version-8.7/components/connectors/react-components/_connectors-table.js

The type of the webhook connector was wrong, therefore the connector could not be found when filtering for "inbound" connectors.

fix(connectors): Fix type of webhook connector

---

docs/self-managed/installation-methods/helm/upgrade/helm-870-880.md

related: https://github.com/camunda/camunda-platform-helm/issues/2574
This PR details how to run the Identity migration app for 8.8

identity migration doc for 8.8 Phase 2

---

docs/reference/announcements-release-notes/880/880-announcements.md

* Avoid confusion that we support generic Opensearch

docs(supportedEnvs): be specific about Amazon OS

---

docs/components/concepts/variables.md
versioned_docs/version-8.5/components/concepts/variables.md
versioned_docs/version-8.6/components/concepts/variables.md
versioned_docs/version-8.7/components/concepts/variables.md

* Not urgent, this was broken a long time (random finding)
* Please note that modeling behavior is also outdated (see https://github.com/camunda/camunda-modeler/issues/3333)
* closes #643

docs: fix input mappings

---

docs/self-managed/installation-methods/helm/configure/configure-multi-tenancy.md
versioned_docs/version-8.5/self-managed/operational-guides/configure-multi-tenancy.md
versioned_docs/version-8.6/self-managed/operational-guides/configure-multi-tenancy.md
versioned_docs/version-8.7/self-managed/operational-guides/configure-multi-tenancy.md

Relates to https://github.com/camunda/camunda-docs/issues/4372.

add note on issue with multi tenancy and zeebe

---

docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/irsa.md
docs/self-managed/installation-methods/helm/configure/database/all-shards-failed.md
sidebars.js

This is related to [SUPPORT-27120](https://jira.camunda.com/browse/SUPPORT-27120). The problem is that OpenSearch now has an increased load due to identity changes in 8.8, and now customers will need to set their read replicas per index to a higher number.  This issue could be partially related to node preemption in AWS managed opensearch, or other networking issues in their managed service. For our customer, they were encountering this issue frequently, many times per day requiring many re-installs of 8.8 alphas where they delete all the data in OpenSearch.
The customer reported that after they increased their read replicas, their problem went away.

fix(irsa): include notice about opensearch read replicas

---

docs/self-managed/concepts/elasticsearch-without-cluster-privileges.md
docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
sidebars.js
versioned_docs/version-8.7/self-managed/concepts/elasticsearch-without-cluster-privileges.md

Relates to:
- https://github.com/camunda/camunda/issues/28989
- https://github.com/camunda/camunda/issues/29668
The feature is already implemented and documented in 8.6 and 8.7, we backported it to 8.8 (with some changes in the configuration), it will be part of 8.8.0-alpha7

docs: standalone schema and backup managers docs

---

docs/components/modeler/bpmn/bpmn-primer.md
howtos/markdown-and-mdx-features.md
package-lock.json
package.json
versioned_docs/version-8.4/components/modeler/bpmn/bpmn-primer.md
versioned_docs/version-8.5/components/modeler/bpmn/bpmn-primer.md
versioned_docs/version-8.6/components/modeler/bpmn/bpmn-primer.md
versioned_docs/version-8.7/components/modeler/bpmn/bpmn-primer.md

chore(deps): migrate to react-player v3

---

docs/components/modeler/bpmn/automating-a-process-using-bpmn.md
docs/components/modeler/web-modeler/model-your-first-diagram.md
versioned_docs/version-8.7/guides/automating-a-process-using-bpmn.md
versioned_docs/version-8.7/guides/getting-started-orchestrate-microservices.md
versioned_docs/version-8.7/guides/model-your-first-process.md

Updating a few academy links by Academy recommendation -- closes https://github.com/camunda/camunda-docs/issues/5997. A lot of content moved in `next` for guides, so some of this is applicable only by version.

update academy links

---

docs/guides/getting-started-example.md

Signed-off-by: Josh Wulf <josh.wulf@camunda.com>
This implements the QA feedback from https://github.com/camunda/camunda-8-get-started/issues/7
As soon as possible.

fix: implement QA feedback in getting-started-example

---

versioned_docs/version-8.5/reference/notices.md
versioned_docs/version-8.6/reference/notices.md
versioned_docs/version-8.7/reference/notices.md

Backport of https://github.com/camunda/camunda-docs/pull/6300

feat: Notice for CVE-2025-52520 [backport]

---

sidebars.js

As per [Slack](https://camunda.slack.com/archives/C026U8GBNSW/p1754038718595839), adding Camunda Exporter to sidebar.
@hisImminence as a follow-up, we should decide on the order of the Exporters in the menu, and adjust the Exporters page bulleted list accordingly 👍

Add Camunda Exporter back into sidebar

---

docs/apis-tools/testing/assertions.md

Added assertion convenience methods to the testing docs.

docs: added assertion convenience methods

---

docs/self-managed/installation-methods/helm/configure/configure-multi-tenancy.md
versioned_docs/version-8.5/self-managed/operational-guides/configure-multi-tenancy.md
versioned_docs/version-8.6/self-managed/operational-guides/configure-multi-tenancy.md
versioned_docs/version-8.7/self-managed/operational-guides/configure-multi-tenancy.md

Follow up to https://github.com/camunda/camunda-docs/issues/4372.

add notes for multi tenancy

---

docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
docs/self-managed/operational-guides/troubleshooting.md
versioned_docs/version-8.5/self-managed/operational-guides/troubleshooting/troubleshooting.md
versioned_docs/version-8.6/self-managed/operational-guides/troubleshooting/troubleshooting.md
versioned_docs/version-8.7/self-managed/operational-guides/troubleshooting/troubleshooting.md

This documents a known issue with the Azure Backup Store that affected at least two customers.

feat: document known issue with Azure backup store

---

docs/apis-tools/zeebe-api/gateway-service.md

This PR adds the new runtime instruction field to the `CreateProcessInstance` RPC. It was introduced in https://github.com/camunda/camunda/pull/35685 as part of https://github.com/camunda/camunda/issues/32217.
For now the only runtime instruction type is `TerminateProcessInstance`.
closes https://github.com/camunda/camunda-docs/issues/5798

feat: runtime instructions in the CreateProcessInstance RPC

---

docs/self-managed/components/orchestration-cluster/tasklist/tasklist-configuration.md

See context: https://camunda.slack.com/archives/C08MRKHJ0CD/p1754380561896809

fix(tasklistAPI): clarify allow-non-self-assignment flag in 8.8

---

docs/apis-tools/testing/assertions.md
docs/apis-tools/testing/getting-started.md
docs/apis-tools/testing/utilities.md

Add new CPT assertions and utilities from `8.8.0-alpha7`:
- https://github.com/camunda/camunda/issues/32663
- https://github.com/camunda/camunda/issues/32648
- https://github.com/camunda/camunda/issues/32666
Changes pages:
- [Assertions](https://preview.docs.camunda.cloud/pr-6360/docs/next/apis-tools/testing/assertions/#hasvariablesatisfies)
- [Utilities](https://preview.docs.camunda.cloud/pr-6360/docs/next/apis-tools/testing/utilities/#set-time)

[CPT] Add new assertions and utilities

---

docs/self-managed/components/orchestration-cluster/zeebe/exporters/camunda-exporter.md

Relates to https://github.com/camunda/camunda-platform-helm/issues/3897

docs(exporter): lowercase camunda exporter id in the documentation

---

docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
docs/self-managed/operational-guides/troubleshooting.md
versioned_docs/version-8.5/self-managed/operational-guides/troubleshooting/troubleshooting.md
versioned_docs/version-8.6/self-managed/operational-guides/troubleshooting/troubleshooting.md
versioned_docs/version-8.7/self-managed/operational-guides/troubleshooting/troubleshooting.md

Retro review of https://github.com/camunda/camunda-docs/pull/6347.

retro review 6347

---

docs/components/modeler/web-modeler/git-sync.md

Closes https://github.com/camunda/web-modeler/issues/16654
Changes apply to WM SaaS only

docs(web-modeler): GitHub Enterprise support for SaaS

---

docs/self-managed/installation-methods/helm/cloud-providers/amazon/aws-ec2.md

related to https://github.com/camunda/team-infrastructure-experience/issues/769
Will ask for a quick check of tech writers after initial review to only have to approve the final version.
It's the first small rework to align it with the remaining structure the we've kept in EKS / ROSA etc.
There will be more changes and restructurings in the future. Just wanted have the text base aligned already.
Yes Léo, I'll look into splitting it maybe up in the future in two parts.

docs: ec2 small rework

---

docs/self-managed/components/components-upgrade/850-to-860.md
versioned_docs/version-8.6/self-managed/operational-guides/update-guide/850-to-860.md
versioned_docs/version-8.7/self-managed/operational-guides/update-guide/850-to-860.md

This PR updates our documentation and example manifests to bump the Zeebe Gateway’s default memory request from 512 Mi to 600 Mi. In version 8.6.0+, the Gateway’s footprint grew, and keeping the old request led to periodic OOMKills (Exit Code 137). Raising the request prevents unnecessary restarts under normal load.
Related support case: [LINK](https://jira.camunda.com/browse/SUPPORT-27299)
Related issue: https://github.com/camunda/camunda/issues/29220

Suggest gateway memory increase while upgrading to 8.6

---

docs/components/whats-new-in-88.md

Add a brief summary outlining the benefits of upgrading to Camunda 8.8.

Add initial benefits summary to What's new in Camunda 8.8

---

docs/components/connectors/out-of-the-box-connectors/googledrive.md
versioned_docs/version-8.7/components/connectors/out-of-the-box-connectors/googledrive.md

Add a note to specify that when using GDrive shared drives, one must use an Oauth2 client, it won't work with a service account.
https://github.com/camunda/connectors/pull/5049

docs(gdrive): Add a note about shared drives specifics

---

versioned_docs/version-8.5/reference/ip-addresses.md
versioned_docs/version-8.6/reference/ip-addresses.md
versioned_docs/version-8.7/reference/ip-addresses.md
versioned_sidebars/version-8.5-sidebars.json
versioned_sidebars/version-8.6-sidebars.json
versioned_sidebars/version-8.7-sidebars.json

Backport the work done in https://github.com/camunda/camunda-docs/pull/6312 to 8.5, 8.6, 8.7.
Completes https://github.com/camunda/camunda-docs/issues/6401.

Backport hostnames and ip addresses

---

versioned_docs/version-8.5/self-managed/setup/install.md
versioned_docs/version-8.6/self-managed/setup/install.md
versioned_docs/version-8.7/self-managed/setup/install.md

Several changes to clarify and update the changes associated with Bitnami. 
- [ x ] This is a bug fix, security concern, or something that needs **urgent release support**. (add `bug` or `support` label)
- [ x ] My changes are for an **already released minor** and are in a `/versioned_docs` directory.

small clarification and changes

---

docs/self-managed/components/orchestration-cluster/operate/data-retention.md
versioned_docs/version-8.5/self-managed/operate-deployment/data-retention.md
versioned_docs/version-8.6/self-managed/operate-deployment/data-retention.md
versioned_docs/version-8.7/self-managed/operate-deployment/data-retention.md

Closes https://github.com/camunda/camunda-docs/issues/3408.

add note on ilm for data retention

---

docs/reference/announcements-release-notes/880/880-release-notes.md

Minor amendments to the alpha 7 release notes.

88 alpha7 release notes fixes

---

docs/apis-tools/migration-manuals/index.md
docs/apis-tools/migration-manuals/migrate-to-camunda-java-client.md
sidebars.js

This PR adds a step by step guidelines to update from Zeebe Java Client to Camunda Java Client
closes #6281

docs(migration): add migration guidelines for camunda java client

---

docs/self-managed/installation-methods/helm/cloud-providers/amazon/aws-ec2.md

related to https://github.com/camunda/team-infrastructure-experience/issues/805
small renaming as files were moved to `procedure` to align with our other usage.

docs: small ec2 folder rename to procedure

---

docs/self-managed/concepts/no-secondary-storage.md
sidebars.js

This is part of the [No Secondary Storage Support epic](https://github.com/camunda/camunda/issues/34371).
We've updated (almost) all orchestration cluster components to support the no secondary storage mode for SM (still auth and helm updates remaining). I'm adding a new page for this "no secondary storage mode" inside the SM docs.
Some considerations
- From the product's perspective we don't want to promote this setup to much as it's not in our longterm interest to do so, see [comment](https://docs.google.com/document/d/1-HrOOEmg8FBvUIUovcV603TfRry_Qe4_98L0ouEF88w/edit?pli=1&disco=AAABnOGDCAM). This is why I've decided to put this inside SM docs "concept" section. We have a small list of customers we already know who want to use this mode and we don't plan on attracting new customers …

docs(self-managed): no secondary storage support

---

api/camunda/camunda-openapi.yaml

As a team, we have agreed on a pattern of `assign`/`unassign` for REST API and client methods.
This PR aligns the naming of the operations.
This PR relates to:
Make naming in rest-api schema consistent #[35312](https://github.com/camunda/camunda/issues/35312)

Align REST API schema naming

---

versioned_docs/version-8.5/self-managed/setup/install.md
versioned_docs/version-8.6/self-managed/setup/install.md
versioned_docs/version-8.7/self-managed/setup/install.md

docs(self-managed): Minor fixes for typos and wording

---

docs/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.4/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.5/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.6/components/modeler/desktop-modeler/troubleshooting.md
versioned_docs/version-8.7/components/modeler/desktop-modeler/troubleshooting.md

Related to https://github.com/camunda/camunda-modeler/issues/5110. Updated mentions of `zeebe instance` with `Orchestration cluster`. In cases were the troubleshooting is about the direct zeebe connection I've kept the zeebe wording. as some of the headers are used as anchors for links in desktop model, I kept the old ids for the headings.
Alternative would be to duplicate the sections and link to them. Once the majority is using newer modeler versions we can remove the old sections
>[!NOTE]
> should go live with next desktop modeler release (2025-08-12)

feat: rename zeebe to orchestration cluster

---

docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/eks-helm.md
docs/self-managed/installation-methods/helm/cloud-providers/azure/microsoft-aks/aks-helm.md
docs/self-managed/installation-methods/helm/configure/accessing-components-without-ingress.md

As part of iteration 1 of
https://github.com/camunda/team-distribution/issues/578 ,
detailed in this comment
https://github.com/camunda/team-distribution/issues/578#issuecomment-3162202540
I will be aligning the port numbers between each deployment method.
This PR updates all documentation recommendations for local port-forwards to match what is recommended by each of the distributions (compose, helm, c8run) so that the same port can be recognized regardless of which distribution you're on.

fix(self-managed): align port numbers

---

docs/components/connectors/out-of-the-box-connectors/embeddings-vector-db.md

Document the embedding model providers added in https://github.com/camunda/connectors/pull/5191 and https://github.com/camunda/connectors/pull/5174.
Document the vector store providers added in https://github.com/camunda/connectors/pull/5152 and https://github.com/camunda/connectors/pull/5194.

Document vector database new providers

---

docs/self-managed/components/orchestration-cluster/identity/configuration.md

Document how to configure the identifier pattern for Identitiy-related entities like users, groups, roles, mapping rules, and tenants.
closes #6413

feat: document configurable identifier pattern

---

docs/components/concepts/access-control/authorizations.md

related to https://github.com/camunda/camunda/issues/36729

fix: change usage metric auth resource to permission

---

docs/components/concepts/access-control/authorizations.md

* The resource "Application" is renamed to "Component" on https://docs.camunda.io/docs/next/components/concepts/access-control/authorizations
* Web application is renamed to web component on that page wherever it refers to one of the individual UIs in the Orchestration Cluster; this is a second commit so could easily be reverted if we prefer to keep the term web application on the page

Rename authorization resource type "application" to "component"

---

versioned_docs/version-8.4/self-managed/modeler/web-modeler/configuration/configuration.md
versioned_docs/version-8.5/self-managed/modeler/web-modeler/configuration/configuration.md
versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/configuration.md
versioned_docs/version-8.6/self-managed/modeler/web-modeler/configuration/database.md

Documentation part of https://github.com/camunda/web-modeler/issues/17071
Should be released with the next patch release cycle at the beginning of September (attached the `8.8.0-alpha8` label for the sake of simplicity).

docs(web-modeler): backport non-public database schema support to 8.6

---

docs/self-managed/installation-methods/helm/cloud-providers/amazon/aws-ec2.md

Small fix of a broken link in AWS EC2. Noticed it when I was looking something up.
Just needs an approval to be merged.

fix: broken link reference in ec2

---

docs/components/concepts/data-retention.md
docs/self-managed/components/orchestration-cluster/zeebe/exporters/camunda-exporter.md

Add new ILM policy config for usage metrics in Camunda Exporter.
closes https://github.com/camunda/camunda/issues/37009

feat: add new ILM policy config for usage metrics in Camunda Exporter

---

docs/self-managed/update/administrators/run-update.md

docs(self-managed): Fix docs link typo

---

docs/self-managed/operational-guides/backup-restore/restore.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/restore.md
versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/restore.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/restore.md

related to [slack](https://camunda.slack.com/archives/C03UR0V2R2M/p1755796672366839)
Just to be explicit about how one can speed up the re-deployment. Not really needed if relying on a rolling update.

chore: add note about speeding up restore

---

docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-authentication.md
docs/self-managed/operational-guides/troubleshooting.md

This change adds the warnings/advice for the performance limitation of Basic Authentication. 
https://github.com/camunda/camunda/issues/36392

docs(identity): add documentation and troubleshooting info for basic authentication (#39392)

---

versioned_docs/version-8.7/self-managed/operate-deployment/operate-configuration.md
versioned_docs/version-8.7/self-managed/tasklist-deployment/tasklist-configuration.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/elasticsearch-exporter.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/exporters/opensearch-exporter.md

Relates to [#6295](https://github.com/camunda/camunda-docs/issues/6295)
Documents a new configuration that will be introduced with 8.7.11 version (**scheduled for Sept 9th**)
The documentation for 8.8 should be done in another pull request

docs(config): document index template priority configuration in 8.7

---

docs/components/modeler/web-modeler/idp/idp-configuration.md
versioned_docs/version-8.7/components/modeler/web-modeler/idp/idp-configuration.md

This PR removes the text regarding the limitation in IDP self managed for basic authentication support.
Closes https://github.com/camunda/web-modeler/issues/16971
Closes https://github.com/camunda/web-modeler/issues/14262

chore(idp): remove basic authentication limitation for idp

---

docs/guides/getting-started-example.md

We guide users from the developer portal to the docs page to learn about Java. Now they have finished, add a guidance back to other examples to learn with.
The idea is coming from [this Asana ticket](https://app.asana.com/1/384886434863350/project/1210078271154755/task/1210360001444121?focus=true)

Guide users back to the developer portal from the documentation page

---

docs/guides/getting-started-agentic-orchestration.md

Made it more clear how to add connector secrets for local environments.

Clarify secret management for local development environments

---

docs/self-managed/installation-methods/manual/cloud-providers/amazon/aws-ec2.md
docs/self-managed/installation-methods/manual/install.md
docs/self-managed/operational-guides/backup-restore/restore.md

Some smaller changes involved:
- Next steps mentioned for ec2 / manual installation to link to securing / embededd identity odic
- restored the backup and restore title for the restore page
- was rebased away a while ago and got lost.

chore: misc changes around ec2 and others

---

docs/self-managed/installation-methods/helm/upgrade/helm-820-830.md
docs/self-managed/installation-methods/helm/upgrade/helm-830-840.md
docs/self-managed/installation-methods/helm/upgrade/helm-840-850.md
docs/self-managed/installation-methods/helm/upgrade/helm-850-860.md
docs/self-managed/installation-methods/helm/upgrade/helm-860-870.md
docs/self-managed/installation-methods/helm/upgrade/helm-870-880.md
docs/self-managed/installation-methods/helm/upgrade/index.md
docs/self-managed/update/administrators/overview.md
src/components/CamundaDistributions/Helm.jsx
src/components/CamundaDistributions/index.jsx
versioned_docs/version-8.4/self-managed/platform-deployment/helm-kubernetes/upgrade.md
versioned_docs/version-8.5/self-managed/setup/upgrade.md
versioned_docs/version-8.6/self-managed/setup/upgrade.md
versioned_docs/version-8.7/self-managed/setup/upgrade.md

Related to: https://github.com/camunda/camunda-platform-helm/issues/3999
- Added note for Bitnami Docker repo rename
- Reworded the upgrade note between minor versions
This PR should be released as soon as possible to support the customers with the recent changes of the Bitnami repo rename.

docs(self-managed): add notes for upgrade

---

docs/self-managed/components/orchestration-cluster/operate/operate-configuration.md
docs/self-managed/components/orchestration-cluster/tasklist/tasklist-configuration.md

Relates to #6295
Similar to #6469 (8.7)
**The configuration pages are currently being re-written in https://github.com/camunda/camunda-docs/pull/6526/**

docs(config): document index template priority in 8.8

---

docs/apis-tools/migration-manuals/index.md
docs/apis-tools/migration-manuals/migrate-to-spring-boot-camunda-starter.md
sidebars.js

Added some more information about the Spring 
closes #6282

docs(migration): add migration guide for spring boot camunda starter

---

docs/self-managed/operational-guides/backup-restore/backup.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/backup.md
versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/backup.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/backup.md

Based on a [slack request](https://camunda.slack.com/archives/C03UR0V2R2M/p1756442660171369). For completeness we should ensure to mention the env vars for OpenSearch as welll.

docs: backup and restore mention OS env vars

---

docs/self-managed/components/console/configuration/configuration.md

- Context: Console Self-Managed
- Adds a config section for experimental features.
- Describes envvar to enable discovery mode.
- [PDP2867](https://github.com/camunda/product-hub/issues/2867)

feat(console): add experimental flags section

---

docs/apis-tools/migration-manuals/index.md
docs/apis-tools/migration-manuals/migrate-from-grpc-to-orchestration-cluster-api.md
docs/apis-tools/migration-manuals/migrate-to-camunda-java-client.md
sidebars.js

Add migration guide to update from gRPC to REST
closes #6283

docs(migration): add migration guide updating from gRPC to REST

---

versioned_docs/version-8.6/self-managed/setup/install.md

Based from consulting feedback and sync with PM, we should reference the prod guide of 8.7 also in 8.6 (customer did not find it).
closes https://github.com/camunda/camunda-platform-helm/issues/3575

fix: reference prod guide in 8.6

---

docs/self-managed/concepts/elasticsearch-without-cluster-privileges.md
docs/self-managed/installation-methods/helm/install.md
docs/self-managed/installation-methods/helm/upgrade/helm-870-880.md
docs/self-managed/operational-guides/backup-restore/backup-and-restore.md
docs/self-managed/operational-guides/backup-restore/restore.md

Part of the unified configuration refactoring in Camunda 8.8 helm chart 13.x.x.
Task: https://github.com/camunda/camunda-platform-helm/issues/3455

docs(self-managed): helm upgrade for orchestration cluster consolidation

---

.github/workflows/build-docs.yaml

Bitnami Apache Docker repository have been deprecated and moved to a new "Bitnami Legacy" repository, as reported in the `bitnami/apache` [dockerhub page](https://hub.docker.com/r/bitnami/apache#%EF%B8%8F-important-notice-upcoming-changes-to-the-bitnami-catalog)
Switching to `bitnamilegacy/apache` should solve the problem 
Since the `build-docs` workflow is currently broken, this fix should be merged asap

chore: use bitnamilegacy apache image to support build-docs workflow

---

sidebars.js

In a recent PR, the Upgrade docs for Self-Managed look to have been moved inside the Optimize section. This PR reverts that change.

Fix nesting of upgrade docs

---

docs/self-managed/installation-methods/helm/cloud-providers/amazon/amazon-eks/dual-region.md

We recently changed for 8.8 to move the storage class creation to outside of k8s to simplify some things.
The note for Dual-Region EKS was missing. It does not require a tech writer review as the same word for word text has already been reviewed in the past.
I already adjusted the path to the file when merged to main.

docs: dual-region eks add note about gp3

---

docs/components/best-practices/development/testing-process-definitions.md

This PR fixes some indentations, typos and leftovers from the previous Twitter example.

fix: adjust indentation and typo in testing process definitions

---

docs/components/modeler/desktop-modeler/element-templates/configuring-templates.md
docs/components/modeler/desktop-modeler/element-templates/using-templates.md
docs/components/modeler/element-templates/defining-templates.md
docs/components/modeler/web-modeler/element-templates/using-templates.md

- Add a short paragraph around how to edit/create element templates on a local machine.
- Add links in the existing templates pages to the new `Element template` page located under `Modeler`. This aims to help users find the modeler agnostic content in case they encounter this other pages before.
- Fixed web modeler publish element template link to avoid opening the connectors page that just redirects users to the new link.

chore(element-templates): document how to edit element template on a local env

---

docs/components/connectors/out-of-the-box-connectors/agentic-ai-aiagent.md

Add documentation for the new OpenAI-compatible provider introduced in https://github.com/camunda/connectors/pull/5311.
Also remove the OpenAI parameters that are removed in https://github.com/camunda/connectors/pull/5312.

docs(agentic-ai): add docs for openai-compatible provider

---

.github/workflows/update-release-links.yml

* Should fix this problem: https://github.com/camunda/camunda-docs/pull/6660#issuecomment-3269249295

fix(gha/update-relaese-links): correctly assign reviewers

---

docs/apis-tools/camunda-spring-boot-starter/getting-started.md
docs/apis-tools/java-client/getting-started.md
docs/apis-tools/migration-manuals/migrate-to-camunda-java-client.md
docs/reference/announcements-release-notes/880/880-announcements.md

see https://github.com/camunda/camunda/pull/36992

feat: set REST as default for the camunda client

---

docs/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.5/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.6/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md
versioned_docs/version-8.7/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore.md

This documents https://github.com/camunda/camunda/issues/36162 which we have shipped with 8.6.27 and will be included in the next patches/minor versions.

docs: zeebe backups can be listed by prefix

---

docs/self-managed/installation-methods/helm/chart-parameters.md

When reading through the page I felt this would help to quickly get a better understanding what the tables are about.

refactor: highlight what chart param tables are about

---

docs/self-managed/components/orchestration-cluster/core-settings/concepts/usage-metrics.md

Usage metrics page enhancements
related with #5573

docs: usage metrics page enhancements

---

docs/reference/announcements-release-notes/880/880-announcements.md

Adds announcement for Elasticsearch/OpenSearch replica default change in 8.8.
https://github.com/camunda/camunda-docs/pull/6664

doc(announcements): Increasing replica count during upgrade to 8.8

---

docs/self-managed/quickstart/developer-quickstart/c8run.md

Not correct anymore and can be removed.

fix: remove trouble shooting guide c8run

---

docs/components/modeler/web-modeler/play-your-process.md
docs/reference/announcements-release-notes/880/880-announcements.md

related to https://github.com/camunda/play/issues/1316

docs(play): document user tasks with job worker implementation not being supported

---

docs/apis-tools/zeebe-api/gateway-service.md
versioned_docs/version-8.5/apis-tools/zeebe-api/gateway-service.md
versioned_docs/version-8.6/apis-tools/zeebe-api/gateway-service.md
versioned_docs/version-8.7/apis-tools/zeebe-api/gateway-service.md

Currently, parts of the API is sorted alphanumerically, but not all RPCs are. Some newer ones are added to the bottom, while others have been added close to "related" RPCs.
However, for users that would be looking for a certain RPCs, an alphabetic (or alphanumeric) ordering would make it easier to find the RPC description they are looking for.
The document is not meant for learning about creating process instances first, and about streaming jobs at the end. Instead, it's general usage will be for reference checking of the available RPCs.
I have no issue to link this to. I just noticed it and thought it could be improved without much effort.

Sort Zeebe API RPCs alphanumerically

---

docs/self-managed/installation-methods/manual/install.md

related to https://github.com/camunda/team-infrastructure-experience/issues/854
Updates the manual installation to use the new unified config settings available in snapshot images and should reflect final 8.8 state.
It simplied the config quite a bit.
Some links are currently a bit generic as the underlying config settings page does not exist yet.

chore: manual installation unified-config changes

---

docs/self-managed/installation-methods/helm/configure/registry-and-images/air-gapped-installation.md

Refactors the Helm chart air-gapped environment installation page (air-gapped-installation) to follow the agreed configuration page template and doc style guide.

docs(helm): align Helm chart air-gapped environment installation with template

---

package-lock.json
package.json

This PR temporarily uses [a patched theme](https://github.com/jwulf/docusaurus-openapi-docs/tree/oneOf-format-display-package) for the API docs. 
This is to address [this issue](https://github.com/camunda/camunda-orchestration-cluster-api/issues/3).
A PR to the upstream theme package is open [here](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/1230).
When the upstream PR is merged and an updated theme package is available, we can revert this change. This technical debt item is tracked in [this issue](https://github.com/camunda/camunda-docs/issues/6830).

fix: correctly format oneOf primitive branch

---

docs/reference/glossary.md

Just random fix of a super small bug

fix(glossary): move btp link to proper heading

---

docs/self-managed/components/management-identity/access-management/access-management-overview.md
docs/self-managed/components/management-identity/application-user-group-role-management/manage-roles.md
docs/self-managed/components/management-identity/configuration/configure-external-identity-provider.md
docs/self-managed/components/management-identity/configuration/connect-to-an-oidc-provider.md
docs/self-managed/components/management-identity/configuration/identity-configuration-overview.md
docs/self-managed/components/management-identity/manage-tenants.md
docs/self-managed/components/management-identity/mapping-rules.md
docs/self-managed/components/management-identity/miscellaneous/application-monitoring.md
docs/self-managed/components/management-identity/miscellaneous/configuration-variables.md
docs/self-managed/components/management-identity/miscellaneous/troubleshoot-identity.md
docs/self-managed/components/management-identity/overview.md
docs/self-managed/components/orchestration-cluster/identity/overview.md
docs/self-managed/concepts/authentication/authentication-to-management-components.md
docs/self-managed/concepts/authentication/authentication-to-orchestration-cluster.md

A TW retro review for https://github.com/camunda/camunda-docs/pull/6719.

Identity: Management Identity 6718 retro review

---

docs/self-managed/components/connectors/connectors-configuration.md
versioned_docs/version-8.5/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.6/self-managed/connectors-deployment/connectors-configuration.md
versioned_docs/version-8.7/self-managed/connectors-deployment/connectors-configuration.md

This pull request updates the connector configuration documentation across multiple versions to include instructions for configuring a custom truststore. This addition helps users securely connect their connector runtime to external systems over HTTPS by specifying the necessary environment variables.
Documentation improvements for HTTPS connectivity:
* Added a new "Truststore" section to the connector configuration docs in `docs/self-managed/components/connectors/connectors-configuration.md`, explaining the purpose and configuration of a custom truststore using environment variables (`JAVAX_NET_SSL_TRUSTSTORE` and `JAVAX_NET_SSL_TRUSTSTOREPASSWORD`).
* Replicated the "Truststore" section in versioned documentation files:  
* `versioned_docs/version-8.5/self-managed/connectors-deployment/c …

docs(sm-connectors-config): Document how to configure a truststore for the connectors Runtime

---

docs/guides/migrating-from-camunda-7/data-migrator/limitations.md

related to: camunda/camunda-bpm-platform/issues/5439

docs(data-migrator): runtime migrator updates skipReason

---

docs/components/concepts/user-task-listeners.md
docs/components/tasklist/api-versions.md

As we won't be fixing these limitations in Tasklist v1 and the deprecated Tasklist API, we've decided to document the limitations instead. For full details, see #6806.
I've split https://github.com/camunda/camunda/issues/38350 into two limitations to make it easier to understand for users:
- One for Tasklist v1 (the UI experience)
- One for Tasklist API
closes #6806
closes https://github.com/camunda/camunda/issues/36246
closes https://github.com/camunda/camunda/issues/38336
closes https://github.com/camunda/camunda/issues/38350

Describe task listener limitations for tasklist v1

---

docs/components/connectors/connector-types.md
versioned_docs/version-8.5/components/connectors/connector-types.md
versioned_docs/version-8.6/components/connectors/connector-types.md
versioned_docs/version-8.7/components/connectors/connector-types.md

docs(inbound-connectors): Document Process Definitions polling limitations

---

versioned_docs/version-8.6/self-managed/tasklist-deployment/data-retention.md
versioned_docs/version-8.7/self-managed/tasklist-deployment/data-retention.md

We already document the corresponding Operate limitation, but never did so for Tasklist. This goes away with 8.8, but we should correctly do this for 8.6 and 8.7 while they are supported.

chore(docs): include limitation around tasklist data retention

---

docs/apis-tools/orchestration-cluster-api-rest/orchestration-cluster-api-rest-swagger.md

This PR is updating the docs for Swagger UI by mentioning our support for CSRF and the considerations.
Since CSRF forces the users to have a session set, we need to update our docs to inform them accordingly. Discussed [here](https://camunda.slack.com/archives/C08DQB6RA8Z/p1758896934582689?thread_ts=1758794789.660239&cid=C08DQB6RA8Z)

docs(api): mention Swagger CSRF

---

docs/self-managed/components/orchestration-cluster/core-settings/configuration/properties.md

Closes #6728
In this PR I align with the format of the Spring client property reference page [here](https://docs.camunda.io/docs/next/apis-tools/camunda-spring-boot-starter/properties-reference/#properties). Some points I would like to highlight:
* I've transition the page to more of a over all switch (as with the Spring client page) so this means we have three tabs, config props, env variables, helm values. 
* The grouping is done to a similar level, a large group of properties typically fall into the same bucket with more targetted properties having their own section
* I have aligned the group titles with the format they represent, for example config props are `x.y.z`, env vars are `X_Y_Z`. This has come with a tradeoff that the title navigation bar is expanded but I think its clearer. …

docs: refactor orchestration properties page to be inline with spring client page

---

docs/reference/announcements-release-notes/880/whats-new-in-88.md

Add agentic orchestration as a section to the what's new page.

docs(reference): add agentic orchestration

---

docs/self-managed/installation-methods/helm/install.md

related to https://github.com/camunda/camunda-platform-helm/issues/4336
Fixing missing secrets on autogenerate by upgrading secrets to new pattern.
Reported [here](https://camunda.slack.com/archives/C03UR0V2R2M/p1759238788966159)

fix: udpate secrets to new pattern for install values.yaml

---

docs/self-managed/deployment/helm/configure/running-custom-connectors.md

fix note on custom connectors

---

docs/components/connectors/custom-built-connectors/host-custom-connector.md
docs/self-managed/deployment/helm/cloud-providers/amazon/amazon-eks/eks-helm.md
docs/self-managed/deployment/helm/cloud-providers/azure/microsoft-aks/aks-helm.md
docs/self-managed/deployment/helm/configure/accessing-components-without-ingress.md
docs/self-managed/deployment/helm/configure/authentication-and-authorization.md
docs/self-managed/deployment/helm/configure/ingress-setup.md
docs/self-managed/operational-guides/backup-restore/backup-and-restore.md

- Add a separated Ingress migration example using `global.extraManifests`.
- Remove leftovers of the Operate/Tasklist old architecture.

docs(self-managed): update ingress and port-forward instructions

---

docs/components/early-access/alpha/alpha-features.md
docs/reference/announcements-release-notes/release-policy.md
versioned_docs/version-8.5/reference/alpha-features.md
versioned_docs/version-8.5/reference/release-policy.md
versioned_docs/version-8.6/reference/alpha-features.md
versioned_docs/version-8.6/reference/announcements-release-notes/release-policy.md
versioned_docs/version-8.7/components/early-access/alpha/alpha-features.md
versioned_docs/version-8.7/reference/announcements-release-notes/release-policy.md

- Moved the "alpha releases cannot be updated" limitation from the SaaS Alpha channel section into the central Alpha release definition.
- Updated the Alpha features page to include the limitation.

docs(reference): clarify alpha release limitations apply to SaaS and Self-Managed

---

docs/self-managed/deployment/helm/upgrade/helm-870-880.md

Fix indentation of migration config

fix: fix indentation of migration config

---

docs/apis-tools/migration-manuals/index.md
docs/reference/announcements-release-notes/880/880-release-notes.md
docs/reference/announcements-release-notes/880/whats-new-in-88.md
docs/self-managed/update/administrators/overview.md

Remove warnings from 8.8 docs in preparation for the 8.8 release.
Also updated the keywords and page rank to improve search.

Update what's new in 8.8

---

versioned_docs/version-8.7/components/concepts/process-applications.md

Test the Algolia search mechanism for process applications.

Update Algolia search

---

docs/reference/announcements-release-notes/880/880-release-notes.md

Dynamic partition scaling was mentioned twice and was showing an outdated *caution* block which I removed
- [] This is on a **specific schedule** and the assignee will coordinate a release with the Documentation team. (create draft PR and/or add `hold` label)

fix(release-notes): Merged duplicated release not on orchestration cluster

---

docs/guides/migrating-from-camunda-7/data-migrator/limitations.md

related to: camunda/camunda-bpm-platform/issues/5455

docs(data-migrator): parallel gateway limitation

---

docs/self-managed/components/orchestration-cluster/zeebe/configuration/broker.md
docs/self-managed/operational-guides/troubleshooting.md
versioned_docs/version-8.6/self-managed/operational-guides/troubleshooting/troubleshooting.md
versioned_docs/version-8.6/self-managed/zeebe-deployment/configuration/broker.md
versioned_docs/version-8.7/self-managed/operational-guides/troubleshooting/troubleshooting.md
versioned_docs/version-8.7/self-managed/zeebe-deployment/configuration/broker.md

Document the new `ZEEBE_BROKER_DATA_BACKUP_S3_SUPPORTLEGACYMD5` configuration property for S3 Backup store config.
ref: https://github.com/camunda/camunda/issues/35953
This will probably be available in September's release iteration.

docs: s3 legacy md5 plugin support

---

docs/reference/announcements-release-notes/880/880-announcements.md

Removed deprecated Zeebe gRPC API endpoints announcement from release notes - Zeebe gRPC will be still supported.

fix (docs):Remove deprecated Zeebe gRPC API endpoints section
